### ISSUE TITLE
VSCode autocompletion comment swagger-php

### ISSUE THREAD

**Issue by cedricDevWP** [zircote/swagger-php#1000]
Hi,

someone would have a solution to auto-fill comments on VSCode ? or with which tools you develop the documentation ?

Thx,
Cédric

**Comment by fuale** [comment]
./.,;''

**Comment by fuale** [comment]
In v4 you can use php8.1 attributes, that has full autocomplete 🤔, but in older versions, I think, there is no solution

**Comment by DerManoMann** [comment]
I know PHPStorm has support for annotations (docblock) and there is even a default for the (older) `@SWG` style.
Not sure if VSCode has something similar where you just have to map the prefix - ie. `@OA` to a namespace...?

**Comment by DerManoMann** [comment]
Closing for now - if you find a reusable solution you could raise a PR to add a link to the 'related projects' section ;)
