### ISSUE TITLE
3.x branch in preparation for swagger-php v4

### ISSUE THREAD

**Issue by DerManoMann** [zircote/swagger-php#1002]
With PHP 8.1 almost upon us its time to get ready for swagger-php v4 :tada: 

I've created a new branch 3.x based on master which will be the root of all subsequent v3.x maintenance releases.

The plan is to merge PR #982 into master soon and create a v4-RC1 release.

**Comment by bfanger** [comment]
👍i'd recommend keeping support for older versions to a minimum.
