### ISSUE TITLE
Please deprecate the library. Docblock is not the place for an API documentation.

### ISSUE THREAD

**Issue by smilesrg** [zircote/swagger-php#1003]
...as it leads to the scrolling of a long canvas of text and obstructs the controller's maintenance.

**Comment by DerManoMann** [comment]
Ha! That is a good one - no one forces you to use it and I believe a lot of people still find it useful.

Even if, what are the alternatives?

**Comment by smilesrg** [comment]
A good alternative is to keep docs inside with `YML` or `JSON` files

**Comment by sharifzadesina** [comment]
@smilesrg Your controllers shouldn't contain business logic in the first place, so you are doing it wrong buddy.

**Comment by smilesrg** [comment]
@sharifzadesina :-D funny. the problem is not in the long controllers, but in long lines of docs on top of the controllers.

**Comment by sharifzadesina** [comment]
@smilesrg So don't use the package. I am personally OK with "long lines of docs" lol

**Comment by smilesrg** [comment]
I'm not using it, but others are using 😄 it's a good practice to keep docs separately from the code. While it's OK to put a tag and auto-generate docs from models, putting description above the controller IMO it's not a good idea

**Comment by JimmyBanks** [comment]
@smilesrg That's nice, IMO putting the docblock in the controller perfectly fine and logical, especially for any project that is using attribute routes. BTW the level of entitlement it takes for somebody to do what you just did is astounding and embarrassing, learn how to post constructive criticism if you don't agree with something.

@DerManoMann This is a great package that makes generating Swagger for PHP significantly more streamlined and enjoyable and I greatly appreciate the time you contribute to this project, and I am sure many others out there appreciate it just as much. Thank you!

**Comment by DerManoMann** [comment]
Thanks @JimmyBanks.
If you are using attributes already you might want to give the V4-rc1 a try that got released yesterday.
Doc's are not that great yet, but all annotations are usable as attributes too (and less nested).
https://github.com/zircote/swagger-php/blob/master/docs/Migrating-to-v4.md

**Comment by smilesrg** [comment]
You can disagree with me for sure. But look at this example from an issue by neighbourhood. It's code pollution. Such a long canvas of text, and it's just for one property:

```php
/**
 *
 * @OA\Property(
 *      type="array",
 *          @OA\Items(
 *               @OA\Property(
 *                    property="discriminator",
 *                    type="string",
 *                    example="discriminator"
 *               ),
 *              @OA\Property(
 *                      property="ids",
 *                      type="array",
 *                      @OA\Items(type="integer"),
 *                      description="array of configure_property_id ids"
 *              )
 *          ),
 *      description="array of discriminators with configure_property_id array"
 * )
 *
 * @var array
 */
public $props_ids;
```

**Comment by DerManoMann** [comment]
Closing as this seems to be a matter of opinion.

One more comment from me would be that annotations (or attributes) can be used for more than just API documentation. For example, https://github.com/DerManoMann/openapi-router allows you to use that same meta data for routing and other things (if needed).

If you are working on a larve Laravel app this might also be of interest in that context: https://stitcher.io/blog/route-attributes
