### ISSUE TITLE
Encoded Json as Response or Payload

### ISSUE THREAD

**Issue by jbgatchalian** [zircote/swagger-php#1004]
Hello, I'm having trouble on finding a fix or a work-around for this. Whenever my response/request body has an attribute that is produced by JSON.stringify or json_encode, this error message appears:

`[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_CURLY_BRACES, got 'formConfig' at position 279.`

Here's a sample response/request body I tried to put on the **@OA/Schema**:

```
@OA\Schema(
   title="Request",
   schema="Request",
   example={
      "configuration":"{\"formConfig\":123}"
   }
 )
 
```

I hope you can help me. Thanks!

**Comment by DerManoMann** [comment]
I think that would be a limitation of the underlying [doctrine annotations](https://github.com/doctrine/annotations) library - maybe someone there can help?

**Comment by olsona-hologram** [comment]
The answer here is to not use `\` to escape quotes, but instead double-quote. So for the example above, you'd want:
```
@OA\Schema(
   title="Request",
   schema="Request",
   example={
      "configuration":"{""formConfig"":123}"
   }
 )
```
