### ISSUE TITLE
Analyzer cant see inherited base classes. No autoloading.

### ISSUE THREAD

**Issue by archadamaster** [zircote/swagger-php#1012]
Analyzer scans files (Finder lib) in some natural order per-file and does not do real analyzing at the end when all `code content` is loaded.

I have project with PSR-4 autoloading/namespacing. Real PHP code works fine.
If you put all in one file then it is ok but then PSR autoloading fails.

Assume you have this code as an example:

**Generated error**
```
Uncaught Error: Class &quot;App\Models\Response\JsonApiBase&quot; not found in /var/www/app/Models/Response/JsonApiAccount.php:13
```

**JsonApiAccount.php**
```
/**
 * @OA\Schema(
 * 
 * )
 */
class JsonApiAccount extends JsonApiBase
{
    /**
     * @OA\Property()
     *
     * @var \App\Models\Entities\Account
     */
    public \App\Models\Entities\Account $data;
}
```

**JsonApiBase.php**
```
/**
 * No schema!
 */
class JsonApiBase
{
    /**
     * @OA\Property()
     *
     * @var string
     */
    public JsonApiHeader $jsonapi;

    /**
     * @OA\Property()
     *
     * @var JsonApiMeta
     */
    public JsonApiMeta $meta;
}
```

**Comment by DerManoMann** [comment]
Are you using swagger-php as part of you project or standalone? 

If it is standalone then there is not much swagger-php can do about autoloading on its own. However, you can add your projects autoload file as bootstrap arg to the `openapi` CL tool.

Something like:
```
  openapi -b ~/projects/myapp/vendor/autoload.php ~/projects/myapp/src
```

**Comment by archadamaster** [comment]
Yes, it worked out.
Updated `composer.json`, coz i have explicit framework `Loader` reconfiguration in my php.
