### ISSUE TITLE
Is it possible to allow all versions of psr/log on v4?

### ISSUE THREAD

**Issue by mprokopiou** [zircote/swagger-php#1014]
Hi,

Is it possible to add the following: "psr/log": "^1 || ^2 || ^3"

https://github.com/zircote/swagger-php/blob/dd5f1b7b84ffa86527e984b292c5223aeac5f50f/composer.json#L47

Thank you in advance.

**Comment by DerManoMann** [comment]
Yes, that change is already merged.

**Comment by DerManoMann** [comment]
Fixed in v4.0.1

**Comment by mprokopiou** [comment]
Thank you

**Comment by tybw** [comment]
Hi there, 

The latest version 4.4.7 has the dependency set to `psr/log: ^1.1 || ^2.0 || 3.0`. It fixes the version to `3.0`. Can it be `^3.0`?

Thanks!

**Comment by DerManoMann** [comment]
Oh, of course!
