### ISSUE TITLE
Order of schemas in allOf

### ISSUE THREAD

**Issue by shortcodes** [zircote/swagger-php#1018]
Hey I have a question:

Is it possible to manage order of merged Schemas??

Example

```
/**
     * @OA\Property(
     *     allOf={
     *        @OA\Schema(
     *              @OA\Property(property="id",readOnly=false),
     *        ),
     *        @OA\Schema( ref="#/components/schemas/SomeSchemaWithIdPropertyMarkedAsReadOnly"),
     *     }
     *
     * )
     *
     *
     */
    private $property;
```

Does not sets `readOnly` to `false` because in schema is already `readOnly` set to `true`

### You may think this is exacly how it should work. Schema overrides property ...

But after switching places ... generated json looks exacly the same.

```
/**
     * @OA\Property(
     *     allOf={
     *        @OA\Schema( ref="#/components/schemas/SomeSchemaWithIdPropertyMarkedAsReadOnly"),
     *        @OA\Schema(
     *              @OA\Property(property="id",readOnly=false),
     *        ),
     *     }
     *
     * )
     *
     *
     */
    private $property;
```

When I switch order directly in `api-docs.json` everything works like a charm. 

Do you have any idea where to start searching solution?

**Comment by DerManoMann** [comment]
Not sure if the order should matter at all. In swagger-php we actually do re-order `allOf` elements in certain situations and sometimes there isn't a way to control the order at all (inheritance, etc).

I would raise this question with whatever tool you use to load the json file and see if it is a problem on their side.

**Comment by shortcodes** [comment]
@DerManoMann what do you mean by tool? I strictly refer to generated `api-docs.json` and I can see that JSON fragment that corresponds to fragments above is regardless of chosen (above) option and stay always the same:

```json
"property": {
    "allOf": [
        {
            "properties": {
                "id": {
                    "readOnly": false
                }
            },
            "type": "object"
        },
        {
            "$ref": "#/components/schemas/SomeSchemaWithIdPropertyMarkedAsReadOnly"
        }
    ]
}
```

But if I modify this fragment to look like this inside generated `api-docs.json` file like this:

```json
"property": {
    "allOf": [
        {
            "$ref": "#/components/schemas/SomeSchemaWithIdPropertyMarkedAsReadOnly"
        },
        {
            "properties": {
                "id": {
                    "readOnly": false
                }
            },
            "type": "object"
        }
    ]
}
```

Then my tool ( I guess you mean Swagger UI - correct me please if I am mistaken) render whole documentation as I desire.

**Comment by DerManoMann** [comment]
Yes, that is what I mean.
I do not know if the spec defines that the order is 
relevant. If so, then this could be considered a bug.

OTOH,  properties and $refs are clearly different so even with random order swagger-ui should be able to merge those the same way.

**Comment by shortcodes** [comment]
@DerManoMann In my opinion (very subjective) all this problem can be reduced to overriding properties. Refs brings schemas with properties and its order defines if ref schema will override property put there off hand or the opposite, if off hand property can override ref schema property.

**Comment by shortcodes** [comment]
@DerManoMann In your opinion is there something that can be done?

**Comment by DerManoMann** [comment]
@shortcodes There is a PR up that changes the ordering of `allOf` (or, in fact, doesn't change it) #1067 Could you please have a look if that helps?

**Comment by DerManoMann** [comment]
This is live now.
