### ISSUE TITLE
how to deprecate api in swagger-php?

### ISSUE THREAD

**Issue by omidxplimbo** [zircote/swagger-php#1023]
hi . i want to do deprecate some api and show in ui swagger . can i do ?

**Comment by mroeling** [comment]
According to OpenApi documentation you can set the deprecated flag to true. `deprecated: true`
https://swagger.io/docs/specification/2-0/paths-and-operations/ --> "Marking as Deprecated"

**Comment by DerManoMann** [comment]
Looks like `deprecated` as property only exists on `Schema` and subclasses. Not sure if that is enough or even correct...

**Comment by DerManoMann** [comment]
Actually, I was wrong. All `Operation` derived annotations have a `deprecated` property too, so closing...
