### ISSUE TITLE
Ignoring of schema name for parent class since verson 3.3.0  

### ISSUE THREAD

**Issue by Volonda** [zircote/swagger-php#1027]
Since version 3.3.0 this code doesn`t work any more. Output json have wrong $ref value in allOf for "Employee" and "Fl"

`     "allOf": [
                    {
                        "properties": {
                            "property3": {
                                "nullable": false,
                                "type": "string"
                            }
                        }
                    },
                    {
                        "$ref": "#/components/schemas/AbstractResponsible"
                    }
                ]
            }
`
Expected: "#/components/schemas/Responsible"
Actual: "#/components/schemas/AbstractResponsible"
 
[AbstractResponsible.txt](https://github.com/zircote/swagger-php/files/7727379/AbstractResponsible.txt)
[Controller.txt](https://github.com/zircote/swagger-php/files/7727380/Controller.txt)
[Employee.txt](https://github.com/zircote/swagger-php/files/7727381/Employee.txt)
[Fl.txt](https://github.com/zircote/swagger-php/files/7727382/Fl.txt)
[Request.txt](https://github.com/zircote/swagger-php/files/7727383/Request.txt)
[openapi_api.json.txt](https://github.com/zircote/swagger-php/files/7727396/openapi_api.json.txt)

P.S.
Perhaps the reason is  here  [line](https://github.com/zircote/swagger-php/blob/c3c93f08e4eddeeed1522aa001572b6856471c40/src/Analysis.php#L351) . It will return  first annotation @OA\Schema(ref="#/components/schemas/FlResponsible")  instead of root @OA\Schema.

If i remove "oneOf" from AbstractResponsible it works well again, but i need way to specify oneOf for AbstractResponsible. My case is Polymorphism from here https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

**Comment by DerManoMann** [comment]
@Volonda Would you be able to test the referenced PR? 

Turns out there was even more than one issue in this - thanks for providing a usable test case!

I've also taken the liberty to add your example code to the examples folder - hope that is ok :)
