### ISSUE TITLE
PHP 8.1 support for 3.x versions

### ISSUE THREAD

**Issue by shyim** [zircote/swagger-php#1035]
Hey,

We want to add support for PHP 8.1, but we can't update the library to the latest version due to breaking changes. Would you accept a pull request for the 3.x versions to add PHP 8.1 support?

**Comment by DerManoMann** [comment]
Sure, any help is welcome. Sorry about having missed that - the PHP 8.1 branch didn't start out to be version 4 so it kind of got lost...

**Comment by shyim** [comment]
I was just stupid. The newest patch versions works well on 8.1 :)
