### ISSUE TITLE
Problem creating response components with l5-swagger

### ISSUE THREAD

**Issue by BrunoFred** [zircote/swagger-php#1040]
I'm trying to create components annotations with L5-Swagger for some HTTP status. But for some reason swagger is not creating the response component, it only works with schema components and i have no idea why. If I change Response for Schema it works. My code:

```
/**
 *  @OA\Response  (
 *      response="Unprocessable Entity",
 *      description="Server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions.",
 *  )
 */

class UnprocessableEntityResponse {}
```

**Comment by DerManoMann** [comment]
I believe `response` is supposed to be the status code or `default`; not sure if that is relevant though.

**Comment by BrunoFred** [comment]
> I believe `response` is supposed to be the status code or `default`; not sure if that is relevant though.

I manage to make it work by making the response content value the same as the file name

**Comment by DerManoMann** [comment]
Interesting. Multiple yaml files?

**Comment by BrunoFred** [comment]
> Interesting. Multiple yaml files?

I'm working with JSON and i wanted to make some components so i can just ref them through my controllers without having to write the same description over and over.
