### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by JimmyBanks** [zircote/swagger-php#1043]
Now that php has native enums Ian there a plan to add in a native enum attribute?

OpenAPI has enum support in version 3

**Comment by DerManoMann** [comment]
Could be done I suppose. How would you see this working?

**Comment by DerManoMann** [comment]
Hmm, maybe something like this?

```php
enum Scheme
{
    case http;
    case https;
}

#[OA\Server(url: "{schema}://host.dev")]
#[OA\ServerVariable(serverVariable: new OA\Enum(Scheme::class))]
```

**Comment by DerManoMann** [comment]
OTOH, can't you just do?
```php
#[OA\ServerVariable(serverVariable: 'schema', enum: Scheme::cases())]
```

**Comment by ymilin** [comment]
Hello @DerManoMann, I would like to add another use case for native enum usage in OpenApi.

Adding an `#[OA\Schema]` Attribute to create a Schema `"type":"string", "enum": ["FOO", "BAR"]` that can be referenced as Shema Property, Parameter, Response, ...

```php
#[OA\Schema]
enum Status
{
    case DRAFT;
    case PUBLISHED;
    case ARCHIVED;
}
```

Should generate:

```yaml
components:
  schemas:
    Status:
      type: string
      enum:
        - DRAFT
        - PUBLISHED
        - ARCHIVED
```

Using Baked enums should generate the same contract:

```php
#[OA\Schema]
enum Status: string
{
    case DRAFT = 'my_draft';
    case PUBLISHED = 'my_published';
    case ARCHIVED = 'my_archived';
}

#[OA\Schema]
enum Status: int
{
    case DRAFT = 1;
    case PUBLISHED = 2;
    case ARCHIVED = 3;
}
```

I could potentially spend some time to implement this but I have no experience with `swagger-php`'s codebase and I would need some help to know how/where to setup test cases at least.

**Comment by DerManoMann** [comment]
Interesting idea. 

For backed enums wouldn't you want the values and not the names? Deserializing would expect those I suspect.

This would be a quite big change as there are a few places in the codebase that check for class/interface/trait and would need to also consider enums... Might be fun :)

**Comment by ymilin** [comment]
We have been using enum this way since a few years already with the [myclabs/php-enum](https://github.com/myclabs/php-enum) library, but we have to maintain the list of enum values in PHPDoc annotations, like this:
```php
<?php

declare(strict_types=1);

namespace Foo;

use MyCLabs\Enum\Enum;

/**
 * @OA\Schema(
 *    schema="Status",
 *    type="string",
 *    enum={"DRAFT", "PUBLISHED", "ARCHIVED"}
 * )
 *
 * @method static Status DRAFT()
 * @method static Status PUBLISHED()
 * @method static Status ARCHIVED()
 */
class Status extends Enum {
    public const DRAFT = 'DRAFT';
    public const PUBLISHED = 'PUBLISHED';
    public const ARCHIVED = 'ARCHIVED';
}
```
This could now all be inferred from the native enum definitions 😍 

I might be biased by my own usages, but I would argue that we would always want enum names in OpenApi contract by default.
- enum values are usually used as a way to represent them internally, like serializing them into a database. It would be prefered to expose standardized/curated names in OpenApi contract instead.
- libraries in other languages are doing it using enum names, like [swagger-api/swagger-core](https://github.com/swagger-api/swagger-core) in Java.

Deserializing would actually be easier when using names, it requires using the [ReflectionEnum](https://www.php.net/manual/en/class.reflectionenum.php) class and its `getCase(string $name)` method.

Here is an example on [3v4l.org](https://3v4l.org/ZlbON#v8.1.1)

**Comment by DerManoMann** [comment]
@ymilin If you have a minute have a play with the PR and let me know what you think...

**Comment by ymilin** [comment]
oh wow! Thank you for working so quickly on this.

I'm going to download the PR, test it tonight and will let you know. I'll also try to review the PR.

In the meantime, I thought of another use case for enum (I don't know if your PR already tackle it):

Enums may also be type as `#[Property]` in a Schema and its type should be inferred even when it's not itself defined as a standalone `#[Schema]`

```php
enum Status
{
    case DRAFT;
    case PUBLISHED;
    case ARCHIVED;
}

#[Schema]
class BlogPost
{
    public function __construct(
        #[Property]
        public int $id,
        #[Property]
        public string $content,
        #[Property]
        public Status $status
    ) {}
}
```
Should produce:
```yaml
components:
  schemas:
    BlogPost:
      properties:
        id:
          type: integer
        content:
          type: string
        status:
          type: string
          enum:
            - DRAFT
            - PUBLISHED
            - ARCHIVED
```

**Comment by DerManoMann** [comment]
@ymilin I created #1056 for the remainder of work - in the last example would the type/enum to be expanded or could a schema $ref also work seeing that we will have a component for the enum already?

**Comment by egesu** [comment]
@DerManoMann @ymilin I've been implementing the enums lately in my project and it's pretty useful for the api docs too. As you discussed above, I was expecting to see the values, not the names for backed enums in the documentation.

I tried changing [ExpandEnums](https://github.com/zircote/swagger-php/blob/master/src/Processors/ExpandEnums.php#L37). From this:

```php
                $schema->enum = array_map(function ($case) {
                    return $case->name;
                }, $re->getCases());
```

To this:

```php
                $schema->enum = array_map(function ($case) {
                    if (method_exists($case, 'getBackingValue')) {
                        return $case->getBackingValue();
                    }

                    return $case->name;
                }, $re->getCases());
```

So if the enum is a backed enum, then it shows the values. If not, shows the names. Is it logically wrong? If not, shall I open a PR for this?

**Comment by DerManoMann** [comment]
Looks generally ok - I would perhaps prefer to check if `$case instanceof \ReflectionEnumBackedCase`, but that is detail.

It might come down to how people de-serialize, but generally I would expect the value too.

If you create a PR could you try to add a simple test? Also, we should get into the habbit of updating docs to where appropriate - not sure how much there is about enums, but I suspect there could be more ;)
S, no pressue ;) Just see how you go - any PR is welcome...
