### ISSUE TITLE
#[PathParameter] does not work as expected

### ISSUE THREAD

**Issue by alshenetsky** [zircote/swagger-php#1044]
Hello.

zircote/swagger-php 4.1.0

#[PathParameter] attribute does not work as expected. According to documentation, I should be able to omit "type" parameter if I have argument type hinted. And "description" argument should generate corresponding description in swagger data.

This is an example:
```php
    #[Get(summary: 'Get a championship by ID.')]
    #[Route(
        path: '/championships/{championshipId}',
        name: 'championship',
        requirements: ['championshipId' => '\d{1,10}'],
        methods: ['GET']
    )]
    #[Response(
        response: JsonResponse::HTTP_OK,
        description: 'Returns a championship',
        attachables: [new JsonContent(ref: '#/components/schemas/ChampionshipResponse')]
    )]
    #[Parameter(
        name: 'championshipId',
        description: 'ID of the Championship',
        in: 'path',
        required: true,
        attachables: [new Schema(type: 'int')]
    )]
    public function getChampionship(int $championshipId): JsonResponse
    {
   ...
```

This code generates correct swagger data:
```json
"parameters":[{"name":"championshipId","in":"path","description":"ID of the Championship","required":true,"schema":{"type":"int","pattern":"\\d{1,10}"}}]
```

So I expect the same result using #[PathParameter] attribute:

```php
    #[Get(summary: 'Get a championship by ID.')]
    #[Route(
        path: '/championships/{championshipId}',
        name: 'championship',
        requirements: ['championshipId' => '\d{1,10}'],
        methods: ['GET']
    )]
    #[Response(
        response: JsonResponse::HTTP_OK,
        description: 'Returns a championship',
        attachables: [new JsonContent(ref: '#/components/schemas/ChampionshipResponse')]
    )]
    public function getChampionship(
        #[PathParameter(description: 'ID of the Championship')] int $championshipId
    ): JsonResponse
   {
   ...
```

But I got incorrect data: wrong type ("string") and no description at all.
```json
"parameters":[{"name":"championshipId","in":"path","required":true,"schema":{"type":"string","pattern":"\\d{1,10}"}}]
```

**Comment by DerManoMann** [comment]
Hmm, just extended tests for `PathParameter` and that seems to work as expected in the test. Would you be able to put together a reduced testcase - can be a single file - and attach/paste that for me to play around with?

Also, I noticed you are using `attachables` for other nested attributes. You definitely should use `content` or `schema` or whatever it is that needs nesting.
The `attachables` parameter is only for generic custom extensions still to come.

**Comment by alshenetsky** [comment]
@DerManoMann looks like I created the issue in the wrong place, sorry for it. I use NelmioApiDocBundle which is (as I realized) does not support this attribute yet. 

Nice that you have such test now :D

And thanks for your notes about me misusing "attachables" parameter, I'll fix that.
