### ISSUE TITLE
[Feature request] Parameter attribute on method parameter

### ISSUE THREAD

**Issue by mathroc** [zircote/swagger-php#1058]
Hi,

We're using Symfony controller' argument resolver to "inject" query parameters as controller arguments, and I'd like it if we could put the `#[OA\Parameter]` attribute directly on the argument. So that the name, type, nullable (description?) could be extracted automatically, eg:

```php
    #[Route("/route-with-optional-number-query-parameter", methods: "GET")]
    public function withNumber(
        #[\OpenApi\Attributes\Parameter(in: "query")] 
        ?int $number
    ): JsonResponse {
        return new JsonResponse(['number' => $number]);
    }
```

Currently, we use another attribute to enable the argument resolver. But if this was possible, we could use the `OA\Parameter` attribute instead

Is this something that could fit in swagger-php?

ps: we're doing the same when deserializing request body into DTOs so I could be interested in adding `RequestBody` attribute to method parameters too

**Comment by DerManoMann** [comment]
You mean like this? https://github.com/zircote/swagger-php/blob/master/tests/Fixtures/Apis/Attributes/basic.php#L57

I would think/hope that that would cover your case.

RequestBody is a bit trickier but the thought has crossed my mind already before...

**Comment by mathroc** [comment]
Exactly like that, yes 🙏 I did not notice this one before

do you want me to create another issue for RequestBody?
