### ISSUE TITLE
Sorting of allOf causing issue in swagger UI with properties and ref

### ISSUE THREAD

**Issue by akalineskou** [zircote/swagger-php#1059]
Right now there is an issue with allOf being sorted with the properties being first always

You can try it yourself using this openapi yaml
https://editor.swagger.io/
```yaml
openapi: 3.0.3

info:
  title: ''
  description: ''
  version: ''

paths:
  /test-endpoint:
    get:
      operationId: test-endpoint
      responses:
        200:
          description: test-endpoint
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - properties:
                      title:
                        nullable: false
                  - $ref: '#/components/schemas/TestEndpoint'
  
components:
  schemas:
    TestEndpoint:
      required:
        - title
      properties:
        title:
          type: string
          example: Some title
          nullable: true
      type: object
```

allOf has the ref schema which has the title `nullable=true` and I want to override it with the property title to be `nullable=false`
But in swagger ui it still shows as `nullable=true`

If we change the sort for the allOf to (the ref first, then properties)
```yaml
                  - $ref: '#/components/schemas/TestEndpoint'
                  - properties:
                      title:
                        nullable: false
```

It correctly shows the title as `nullable=false`

After some debugging I came to the conclusion that this code is the culprit https://github.com/zircote/swagger-php/blob/3.x/src/Processors/AugmentSchemas.php#L128
Commenting it leaves the ref first (as I have it in my code, then the properties override)

**Comment by DerManoMann** [comment]
Related to #1018 - on my to-do list :shrug:

**Comment by DerManoMann** [comment]
Just for my understanding - `properties` should always be last in `allOf`? or whatever natural order they come in?

When expanding class/interface/trait hierarchies new `allOf` might be created or existing modified. Except for this specific case ordering is not deterministic....

**Comment by akalineskou** [comment]
Not sure if properties should always be last... maybe #1 $ref #2 properties, then the rest...

**Comment by DerManoMann** [comment]
Yeah, that is the tricky question. I am not sure if the spec explicitely defines this but that seems to be what happens.

**Comment by DerManoMann** [comment]
@akalineskou Would you be able to please test the PR that I created to fix this?
