### ISSUE TITLE
Declare type of array for php8 attributes

### ISSUE THREAD

**Issue by momala454** [zircote/swagger-php#1064]
https://github.com/zircote/swagger-php/blob/8f53ded4c90ec7cccb18333c1d7d8a4c16f0c3c8/src/Attributes/OperationTrait.php#L22

We must define the type of elements that are on arrays, so IDE can suggest what to type when writing php8 attributes.
Exemple :
```php
/** 
     * @param \OpenApi\Attributes\Parameter[] $parameters
     */
```

the same for all others array

**Comment by momala454** [comment]
additionnally, I don't know what i should provide for "security". Using anotation, it's 
security={{"api_key":{}}},

but for attributes, it's also an array but I don't know what to provide
security: ['api_key'=> true]
and
security: ['api_key']

are not working

**Comment by momala454** [comment]
how do we tell that the jsonContent is of type "class name" like "\Api\Response"?
responses: [new \OpenApi\Attributes\Response(response: '200', description: 'test', content: new \OpenApi\Attributes\JsonContentitems: new \OpenApi\Attributes\Items(properties: [new \OpenApi\Attributes\Property(type: \Api\Response::class)])))],

**Comment by DerManoMann** [comment]
> edit2 : please also add some documentation and examples for the ide on the docblock

Doing what I can - pull request are most welcome.

**Comment by DerManoMann** [comment]
> how do we tell that the jsonContent is of type "class name" like "\Api\Response"? responses: [new \OpenApi\Attributes\Response(response: '200', description: 'test', content: new \OpenApi\Attributes\JsonContentitems: new \OpenApi\Attributes\Items(properties: [new \OpenApi\Attributes\Property(type: \Api\Response::class)])))],

Is this still a question or is the badly pasted attribute the answer?

Generally it would be good to create separate issues for unrelated issues/questions. I'd be happy to help if you could provide some more context; for example:
* the (simplified) version of your `Api\Response` class
* the expected YAML

Also using formatting for code does really help with readability - thanks.

**Comment by DerManoMann** [comment]
> We must define the type of elements that are on arrays, so IDE can suggest what to type when writing php8 attributes.

Todays release has quite a few additions to docblocks - have a play and see if there are more missing...

**Comment by momala454** [comment]
thank you for your help, for Api\Response i finally found how to, by reading a lot the doc and the exemples
```
responses: [new \OpenApi\Attributes\Response(response: '200', description: '', content: new \OpenApi\Attributes\JsonContent(allOf: [
        new \OpenApi\Attributes\Schema(ref: '#/components/schemas/Response'),
        new \OpenApi\Attributes\Schema(ref: '#/components/schemas/EmailPattern')
    ]))], 
```
i still need to modify it however it's not exactly how I want. So apparently, we can't use class directly without writing 
#[\OpenApi\Attributes\Schema()]
and 
#[\OpenApi\Attributes\Property()]
to all properties ?
but what about the class namespaces, how can I have the class to keep the namespace for openapi ? By example when writing \OpenApi\Attributes\Schema, a lot of parameters are available, i'm not sure if all are pertinent to Schema. The docblock could put some explanation to their use to each of them.
By example, i've read on the documentation the answer of this question, but at first, i was wondering what is difference between type and format ?
But what is x etc ?
The "type" parameter, it could list all possible accepted values 
```
null:  A JSON "null" value

   boolean:  A "true" or "false" value, from the JSON "true" or "false"
      value

   object:  An unordered set of properties mapping a string to an
      instance, from the JSON "object" value

   array:  An ordered list of instances, from the JSON "array" value

   number:  An arbitrary-precision, base-10 decimal number value, from
      the JSON "number" value

   string:  A string of Unicode code points, from the JSON "string"
      value
```

**Comment by DerManoMann** [comment]
@momala454 I've restructured the docs - adding small things to the [cookbook](https://zircote.github.io/swagger-php/guide/cookbook) or bigger things to the [guide](https://zircote.github.io/swagger-php/guide/) or  [reference](https://zircote.github.io/swagger-php/reference/) should now be a lot easier.

**Comment by momala454** [comment]
thanks
