### ISSUE TITLE
Migrating from 3.* to 4.* Schema issues

### ISSUE THREAD

**Issue by JimmyBanks** [zircote/swagger-php#1069]
Using identical code, after migrating from `3.*` to `4.*`, a significant number of my schemas have a blank definition.

Similarly, endpoint response example values no longer display the object definition, but simply display "string".

I've looked through the release notes and haven't been able to identify what is wrong, I have also done a significant amount of trial and error and am stuck.

Here is an example of a schema that works in `3.*`, but is not populating in `4.*`

    /** @OA\Schema() */
    class SubjectList implements ListInterface
    {
        use ListTrait;
    
        public function __construct(
            /** @OA\Property() */
            public ListSettings $settings,
            /** 
             * @OA\Property() 
             * @var Item[]
             * */
            public array $list
        )
        {
            $this->count = \count($list);
        }
    }

Here is an example of an endpoint that previously displayed the return object content, but now just displays "string"

    class ListController extends AbstractController
    {
      public function __construct(
          private ListData $data,
          private ListService listService,
      )
      {}
    
      /**
       * @OA\Get(
       *     path="/list/{typeId}/{slug}/{dateSpan}",
       *     summary="Returns a List model",
       *     tags={"SubjectList"},
       *     @OA\Response(
       *          response=200,
       *          description="SubjectList Schema returned",
       *          @OA\Schema(type="object"),
       *          @OA\JsonContent(ref="#/components/schemas/SubjectList"),
       *          @OA\Link(link="SubjectList", ref="#/components/schemas/SubjectList")
       *     )
       * )
       * 
       * @OA\Get(
       *     path="/list/id/{slug}",
       *     summary="Returns a SubjectList model filtered",
       *     tags={"SubjectList"},
       *     @OA\Response(
       *          response=200,
       *          description="SubjectList Schema returned",
       *          @OA\Schema(type="object"),
       *          @OA\JsonContent(ref="#/components/schemas/SubjectList"),
       *          @OA\Link(link="SubjectList", ref="#/components/schemas/SubjectList")
       *     )
       * )
       */
      public function default(bool $editPermissions = false)
     {
         ...
     }

**Comment by DerManoMann** [comment]
There is a limitation in the new code where annotations on method parameters (like the promoted properties in the constructor in your example) do not work any more. It does work for attributes, though.

If you cannot update to attributes you might be stuck with either v3 or use v4 legacy. In case you use swagger-php via a plugin/bundle that might be hard though.

**Comment by JimmyBanks** [comment]
I'm using composer so staying on `3.*` isn't an issue for the time being.

I started migrating to attributes until I ran into the issue I posted here https://github.com/zircote/swagger-php/issues/1068

Thanks for the quick reply, I'll stick with v3 for the time being 👍

**Comment by DerManoMann** [comment]
Cool, thanks for the update.

BTW: Tried your sample code and PHPStorm complains about `List` being a reserved word...

You woudldn't know the cause of the 500 from your logs?

In my test example I am getting a recursion error which I guess would translate into a 500 in a request context...
Either way an interesting find :)

**Comment by JimmyBanks** [comment]
In my actual code the class isn't called List, it is called SubjectList for example, I tried to simplify it to make the code clearer and evidently that was a brainfart on using the reserved keyword instead, I'll edit the examples 🤦

**Comment by DerManoMann** [comment]
@JimmyBanks New version is out that fixes this issue (and a few more!) - happy testing.

**Comment by JimmyBanks** [comment]
@DerManoMann Thank you! I'll check it out 👍

**Comment by DerManoMann** [comment]
Assuming this is resolved...

**Comment by DerManoMann** [comment]
@hotrush yes, unfortunately that is correct.

**Comment by hotrush** [comment]
I see, sad because it cannot be replaced with attributes or smth...
