### ISSUE TITLE
Multiple promoted properties cause a segmentation fault

### ISSUE THREAD

**Issue by szeber** [zircote/swagger-php#1071]
When using more than one promoted property, the generator crashes with a segfault.

Example code:
```php
<?php
use OpenApi\Attributes as OA;

#[OA\Info(title: 'demo', version: '1.0.0')]
#[OA\Get(path: '/')]
#[OA\Response(response: 204, description: 'test')]
#[OA\Schema(schema: 'test')]
class Foo {
    public function __construct(
        #[OA\Property] public int $foo,
        #[OA\Property] public int $bar,
    ) {
    }
}
```

When executing `vendor/bin/openapi test.php --output openapi.json` the script exits with a status code of `139` and the message `Segmentation fault`. When digging into this issue, the cause seems to be that `Property` objects can be parents to other `Property` objects, so when looking for possible parents in  `\OpenApi\Analysers\AttributeAnnotationFactory` (lambda function in line 72 in v4.2.2), it creates a circular dependency with the first property being the child of the second one and vice versa, when they should just be 2 independent properties. 

I'm not sure why a property is allowed to be the parent of another property, so I didn't dig deeper down that rabbit hole :).

**Comment by DerManoMann** [comment]
Yeah, I just found this about 5 minutes ago! Duplicate of #1068.

Good news is that I think I am close to fixing it :)

**Comment by szeber** [comment]
That is great news for sure, thanks :)
