### ISSUE TITLE
Update zircote/php-swagger to version 4.*

### ISSUE THREAD

**Issue by shortcodes** [zircote/swagger-php#1072]
Is it possible to inlcude newest version of zircote/php-swagger to this package?

Regards

**Comment by DerManoMann** [comment]
I am confused - this is the swagger-php repository!?

**Comment by shortcodes** [comment]
Oh crap. @DerManoMann sorry for confusion and my mistake! FYI I mean https://github.com/DarkaOnLine/L5-Swagger. Apology once again!
