### ISSUE TITLE
Required @OA\Info() not found in /opt/app/src/vendor/zircote/swagger-php/src/Loggers/DefaultLogger.php

### ISSUE THREAD

**Issue by malakaton** [zircote/swagger-php#1077]
I have an issue with my php project. Im with the 4.2.3 version of zircote/swagger-php. I have on my routes.php the follow path:

`Route::get('/swagger-json', function () {
    $openapi = \OpenApi\Generator::scan([__DIR__ . '/../public/doc']);
    $t = $openapi->toJson();
});`

and in public/doc i have a php file with the follow content:

`<?php

use OpenApi\Annotations as OA;

/**
 * @OA\Info(
 *   version="1.0.0",
 *   title="My API",
 *   @OA\License(name="MIT"),
 *   @OA\Attachable()
 * )
 */`

With 3.3.3 version works fine, im doing something wrong? 

Thanks a lot

**Comment by DerManoMann** [comment]
Just for the record - the issue here is that the `@OA\Info` must be associated with a class/interface/trait or enum - even just a empty dummy implementation.
Since the new code uses reflection for the main processing part (required to load attributes) access to docblocks is restricted the same way.

**Comment by akalongman** [comment]
@DerManoMann my doc blocks are placed outside of the actual code. How can I use swagger 4.*?

**Comment by DerManoMann** [comment]
You'll have to add empty dummy classes. 

The alternative is to keep using the v3 analyser. The CLI tool has a --legacy option for that
