### ISSUE TITLE
Missing `minimum`/`maximum` in Schema when using Attributes

### ISSUE THREAD

**Issue by hmazter** [zircote/swagger-php#1078]
It may be me that is missing something, but I can't find `minimum`/`maximum` on Schema anymore after trying to migrate to Attribute.

This is what I had using v3 with Annotations:
```php
/**
 *     @OA\Parameter(
 *         name="per_page",
 *         in="query",
 *         description="Number of records to include per page.",
 *         required=false,
 *         example=100,
 *         @OA\Schema(
 *             type="integer",
 *             default=100,
 *             minimum=1,
 *             maximum=1000
 *         )
 *     )
 */
```

And this is what I try to use with Attributes in v4.2.3:
```php
#[Parameter(
    name: 'per_page',
    description: 'Number of records to include per page.',
    in: 'query',
    required: false,
    schema: new Schema(type: 'integer', default: 100, minimum: 1, maximum: 1000, example: 100),
)]
```

Everything else in that Parameter and Schema seems to work except `minimum` and `maximum`.

I get the following error: `Unknown named parameter $minimum`

Please accept my apology if it's just me that has missed something. That they should be nested or are located somewhere else.

**Comment by DerManoMann** [comment]
Nah, there is one more batch of parameters missing on Schema based attributes.
