### ISSUE TITLE
Is annotation of class constants supported in v4?

### ISSUE THREAD

**Issue by sadikinfosec** [zircote/swagger-php#1082]
As far as I can tell it doesn't seem to be, but I wanted to double-check. 

The use case here is there's a class constant thats an associative array with string keys and string values, effectively functioning as a makeshift string enum. The values are part of the api documentation so it seems to make the most sense to have the corresponding comment block adjacent to the class constant, but this doesn't seem to be recognized in v4.

The workaround I chose was to put it on a nearby, related class method instead, after which it seems to show up in the generated json as expected

**Comment by DerManoMann** [comment]
Hmmm, it's an idea. Could you perhaps post a little example of how that would look?

**Comment by DerManoMann** [comment]
Fixed via #1193
