### ISSUE TITLE
How to customize JSON content in the response body?

### ISSUE THREAD

**Issue by BrunoFred** [zircote/swagger-php#1083]
Hello. I'm having a problem where my json is being hard to read and it shows a lot of data in the same line instead of each line having one "key" : "value" content. I'd like to know how can i fix that. I having this in the response body

**{"name":"Bruno","email":"myemail@test.com"}**

Where i'd like to have it like this

**{
     "name":"Bruno",
     "email":"myemail@test.com"
}**

**Comment by DerManoMann** [comment]
If you are talking about the JSON generated by your application code then you've come to the wrong place - that is something you have to solve for yourself.

I would expect that any decent framework allows to pretty print JSON content and if you are using `json_encode()` in your code directly [there are flags](https://www.php.net/manual/en/json.constants.php) to make PHP pretty print too.

**Comment by BrunoFred** [comment]
> If you are talking about the JSON generated by your application code then you've come to the wrong place - that is something you have to solve for yourself.
> 
> I would expect that any decent framework allows to pretty print JSON content and if you are using `json_encode()` in your code directly [there are flags](https://www.php.net/manual/en/json.constants.php) to make PHP pretty print too.

I'm don't think it's my fault cause i made a request in Insomnia and the returned JSON content was the way i wanted it, but when i try in the Swagger UI it doesnt

**Comment by DerManoMann** [comment]
I guess in that case you should head over to https://github.com/swagger-api/swagger-ui/issues and ask there?
Swagger-php has nothing to do with how the data is rendered. Also, maybe insomnia does auto-format Jason?

**Comment by BrunoFred** [comment]
> I guess in that case you should head over to https://github.com/swagger-api/swagger-ui/issues and ask there? Swagger-php has nothing to do with how the data is rendered. Also, maybe insomnia does auto-format json?

I'll try that, thanks

**Comment by DerManoMann** [comment]
Nothing more to be done here.
