### ISSUE TITLE
Annotation Beautifier

### ISSUE THREAD

**Issue by devbro1** [zircote/swagger-php#1091]
Problem:
I use code beautifiers such as php-cs-fixer and parallel-lint to clean and organize my php files. one problem that I have run into a problem where my annotation for OA is disorganized and makes it very hard to update.

I am trying to create a mini program that would exact the comments, beautify it, then puts them back in code. I would think adding such a feature to the command line would be useful:
`./vendor/bin/openapi --beautify ./source/test_file.php`

so it would turn 
```
/**
     * @OA\Post(
     *     path="/api/v1/announcements/",summary="create new announcement",
     *      tags={"Announcements"},
     *     @OA\Response(
     *         response=200, description="OK",
     *         @OA\JsonContent(
 *               @OA\Examples(example="result", summary="An result object.", value={}, ),)
     *     )
     * ,
 *    * @OA\Response(
     *         response=401,
     *         description="Unauthenticated"
     *     )
     * )
     */
```

to 
```
    /**
     * @OA\Post(
     *     path="/api/v1/announcements/",
     *     summary="create new announcement",
     *     tags={"Announcements"},
     *     @OA\Response(
     *         response=200, description="OK",
     *         @OA\JsonContent(
     *              @OA\Examples(
     *                example="result",
     *                summary="An result object.",
     *                value={}
     *              )
     *         )
     *     )
     *     @OA\Response(
     *         response=401,
     *         description="Unauthenticated"
     *     )
     * )
     */
```

**Comment by DerManoMann** [comment]
I am not sure that is the responsibility of this library. I would think this could be better done as a php-cs-fixer rule (or whatever code-style tool you are using)

**Comment by jtreminio** [comment]
You want to use `friendsofphp/php-cs-fixer` with the `@DoctrineAnnotation` rule enabled.

**Comment by devbro1** [comment]
@jtreminio thank you so much, that actually did the trick.

for anyone that might see this:

I created a file `.php-cs-fixer.dist.php` at the root of the project with this content:
```
<?php

$config = new PhpCsFixer\Config();
return $config->setRules([
        '@DoctrineAnnotation' => true,
    ])
;
```

then ran my usual command:
`./vendor/bin/php-cs-fixer fix ./app`

this did the trick
