### ISSUE TITLE
Changing order of the http operations

### ISSUE THREAD

**Issue by sachinbahukhandi-cometchat** [zircote/swagger-php#1092]
Hi,
Is there a way to order operations on some basis inside Filters?
The current operational order is: 
`GET, POST, PUT, PATCH, DELETE`
I want the order to be:
`POST, GET, PUT, PATCH, DELETE`
Is there some way it is possible?

**Comment by DerManoMann** [comment]
You could write a custom processor; something similar to https://github.com/zircote/swagger-php/blob/master/Examples/processors/sort-components/SortComponents.php

**Comment by sachinbahukhandi-cometchat** [comment]
I actually tried writing one using the following logic:
` if (is_object($analysis->openapi->components) && is_iterable($analysis->openapi->components->schemas)) {
            foreach ($analysis->openapi->paths as $pathKey => $pathValue) {
                $path = &$pathValue;
                if (($pathValue->get != UNDEFINED && is_object($pathValue->get)) && ($pathValue->post != UNDEFINED && is_object($pathValue->post))) {
                    //LOGIC TO GO HERE
                }
            }
            
        }`
Can you help me with the logic inside it? Because I actually wanted to `unset($pathValue->post)` and `unset($pathValue->get)` but it caused error when after unsetting I tried to do : $pathValue->get= "Something"

**Comment by DerManoMann** [comment]
Ha! Turns out you cannot! Methods are explicit class properties on `PathItem` which means you'd have to remove/add them and even then there is no guarantee that things work as expected.

Your best bet might be to post process the generated spec file (yaml/json); sorry.

**Comment by sachinbahukhandi-cometchat** [comment]
Sure, got it.
