### ISSUE TITLE
Documentation for attributes

### ISSUE THREAD

**Issue by 24unix** [zircote/swagger-php#1094]
Hi, I just started using swagger-php, but want to make use of attributes instead of annotations, I found the examples usings-links-php81 very helpful, but I'm lost regarding to server and security tags.

So I have like:

`       *        security={
	 *         {"Authorization":{"read":"write"}}
	 *     }` 

How would that be written as an attribute?
	 
And how to handle servers?

**Comment by DerManoMann** [comment]
Good timing - there is a PR up to refactor the docs :)

Not sure about the `"read":"write"` - I think that might be a list?

All the curley baces syntax translates into nested arrays for attributes:
(untested...)

```php
#[OA\Get(
  path: '/users',
  security: [
    ['Authorization' => ['read', 'write']]
  ]
)]
```

**Comment by 24unix** [comment]
Thanks for the fast reply :-)

That read:write thing was a mistake of me, I just started to use Swagger yesterday, it worked, but was wrong :)

Currently, this is valid json and accepted by swagger:

`"security": [
					{
						"Authorization": []
					}
				]`
I just completed it for the moment with a static openapi.json, but using attributes and have a real live result is way nicer.

Might you give me a hint, how I define a server?

`	 * @OA\Server(
	 *   url = "https://ns2.24unix.net/api"
	 * )
`

And what to put under server:

This is what I currently have:

`#[OAT\Get(
		path: '/domains',
		operationId: 'getAllDomains',
		description: 'Returns a list of all domains on this server.',
		summary: 'Listing all domains.',
		security: ['Authorization'],
		servers: [],
		tags: ['Domains'],
		responses: [
			new OAT\Response(
				response: 200,
				description: 'OK'
			),
			new OAT\Response(
				response: 401,
				description: 'API key is missing or invalid.'
			),
			new OAT\Response(
				response: 404,
				description: 'Domain not found.'
			)]
	)]`


Sorry, but MS-GitHub ignores the linebreaks :-(

**Comment by DerManoMann** [comment]
You can specify servers at the top level which makes them available to all endpoints. I am not sure what the exact mechanism is when override that on endpoint level (merge? replace?)

At the top level you put something like what you already pasted
```php
 * @OA\Server(
 *      url="{schema}://host.dev",
 *      description="OpenApi parameters",
 *      @OA\ServerVariable(
 *          serverVariable="schema",
 *          enum={"https", "http"},
 *          default="https"
 *      )
 * )
```

or even
```php
#[@OA\Server(
    url: "{schema}://ns2.24unix.net/api",
    description: "Production Server",
    variables: [
        new @OA\ServerVariable(
            serverVariable: "schema",
            enum: ["https", "http"],
            default: "https"
        )
    ]
)]
```

Keep in mind that you can configure more than one server...

**Comment by 24unix** [comment]
Thank you very much, that lead me to the right direction, some minor chanegs were required:

```
#[OAT\Server(
	url: "{schema}://ns2.24unix.net/api",
	description: "Production Server",
	variables: [
		new OAT\ServerVariable(
			serverVariable: "schema",
			default: "https",
			enum: ["https", "http"]
		)
	]
)]
```

Can I make that nameserver an editabel variable like here:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/36622631/152333481-99481fc8-9584-4bf7-8a1f-b0c1aa044e93.png">

**Comment by DerManoMann** [comment]
Seems this is answered so closing..
