### ISSUE TITLE
How to specify OA\MediaType in OA\RequestBody using Attributes?

### ISSUE THREAD

**Issue by caugner** [zircote/swagger-php#1096]
Using annotations, the `@OA\MediaType` annotation can be simply added as an additional unnamed parameter to `@OA\RequestBody`:

https://github.com/zircote/swagger-php/blob/dd5f1b7b84ffa86527e984b292c5223aeac5f50f/Examples/petstore.swagger.io/controllers/UserController.php#L35-L45

Using PHP Attributes, I would expect the following to work, but the `RequestBody` attribute constructor only accepts parameters `attachables`, `content`, `description` and `x`, but no additional parameters, such as `mediaType[s]`:

```php
use OpenApi\Attributes as OA;

#[OA\Post(
    path: "/user/createWithArray",
    tags: ["user"],
    summary: "Creates list of users with given input array",
    description: "",
    operationId: "createUsersWithArrayInput",
    requestBody: new OA\RequestBody(
        description: "List of user object",
        required: true,
        mediaType: new OA\MediaType(
            mediaType: "multipart/form-data",
            schema: new OA\Schema(
                type: "array",
                items: new OA\Items(ref: "#/components/schemas/User")
             )
         )
     ),
    responses: [
      new OA\Response(response: "default", description: "successful operation")
   ]
)]
 ```

**edit**: FWIW #1084 does not cover this.

**Comment by caugner** [comment]
Oh, it looks like I should be using `content` instead:

```
new OA\RequestBody(
    description: "List of user object",
    required: true,
    content: [
        new OA\MediaType(
            mediaType: "multipart/form-data",
            schema: new OA\Schema(
                type: "array"
                items: new OA\Items(ref: "#/components/schemas/User")
            )
        )
    ]
)
```

Unfortunately, `content` does not have a type annotation, which makes it hard to discover what it expects:

https://github.com/zircote/swagger-php/blob/84312fc48de177f74807d12e3f2895cacd09c0cb/src/Attributes/RequestBody.php#L21

**Comment by DerManoMann** [comment]
> edit: FWIW https://github.com/zircote/swagger-php/pull/1084 does not cover this.

About to merge this. After that PRs to improve documentation should be a lot easier :)
