### ISSUE TITLE
Attribute class "JetBrains\PhpStorm\ArrayShape" not found

### ISSUE THREAD

**Issue by Messhias** [zircote/swagger-php#1099]
After updating to the new version when I try to generate the documentation I'm getting this:

```
[2022-02-03 20:24:22] local.ERROR: Attribute class "JetBrains\PhpStorm\ArrayShape" not found {"exception":"[object] (Error(code: 0): Attribute class \"JetBrains\\PhpStorm\\ArrayShape\" not found at vendor/zircote/swagger-php/src/Analysers/AttributeAnnotationFactory.php:46)
[stacktrace]
#0 vendor/zircote/swagger-php/src/Analysers/AttributeAnnotationFactory.php(46): ReflectionAttribute->newInstance()
#1 vendor/zircote/swagger-php/src/Analysers/ReflectionAnalyser.php(128): OpenApi\\Analysers\\AttributeAnnotationFactory->build(Object(ReflectionMethod), Object(OpenApi\\Context))
#2 vendor/zircote/swagger-php/src/Analysers/ReflectionAnalyser.php(55): OpenApi\\Analysers\\ReflectionAnalyser->analyzeFqdn('App\\\\Classes\\\\Fin...', Object(OpenApi\\Analysis), Array)
#3 vendor/zircote/swagger-php/src/Generator.php(378): OpenApi\\Analysers\\ReflectionAnalyser->fromFile('...', Object(OpenApi\\Context))
#4 vendor/zircote/swagger-php/src/Generator.php(342): OpenApi\\Generator->scanSources(Object(Symfony\\Component\\Finder\\Finder), Object(OpenApi\\Analysis), Object(OpenApi\\Context))
#5 vendor/darkaonline/l5-swagger/src/Generator.php(181): OpenApi\\Generator->generate(Object(Symfony\\Component\\Finder\\Finder), Object(OpenApi\\Analysis))
#6 vendor/darkaonline/l5-swagger/src/Generator.php(122): L5Swagger\\Generator->scanFilesForDocumentation()
#7 vendor/darkaonline/l5-swagger/src/Http/Controllers/SwaggerController.php(60): L5Swagger\\Generator->generateDocs()
#8 vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): L5Swagger\\Http\\Controllers\\SwaggerController->docs(Object(Illuminate\\Http\\Request), 'api-docs.json')
#9 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('docs', Array)
#10 vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(L5Swagger\\Http\\Controllers\\SwaggerController), 'docs')
#11 vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#12 vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#13 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 vendor/darkaonline/l5-swagger/src/Http/Middleware/Config.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): L5Swagger\\Http\\Middleware\\Config->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#18 vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#19 vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#20 vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#21 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#22 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#23 app/Http/Middleware/CorsMiddleware.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CorsMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#41 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#42 public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#43 server.php(21): require_once('...')
#44 {main}
"} 

```

**Comment by Messhias** [comment]
Hi @DerManoMann, it's merged but right now I tried again to execute `php artisan l5-swagger:generate` and I'm still getting the same issue.

<img width="1408" alt="Screenshot 2022-02-04 at 08 48 14" src="https://user-images.githubusercontent.com/1161283/152499153-50e4713c-863b-46f3-990f-51d5d3d50b04.png">

**Comment by InfluxOW** [comment]
I had the same issue as mentioned above. But after updating to master branch the error changed a little.

`[2022-02-04 13:10:53] local.ERROR: Could not instantiate attribute: Attribute class "JetBrains\PhpStorm\ArrayShape" not found {"exception":"[object] (ErrorException(code: 0): Could not instantiate attribute: Attribute class \"JetBrains\\PhpStorm\\ArrayShape\" not found at /var/www/html/vendor/zircote/swagger-php/src/Loggers/DefaultLogger.php:27)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/vendor/zircote/swagger-php/src/Loggers/DefaultLogger.php(27): trigger_error()
#2 /var/www/html/vendor/psr/log/src/LoggerTrait.php(86): OpenApi\\Loggers\\DefaultLogger->log()
#3 /var/www/html/vendor/zircote/swagger-php/src/Analysers/AttributeAnnotationFactory.php(52): Psr\\Log\\AbstractLogger->warning()
#4 /var/www/html/vendor/zircote/swagger-php/src/Analysers/ReflectionAnalyser.php(128): OpenApi\\Analysers\\AttributeAnnotationFactory->build()
#5 /var/www/html/vendor/zircote/swagger-php/src/Analysers/ReflectionAnalyser.php(55): OpenApi\\Analysers\\ReflectionAnalyser->analyzeFqdn()
#6 /var/www/html/vendor/zircote/swagger-php/src/Generator.php(378): OpenApi\\Analysers\\ReflectionAnalyser->fromFile()
#7 /var/www/html/vendor/zircote/swagger-php/src/Generator.php(342): OpenApi\\Generator->scanSources()
#8 /var/www/html/vendor/darkaonline/l5-swagger/src/Generator.php(181): OpenApi\\Generator->generate()
#9 /var/www/html/vendor/darkaonline/l5-swagger/src/Generator.php(122): L5Swagger\\Generator->scanFilesForDocumentation()
#10 /var/www/html/vendor/darkaonline/l5-swagger/src/Console/GenerateDocsCommand.php(72): L5Swagger\\Generator->generateDocs()
#11 /var/www/html/vendor/darkaonline/l5-swagger/src/Console/GenerateDocsCommand.php(58): L5Swagger\\Console\\GenerateDocsCommand->generateDocumentation()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): L5Swagger\\Console\\GenerateDocsCommand->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#18 /var/www/html/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#20 /var/www/html/vendor/symfony/console/Application.php(1015): Illuminate\\Console\\Command->run()
#21 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#22 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#25 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#26 {main}
"} 
`

**Comment by Messhias** [comment]
> ### **[InfluxOW](/InfluxOW) ** commented [1 hour ago](#issuecomment-1029976778) •

@DerManoMann can you please give us feedback? I'm having problems in production because of that. I'll do a downgrade now.

**Comment by DerManoMann** [comment]
🤦 that stupid default logger. Yeah, that needs a bit more tweaking.

**Comment by Messhias** [comment]
> 🤦 that stupid default logger. Yeah, that needs a bit more tweaking.

So we'll reopen the issue?

**Comment by Messhias** [comment]
> 🤦 that stupid default logger. Yeah, that needs a bit more tweaking.

If you explain to me a little better how the library works might be I can help you, I have experience in open source contributions (I am still active in open source contributions by the way).

Might be I can help you with your merge request.

**Comment by DerManoMann** [comment]
Thanks for the offer but you are too late ;)

This one also was a bit special as I introduced a non critical log message.

OTOH, this is fine on the command line but with a framework in the mix there are usually additiona error handlers and the default logger in swagger-php unfortunately is abused to signal errors/warnings and calls `trigger_error` :/

Just merged a PR and the latest master should be good.

**Comment by Messhias** [comment]
> Thanks for the offer but you are too late ;)
> 
> This one also was a bit special as I introduced a non critical log message.
> 
> OTOH, this is fine on the command line but with a framework in the mix there are usually additiona error handlers and the default logger in swagger-php unfortunately is abused to signal errors/warnings and calls `trigger_error` :/
> 
> Just merged a PR and the latest master should be good.

When you push it on packist let me know.

**Comment by v131313** [comment]
just try
 composer require --dev jetbrains/phpstorm-attributes

**Comment by DerManoMann** [comment]
> When you push it on packist let me know.

Oh, didn't I? Well, updated now..

**Comment by DerManoMann** [comment]
> just try composer require --dev jetbrains/phpstorm-attributes

That is missing the point - the code should be able to deal with this without breaking.

**Comment by DerManoMann** [comment]
Fixed in 4.2.6

**Comment by Messhias** [comment]
Now we have the following:

```
[2022-02-10 10:46:30] local.ERROR: Required @OA\Info() not found {"exception":"[object] (ErrorException(code: 0): Required @OA\\Info() not found at /vendor/zircote/swagger-php/src/Loggers/DefaultLogger.php:31)
``` 

It's missing something mandatory now? If yes, might be necessary to change the documentation.

<img width="1440" alt="Screenshot 2022-02-10 at 10 47 48" src="https://user-images.githubusercontent.com/1161283/153391549-bbd4e075-18eb-4136-93e5-bc469fb5fc41.png">

**Comment by DerManoMann** [comment]
Might be worth opening a new issue for this as this is unrelated, IMO.
I would suspect you have a Info annotation somewhere, but not attached to a class/interface/trait/enums or so.
Since version 4 relies on reflection annotations are only read in places where reflection has access.
The docs actually changed quite a bit last week...
