### ISSUE TITLE
Auto generate annotations/attribute reference documentation

### ISSUE THREAD

**Issue by DerManoMann** [zircote/swagger-php#1102]
This looks like a 2-step task:
1. Add appropriate docblocks to annotations/attributes
2. Write a small script to generate `.md` files out of that

**Comment by jtreminio** [comment]
Wouldn't this be covered one of the [`openapi-generator` documentation generators](https://openapi-generator.tech/docs/generators/#documentation-generators)?

**Comment by DerManoMann** [comment]
Bad wording - I am talking about the docs here: https://zircote.github.io/swagger-php/reference/
