### ISSUE TITLE
Using constants as array

### ISSUE THREAD

**Issue by sachinbahukhandi-cometchat** [zircote/swagger-php#1103]
Hi,
I want to use refer to arrays as an index inside Swagger properties:
```
define('SUMMARY', ["summary1", "summary2"]);
```
Inside my Swagger Annotation:
I was accessing it as:
```
*   summary=SUMMARY[0]
```

But I am getting this error:
```
Error: [Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got '['
```

**Comment by DerManoMann** [comment]
You'd have to look at the doctrine annotations library docs to see what is possible.
I don't think this is going to work, though.

**Comment by jtreminio** [comment]
Constants as array definitely works, but what might be causing issues for you is the `[0]` part.

For example, this works for me:

```php
<?php

declare(strict_types=1);

namespace PetStoreApi\Model;

use OpenApi\Annotations as OA;

/**
 * @OA\Schema(schema="Pet")
 */
class Pet
{
    public const TYPE_ENUM = [
        'dog',
        'cat',
        'fish',
    ];

    /**
     * @var string
     * @OA\Property(type="string",
     *     enum=\PetStoreApi\Model\Pet::TYPE_ENUM
     * )
     */
    public $type;
}

```

If you want to reference a value within an array inside a constant, define another constant that reads the value:

```php
<?php

declare(strict_types=1);

namespace PetStoreApi\Model;

use OpenApi\Annotations as OA;

/**
 * @OA\Schema(schema="Pet")
 */
class Pet
{
    public const ENUM_DEFS = [
        'type' => [
            'dog',
            'cat',
            'fish',
        ],
    ];

    public const TYPE_ENUM = self::ENUM_DEFS['type'];

    /**
     * @var string
     * @OA\Property(type="string",
     *     enum=\PetStoreApi\Model\Pet::TYPE_ENUM
     * )
     */
    public $type;
}

```

**Comment by DerManoMann** [comment]
Ah, I see. 
I think you are out of luck then; the parsing of the annotations is done by the doctrine annotations library and we are constrained by what that can do

**Comment by sachinbahukhandi-cometchat** [comment]
Yes I read doctrine's thread and it said that due to security issues they do not evaluate the entered constant, thus expressions would not be of any use.

**Comment by DerManoMann** [comment]
Sounds reasonable, so I guess there is nothing to be done, unless you could switch to attributes, but obviously that is not possible all the time.

**Comment by sachinbahukhandi-cometchat** [comment]
Can we get that done on our end, maybe by extending the Doctrine's class as a PR for swagger-php?

**Comment by DerManoMann** [comment]
Happy to look at a PR, but the future is attributes, I think.

**Comment by sachinbahukhandi-cometchat** [comment]
By attributes you mean using refs?

**Comment by DerManoMann** [comment]
Closing as there is nothing more to say.
