### ISSUE TITLE
Promoted property type override not working with attributes

### ISSUE THREAD

**Issue by szeber** [zircote/swagger-php#1108]
When specifying an OA property and specifying a type for it AND using constructor property promotion, the type is going to be derived from the PHP type not the type specified by the `type` keyword.

Example code: 
```php
<?php
declare(strict_types=1);

use OpenApi\Attributes as OA;

#[OA\Info(version: '1.0', title: 'Demo')]
#[OA\Get(path: '/', responses: [new OA\Response(response: 204, description: 'demo response')])]
class Entrypoint
{
}

#[OA\Schema(schema: 'Test')]
class Request
{
    #[OA\Property(type: 'string', format: 'date-time')]
    protected DateTimeInterface $updatedAt;

    public function __construct(
        #[OA\Property] protected int $id,
        #[OA\Property(type: 'string', format: 'date-time')] protected DateTimeInterface $createdAt,
        DateTimeInterface $updatedAt,
    ) {
        $this->updatedAt = $updatedAt;
    }
}
```

When running `vendor/bin/openapi test.php --output test_openapi.json` to generate the API documentation the following JSON gets generated:
```json
{
    "openapi": "3.0.0",
    "info": {
        "title": "Demo",
        "version": "1.0"
    },
    "paths": {
        "/": {
            "get": {
                "responses": {
                    "204": {
                        "description": "demo response"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Test": {
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "createdAt": {
                        "type": "DateTimeInterface",
                        "format": "date-time"
                    },
                    "updatedAt": {
                        "type": "string",
                        "format": "date-time"
                    }
                },
                "type": "object"
            }
        }
    }
}
```

Expected: The `type` of the `createdAt` property will be `string` similar to how the `updatedAt` works.

Actual: The PHP type of `DateTimeInterface` is set as the type for `createdAt`

**Comment by DerManoMann** [comment]
Tricky one. I think I might have changed the priority order here; shouldn't the native type be used as that is the one PHP will enforce?
But, OTOH, serialised that is a different matter...

**Comment by szeber** [comment]
I would say since the type is inferred normally, if it's specified explicitly, then that should take precedence. In requests you may have a mapper that will parse the date from the request body and map it to the request object, and in responses you may use a class to represent a value and that class may have a `\JsonSerializable` implementation and that will serialize to a `string` for example.

So IMHO specifying the type should override what PHP says in this case.

**Comment by szeber** [comment]
Or in our case, we have a `JsonSerializable` implementation on our response classes that will turn Carbon or DateTime values to ISO-8601 strings when they are being serialized to JSON

**Comment by szeber** [comment]
Also thanks for the quick response to the issue and happy observed Waitangi day :D

**Comment by DerManoMann** [comment]
> Also thanks for the quick response to the issue and happy observed Waitangi day :D

Well, public holidays are good for things like posting on github issues :)
