### ISSUE TITLE
Type error when using Property inside Schema

### ISSUE THREAD

**Issue by gmeister2** [zircote/swagger-php#1129]
When using the example below, PHPStan gives an error:
> Parameter $properties of attribute class OpenApi\Attributes\Schema constructor expects array<string, mixed>|null, array<int, OpenApi\Attributes\Property> given.

```php
#[OA\Schema(
    schema: 'Result',
    description: 'Result text.',
    properties: [
        new OA\Property(
            type: 'object',
            property: 'result',
            description: 'Result data.',                
        ),
    ]
)]
```

You can specify an extra key, which generates the same openapi json and solves the PHPStan error, but this key seems redundant.

```php
#[OA\Schema(
    schema: 'Result',
    description: 'Result text.',
    properties: [
        'result' => new OA\Property(
            type: 'object',
            property: 'result',
            description: 'Result data.',                
        ),
    ]
)]
```

Above error also appears in other situations, for example when using MediaType inside RequestBody:
> Parameter $content of class OpenApi\Attributes\RequestBody constructor expects array<string, OpenApi\Attributes\MediaType>|OpenApi\Attributes\JsonContent|OpenApi\Attributes\XmlContent|null, array<int, OpenApi\Attributes\MediaType> given.

```php
#[OA\Post(
    path: '/file-upload',
    summary: 'Info text.',
    requestBody: new OA\RequestBody(
        required: true,
        content: [
            new OA\MediaType(
                mediaType: 'multipart/form-data',
                schema: new OA\Schema(
                    properties: [
                        new OA\Property(
                            description: 'File to upload.',
                            property: 'file',
                            type: 'string',
                            format: 'binary'
                        ),
                    ],
                    required: ['file']
                )
            ),
        ]
    ),
    responses: [
        new OA\Response(
            response: 200,
            description: 'ok'
        ),
    ]
)]
```

**Comment by DerManoMann** [comment]
PR #1131 shuold fix this - could you give that a go?

**Comment by gmeister2** [comment]
This fixes the issue for the doctype of src/Attributes/Schema,php.

Is it possible, if appropriate in this case, to also tweak src/Attributes/RequestBody.php, with a similar adjustment (see second error and example in my original post)?

**Comment by gmeister2** [comment]
What I meant to say is that I share caugner's (PR https://github.com/zircote/swagger-php/pull/1098) confusion as to why we need a dual declaration of for example 'multipart/form-data' (in the key, and as value of 'mediaType' inside the mediaType object).

Is the spec, Map[string, [Media Type Object], in this case not in reference to the final openapi json? Which is generated correctly regardless of the key value in front of the media object in the attributes.

ps. this library is much appreciated

**Comment by DerManoMann** [comment]
Ah, now I see. I think the type hints might confuse the spec structures with what swagger-php allows to do. I agree this could be simpler.
