### ISSUE TITLE
Question about private/public

### ISSUE THREAD

**Issue by pascalf22** [zircote/swagger-php#1134]
Hello !
I have a little question..
I want to instal swagger-php on my server... does documentation created by swagger-php will be private or public ? I mean.. on Swagger website.. when creating a new API.. if you want to make private, we have to be a paid member...

So my question is about that.. when creating documentation for API (using swagger-php and swagger-ui).. is it private ?

Thanks a lot ! 

Pascal

**Comment by DerManoMann** [comment]
That is entirely up to you. `swagger-php` itself is just a command line tool that will either print to stdout or into a local file.

If you use it via a plugin like [DarkaOnLine/L5-Swagger](https://github.com/DarkaOnLine/L5-Swagger) or [nelmio/NelmioApiDocBundle](https://github.com/nelmio/NelmioApiDocBundle) then things are a bit different. 

In that case, however, you need to look at what options those projects offer to protect things if needed.

**Comment by pascalf22** [comment]
Hello ! 
Thank you for your answer! I appreciated it ! 
Just to be sure, because i'm really, really new to swagger and the world of API.... so if i install it on my server(PHP) and it will scan my API folder... none of my documentations(api) will be saved to swagger website ? I mean, the only way to access the docs, will be from my server with the url ?

Thank you again !

Pascal

**Comment by DerManoMann** [comment]
Yes, that is correct. swagger-php does not submit any data at all to other websites.

**Comment by pascalf22** [comment]
Thank you so much !! I really appreciated it :) 
Have a great day !!
