### ISSUE TITLE
3.x Analyser contains switched deprecation comments

### ISSUE THREAD

**Issue by Revisor** [zircote/swagger-php#1135]
Hi, in the 3.x branch the `OpenApi\Analyser` contains deprecation notices for properties `$whitelist` and `$defaultImports`.
However the comments regarding the new recommended methods are switched.

- `$whitelist` recommends using `Generator::setAliases()`
- `$defaultImports` recommends using `Generator::setNamespaces()`

It should be the opposite.
- The replacement for `$whitelist` is `Generator::setNamespaces()`
- The replacement for `$defaultImports` is `Generator::setAliases()`

**Comment by DerManoMann** [comment]
v3.3.4 released
