### ISSUE TITLE
Is it possible to use attributes with php 8.0?

### ISSUE THREAD

**Issue by meoweloper** [zircote/swagger-php#1143]
I'm trying to migrate from annotations to attributes in my project. I'm using the example from the home page of the package - minimum required attributes and command line generating. 

Run the command using attributes and php 8 I get this message and nothing is generated except for version

```
Warning: Required @OA\Info() not found
Warning: Required @OA\PathItem() not found
```

Run the command using annotations and php 8 and everything is fine.
Run the command using attributes and php 8.1 and everything is fine.

I was just wondering if its possible to use php8 with attributes since my project is still on that version.

Thanks

**Comment by DerManoMann** [comment]
Some could probably work but a lot relies on nesting which only works with 8.1, sorry. 

There is also code using 8.1 type hints and some enum related code that would break.

So I guess you'll have to stick with annotations until you can upgrade.

**Comment by meoweloper** [comment]
I guess I'll have to upgrade.

Thanks a lot for the reply 🍺

**Comment by holtkamp** [comment]
_TLDR; "**nested** attributes" are used by this library which are only supported as of [PHP 8.1](https://www.php.net/releases/8.1/en.php#new_in_initializers)_

I also encountered this "wish" and my brain got stuck at this part of the explanation:

>Some could probably work but a lot relies on **nesting** which only works with 8.1

This might be obvious to some people, but I did not realise that nested attributes were not supported in PHP 8.0...

It only got introduced in 8.1: https://www.php.net/releases/8.1/en.php#new_in_initializers

Maybe this clarification helps others 😉
