### ISSUE TITLE
@OA\Info Not found

### ISSUE THREAD

**Issue by werlus** [zircote/swagger-php#1144]
I am trying to use the generator to create my spec .json file, but I continue to get issues. 

Warning: Skipping unknown AppBundle\Controller\PartnerApi\CatalogController
Warning: Skipping unknown AppBundle\Controller\PartnerApi\FundsBankController
Warning: Skipping unknown AppBundle\Controller\PartnerApi\PingController
Warning: Required @OA\Info() not found
Warning: Required @OA\PathItem() not found

My controller:
`use OpenApi\Annotations as OA;

/**
 * @OA\Info(title="Search API", version="1.0.0")
 */

/**
 * @Route("/partner/v1/ping", methods={"GET"})
 */
class PingController extends AbstractController
{
    /**
     * @OA\Get(path="/partner/v1/ping",
     * @OA\Response(response="200", description="Success"),
     * @OA\Response(response="400", description="Not found")
     * )
     */

    private Paginator $paginator;

    public function __construct(
        Paginator $paginator
    ) {
        $this->paginator = $paginator;
    }

    /**
     * @Route("")
     */

    }
}`

**Comment by DerManoMann** [comment]
Just for you :) https://zircote.github.io/swagger-php/guide/faq#warning-required-oa-info-not-found

**Comment by SerafimArts** [comment]
@DerManoMann This "hotfix" doesn't work:
```php
/** @OA\Info(title="Example", version="1.0.0") */
#[OA\Server(url: 'http://localhost/v4')]
abstract class Controller
{
}
```

If the attribute is replaced with an annotation, then everything is OK.
