### ISSUE TITLE
Is it possible to return an array in a responses 200?

### ISSUE THREAD

**Issue by pascalf22** [zircote/swagger-php#1146]
Hello !

Is there a way to return an array in a responses...

i mean, my api return something like this : 

```
{
    "status": "SUCCESS",
    "http_code": 200,
    "message": "",
    "data": {
        "token": {
            "access_token": "8a........",
            "refresh_token": "097d32bc77f...."
        },
        "ProfileInfos": {
            "userid": "1",
             "avatar" :"url de l'image"
             .....
         }
}
```

I am able to return status, http_code and messages... but how to return an array for "token" and for "profileInfos"

Thank you so much ! 
Have a great day ! 
Pascal

**Comment by DerManoMann** [comment]
Same way as in a request - you can use `@OA\JsonContent`

```
/*
 * @OA\Response(
 *     response=200,
 *     description="OK",
 *     @OA\JsonContent(
 *       ....
```

**Comment by pascalf22** [comment]
Great ! Thank you so much !!
I REALLY, REALLY appreciated it :)

Have a great day !
