### ISSUE TITLE
Running `openapi` commands does exactly nothing

### ISSUE THREAD

**Issue by KarlisJ** [zircote/swagger-php#1161]
Tried installing both to the project and globally with composer per documentation 

```
composer require zircote/swagger-php

composer global require zircote/swagger-php
```

typing `./vendor/bin/open..` has autocompletion so it's installed. 

However, I can't get any output form the commands

```
./vendor/bin/openapi app -o openapi.yaml
openapi app -o openapi.yaml
./vendor/bin/openapi -h -d
...
```

Always just getting a new line in console with nothing happening. 

Tried on php7 and php8.

**Comment by DerManoMann** [comment]
Strange. Have you checked what `./vendor/bin/openapi` actually is - ie. a symlink, file and what the actual content is?

Apart from that I've got no idea at all right now, sorry.

**Comment by KarlisJ** [comment]
It's an actual PHP script that I can debug with xDebug. Execution seems to be fine. The script receives the arguments and follows the intended flow. For example `-h` option will end up in the if statement that logs the help but seems that it dies at 
```
$logger->info($help);
```

and I can't also step into it. 

As for the generation, I've managed to get it running and `openapi.yml` file is created with content
```
openapi: 3.0.0
```

but nothing from the annotation in the code is picked up. 

I suppose if I could get the logger to work I could maybe see if there are any errors and instruction to fix them.

**Comment by gavin-harris-net-za** [comment]
I have exactly the same issue, any solution yet - I'm going to go back a version or two to see if that works.

**Comment by DerManoMann** [comment]
Have you got annotations without code? In that case have a look at the guide/faq

**Comment by syntheticminds** [comment]
I've just come across this.

```
$ ./vendor/bin/openapi -h
$
```

Digging around in the file, the help command runs `$logger->info($help);` but `ConsoleLogger()::log()` never actually does anything with it it seems.

zircote/swagger-php v4.2.15
PHP 8.0.15

**Comment by DerManoMann** [comment]
Hmm, interesting, will investigate

**Comment by arueckauer** [comment]
By setting `error_log` in `php.ini` I can reproduce the issue. With a set `error_log`, the output of the `error_log()` function is written to that log and nothing will appear in the console.

**Comment by DerManoMann** [comment]
Ha, that is a good one!

I think #1162 will help with that. Once error handling and logging are separate there is no more reason to use error_log but we can start using a standard PSR logger.

**Comment by DerManoMann** [comment]
@KarlisJ @gavin-harris-net-za @syntheticminds Could you please check if you have `error_log` set in your environments as one possible reason for this behaviour?

**Comment by syntheticminds** [comment]
```
$ php -i | grep error_log
Additional .ini files parsed => /opt/homebrew/etc/php/8.1/conf.d/error_log.ini,
error_log => /Users/matt/.config/valet/Log/php-fpm.log => /Users/matt/.config/valet/Log/php-fpm.log
opcache.error_log => no value => no value
```
