### ISSUE TITLE
Examples for work with attributes instead of annotations

### ISSUE THREAD

**Issue by Eugentis** [zircote/swagger-php#1164]
Hi

Do you have any plans or terms about more detailed and complex examples with attributes?

Sometimes it is hard to imagine which structure you expect as attribute. Especially for nested structures.

**Comment by DerManoMann** [comment]
I am working on improving the docs all the time. One aim was to make it easier for others to contribute :)

There are so far two working examples of attributes:
https://github.com/zircote/swagger-php/tree/master/Examples/using-links-php81
https://github.com/zircote/swagger-php/blob/master/tests/Fixtures/Apis/Attributes/basic.php

The main difference is that for nesting you need a parameter name; annotations could just be nested without a key (which is really a neat feature).

Hope that helps a bit.

**Comment by blueloveh** [comment]
Is it possible to specify the response as a json file and use it??

**Comment by DerManoMann** [comment]
@blueloveh I am not sure I understand your question.
Is this about example Json or an actual response from your app .

**Comment by DerManoMann** [comment]
Closing as I feel the original question has been answered. Any PRs to improve the docs are welcome...
