### ISSUE TITLE
Usage of ref in examples? Is it required

### ISSUE THREAD

**Issue by sachinbahukhandi-cometchat** [zircote/swagger-php#1166]
Hi,
I just came across using @OA\Examples.
I am confused on if is it even being used?

e.g:
```
 *      examples={
 *          @OA\Schema(ref="#/components/examples/result_1",  example="abc"),
 *          @OA\Schema(ref="#/components/examples/result_2",  example="abcd"),
 *      },
```

While defining it:
```
/**
 *       @OA\Examples(
 *       example="result_1",
 *       value=SWAGGER_EXAMPLE,
 *       summary="An result object. 1"
 *     ),
*/
/**
 *       @OA\Examples(
 *       example="result_2",
 *       value=SWAGGER_EXAMPLE,
 *       summary="An result object. 2"
 *     ),
*/
```

So my question is why is it needed while referencing and if provided why is it required inside @OA\Examples().
Thanks.

**Comment by DerManoMann** [comment]
It is used. However, you do not need to assign it to `examples`. Nested annotations are added without a key.

Keep in mind that swagger-php v4 requires all annotations to be associated with a structural element (class, etc). That is why there is a class `XYZ` to anchor the example annotations.

For example:
```
/**
 *   ....
 *      @OA\MediaType(
 *          ...,
 *          @OA\Examples(example="abc", value=1, summary="The ABC"),
 *          @OA\Examples(example="def", ref="#/components/examples/xyz")
 *      )
 *   ....
 */
public function handleRequest() { /* ... */ }


/**
 * @OA\Examples(example="xyz", value=2, summary="The XYZ")
 */
class XYZ {}
```

**Comment by sachinbahukhandi-cometchat** [comment]
Hi, I mean to say see inside example you provided `"abc"`.
What does it reference to?

**Comment by DerManoMann** [comment]
Look at the generated yaml and what it looks like in something like swagger-ui.
Examples is a map and `abc` will be the key. It can be a name for example 😜

**Comment by sachinbahukhandi-cometchat** [comment]
Ohh got it. Cool.
