### ISSUE TITLE
Reusable JsonContent BaseResponse

### ISSUE THREAD

**Issue by nirajfu3e** [zircote/swagger-php#1169]
I am trying to create the following JSON structure for a response body.
```json
{
     "data": [
          {
          "id": "1",
          "name": "FooBar",
          }
     ],
     "page": "string",
}
```
I can create this as follows:
```php
/**
* @OA\Get (
*     path="/api/v1/endpoint",
*     tags={"Tag Group"},
*     @OA\Response(
*      response="200",
*      description="OK",
*      @OA\JsonContent(
*          @OA\Property(property="data", type="array", @OA\Items(ref="#/components/schemas/DataResource")),
*          @OA\Property(property="page", type="string"),
*     ),
*    ),
* )
*/
```
The `page` property and other related property on these endpoints could be the same across 100s of endpoint. I was wondering if we could use a BaseResponse that merges with the custom `JsonContent` or if there is some way to extend the `JsonContent` in the response, if that's the right word. So I was expecting something like this to produce the same `json` as the above:
```php
// BaseResponse
/**
 * @OA\Response(
 *     response="BaseResponse",
 *     description="base response",
 *     @OA\Schema(
 *          @OA\Property(
 *              property="page",
 *              type="string"
 *          )
 *     )
 * )
 */
class BaseResponse {}
```

```php
/**
* @OA\Get (
*     path="/api/v1/endpoint",
*     tags={"Tag Group"},
*     @OA\Response(
*      response="200",
*      description="OK",
*      ref="#/components/responses/BaseResponse",
*      @OA\JsonContent(
*          @OA\Property(property="data", type="array", @OA\Items(ref="#/components/schemas/DataResource")),
*     ),
*    ),
* )
*/
```
That didn't work and I also tried a few other things like using `allOf` to combine the `JsonContent` but none of it seems to work. Is this even possible to achieve what I am trying here?

**Comment by DerManoMann** [comment]
I think you might be out of luck there.

The spec allows to 'extend` components using `allOf`, etc but that only works on the top level of the component. Merging of nested structures is not supported.

I guess the best you can do is use `refs` and '`allOf` inside `JsonContent` so at least you do not have to write all properties again and again, for example https://github.com/zircote/swagger-php/blob/master/Examples/example-object/OpenApiSpec.php#L86

**Comment by nirajfu3e** [comment]
Thanks @DerManoMann.

I actually got it do what I expected based on your advice. It was something like this for reference:
```php
*     @OA\Response(
*         response="200",
*         description="Request Response",
*         @OA\JsonContent(
*             allOf={
*                 @OA\Schema(ref="#/components/schemas/PaginationRefs"),
*                 @OA\Schema(
*                     type="object",
*                     @OA\Property(property="data", type="array", @OA\Items(ref="#/components/schemas/DataResource"))),
*             },
*         )
*     )
```
