### ISSUE TITLE
Is there a way to always stay logged in swagger-php UI ? (green padlock Authorize button)

### ISSUE THREAD

**Issue by pascalf22** [zircote/swagger-php#1178]
Hello !

I wonder if it's possible to prevent to always have to click on 'authorize' button on every page refresh to copy/past the token?

Is it possible, by code.. to specify the token to use on my dev server ? So on every refresh page or page load.. we will be logged in ?

Thank you so much ! 
Have a great day ! 
Pascal

**Comment by DerManoMann** [comment]
You'd have to store the token somewhere and then have code to retrieve it again on first load.

However, that is a question for the [swagger-ui project](https://github.com/swagger-api/swagger-ui) and unrelated to swagger-**php**.

**Comment by pascalf22** [comment]
Hello  
Thank you for your message! I really appreciated it ! 
I will contact swagger-ui project !

Thank you so much :)
Have a great weekend :)
