### ISSUE TITLE
Working with attributes, documentation and examples

### ISSUE THREAD

**Issue by perlowgren** [zircote/swagger-php#1180]
Hello,

I've spent several hours now trying to get the swagger-php to compile, but keep getting "Required @OA\Info() not found" and "Required @OA\PathItem() not found" warnings no matter what I do. It's the version 4.2.13. Almost all documentation and examples are for the annotations, but very little reference material for the attributes.

If I use annotations with block comments for @OA\Info then the attributes are not caught, and if I use it as an attribute it isn't registered.

Please include more documentation and examples how to use the attributes, like you have done for the annotations, because without a template it's difficult to tell what is missing.

Thanks!

**Comment by mroeling** [comment]
I exactly had the same issue, so thanks for the examples, very helpful!

The main issue for me was that I simply changed `@SWG` to `@OA`. But since we want to change to attributes, the second part needs to be changed as well. And now I also understand why it says OAT instead of OA... 
`// use Swagger\Annotations as SWG;`
`use OpenApi\Attributes as OAT;`
So, `Attributes` instead of `Annotations`... 

HTH

**Comment by DerManoMann** [comment]
Migrating from version 2 to 3 has its own rules too as this also switches to OpenAPI v3 - https://zircote.github.io/swagger-php/guide/migrating-to-v3

Once you've got that, switching from annotations to attributes should be (mosty) a change in syntax.

Biggest changes between annotations and attributes are that nesting always needs a parameter name whereas annotations can just be nested.

Also, keep in mind that both annotations and attributes need to be assocated with structural elements like class, enum etc. or methods and properties.

**Comment by DerManoMann** [comment]
If you feel the docs are lacking (which they do) - PRs are welcome. All that is needed is changing the `.md` files ...

**Comment by mroeling** [comment]
> If you feel the docs are lacking (which they do) - PRs are welcome. All that is needed is changing the `.md` files ...

I've started on the docs, some minor things for now, but will add more when I'm really starting. Now just reading and investigating. Full switch from Swagger due within couple of months.

**Comment by perlowgren** [comment]
Thank you for the quick response!

These examples should be enough to get started. Thanks!
