### ISSUE TITLE
[Documentation] Add requirement for PHP version

### ISSUE THREAD

**Issue by jtamyrc** [zircote/swagger-php#1181]
I check the [documentation](https://zircote.github.io/swagger-php/guide/installation.html), there is no requirement indicated for PHP version.

I tried with PHP 7.2 for swagger-php v4+ and there is some error. 

```
 Uncaught Error: Class 'PHPUnit\Framework\TestCase' not found in
 /var/www/html/vendor/psr/log/Psr/Log/Test/LoggerInterfaceTest.php:15
```

Please add PHP version support for each version of `swagger-php` in documentation.

**Comment by DerManoMann** [comment]
You are right, this is missing! Thanks for that.

So, requirements for annotations are PHP 7.2 and for using attributes PHP 8.1.

The error you posted, however, seems to be totally unrelated to swagger-php - Looks like you are trying to run the unit tests og the Psr/Log package - I think you'd need to provide a few more details about how you are trying to use swagger-php before anyone can help you.
