### ISSUE TITLE
Allow Tag attribute in class methods

### ISSUE THREAD

**Issue by aprat84** [zircote/swagger-php#1185]
Should be as easy as changing:
```php
// This
#[\Attribute(\Attribute::TARGET_CLASS | \Attribute::IS_REPEATABLE)]
class Tag extends \OpenApi\Annotations\Tag 
{
    // ...
}

// For this
#[\Attribute(\Attribute::TARGET_CLASS | \Attribute::TARGET_METHOD | \Attribute::IS_REPEATABLE)]
class Tag extends \OpenApi\Annotations\Tag 
{
    // ...
}
``` 

My use case is that, as I'm using NelmioApiDocBundle, it extracts the request info from the symfony `Route` attribute.
So, instead of adding a request attribute just for annotating tags `#[OA\Get(tags: ['some-tag'])]`, it would be much cleaner to just add the Tag attribute `#[OA\Tag('some-tag')]`.

**Comment by DerManoMann** [comment]
I had a look and actually this is more complicated. The `@OA\Tag` annotation (or attribute) is used to globally define tags.
This is done by using the annotation globally or nested inside `@OA\OpenApi`.

The `tags` array on operations is just a reference to those global tags. That means they do not accept a tag instance but just a tag name.

**Comment by DerManoMann** [comment]
This would need a new annotation/attribute with probably a new processor. CLosing for now, PRs welcome.
