### ISSUE TITLE
swagger-php and doctrine annotation not playing nice.

### ISSUE THREAD

**Issue by scoch** [zircote/swagger-php#119]
Hi,

I currently have swagger-php generating JSON formatted documentation through the commandline util swagger.phar. 

I am trying to do the same now for the models/OM but I am having issues with this. Our project currently uses Doctrine's @ ORM annotation for DB mapping and the two seem to be clashing.

My main question is (as I am not experienced with this) is @ ORM and @ SWG model annotations compatible? And if they are, do you have an example of them working in harmony?

If I include both in my annotation, the @ ORM annotation fails, causing my application to error. E.g:

https://gist.github.com/scoch/fd3efc5bb1e11a2f7fb1 

I've tried swapping their order various other ways but to no avail, it usually results in a    "message": "An exception was raised while creating \"classnamehere\"; no instance returned", error or the @ SWG model annotation above the class being ignored/ commandline error.

Thanks for any assistance you can provide.

Regards,
Steven

**Comment by CoderPoet** [comment]
you can `AnnotationReader::addGlobalIgnoredNamespace("SWG");`

**Comment by dennisameling** [comment]
Now that "SWG" [has been replaced](http://zircote.com/swagger-php/Migrating-to-v3.html) by "OA" for OpenAPI 3, the command becomes

`AnnotationReader::addGlobalIgnoredNamespace("OA");`

This solved the issue for me in working with both swagger-php and Doctrine ORM.

**Comment by yapro** [comment]
@dennisameling thank you!

My error in symfony:
```
HTTP 500 Internal Server Error [Semantical Error] The annotation "@OA\Post" in method
```
My solve the problem - add into the file config/bootstrap.php next string:
```
\Doctrine\Common\Annotations\AnnotationReader::addGlobalIgnoredNamespace("OA");
````
Result:
![image](https://user-images.githubusercontent.com/263248/77133874-c8c08700-6a75-11ea-8760-212c1cf08d68.png)
