### ISSUE TITLE
Basic Authentication  problem

### ISSUE THREAD

**Issue by brunopojani** [zircote/swagger-php#1192]
I have problem with basic authentication on swagger documentation is very clear 

```
openapi: 3.0.0
...
components:
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
security:
   basicAuth: []  # 
```

but when i try with zircote-swagger it doesnt work 

```
   @OA\SecurityScheme(
      type="http",
      in="header",
      securityScheme="basic",
      name="Authorization"
  )
 ```
 
 
![image](https://user-images.githubusercontent.com/24706075/162153512-a94141f2-bfe7-4dd5-93c8-f0c9052c6999.png)

**Comment by DerManoMann** [comment]
Could you post what your generated yaml looks like? If the security  schema is missing then I would suspect that you've recently upgraded and your annotations are standalone and therefore are ignored.

The [FAQ](https://zircote.github.io/swagger-php/guide/faq) has more details about what this means and how to fix it.

Basically your annotations need to be associated with a class (even a dummy one); something like this should be enough?

```php
/**
  * @OA\SecurityScheme(
  *       type="http",
  *       in="header",
  *       securityScheme="basic",
  *       name="Authorization"
  *   )
  */
class OpenApiSpec{}
```

**Comment by brunopojani** [comment]
Hi thank you for response I have already related the annotations with a dummy class , here is the json generated 

```
"basic": {
                "type": "http",
                "description": "Class Openapi",
                "name": "Authorization",
                "in": "header"
            }

```

**Comment by DerManoMann** [comment]
Looks like you are missing the `scheme: basic` bit, so setting that in the annotations should fix that.

**Comment by DerManoMann** [comment]
Looking at the reactions this can be closed.
