### ISSUE TITLE
getting syntax error, unexpected '|'

### ISSUE THREAD

**Issue by thakurakhilesh** [zircote/swagger-php#1197]
**PHP version**:  7.4
**swagger php version**: "zircote/swagger-php": "^4.2"

**Run command** : 
cd /path/to/swagger
cd ./vendor/zircote/swagger-php/bin
./openapi project path/ -o project path/swagger.json

**Error** :
ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in swagger/vendor/zircote/swagger-php/src/Attributes/AdditionalProperties.php:21

I am getting above error when we run command to generate swagger.json.

**Comment by DerManoMann** [comment]
You are trying to use PHP attributes with PHP 7.4 which does not work. Attributes in swagger-php require at least PHP 8.1.

Unless you can change your PHP version you will need to use annotations with are in the `OpenApi\Annotations` namespace.

**Comment by thakurakhilesh** [comment]
No, I am using "use OpenApi\Annotations as OA;"

I have downgrade swagger php version 4.2 to "zircote/swagger-php": "^3.0"
"doctrine/annotations": "^1.13"

In controller we are writing like below:
/**
 * @OA\Info(title="My First API", version="0.1")
 */
 
 /**
 * @OA\Get(
 *     path="/api/resource.json",
 *     @OA\Response(response="200", description="An example resource")
 * )
 */
 
 Now i getting below error:
 Error: [Semantical Error] Couldn't find constant User::CONSTANT.
Error: [Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got '(' at position 194.

when we run command to generate swagger.json.

**Comment by DerManoMann** [comment]
> No, I am using "use OpenApi\Annotations as OA;"

Not going to argue, but the error message explicitely references .../src/**Attributes**/AdditionalProperties.php; just saying.

>  Error: [Semantical Error] Couldn't find constant User::CONSTANT.

No idea.`User::CONSTANT` is not part of the swagger-php codebase so I would guess that comes from your sources.
It would be nice to get a reduced test case with a complete file. Also, when posting code could you please use [code block formatting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to make things more readable.

**Comment by thakurakhilesh** [comment]
Thanks for the quick reply. I'll take care of the code formatting from next time onwards.
