### ISSUE TITLE
Warning: Required @OA\Info() not found

### ISSUE THREAD

**Issue by LaBaude32** [zircote/swagger-php#1198]
Hi,

I made the update from 4.2.4 to 4.2.14 and i have that new error when i try to generate the doc with : `php vendor/bin/openapi -o public/doc/swagger.json src/ docs/docSwagger.php` : 

> Warning: Skipping unknown \MatosApp
> Warning:` Required @OA\Info() not found

That is my docSwagger.php : 

```php
<?php

use OpenApi\Annotations as OA;

/**
 * @OA\Info(
 *      title="Matos App API", 
 *      version="0.1",
 *      description="Application de gestion de materiel et bien plus"
 * )
 * @OA\Server(
 *      url="http://localhost:8000/api/v1",
 *      description="API server"
 * )
 */
class MatosApp
{
}

```

So i have check all the documentation and i don't find the problem in my code.
Where is my issue ? 

Regards !

**Comment by DerManoMann** [comment]
You might have missed this one then: https://zircote.github.io/swagger-php/guide/faq#warning-required-oa-info-not-found

**Comment by LaBaude32** [comment]
> You might have missed this one then: https://zircote.github.io/swagger-php/guide/faq#warning-required-oa-info-not-found

Hello, thank you for your answer. But I saw this explanation and I can't understand because my code is identical to the example given. So what did I miss?

**Comment by DerManoMann** [comment]
Sorry, you are right - I missed that bit. That's what you get for answering from my phone...

I think your problem is that in order for reflection to work all classes need to be auto loadable. I would expect that everything under `src` is covered by composer but the docs folder is not.

Using the `-b` option does help. For example, with your example _docSwagger.php_ file, running this command does work:
```
 ./bin/openapi -b foo/docSwagger.php foo/docSwagger.php
```

**Comment by LaBaude32** [comment]
I tried to but i still have that error : 

> Warning: Required @OA\Info() not found

So my Infos does not appear.

**Comment by DerManoMann** [comment]
Not sure what else to try. I've created a local copy of your docSwagger.php file and get this (gen is another empty folder, just to see that multiple sources work...)

```
$ ./bin/openapi -b scratch/foo/docSwagger.php gen scratch/foo
Warning: Required @OA\PathItem() not found
openapi: 3.0.0
info:
  title: 'Matos App API'
  description: 'Application de gestion de materiel et bien plus'
  version: '0.1'
servers:
  -
    url: 'http://localhost:8000/api/v1'
    description: 'API server'
```
Using the exact filename results in the same output...
```
 ./bin/openapi -b scratch/foo/docSwagger.php gen scratch/foo/docSwagger.php
```

**Comment by LaBaude32** [comment]
Ok thx ! I tried too, it works but only if I give the docSwagger.php twice. It's a odd behavior no ? 

> ./vendor/bin/openapi -b docs/docSwagger.php docs/docSwagger.php src -o public/doc/swagger.json

**Comment by DerManoMann** [comment]
First time is as argument to the -b option; that will load the file so reflection can find the class. That's what I tried to explain in my previous response.
