### ISSUE TITLE
How to configure basepath?

### ISSUE THREAD

**Issue by Glarionov** [zircote/swagger-php#1200]
I've used things I find online, like 

```
/**
 * @OA\Server(url="https://api.example.com/v3")
 */

/**
 * @OA\OpenApi(
 *     host="awesome.com",
 *     basePath="/whatever",
 */

```
 
above my controller class
 But it didn't work.
 
 What can I add to not add "api" to every path?

**Comment by DerManoMann** [comment]
Couple things:
- Try moving both annotations into a single docblock
- there is a surplus trailing ',' after `"/whatever"` (unless there is more that is cut off)
- there is a closing bracket ')' missing for the `OpenApi` annotation

Then, of course, `OpenApi` does not have a `host` or `basePath` property.

I suppose you could append `api` to the url in your `@OA\Server`?

There is also the option to look at my `openapi-router` package which contains a `Controller` annotation that allows to configure a `prefix` for all endpoints within the annotated controller: https://github.com/DerManoMann/openapi-router/blob/master/docs/AnnotationExtensions.md

Apart from that I suppose you are out of luck.

**Comment by DerManoMann** [comment]
Last ditch effort could be a custom processor that injects the prefix into all paths.
