### ISSUE TITLE
Cannot set `$in` target in `PathParameter` attribute

### ISSUE THREAD

**Issue by mathroc** [zircote/swagger-php#1204]
when creating a `#[PathParameter(in: 'query')]` the `$in` argument is ignored and always set to `path`

that's because the [ParameterTrait constructor](https://github.com/zircote/swagger-php/blob/0e4a64bbf0d476e310e5a5d4fe5d5e04cc8642ee/src/Attributes/ParameterTrait.php) ignores the argument if `$this->in` is not the `OpenApi\Generator` default value. but it's `path` so it always ignores the argument

**Comment by DerManoMann** [comment]
That's why it is called path parameter. What you want is just the `Parameter` annotation.

**Comment by mathroc** [comment]
> What you want is just the Parameter annotation.

oh, I want the `Paramater` attribute, but yes. so the `PathParameter` is just a shortcut for `Parameter(in: 'path', required: true)`, right?
