### ISSUE TITLE
Cannot add `Parameter` attribute to argument like `PathParameter`

### ISSUE THREAD

**Issue by mathroc** [zircote/swagger-php#1205]
I wanted to add the `Parameter` attribute to some route argument to describe query parameters (maybe headers and cookie too, later)
but [I got confused and tried it with the `PathParameter`](https://github.com/zircote/swagger-php/issues/1204) instead because the `Parameter` can't be applied to a function argument like the `PathParameter`

Is it possible to allow this? We created argument resolver in Symfony for those, and I'd like to replace the attribute we added with this one to avoid having duplicated information about the query parameters. This would make it easier to implement & read, and would prevent the OpenAPI annotation to be out of sync

**Comment by DerManoMann** [comment]
Stange. Both Parameter and PathParameter have the saem attribute flags set:
```
    #[\Attribute(\Attribute::TARGET_CLASS | \Attribute::TARGET_METHOD | \Attribute::TARGET_PARAMETER | \Attribute::IS_REPEATABLE)]

```

Have you perhaps accidentally tried to use an Annotation?
