### ISSUE TITLE
Include parameters based on context

### ISSUE THREAD

**Issue by mvanbeusekom** [zircote/swagger-php#1224]
In the light of DRY, it would be very useful if Swagger-PHP would be able to generate documentation for parameters based on already existing documentation formatted using phpDoc. 

Consider the following example (disclaimer, this is just some random method I quickly created):
```php
/**
 * Returns the name of the author.
 * 
 * This is a very difficult algoritm that uses some hard coding to return 
 * the name of the developer in a JSON formatted string. 
 * 
 * @param string format The format in which the name of the author should be formatted.
 */
#[OA\Get(
    path: '/api/resource',
    parameters: [
        new OA\Parameter(
            name: 'format',
            in: 'path',
        )
        ],
    responses: [
        new OA\Response(response:200, description: 'The data'),
    ]
)]
public function resource(string $format) {
    return "{ 'name': 'Maurits' }";
}
```

It would be great if it would match the parameter based on the supplied name and uses the type and description specified in the `@param ...` attribute to generate proper OpenAPI spec.

Current version (4.3) generates:
```yaml
openapi: 3.0.0
info:
  title: 'My First API'
  version: '0.1'
paths:
  /api/resource:
    get:
      summary: 'Returns the name of the author.'
      description: "This is a very difficult algoritm that uses some hard coding to return \nthe name of the developer in a JSON formatted string."
      operationId: c5b40d0336f4e61cf92eb33f2fd73c9f
      parameters:
        -
          name: format
          in: path
      responses:
        '200':
          description: 'The data'
```

The desired output would be:
```yaml
openapi: 3.0.0
info:
  title: 'My First API'
  version: '0.1'
paths:
  /api/resource:
    get:
      summary: 'Returns the name of the author.'
      description: "This is a very difficult algoritm that uses some hard coding to return \nthe name of the developer in a JSON formatted string."
      operationId: c5b40d0336f4e61cf92eb33f2fd73c9f
      parameters:
        -
          name: format
          in: path
          description: 'The format in which the name of the author should be formatted.'
          schema:
            type: string
      responses:
        '200':
          description: 'The data'
```

A related feature would be to automatically add parameters to the generated OpenAPI spec if they are available in the documentation but not included as a `OA\Parameter` attribute / annotation:

```php
/**
 * Returns the name of the author.
 * 
 * This is a very difficult algoritm that uses some hard coding to return 
 * the name of the developer in a JSON formatted string. 
 * 
 * @param string format The format in which the name of the author should be formatted.
 */
#[OA\Get(
    path: '/api/resource',
    responses: [
        new OA\Response(response:200, description: 'The data'),
    ]
)]
public function resource(string $format) {
    return "{ 'name': 'Maurits' }";
}
```

Desired output:
```yaml
openapi: 3.0.0
info:
  title: 'My First API'
  version: '0.1'
paths:
  /api/resource:
    get:
      summary: 'Returns the name of the author.'
      description: "This is a very difficult algoritm that uses some hard coding to return \nthe name of the developer in a JSON formatted string."
      operationId: c5b40d0336f4e61cf92eb33f2fd73c9f
      parameters:
        -
          name: format
          in: null
          description: 'The format in which the name of the author should be formatted.'
          schema:
            type: string
      responses:
        '200':
          description: 'The data'
```

**Comment by DerManoMann** [comment]
It would be nice, agreed :)

In fact, this is almost possible already, although there is still an issue with docblock comments in the latest release.

A somewhat shorter way would be to:
* Move the response outside - this is a personal preference, but I think it reads easier (but unrelated to the issue itself)
* Move the parmeter attribute to actually annotate the parameter :) That allows the code to use reflection to inspect the parameter details like type, etc.

```php
    /**
     * Returns the name of the author.
     *
     * This is a very difficult algoritm that uses some hard coding to return
     * the name of the developer in a JSON formatted string.
     *
     * @param string format The format in which the name of the author should be formatted.
     */
    #[OA\Get(path: '/api/resource2')]
    #[OA\Response(response: 200, description: 'The data2')]
    public function resource(
        #[OA\PathParameter] ?string $format
    )
    {
        return "{ 'name': 'Maurits' }";
    }
```
Using latest `master` this results in:
```yaml
  /api/resource2:
    get:
      operationId: 66028f29429a4ea1e001634ef41eab98
      parameters:
        -
          name: format
          in: path
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'The data2'
```

**Comment by mvanbeusekom** [comment]
That indeed looks promising. I wouldn't mind moving the parameter attribute to annotate the actual parameter, however at the moment this is only supported for path parameters. We also make extensive use of query parameters and body parameters (via POST/ PUT requests) and of course would like to cover those as well.

And maybe obvious the biggest duplication is the description. We put quite some effort in documenting all our public members and of course it would help a lot if Swagger-PHP could just pick it up so we don't have to duplicate it.

Let me finish with saying: thank you, you are doing an amazing job and we are very happy using Swagger-PHP. If helpful I think I can help and create a PR for adding a `QueryParameter` and `BodyParameter` attribute. However not sure if there is more involved than just adding those new attributes.

**Comment by DerManoMann** [comment]
PathParameter is the only specialised version. Just `Parameter` should also work, you just need to also set the `in` option.

**Comment by mvanbeusekom** [comment]
Hi @DerManoMann,

Looking at the alternative mentioned using the `PathParameter` (or `Parameter`) attributes and the generated output you mentioned, it seems the description is not copied over from the `@param` definition. For us this would be the biggest advantage as we document parameters quite extensively and would really benefit from not having to repeat ourselves.

B.t.w. we also have some projects that are documented using docblock annotations, would something similar be possible here as well? 

I am more then willing to put some time in to setting up a PR if that helps?

**Comment by DerManoMann** [comment]
I can appreciate your comment about fragmentation, but that is the nature of metadata (annotations/attributes) that it is supposed to be close to the code it annotates.

Not sure I can follow the issue about examples - in both examples they are nested inside the `Parameter` so that doesn't really change with moving the `Parameter` attribute.

Moving the attributes into the method has the additional advantage of picking up the data type - some frameworks allow parameters to be typed and will cast the value into the right type, so you could have a `int $id)` parameter to a method that looks up data by `id` and the attribute would refect this.

As for a PR, sure. There might be opinions about how to do things but I am always happy for people to fix issues themselfs :)

I would think that the method docblock is available in the context of the `Get` attribute (which is a `Operation` subclass. Based on that a processor similar to `DocBlockDescriptions` should be possible (iterating over all `Operation` annotations).
Happy to help if needed, of course.

**Comment by DerManoMann** [comment]
Had a bit of a play which ended up in quite some refactoring :roll_eyes: PR coming soon I hope...

**Comment by mvanbeusekom** [comment]
Great work, thanks @DerManoMann!
