### ISSUE TITLE
Error Skipping unknown \CreateTypesTable

### ISSUE THREAD

**Issue by rmeira** [zircote/swagger-php#1231]
What's up guys, i need a help...

The following error below is happening to me.
I don't know how to solved this

```
Skipping unknown \CreateTypesTable

# my function...
public function api()

    {

        return response(Generator::scan([module_path('FinanceSupport', '')])->toJson());

    }
```

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/8323576/167508053-a23369a6-4eca-4040-a000-38627b05cda2.png">

**Comment by DerManoMann** [comment]
Typcally this means that the class in question cannot be auto loaded. Usually this happens when the namespace is not correct.
https://zircote.github.io/swagger-php/guide/faq#skipping-unknown-someclass
