### ISSUE TITLE
OpenApi\Attributes\Tag Attribute not working

### ISSUE THREAD

**Issue by axellworks** [zircote/swagger-php#1234]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/41114642/168246294-64c68a0a-8f73-4882-b046-bd541f3947d1.png">

**Comment by DerManoMann** [comment]
Ah, it would be good to see a bit more context here.
The tag attribute is typically at the top level or nested inside the OpenApi attribute so it doesn't make much sense on method level.

**Comment by axellworks** [comment]
@DerManoMann Im trying to use it like in this example from symfony documentation
```
namespace AppBundle\Controller;

use AppBundle\Entity\Reward;
use AppBundle\Entity\User;
use Nelmio\ApiDocBundle\Annotation\Model;
use Nelmio\ApiDocBundle\Annotation\Security;
use OpenApi\Attributes as OA;
use Symfony\Component\Routing\Annotation\Route;

class UserController
{
    /**
     * List the rewards of the specified user.
     *
     * This call takes into account all confirmed awards, but not pending or refused awards.
     */
    #[Route('/api/{user}/rewards', methods=['GET'])]
    #[OA\Response(
        response: 200,
        description: 'Returns the rewards of an user',
        content: new OA\JsonContent(
            type: 'array', 
            items: new OA\Items(ref: new Model(type: AlbumDto::class, groups: ['full']))
        )
    )]
    #[OA\Parameter(
        name: 'order',
        in: 'query',
        description: 'The field used to order rewards',
        schema: new OA\Schema(type: 'string')
    )]
    #[OA\Tag(name: 'rewards')]
    #[Security(name: 'Bearer')]
    public function fetchUserRewardsAction(User $user)
    {
        // ...
    }
}
```

https://symfony.com/bundles/NelmioApiDocBundle/current/index.html

**Comment by axellworks** [comment]
By using annotations, all works perfect, but when switch to Attributes, this doesn't work

**Comment by DerManoMann** [comment]
I see. Hmm, this is, in fact, the same as #1185. Looks like the bundle allows tag on routes which is not hiw swagger-php itself works. I guess there is no harm in allowing tags to make the bundle code happy.
