### ISSUE TITLE
Unable to generate swagger yaml

### ISSUE THREAD

**Issue by sjathin** [zircote/swagger-php#1237]
I am trying to use swagger-php for the first time, but I am unable to generate any swagger yaml files. 

`src/OpenApiSpec.php`:
```
<?php

namespace MyNamespaceName;

use OpenApi\Annotations as OA;

/**
 * @OA\Tag(
 *     name="user",
 *     description="User related operations"
 * )
 * @OA\Info(
 *     version="1.0",
 *     title="Example for response examples value",
 *     description="Example info",
 *     @OA\Contact(name="Swagger API Team")
 * )
 * @OA\Server(
 *     url="https://example.localhost",
 *     description="API server"
 * )
 */
class OpenApiSpec
{
}
?>
```

When I Run the command:
`./vendor/bin/openapi -b ./vendor/autoload.php src`

I get errors:

```
Warning: Skipping unknown MyNamespaceName\OpenApiSpec
Warning: Required @OA\Info() not found
Warning: Required @OA\PathItem() not found
openapi: 3.0.0
```

Can someone let me know where I am going wrong?

**Comment by DerManoMann** [comment]
I would think that composer autoloading is not configured correctly.

Make sure you have the following in your `composer.json` 

```yaml
    "autoload": {
        "psr-4": {
            "MyNamespaceName\\": "src"
        }
    }
```

and then run 
```shell
composer dumpautoload
```

After that your namespaced classes should be found by the composer autoloader..

**Comment by sjathin** [comment]
This worked, able to generate the YAML now.
