### ISSUE TITLE
OpenApi\Attributes\SecurityScheme only allowed on classes

### ISSUE THREAD

**Issue by gmeister2** [zircote/swagger-php#1241]
Would it be possible to also allow setting a SecurityScheme on methods and properties?
Reason would be to list multiple of them inside one class.

**Comment by DerManoMann** [comment]
I guess we could. Why would that semantically make more sense than on the class itself? The scheme would not be restricted to a property or method?

**Comment by gmeister2** [comment]
I set it up like this for my common parameters, and thought of doing the same for the SecuritySchemes.
This file/class is not actually used, it is just a place to list reusable openapi components.

But admittedly, the semantic improvement might be somewhat arbitrary.

```php
<?php declare(strict_types=1);

namespace Src\OpenApi\Schemas;

use OpenApi\Attributes as OA;

class CommonParameters
{
    #[OA\Parameter(
        parameter: 'lang',
        name: 'lang',
        in: 'path',
        description: '',
        required: true,
        schema: new OA\Schema(
            type: 'string',
        ),
    )]
    public string $lang;

    #[OA\Parameter(
        parameter: 'module',
        name: 'module',
        in: 'path',
        description: '',
        required: true,
        schema: new OA\Schema(
            type: 'string',
        ),
    )]
    public string $module;
}
```
