### ISSUE TITLE
Is oneOf, anyOf, allOf schema's type set to 'object' expected behaviour?

### ISSUE THREAD

**Issue by Moussa112** [zircote/swagger-php#1253]
In the following commit #1199; in the `src/Processors/AugmentSchemas.php` file the schema type of the "oneOf, anyOf, allOf" date models is being set to object. This is new behaviour and is the cause of new validation errors.

For example I have a schema with a property that can be a string or number that looks like this:

```
    /**
     * @var mixed
     * @OA\Property(oneOf={@OA\Schema(type="string"), @OA\Schema(type="number")})
     */
    public $after;
```
this used to generate the following swagger doc:
```
"after": {
    "oneOf": [
            {
                "type": "string"
            },
            {
                "type": "number"
            }
        ]
}
```
with the changes in #1199 this now generates the following swagger doc:
```
"after": {
    'type": "object"
    "oneOf": [
            {
                "type": "string"
            },
            {
                "type": "number"
            }
        ]
}
```

The new doc causes a validation error that an object is required when I pass a string or number.
Is this new behaviour intended and should I refactor my code?

**Comment by DerManoMann** [comment]
I'd say that is a bug :/
