### ISSUE TITLE
Conflict between Symfony, `swagger-php`, and NelmioApiDocBundle?

### ISSUE THREAD

**Issue by copiri-six** [zircote/swagger-php#1261]
I'm not sure this is a bug, but I've been searching for hours and haven't found anything to resolve a conflict I'm seeing.  In short: I can't seem to document multiple routes such that they are accepted by both Symfony and `swagger-php`, and viewable by `NelmioApiDocBundle`.

Here's what I'm trying to do:

```
public function myFunction(?int $var1, ?string $var2 = ""): Response
```

`$var2` is optional, so I have the following Symfony routing annotations:

```
 * @Route("/endpoint/{var1}/extra", name="var_1", methods={"POST"})
 * @Route("/endpoint/{var1}/extra/{var2}", name="var_2", methods={"POST"})
```

And to document it for Swagger, I have (reduced to only the things that cause trouble):

```
/**
 * @OA\Post(
 *     path="/endpoint/{var1}/extra",
 *     operationId="var_1",
 *     tags={"My Tag"}
 * ),
 * @OA\Post(
 *     path="/endpoint/{var1}/extra{var2}",
 *     operationId="var_2",
 *     tags={"My Tag"}
 * )
 */
```

The problem is this:

- When I include both the `@Route` and the `path`, NelmioApiDocBundle ignores the tags, and combines the two endpoints into one.  It also seems to take some combination of the values... for example if only one is `deprecated`, the single endpoint that's viewable will be deprecated, even if the actual path being shown is not the path that was deprecated.  Regardless, the upshot is that the human-viewable docs are incorrect because instead of 2 endpoints, only one is visible... and it's in the "Default" tag group instead of where it should be.

- When I remove the `@Route` and keep the `path`, as you would expect, Symfony no longer recognizes the route and calls fail.  Nothing is visible in NelmioApiDocBundle's view.

- When I remove the `path` and keep the `@Route`, the API calls work but I get a stack of warning from `swagger-php`:
- - `User Warning: Multiple definitions for @OA\Post()->operationId`
- - `User Warning: Multiple definitions for @OA\Post()->parameters`
- - `User Warning: Multiple definitions for @OA\Post()->responses`
- - `User Warning: operationId must be unique. Duplicate value found: "var_1"`

Note that the warnings about the duplicate `operationId` values are seen even though the values are unique through the entire API.  

I've got to be missing something here... can anyone tell me what?  Thanks!

**Comment by copiri-six** [comment]
I just found a related bug at the `nelmio\api-doc-bundle` repo, which might be the cause of the first problem listed.  Not sure if it would cause the third item, as those are coming from this library.  A full error is below:

```
php.WARNING: User Warning: operationId must be unique. Duplicate value found: "var_1" {"exception":"[object] (ErrorException(code: 0): User Warning: operationId must be unique. Duplicate value found: \"var_1\" at /app/vendor/zircote/swagger-php/src/Loggers/DefaultLogger.php:31
```

Thanks for any thoughts!

**Comment by DerManoMann** [comment]
Tricky one - I guess you could try to run just swagger-php over your code and see what comes out of that. It might be incomplete as the data from all non-swagger-php annotations will be missing. However it will give you some insight into just the OpenApi annotations.

Something like
```
./bin/openapi src -o swagger_only_spec.yaml
```

As far as merging with `@Route` and others is concerned that is definitely something to discuss over at `NelmioApiDocBundle`.

Sidenote: the second annotation in your example is missing a `/`:
```path="/endpoint/{var1}/extra{var2}",```

**Comment by DerManoMann** [comment]
Looks like this got resolved via https://github.com/nelmio/NelmioApiDocBundle/issues/1993, so closing.
