### ISSUE TITLE
Validation on Windows vs Linux

### ISSUE THREAD

**Issue by monsterlane** [zircote/swagger-php#1264]
I'm using Lumen and this package to document an API. The routes are defined in the controllers, schema's in models, and I have a directory full of re-usable schema's and info files. One example being;

```
<?php

namespace App\Specs;

use OpenApi\Annotations as OA;

/**
 * @OA\Info(
 *     title="My API",
 *     version="1.0",
 *     description="My cool API",
 * )
 */

class OpenApi
{
}
```

I'm using an artisan command to generate docs:

```
public function handle(Generator $openApiService): void
{
    $paths = [app()->basePath('app')];
    $options = ['validate' => !((PHP_OS_FAMILY === 'Linux'))]; // ???

    $docs = $openApiService::scan($paths, $options);

    Storage::disk('root')->put($this->file, $docs->toYaml());

    $this->info('./' . $this->file . ' was generated.');
}
```

This works fine on Windows, but when Jenkins runs my unit test it fails with the following error:

```
Tests\Commands\CommandsTest::testMakeDocs
ErrorException: Required @OA\PathItem() not found
```

I've narrowed this down to `src/Annotations/AbstractAnnotation.php` around line 469:
```
if ($this instanceof OpenApi) {
    $message = 'Required ' . Util::shorten($class) . '() not found';
```

If I print `$this->_context` it shows the placeholder files like the one above.

`Required @OA\PathItem() not found /root/Projects/app/Specs/OpenApiSpec.php on line 88`

The documentation gives an example of doing this, why does this work on Windows and not Linux? It seems it's validating per file instead of across the entire project as I do have paths defined in controllers. Setting validate to false does generate a valid openapi.yaml I've checked the schema in SwaggerHub. On Windows it runs fine via artisan or the CLI with validate=true.

**Comment by DerManoMann** [comment]
Hmm, your code looks reasonable. 

The most obvious reason for me would be around upper/lower case of classes and filenames.
Related to that is the question of both ways use the same composer autoloading; ie. optimized yes/no?
Finally, it shouldn't matter but perhaps the order in which files are processed is different and does matters; in your case ?!?

OTOH, you say the spec file is correct without validation? Hard to imagine since the code suggests that the given `OpenApi` instance does not have `OpenApi::$paths` set.

All speculation I know but this looks hard to debug without a working (broken) example. If you feel like it I'd be happy to look at a small repo that replicates the issue.

Funny, from the title I'd have expected things to break on Windows :) I have been wondering lately if it is worth looking at running the swagger-php tests on Windows...

**Comment by tim-breitenstein-it** [comment]
I run into the same Exception by using a Slim Application running on Windows.

`app/routes.php`
```
<?php
declare(strict_types=1);

use OpenApi\Annotations as OA;
use OpenApi\Generator;
use OpenApi\Util;
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\App;
use Slim\Exception\HttpNotFoundException;
use Slim\Interfaces\RouteCollectorProxyInterface as Group;

/**
 * @OA\Info(
 *     title="Endpoint Server",
 *     version="0.1.0"
 * ),
 * @OA\Server(
 *     url="http://localhost:8080/api"
 * )
 */
return function (App $app) {

    /**
     * CORS Pre-Flight OPTIONS Request Handler
     */
    $app->options('/{routes:.*}', function (Request $request, Response $response) {

        return $response;

    });

    /**
     * Header: application/json
     */
    $app->add(function (Request $request, $handler): Response {

        $response = $handler->handle($request);

        return $response
            ->withHeader('Content-Type', 'application/json')
            ->withHeader('Access-Control-Allow-Origin', '*')
            ->withHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type, Accept, Origin, Authorization')
            ->withHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');

    });

    /**
     * Swagger
     */
    $app->get('/doc', function (Request $request, Response $response): Response {

        //$openapi = Generator::scan([__DIR__]);

        $openapi = Generator::scan(
            Util::finder(
                __DIR__,
                [
                    'dependencies.php',
                    'middleware.php',
                    'repositories.php',
                    'settings.php'
                ],
                '*.php'
            ),
            [
                'validate' => true
            ]
        );

        $payload = $openapi->toJson();

        $response->getBody()->write($payload);

        return $response;

    });

    $app->group('/api', function (Group $group) {
    
        /**
         * @OA\Get(
         *     path="/api/test",
         *     @OA\Response(
         *         response="200",
         *         description="An example resource"
         *     )
         * )
         */
        $group->get('', function (Request $request, Response $response) {

            $payload = json_encode(array('Hello Typo3!'));
            
            $response->getBody()->write($payload);

            return $response;

        });
    
    });

    /**
     * CORS
     */
    $app->map(
        ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'],
        '/{routes:.+}',
        function (Request $request): Response {

            throw new HttpNotFoundException($request);

        }
    );
};
```

`composer start`

`http://localhost:8080/doc`

```
{
  "statusCode": 500,
  "error": {
    "type": "SERVER_ERROR",
    "description": "WARNING: Required @OA\\PathItem() not found"
  }
}
```

**Comment by DerManoMann** [comment]
@tim-breitenstein-it As of version 4 of swagger-php annotations must be associated with structural elements like classes, methods, interfaces, traits, properties or similar.
Annotating anonymous functions does not work any more as the code relies on reflection for certain things. This was a requirement to make annotations and attributes behave the same.

You can fallback to using the v3 analyser by passing an instance into the scan method:
```
        $openapi = Generator::scan(
            Util::finder(
                __DIR__,
                [
                    'dependencies.php',
                    'middleware.php',
                    'repositories.php',
                    'settings.php'
                ],
                '*.php'
            ),
            [
                'validate' => true,
                'analyser' => new OpenApi\Analysers\TokenAnalyser(),
            ]
        );

```

**Comment by DerManoMann** [comment]
Closing as inactve.
