### ISSUE TITLE
Hard to find out problem with invalid attribute

### ISSUE THREAD

**Issue by zim32** [zircote/swagger-php#1267]
Right now, invalid attribute is logged with DEBUG level.
Default logger just ignores this level.

So it is impossible to know if something whent wrong f.e.when instantiating OA\Get(...) attribute throws excpeption, it is silently dropped.
Don't know how to improve, just point this issue.

**Comment by DerManoMann** [comment]
I guess this depends on whether you are using a 3rd party tool or swagger-php directly. 

You can always pass a custom `Psr\Logger` instance into the `Generator` or run `./bin/openapi` with `--debug`

**Comment by DerManoMann** [comment]
I suppose https://github.com/zircote/swagger-php/blob/master/src/Analysers/AttributeAnnotationFactory.php#L52 could be conditional depending on whether the attribute class was OpenApi related or not.

Not being able to instantiate unrelated attributes (for example `JetBrains\PhpStorm\Pure` or similar) should not be considered important in the context of `swagger-php`.

**Comment by zim32** [comment]
> I guess this depends on whether you are using a 3rd party tool or swagger-php directly.
> 
> You can always pass a custom `Psr\Logger` instance into the `Generator` or run `./bin/openapi` with `--debug`

Maybe it should be more explicitly mentioned in the docs. Because I need to spend quite a lot of time to figure out the problem

**Comment by naitsirch** [comment]
I had the same issue and it took me several hours to find the reason why a property wasn't added to the spec. I hope my PR gets merged to prevent this kind of issues.
