### ISSUE TITLE
Merging API declarations sharing the same path

### ISSUE THREAD

**Issue by timwhitlock** [zircote/swagger-php#127]
I don't know if this is already supported, or if I'm doing it wrong, but I recently found my doc blocks getting so large that I started splitting up API annotations into multiple places for multiple operations. This was split in such a way that I had to duplicate the `@SWG\Api` declaration.

This has the effect that multiple operations under the same path are listed in the exported data as separate APIs. It doesn't actually appear to be a huge problem - swagger-ui and other consumers simply merge them - but it looks a bit odd in the raw JSON and I'm wondering if it's a limitation or if I'm doing something odd.

Either way, I ended up merging the operations myself before writing out my JSON. No big deal, but would be cool if the resources were added to the same `apis` index if the path is an exact match - perhaps checking for some other data (such as description) that implies they should be kept separate. 

I'm happy to fork this and have a go myself, but just wanted to check whether this is inline with how the whole thing should work.

**Comment by bfanger** [comment]
Inspired by this issue, instead of:
```php
/**
 * @SWG\Path(
 *   path="users"
 *   @SWG\Operation(
 *     method="get",
 *     summary="List all users"
 *   )
 * )
 */
```
In swagger-php **2.x** you'll write:

```php
/**
 * @SWG\Get(
 *   path="users",
 *   summary="List all users"
 * )
 */
```
And swagger-php merges the operations with the same paths.
