### ISSUE TITLE
Transform nested response attribute to not nested attribute

### ISSUE THREAD

**Issue by nsinisterra** [zircote/swagger-php#1278]
Hi there,

I'm rewriting our Swagger 2 docs to Swagger 3 and migrating to Attributes, all in :trollface: 

I have successfully transformed one of our endpoints
```php
    #[OA\Get(path: '/api/v3/sites/{siteId}/tags', operationId: 'getTagsForSite', security: [['api_key' => []]], tags: ['Tags'])]
    #[OA\Parameter(name: 'siteId', in: 'path', required: true, schema: new OA\Schema(type: 'string'))]
    #[OA\Response(
        response: 200,
        description: 'Tag object',
        content: new OA\JsonContent(
            required: ['data'],
            properties: [
                new OA\Property(property: 'data', items: new OA\Items('#/components/schemas/Tag'))
            ],
            type: 'object'
        )
    )]
    #[OA\Response(response: 401, description: 'Unauthorized - Check credentials')]
    #[OA\Response(response: 404, description: 'Site not found')]
    public function index(Site $site, Request $request)
```

The expected response example works fine:

```json
{
  "data": [
    {
      "id": 123,
      "content": "ExampleTag"
    }
  ]
}
```

But, honestly, I'm not really happy with the response block, I feel that this should be "de-nested", I have tried with multiple structures, but this is just ignored (https://github.com/zircote/swagger-php/issues/1151).

## First attempt
```php
    #[OA\Get(path: '/api/v3/sites/{siteId}/tags', operationId: 'getTagsForSite', security: [['api_key' => []]], tags: ['Tags'])]
    #[OA\Parameter(name: 'siteId', in: 'path', required: true, schema: new OA\Schema(type: 'string'))]
    #[OA\Response(response: 200, description: 'Microtag object')]
    #[OA\JsonContent(required: ['data'])]
    #[OA\Property(property: 'data',type: 'object')]
    #[OA\Items('#/components/schemas/Microtag')]
    #[OA\Response(response: 401, description: 'Unauthorized - Check credentials')]
    #[OA\Response(response: 404, description: 'Site not found')]
    public function index(Site $site, Request $request)
```

The result is that the content is just ignored. The `200 response` is documented but without body.

Checking the [reference](https://zircote.github.io/swagger-php/reference/annotations.html#response) I saw that Response doesn't have JsonContent as Nested elements neither. Added to that JsonContent has just `CLASS` as target, not method.

Then, is possible write this response in a simpler way?

Thanks so much!

**Comment by DerManoMann** [comment]
Unfortunately no. De-nesting is possible as long as all attributes In a group can be nested again in an un-ambiguous manner.

I an not quite sure why nesting is such a big deal as it clearly shows the dependencies; in the flat structure it requires a lot more mental effort to see these relationships, IMHO.

Were your SWG annotations also that flat?

**Comment by nsinisterra** [comment]
Thanks for your fast answer and hard work @DerManoMann!

Understood, and makes sense. Honestly, is not a deal at all, is just personal preference. The actual way is thousand time better than my old SWG annotations.


I wasn't very convinced about the required docblock length required for this kind of documentation, I feel that long dockblocs made the class readability harder. The not nested way seem to be shortest for me, but again, is just for personal preferences.

As the main question is solved (The Response attribute can't be de-nested), i'll close the issue, but feel free to reopen or write again :)

Thanks again!
