### ISSUE TITLE
Swagger displaying .json in path

### ISSUE THREAD

**Issue by seanmc5** [zircote/swagger-php#128]
OK, so when I run " php swagger.phar directory -o wherever" my api-docs.json contains the following:

```
   }
        "path":"/customer.json",
        "description":"Operations about addresses"
    },
    {
        "path":"/contact.json",
        "description":"Operations about contacts"
    },
    {
        "path":"/order.json",
        "description":"Operations about orders"
    },
```

The problem is when I view the json using the swagger ui. The .json is displayed after the path name. Which is not ideal. I've noticed if I manually replace the .json with .{format}. Everything is displayed correctly and works well. How come the cli tool does not automatically insert the .{format} for me instead of the .json?

Thanks

EDIT:

Also, another problem I have:
When I run the cli tool I get the following error multiple times:

[WARN] [Semantical Error] The annotation "@Doctrine\ORM\Mapping\Column"  ...... does not exist or could not be autoloaded.

If my Swagger annotations are embedded amongst Doctrine annotations they will not work. However if I throw them down the end of the Model class. They will be rendered.

Either way I am presented with the above error when I run php swagger.phar 

One final thing to mention when I was using the outeredge module for zf2 and generating the json on the fly I had no issues. This error only exists when I run from the command line?? Am I missing something? 

Any help greatly appreciated. Thanks

**Comment by nick4fake** [comment]
I am observing similar error. After enabling swagger:
````
                                                                                   
  In AnnotationException.php line 54:                                              
                                                                                   
    [Semantical Error] The annotation "@Sensio\Bundle\FrameworkExtraBundle\Conf    
    iguration\Route" in method ...\...\...\Controller\D    
    ictController::indexAction() does not exist, or could not be auto-loaded.      
                                                           
````
