### ISSUE TITLE
Is it possible for a team to generate only part of the documentation?

### ISSUE THREAD

**Issue by Vasiliy-Makogon** [zircote/swagger-php#1281]
Hello. Is it possible for a team to generate only a part of the documentation, according to some criteria, for example, the presence of a certain tag in annotations?

**Comment by DerManoMann** [comment]
Cross posted: https://github.com/DarkaOnLine/L5-Swagger/issues/480

**Comment by DerManoMann** [comment]
In the context of swagger-php you could write a custom processor to strip certain endpoints.

There is also a processor available to further exclude unused components https://github.com/zircote/swagger-php/blob/master/src/Processors/CleanUnusedComponents.php

**Comment by DerManoMann** [comment]
Closing as inactve.
