### ISSUE TITLE
Backed enums

### ISSUE THREAD

**Issue by Epse** [zircote/swagger-php#1290]
Hi, I tried to document some API that stores data using a backed enum.
I was delighted to see the enum support in `Schema`, but it shows the case names as options in the documentation rather than the backing values.

I see this was discussed near the end of #1043, but it does not seem implemented to me?

**Comment by DerManoMann** [comment]
I did the original implementation but not the additional changes . I was under the impression we had all cases covered.

Could you please post a simple enum example and the expected yaml?
I have this nagging feeling that there are conflicting requirements, we'll see.

**Comment by Epse** [comment]
So if I have an implementation like this:
```php
#[Schema()]
enum ReportType: string
{
    case Training = 'training';
    case CPT = 'cpt';
}
```

Then I expect the resulting documentation to look like:
```json
"enum": [
    'training',
    'cpt'
]
```
so that the Swagger UI sends the appropriate values into the request.
What I instead get is the names of the values, so in this case:
```json
"enum": [
    "Training",
    "CPT"
]
```

In hindsight that was not the best example ever, but I do hope you get the gist.
I tried setting the `enum` property of the `Schema` manually, but it got overridden.
If I wanted the case names as values, I'd just not use a backed enum, no?

**Comment by DerManoMann** [comment]
I haven't tried the latest tagged version, but with the current `master` I get
```
openapi: 3.0.0
components:
  schemas:
    ReportType:
      type: string
      enum:
        - training
        - cpt
```

for this PHP code:
```
<?php

use OpenApi\Attributes as OAT;

#[OAT\Schema()]
enum ReportType: string
{
    case Training = 'training';
    case CPT = 'cpt';
}
```

**Comment by Epse** [comment]
You're absolutely right, seems I was running a slightly outdated version. My apologies
