### ISSUE TITLE
Is swagger-php enable for import annotation from different file ?

### ISSUE THREAD

**Issue by RatchagridMek** [zircote/swagger-php#1291]
Hi I'm using zircote/swagger-php and get some issue about display response example to write for all condition it take a lot line of code so I thought about writing annotations in other file and import this annotation file to my controller file but I got some issue about how to do it do you have any suggest about this problem.

**Comment by DerManoMann** [comment]
swagger-php will scan/load multiple files if given a directory. There is no need to import files into your controller as the merging of all parsed annotations/attributes is done automatically at the end.

**Comment by DerManoMann** [comment]
Closing as inactve.
