### ISSUE TITLE
Q: How to wrap "\OpenApi\Annotations\Response" with custom Attribute

### ISSUE THREAD

**Issue by sebastianstucke87** [zircote/swagger-php#1292]
I would like to reuse `\OpenApi\Attributes\Response`-attributes (DRY). 

Using `ref` still requires one attribute per `Response` and a redundant (?) parameter `response`:

```php
    #[OpenApi\Response(
        ref: '#/components/responses/201',
        response: '201'
    )]
    #[OpenApi\Response(
        ref: '#/components/responses/400',
        response: '400'
    )]
    public function foo(): void
    {
        // (...)
    }
```
(see https://zircote.github.io/swagger-php/guide/cookbook.html#reusing-responses)

---

So I was wondering if Instead of this:

```php
namespace Currently {

    final class Controller
    {
        #[\OpenApi\Attributes\Response(
            response: 201,
            description: 'Created',
        )]
        #[\OpenApi\Attributes\Response(
            response: 400,
            description: 'Bad Request',
        )]
        public function foo(): void
        {
            // (...)
        }
    }
}
```

Something like this would be possible:

```php
namespace Mockup {

    #[\Attribute(\Attribute::TARGET_CLASS | \Attribute::TARGET_METHOD)]
    #[\OpenApi\Attributes\Response(
        response: 201,
        description: 'Created',
    )]
    #[\OpenApi\Attributes\Response(
        response: 400,
        description: 'Bad Request',
    )]
    final class PostResponse
    {
        // NOP
    }


    final class Controller
    {
        #[PostResponse]
        public function foo(): void
        {
            // (...)
        }

        #[PostResponse]
        public function bar(): void
        {
            // (...)
        }
    }
}

```

**Comment by DerManoMann** [comment]
The `response` property is required as it is used as the key in the `responses` map in the spec. So even if you re-use the same response class you might still want to return the same data structure with a different HTTP response code.

In your mock example this is not given. If `PostResponse` can be a `201` and also a `400`, how would swagger-php know which one you want for `#[PostResponse]`?

You could simplify things by having custom attributes for status code and then only `description` is custom.

```php
namespace Mockup {

    #[\Attribute(\Attribute::TARGET_CLASS | \Attribute::TARGET_METHOD)]
    final class Response400 extends \OpenApi\Attributes\Response
    {
        // set response to 400
        $this->response = 400;
    }


    final class Controller
    {
        #[Response400(description: 'foo not valid']
        public function foo(): void
        {
            // (...)
        }

        #[Response400(description: 'bar not valid']
        public function bar(): void
        {
            // (...)
        }
    }
}
```

Turns out the above is not quite so simple as you'd have to re-implement the constructor in order to get the 400 in :/
I think I'll add support for a post-constructor hook so custon attribute classes that extend from existing OpenApi attributes do not have to deal with all of that...

**Comment by sebastianstucke87** [comment]
> In your mock example this is not given. If `PostResponse` can be a `201` and also a `400`, how would swagger-php know which one you want for `#[PostResponse]`?

I want both! 😄 For a single endpoint:
- 1x status code for success (`200`/`201`)
- multiple status codes for various errors (`4XX`)

An example would be https://petstore.swagger.io/#/pet/updatePet with 3 error responses:
- `400 - Invalid ID supplied`
- `404 - Pet not found`
- `405 - Validation exception`

The thing is, almost all endpoints have `400`. Most have `401` and `403` but not all have `404` (or something else). So that is what I'm trying to document without having too much duplication...

---

> You could simplify things by having custom attributes for status code and then only `description` is custom.

Ah! Sorry, I totally forgot about inheritance..  😅 This looks way cleaner now:

```php
namespace CurrentlyV2 {

    #[\Attribute(\Attribute::TARGET_CLASS | \Attribute::TARGET_METHOD)]
    final class Ok extends \OpenApi\Attributes\Response
    {
        public function __construct()
        {
            parent::__construct(
                response: 200,
                description: 'OK'
            );
        }
    }

    #[\Attribute(\Attribute::TARGET_CLASS | \Attribute::TARGET_METHOD)]
    final class Created extends \OpenApi\Attributes\Response
    {
        public function __construct()
        {
            parent::__construct(
                response: 201,
                description: 'Created'
            );
        }
    }

    final class Controller
    {
        #[Ok]
        public function foo(): void
        {
            // (...)
        }

        #[Created]
        public function bar(): void
        {
            // (...)
        }
    }
}
```

**Comment by DerManoMann** [comment]
👍

**Comment by DerManoMann** [comment]
Looks solved, so closing.

**Comment by sebastianstucke87** [comment]
@DerManoMann Awesome! Thank you very much!! :smiley:
