### ISSUE TITLE
Handling different basePaths

### ISSUE THREAD

**Issue by StefanGla** [zircote/swagger-php#130]
Hello,
I'm using swagger-php inside a php project. Everything works fine, except for the basePaths. I define a ressource with basePath="http://myproject.localhost"... on my production environment I need to change that to basePath="http://myproject.example.org". 

So how can I handle different basePaths? I'm using Git inside my projects.

Best regards,
Stefan

**Comment by arunviscus** [comment]
Please help me to find swagger.phar
