### ISSUE TITLE
Feature Request: Split output by tags

### ISSUE THREAD

**Issue by Dmitrev** [zircote/swagger-php#1301]
There is currently a feature to filter by filepath.
It would be great to have a filter in the cli to specify only the specifics tags you want to export (incl related schemas)

```
openapi --tags=MyTag1,MyTag2 app -o mytags.yaml
```

One reason for this is that if you are using a cloud service to upload the exported documents there is a limit to how much you can transfer. Splitting it by tags would make it easier to split the docs into chunks without having the files living in the same subdir.

Or there is a way to achieve this with existing functionality?

**Comment by DerManoMann** [comment]
I suppose you could write a processor that would drop path items based on a  tag list. Then you might also want to add the `CleanUnusedComponents` processor to remove unused schemas, etc.
Pull requests welcome :)

**Comment by Dmitrev** [comment]
@DerManoMann I have since stopped working on the project that required this, therefor I will close the issue.
