### ISSUE TITLE
Hide Some of the Schemas for swagger ui

### ISSUE THREAD

**Issue by nibak** [zircote/swagger-php#1304]
I am very new to swagger ui. 
**Is there a we can hide certain schema in swagger-ui ?** for eg 

![image](https://user-images.githubusercontent.com/70001044/187779273-aeed8ca4-0e95-4165-91e1-b6e02c4151b3.png)

I want to hide the `Sale State Attributes` and `Sale State Relationship`  because it gets included in the  `Sale State`. This is because for every end point I create I have to have the attribute and the relationship this will make my schema very big and hard to find stuff

**Comment by DerManoMann** [comment]
Depends. If those schemas are referenced in the spec file then you will need them.

If these are there just for compleness and are not used in the spec then you could try registering the optional `CleanUnusedComponents` processor.

On the command line that would look something like
```
./bin/openapi -p "OpenApi\Processors\CleanUnusedComponents" ...
```

**Comment by nibak** [comment]
Yeah it is being referenced. here's what my annotation looks like 
```
 * @OA\Schema(schema="saleStateAttribute", title="Sale State Attributes")
 *
 * @OA\Schema(
 *     schema="SaleState",
 *     title="Sale State",
 *     description="Inventory balance is a resource type that extends the resource object",
 *     allOf={
 *          @OA\Schema(ref="#/components/schemas/ResourceObject"),
 *     },
 *     @OA\Property(
 *         example="saleState_46iyUKiQC7DWxuB3YSJlO",
 *         property="id",
 *     ),
 *     @OA\Property(
 *         example="saleState",
 *         property="type",
 *     ),
 *     @OA\Property(
 *         property="attributes",
 *         description="Record contains the inventory balance attributes",
 *         allOf={
 *             @OA\Schema(ref="#/components/schemas/saleStateAttribute"),
 *         }
 *     ),
 *     @OA\Property(
 *          property="relationships",
 *          allOf={
 *              @OA\Schema(ref="#/components/schemas/SaleStateRelationship"),
 *          }
 *      )
 * )
```

**Comment by DerManoMann** [comment]
If you need them then I guess you are out of luck here. Whatever tool you use to look at the spec will need them too.
If at all the UI might have a way of hiding components from the list but that is outside the scope of this project.

**Comment by nibak** [comment]
Thanks for your response
