### ISSUE TITLE
Error related to doctrine in laravel

### ISSUE THREAD

**Issue by Ola-jed** [zircote/swagger-php#1308]
I am integrating swagger-php in a laravel api.
In order to do this, I created a class `OpenApi`

```php
<?php

namespace App;

use OpenApi\Annotations as OA;

/**
 * @OA\Info(title="API", version="0.1")
 */
class OpenApi {}
```
On top of a method of one controller, I also added a dummy annotation, 
```php
/**
  * @OA\Get(path="api/tasks", @OA\Response(response="200", description="Description"))
  *
  * Get all the tasks created by the user
  * @param Request $request
  * @return JsonResponse
  */
 public function all(Request $request): JsonResponse {....}
```

When I run the command `./vendor/bin/openapi /srv/http/todo-api -o /srv/http/todo-api/swagger.json`, I have the following error
```
PHP Fatal error:  Declaration of Doctrine\Common\Cache\Psr6\CacheItem::get() must be compatible with Psr\Cache\CacheItemInterface::get(): mixed in /srv/http/todo-api/vendor/doctrine/cache/lib/Doctrine/Common/Cache/Psr6/CacheItem.php on line 51
```

I have tried using attributes instead of annotations but I have the same error.
I am using laravel 9 with php 8.1.9 and composer 2.3.10 installed

**Comment by DerManoMann** [comment]
Hmm, looks more like a composer issue than swagger-php itself.

Looks to me as if the installed `psr/cache` is version 3.0 and doctrine is only compatible with version 2.0. The difference is the `mixed` return type-hint.

Fixing `psr/cache` at 2.0 should make things work.

**Comment by Ola-jed** [comment]
By adding the line `"psr/cache": "2.0"` in my composer.json, I get the same error.
Is it possible to bypass this issue by any mean ?

**Comment by DerManoMann** [comment]
Hmm, you did a `composer update`, did you?

`composer show` will give you a list of installed packages and their versions. If `composer update` doesn't downgrade `psr/cache` then you might have other libraries with dependencies on version 3 I suspect.

**Comment by Ola-jed** [comment]
Thanks. After deleting the composer.lock and trying `composer install` again, it works
