### ISSUE TITLE
CleanUnusedComponents processor does not filter out all unused components. 

### ISSUE THREAD

**Issue by Prusias** [zircote/swagger-php#1320]
While using the `CleanUnusedComponents` processor, I kept getting unused schema's in my final documentation. After looking into it a bit, it seems in most cases it includes components that are referencing each other, but that are not used anywhere else. Though some components also still showed up while not being referenced at all in the final documentation. 

I've fixed it for myself by filtering the components passed to the CleanUnusedComponents processor, but I think a better fix could be thought of.

<details>
<summary>Filtering code example</summary>

```
class CleanUnusedComponentsExtended
{
    public function __invoke(Analysis $analysis)
    {
	    if (Generator::isDefault($analysis->openapi->components)) {
		    return;
	    }
    
	    $this->cleanup($analysis);
    }
    
    public function cleanup(Analysis $analysis): void
    {
	    $filtered_annotations = new SplObjectStorage();
    
	    /** @var AbstractAnnotation $annotation */
	    foreach ($analysis->annotations as $annotation) {
		    $this->filterAnnotations($annotation, $filtered_annotations);
	    }
    
	    $cleanup_unused_components = new CleanUnusedComponents();
	    $analysis->annotations = $filtered_annotations;
	    $cleanup_unused_components($analysis);
    }
    
    private function filterAnnotations(AbstractAnnotation $annotation, SplObjectStorage $storage): void
    {
	    if (
		    $annotation instanceof PathItem ||
		    $annotation instanceof SecurityScheme ||
		    $annotation instanceof Info ||
		    $annotation instanceof Server ||
		    $annotation instanceof Tag ||
		    $annotation instanceof ExternalDocumentation
	    ) {
		    $storage->attach($annotation);
		    $this->traverseAnnotation($annotation, $storage);
	    }
    }
    
    private function traverseAnnotation(AbstractAnnotation $annotation, SplObjectStorage $storage): void
    {
	    foreach (array_merge($annotation::$_nested, ['allOf', 'anyOf', 'oneOff']) as $nested) {
		    if (is_array($nested)) {
			    foreach ($nested as $field_name) {
				    if (isset($annotation->{$field_name})) {
					    $this->innerTraverseAnnotation($annotation->{$field_name}, $storage);
				    }
			    }
		    } else if (isset($annotation->{$nested})) {
			    $this->innerTraverseAnnotation($annotation->{$nested}, $storage);
		    }
	    }
    }
    
    private function innerTraverseAnnotation($obj, SplObjectStorage $storage): void
    {
	    if ($obj !== null && !is_string($obj)) {
		    if (is_array($obj)) {
			    foreach ($obj as $value) {
				    $this->innerTraverseAnnotation($value, $storage);
			    }
		    } else if (!$storage->contains($obj)) {
			    $storage->attach($obj);
			    $this->traverseAnnotation($obj, $storage);
		    }
	    }
    }
}
```
</details>

**Comment by DerManoMann** [comment]
I was aware that the `Analysis` storage never captured all annotations but never really had a good enough reason to spend a lot of time on this, so thanks for this.

**Comment by DerManoMann** [comment]
I've refactored your code a bit ;) - this now picks up even more annotations when traversing. Would you mind trying that to see if that still works for you?

<details>
<summary>Collector</summary>

```php
<?php declare(strict_types=1);

namespace OpenApi;

use OpenApi\Annotations as OA;

/**
 * Collects a complete list of all nested/referenced annotations.
 */
class Collector
{
    public function collect(\SplObjectStorage $annotations): \SplObjectStorage
    {
        $storage = new \SplObjectStorage();

        foreach ($annotations as $annotation) {
            if ($annotation instanceof OA\AbstractAnnotation) {
                $this->traverse($annotation, $storage);
            }
        }

        return $storage;
    }

    protected function traverse(OA\AbstractAnnotation $annotation, \SplObjectStorage $storage): void
    {
        if ($storage->contains($annotation)) {
            return;
        }

        $storage->attach($annotation);

        foreach (array_merge($annotation::$_nested, ['allOf', 'anyOf', 'oneOff']) as $nested) {
            if (is_array($nested)) {
                foreach ($nested as $nestedProperty) {
                    if (isset($annotation->{$nestedProperty})) {
                        $this->traverseNested($annotation->{$nestedProperty}, $storage);
                    }
                }
            } elseif (isset($annotation->{$nested})) {
                $this->traverseNested($annotation->{$nested}, $storage);
            }
        }
    }

    /**
     * @param string|array|OA\AbstractAnnotation $nested
     */
    protected function traverseNested($nested, \SplObjectStorage $storage): void
    {
        if (is_array($nested)) {
            foreach ($nested as $value) {
                $this->traverseNested($value, $storage);
            }
        } elseif ($nested instanceof OA\AbstractAnnotation) {
            $this->traverse($nested, $storage);
        }
    }
}
```

</details>

All you need to do to use it would be to patch `CleanUnusedComponents` with a single line:

```php
// ...
class CleanUnusedComponents
{
    public function __invoke(Analysis $analysis)
    {
        if (Generator::isDefault($analysis->openapi->components)) {
            return;
        }

        $analysis->annotations = (new \OpenApi\Collector())->collect($analysis->annotations);

        // allow multiple runs to catch nested dependencies
        for ($ii = 0; $ii < 10; ++$ii) {
            if (!$this->cleanup($analysis)) {
                break;
            }
        }
    }

    // ...
}
```

**Comment by Prusias** [comment]
I'll try it out first thing when I can on Monday, your code is a lot cleaner! I recall having issues immediatly passing along all instances of `AbstractAnnotation`, as this didn't prevent all unused documentation. Looking at the code that might still happen. Propably the schema's that reference one another?

**Comment by DerManoMann** [comment]
Might be - I only looked at your code to collect *all* annotations rather than just the ones tracked officially.
Dealing with circular refs might be the next step...

**Comment by Prusias** [comment]
Gave it a go, for me, it seems to fix neither unfortunately. Running it and looking at the generated output .yaml there is no difference. It is still picking up both unreferenced schema's and circular references. 

Looking at the process step by step, for me, it seems that before and after updating the analysis annotations, the count is the increased by one. (332 to 333). Replacing the logic in the collector with the logic in the code I provided above results in 55 annotations, from there on I get no more unreferenced/circular schema's.

**Comment by DerManoMann** [comment]
Hmm, worth a try :) Is presume your project is not public? It would be nice to have a way to replicate this locally for me ...

**Comment by Prusias** [comment]
Yep, not public. I've taken the effort to copy and simplify a small repo, that reproduces the bug. https://github.com/Prusias/SwaggerPHPBugExample

**Comment by DerManoMann** [comment]
I think I made some progress. The key was that detaching an annotation also required to remove all nested child annotations in the `CleanUnusedComponents` processor.

Could you try #1322 and let me know if that works any better?

**Comment by Prusias** [comment]
Hey, doesn't make a difference, unfortunately. Also does not seem to solve it with the repo I provided above.

**Comment by DerManoMann** [comment]
Strange, did work for me :/
Oh, well, some more digging then.

**Comment by DerManoMann** [comment]
Double checked and this is working for me. I am also not entirely sure how you run your `Test.php` without additional autoloader setup...

I've updated the collector branch to include the latest master which allows to specify multiple bootstrap files. That, in addition to using the  updated processor I get this:

```sh
`/SwaggerPHPBugExample$ ../swagger-php/bin/openapi -b Path1/*.php -b Path2/*.php Path1 Path2 -p "OpenApi\Processors\CleanUnusedComponents"
Warning: Required @OA\Info() not found
openapi: 3.0.0
paths:
  /path:
    parameters:
      -
        name: example_param
        in: query
        required: true
        style: spaceDelimited
        explode: true
components:
  schemas: {  }

```

**Comment by Prusias** [comment]
Hmm, that would be what I expect. I'll give it another look tomorrow. As for the auto loading. I think I had a composer autoloader I loaded in/

**Comment by Prusias** [comment]
Alright ye, something must have gone wrong with my testing. https://github.com/zircote/swagger-php/pull/1322 solves the issue!
