### ISSUE TITLE
Segmentation fault (exit code 139) on large number of files to be parsed

### ISSUE THREAD

**Issue by TarasZakus** [zircote/swagger-php#1321]
PHP: 8.1.10
zircote/swagger-php: >= 4.2.0
The number of files with #[OpenApi\Attributes\* definition to be parsed: approx 500.

When I reduce the number of files to ~300 or downgrade zircote/swagger-php to ~4.1.0, the error is gone.

**Comment by DerManoMann** [comment]
Have you tried giving it more RAM?

If you have the time to narrow it down to a specific version that would be helpful, I suppose. Ideally the commit will be needed I suspect..

Might be hard to reproduce:/

**Comment by TarasZakus** [comment]
Hi @DerManoMann, thanks for the feedback.
It seems like something is wrong with my Docker container setup.
If I run it in a fresh container (based on the same image), it works without any issues  :)
