### ISSUE TITLE
Merging properties from non-schema parent should include traits

### ISSUE THREAD

**Issue by DerManoMann** [zircote/swagger-php#1325]
Given the following:
```php
trait HasId
{
    /**
     * @OA\Property(
     *     format="int64",
     *     readOnly=true,
     * )
     *
     * @var int
     */
    public int $id;
}

abstract class Model
{
    use HasId;
}

/**
 * @OA\Schema(
 *     required={"street"},
 *     @OA\Xml(
 *         name="Address"
 *     )
 * )
 */
class Address extends Model
{
    /** @OA\Property */
    public string $street;
}
```

The `ExpandClasses` processor should merge not just direct properties properties from `Model` into `Address`, but also properties inherited from `HasId`.

Related to https://github.com/DarkaOnLine/L5-Swagger/issues/499

**Comment by DerManoMann** [comment]
@rickgoemans Not sure if you actually tried the PR orjust looked at the code changes - either way, I added a test that looks at both parent *and* own class traits and I believe things do work as expected in both cases...

**Comment by DerManoMann** [comment]
Phew! This got a bit bigger than expected.

I've updated the PR; includes some code cleanup and shuffling but your last example now passes for me :)

**Comment by rickgoemans** [comment]
Are you referring this  PR https://github.com/zircote/swagger-php/pull/1333/files?
I see it is merged but there is no release yet so I can't test it.

**Comment by DerManoMann** [comment]
Nah, #1331. You'd have to pull from the PR repo and use that version.
Hmm, I guess I'll merge and create a release. Pretty sure this is it :)
