### ISSUE TITLE
How to document query parameter with dynamic keys?

### ISSUE THREAD

**Issue by gremo** [zircote/swagger-php#1327]
My API could sort items with the query parameter: `sortBy[name]=asc`, where name in square brackets could be a list of fields (i.e. `firstName`, `lastName`) and value is asc or desc. Is there any way to document this requirement?

**Comment by DerManoMann** [comment]
Good question. I don't know if that is possible at all, so it might be a good first step to investigate what the actual spec would need to look like.
If there is a solution we can figure out how to generate it :)

**Comment by grnsv** [comment]
Found also this issue
https://github.com/zircote/swagger-php/issues/401

May be comething like this?
`* @SWG\Parameter(
 *   name="sortBy",
 *   in="query",
 *   description="Sort by",
 *   required=false,
 *   @SWG\Schema(
 *     type="object",
 *     @SWG\Property(
 *       property="sortBy",
 *       type="array",
 *       @SWG\Items(
 *         type="object",
 *         example={"name":asc},
 *       )
 *     )
 *   )
 * ),`

**Comment by DerManoMann** [comment]
Nice one @grnsv!

Updated to swagger-php v3+ a full example could look like this:
```php
<?php

use OpenApi\Annotations as OA;

/**
 * An API endpoint.
 *
 * @OA\Info(title="API", version="1.0")
 *
 * @OA\Get(
 *     path="/api/endpoint",
 *     description="An endpoint",
 *     operationId="endpoint",
 *     tags={"endpoints"},
 *     @OA\Parameter(
 *         name="sortBy",
 *         in="query",
 *         description="Sort by",
 *         required=false,
 *         @OA\Schema(
 *             type="object",
 *             @OA\Property(
 *                 property="sortBy",
 *                 type="array",
 *                 @OA\Items(
 *                     type="object",
 *                     example={"name":"asc"}
 *                 )
 *             )
 *         )
 *     ),
 *     @OA\Response(response="200", description="OK")
 * )
 */
class Endpoint
{
}
```

Generated spec:
```yaml
openapi: 3.0.0
info:
  title: API
  version: '1.0'
paths:
  /api/endpoint:
    get:
      tags:
        - endpoints
      summary: 'An API endpoint.'
      description: 'An endpoint'
      operationId: endpoint
      parameters:
        -
          name: sortBy
          in: query
          description: 'Sort by'
          required: false
          schema:
            properties:
              sortBy:
                type: array
                items:
                  type: object
                  example: { name: asc }
            type: object
      responses:
        '200':
          description: OK
```
Only downside is that in swagger-ui this will be rendered as JSON :/
![image](https://user-images.githubusercontent.com/47783/196562962-88ea6f56-f5d6-4487-a8e4-e5bd8fbe455e.png)

**Comment by DerManoMann** [comment]
If someone feels like adding this to the docs I'd be happy to merge ;)

**Comment by gremo** [comment]
Not working for me:

> User Notice: @SWG\\Parameter(name="sortBy",in="query")->type is required when @SWG\\Parameter()->in

**Comment by DerManoMann** [comment]
Type="object" would be my guess, but I am not looking at swagger-php version 2 any more, sorry.

**Comment by DerManoMann** [comment]
Closing as inactve.
