### ISSUE TITLE
How to document multiple Set-Cookie response?

### ISSUE THREAD

**Issue by Buzka91** [zircote/swagger-php#1328]
How can i set multiple response header named "Set-Cookie" with different examples?

![image](https://user-images.githubusercontent.com/22677022/196444127-080aff62-0847-4227-97bf-e91e01c94837.png)

```
 *          @OA\Header(
 *              @OA\Schema(
 *                  type="string",
 *                  example="test1=test1",
 *              ),
 *              header="Set-Cookie1",
 *          ),
 *          @OA\Header(
 *              @OA\Schema(
 *                  type="string",
 *                  example="test2=test2",
 *              ),
 *              header="Set-Cookie2",
 *          ),
```

Having two headers named "Set-Cookie" gives warning:
> PHP Warning:  Multiple @OA\Header() with the same header="Set-Cookie"

![image](https://user-images.githubusercontent.com/22677022/196445418-f33e709e-aa64-48cc-9fbf-28138c9fe511.png)

and docs got only one header...

```
 *          @OA\Header(
 *              @OA\Schema(
 *                  type="string",
 *                  example="test1=test1",
 *              ),
 *              header="Set-Cookie",
 *          ),
 *          @OA\Header(
 *              @OA\Schema(
 *                  type="string",
 *                  example="test2=test2",
 *              ),
 *              header="Set-Cookie",
 *          ),
```

**Comment by DerManoMann** [comment]
Looks to me that this is not possible. The headers property on response is a map with the header name as key and the value being the header object.

That means there can always ever be one header for a given name.

For example (see the `headers` field) https://spec.openapis.org/oas/v3.0.3#response-object

**Comment by DerManoMann** [comment]
Sneaky!

**Comment by DerManoMann** [comment]
Just going through issues to see what can be closed. [RFC-6265](https://www.rfc-editor.org/rfc/rfc6265#section-5.4) states that: 

```
When the user agent generates an HTTP request, the user agent MUST NOT attach more than one Cookie header field.
```

Chances are that browser will tolerate and handle multple, tho. 

Closing as I would consider this resolved.
