### ISSUE TITLE
Marking a property as nullable

### ISSUE THREAD

**Issue by CxDevLead** [zircote/swagger-php#1338]
I am creating a schema as follows:

```
#[OA\Schema(    //manually create the return schema for the api response
    schema: "ResponseData",
    properties: [
        new OA\Property(
            property: "yearDisplay",
            ref: "#/components/schemas/YearDisplayModel",
            type: "object",
            nullable: true,
        ),
    ],
    type: "object",
)]
```

In the output swagger, the property 'yearDisplay' is not marked as being `null` or `YearDisplayModel`, how do I set the output to include that the property can also be null instead of the object?

**Comment by DerManoMann** [comment]
This is a known issue. The spec for 3.0 doesn't allow any other properties next to `ref` and in 3.1 the only ones allowed are `summary` and `description`.

swagger-php currently just strip all other properties.

I believe the "correct" way to archive this is to use `oneOf` where you have the ref and null as possible values.  Although, I am not sure how to represent a `null` of the top of my head.

**Comment by CxDevLead** [comment]
Understood, thanks, I'll add it to the descriptions.

**Comment by momala454** [comment]
@DerManoMann 
How do I do "oneOf" on top of a class attribute ?

```php
class MyClass
{
    public function __construct(
        #[\OpenApi\Attributes\Property(anyOf: [new \OpenApi\Attributes\Schema(type: 'null'), new \OpenApi\Attributes\Schema(type: MyClass::class)])]
        public ?MyClass $folder,
    ) 
{}
```

the "anyOf" is ignored

**Comment by DerManoMann** [comment]
Good question, never tried that. Have you tried `oneOf`?

**Comment by momala454** [comment]
yes, same result, it's ignored

**Comment by momala454** [comment]
@DerManoMann this is the solution i've made which seems to work.
File
vendor/zircote/swagger-php/src/Annotations/AbstractAnnotation.php

Method jsonSerialize

Modify this part
```php
// $ref
        if (isset($data->ref)) {
            // Only specific https://github.com/OAI/OpenAPI-Specification/blob/3.1.0/versions/3.1.0.md#reference-object
            $ref = ['$ref' => $data->ref];
            if ($this->_context->version == OpenApi::VERSION_3_1_0) {
                $defaultValues = get_class_vars(get_class($this));
                foreach (['summary', 'description'] as $prop) {
                    if (property_exists($this, $prop)) {
                        if ($this->{$prop} !== $defaultValues[$prop]) {
                            $ref[$prop] = $data->{$prop};
                        }
                    }
                }
            }
            $data = (object) $ref;
        }
```

to
```php
// $ref
        if (isset($data->ref)) {
            // Only specific https://github.com/OAI/OpenAPI-Specification/blob/3.1.0/versions/3.1.0.md#reference-object
            $ref = ['$ref' => $data->ref];
            if ($this->_context->version == OpenApi::VERSION_3_1_0) {
                $defaultValues = get_class_vars(get_class($this));
                foreach (['summary', 'description'] as $prop) {
                    if (property_exists($this, $prop)) {
                        if ($this->{$prop} !== $defaultValues[$prop]) {
                            $ref[$prop] = $data->{$prop};
                        }
                    }
                }
            }
            $defaultValues = get_class_vars(get_class($this));
            if (property_exists($this, 'nullable') && $this->nullable === true) {
                if ($this->nullable !== $defaultValues['nullable']) {
                    $ref['nullable'] = $data->nullable;
                    $ref['oneOf'] = [
                        ['$ref' => $data->ref],
                    ];
                    unset($ref['$ref']);
                }
            }
            $data = (object) $ref;
        }
```

**Comment by momala454** [comment]
@DerManoMann 
can you please check my solution ?

**Comment by momala454** [comment]
Hello @DerManoMann can you please tell something about the fix?
Thank you

**Comment by DerManoMann** [comment]
Hi @momala454, sorry, I've been too busy lately to spend much time on this project. I hope that after Christmas I'll get back on to it.

**Comment by Dooks123** [comment]
@momala454 Did you find a fix for this?

**Comment by momala454** [comment]
@Dooks123 the fix have already been merged

**Comment by Dooks123** [comment]
@momala454 Thank you for your response - I had a "similar" but totally different issue actually. My issue is I have circular reference object, Swagger UI can't handle that scenario - Just plainly omits the type. So I ended up just removing the reference and making it a generic object with a description of the object itself.

**Comment by momala454** [comment]
create a new issue with your problem
