### ISSUE TITLE
Indirect deprecations in 4.5.0

### ISSUE THREAD

**Issue by michaljusiega** [zircote/swagger-php#1339]
Hi,

I'm facing of the problem with indirect deprecations about `Context::detect()` released in https://github.com/zircote/swagger-php/pull/1334 and after update up to `zircote/swagger-php:4.5.0`

I got deprecations messages after all tests:

```
Remaining direct deprecation notices (480)

  480x: Since zircote/swagger-php 4.0: Context detecting is deprecated
    384x in DomoticzAddControllerTest::testFunctionalInvoke1 from JUSIASOFT\HomeAssistant\Tests\Domoticz\Application\Controller
    38x in ApiJSONControllerTest::testFunctionalInvoke1 from JUSIASOFT\HomeAssistant\Tests\Api\Application\Controller
    32x in ApiUIControllerTest::testFunctionalInvoke1 from JUSIASOFT\HomeAssistant\Tests\Api\Application\Controller
    26x in AttributesArePossibleToCreateTest::testUnitAttributesArePossibleToCreate from JUSIASOFT\HomeAssistant\Tests\VariousTests\Project

Remaining indirect deprecation notices (201)

  133x: Since zircote/swagger-php 4.0: Context detecting is deprecated
    128x in DomoticzAddControllerTest::testFunctionalInvoke1 from JUSIASOFT\HomeAssistant\Tests\Domoticz\Application\Controller
    2x in ApiJSONControllerTest::testFunctionalInvoke1 from JUSIASOFT\HomeAssistant\Tests\Api\Application\Controller
    2x in ApiUIControllerTest::testFunctionalInvoke1 from JUSIASOFT\HomeAssistant\Tests\Api\Application\Controller
```

IMO this isn't my mistake. I'm not using this method directly. Let's fix this and change the signature from `@deprecation` into `@internal`

**Comment by schodemeiss** [comment]
Indeed, I just hit the same thing. I'm not directly using it directly but via Nelmio Bundle.

**Comment by michaljusiega** [comment]
> Indeed, I just hit the same thing. I'm not directly using it directly but via Nelmio Bundle.

Yea, I forgot to write I'm also using Nelmio Api Doc Bundle.

**Comment by DerManoMann** [comment]
Hmm, so would we ever be able to deprecate this?
Sure, you are not using this directly so wouldn't it make more sense to raise this with nelmio?
I understand the pain, though. I might need to mull this over again...

**Comment by schodemeiss** [comment]
> Hmm, so would we ever be able to deprecate this? Sure, you are not using this directly so wouldn't it make more sense to raise this with nelmio? I understand the pain, though. I might need to mull this over again...

I've raised an issue with Nelmio, too. You're probably right in that Nelmio should stop calling the function which is triggering the deprecation. Either way, it's quite frustrating.

For now, I've locked the version of Zircote in our local package to 4.4.10 to avoid the deprecations, but that's obviously not an ideal solution.

**Comment by michaljusiega** [comment]
@DerManoMann I saw you released 4.5.1 (https://github.com/zircote/swagger-php/pull/1345), so we can close this topic, right ?

**Comment by DerManoMann** [comment]
Yes, sorry, forgot about that.

**Comment by rodrigoprobst** [comment]
it got back on https://github.com/zircote/swagger-php/pull/1563/files
