### ISSUE TITLE
Documentation / Support for custom processors

### ISSUE THREAD

**Issue by 0xSpell** [zircote/swagger-php#1348]
I'm currently playing around with Laravel and Custom processors in an attempt to generate schemas for endpoints automatically from Laravel FormRequest validation.
I got started writing a custom processor and some basic parsing/generation code, but I'm not very certain on how to use the Analysis instance passed into the processor to add generated schema annotations for the request objects.
I tried to use:
```php
$analysis->unmerged()->addAnnotation(
                    new OA\Schema(
                        title: "Update request",
                        description: "Request doing updates",
                        required: ["name"],
                        properties: [
                            new OA\Property(
                                property: "name,
                                description: "display name",
                                type: "string",
                                example: "Test"
                            ),
                        ],
                        type: "object"
                    ),
                    new Context()
                );
```

But it does not show up in the generated openapi.yml. I suppose maybe its got something to do with the context?

I'd be grateful for some response, but I'll keep poking around in the code nevertheless. Thanks for your time!

**Comment by 0xSpell** [comment]
Don't worry about the response time :-)
This clarifies things a lot for me, I'll give it a try and see how it goes!

**Comment by 0xSpell** [comment]
Do you have any advice how to go about changing an annotation in a processor?
E.g. I have annotated my operations with Get operations and want to leave out the path: Parameter to insert that later via a processor, which draws in routing information.
When I attempt to change the annotations via direct access or mergeProperties, it seems the info doesn't actually get updated in the root analysis?

**Comment by 0xSpell** [comment]
I found the solution myself:
It seems the paths of operations are actually aggregated into the $analysis->openapi->paths PathItem types and taken from these, when the actual document is generated.
Meaning there is no use in updating the path in the annotations,but instead the pathitems have to be updated.

**Comment by 0xSpell** [comment]
Additionally, I found out that I should have considered the order in which I insert the default processors used by swagger-php, as there is a processor which collects the paths from the annotations and builds the openapi paths from that - so feel free to close this.

**Comment by DerManoMann** [comment]
Sounds good, thanks.
