### ISSUE TITLE
Cannot use positional argument after named argument

### ISSUE THREAD

**Issue by lucaele** [zircote/swagger-php#1349]
PHP: 8.1.7
Laravel: 9.39.0
Swagger-php: 4.5

This above code generete error

"Whoops\Exception\ErrorException 
Cannot use positional argument after named argument"

---
namespace App\Http\Controllers\Api_EMP;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use OpenApi\Attributes as OA;

#[OA\Info(
    title:"EMP2.3",
    description:"EMP",
    version:"0.1.1"
)]

#[OA\Server(
    description:"EMP",
    url:L5_SWAGGER_CONST_HOST_EMP
)]

#[OA\Schema(
    schema:"req_Data2",
    required:["code", "message"],
    new OA\Property(
        property:"code",
        type:"integer",
        format:"int32"
    ),
    new OA\Property(
        property:"message",
        type:"string"
    )
)]

#[OA\Post(
    path:"/emp/data2",
    tags:["EMP"],
    summary:"Adds a new user - with oneOf examples",
    description:"Return a list of Data",
    new OA\RequestBody(
        new OA\JsonContent(
            ref:"#/components/schemas/req_Data2",
            new OA\Examples(example:"result", summary:"With Post Customer Object", value:["code" => 1, "message" => "ci siamo!"]),
        ),
    ),
    new OA\Response(
        response:200,
        description:"OK",
        new OA\JsonContent(
            oneOf:[
                new OA\Schema(ref:"#/components/schemas/req_Data2")
            ],
            new OA\Examples(example:"result", summary:"With Post Customer Object", value:["code" => 1, "message" => "ci siamo!"]),
        )
    )
)]

class emp_controller extends Controller
{
    //
}
---

Any idea how fix it?

**Comment by DerManoMann** [comment]
Nested attributes need to use a named argument as well. This is regular PHP syntax, so properties, for example, need to be passed in something like this:
```
   ..., properties: [new OA\Property(...), ...]```

**Comment by lucaele** [comment]
Thanks for reply,
but now received generic error: "Required @OA\Info() not found".
Where is my error?

___
namespace App\Http\Controllers\Api_EMP;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

#[OA\Info(
title:"EMP2.3",
description:"EMP",
version:"0.1.1"
)]

#[OA\Server(
description:"EMP",
url:L5_SWAGGER_CONST_HOST_EMP
)]

#[OA\Schema(
schema:"req_Data2",
required:["code", "message"],
properties: [
        new OA\Property(
            property:"code",
            type:"integer",
            format:"int32"
        ),
        new OA\Property(
            property:"message",
            type:"string"
        )
    ]
)]

#[OA\Post(
path:"/emp/data2",
tags:["EMP"],
summary:"Adds a new user - with oneOf examples",
description:"Return a list of Data",
requestBody: [ new OA\RequestBody(
        jsonContent: [ new OA\JsonContent(
            ref:"#/components/schemas/req_Data2",
            examples: [ new OA\Examples(example:"result", summary:"With Post Customer Object", value:["code" => 1, "message" => "ci siamo!"]) ],
        )],
    )],
    response: [ new OA\Response(
        response:200,
        description:"OK",
        jsonContent: [ new OA\JsonContent(
            oneOf:[
                new OA\Schema(ref:"#/components/schemas/req_Data2")
            ],
            examples: [new OA\Examples(example:"result", summary:"With Post Customer Object", value:["code" => 1, "message" => "ci siamo!"])],
        )]
    )]
)]

class emp_controller extends Controller
{
//

**Comment by DerManoMann** [comment]
Not exactly sure why you get exactly that, but there are still a few issues in your code.
* `response:` should be `responses:`
* `jsonContent` is not a valid parameter; use `content` instead
* `requestBody` does not expect an array but just a single object

I am surprised that your IDE doesn't flag these things as there are lots of typehints in the attributes.

Finally, when posting code here could you [format it properly](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) as that makes reading things a lot easier.

Here is a fixed, complete version of your code to compare :) Note that I had to strip a couple references to framework code, etc.
```php
<?php

namespace App\Http\Controllers\Api_EMP;

use OpenApi\Attributes as OA;

#[OA\Info(
    title: "EMP2.3",
    description: "EMP",
    version: "0.1.1"
)]
#[OA\Server(
    description: "EMP",
    url: 'L5_SWAGGER_CONST_HOST_EMP'
)]
#[OA\Schema(
    schema: "req_Data2",
    required: ["code", "message"],
    properties: [
        new OA\Property(
            property: "code",
            type: "integer",
            format: "int32"
        ),
        new OA\Property(
            property: "message",
            type: "string"
        )
    ]
)]
#[OA\Post(
    path: "/emp/data2",
    tags: ["EMP"],
    summary: "Adds a new user - with oneOf examples",
    description: "Return a list of Data",
    requestBody: new OA\RequestBody(
        content: [new OA\JsonContent(
            ref: "#/components/schemas/req_Data2",
            examples: [new OA\Examples(example: "result", summary: "With Post Customer Object", value: ["code" => 1, "message" => "ci siamo!"])],
        )],
    ),
    responses: [new OA\Response(
        response: 200,
        description: "OK",
        content: [new OA\JsonContent(
            oneOf: [
                new OA\Schema(ref: "#/components/schemas/req_Data2")
            ],
            examples: [new OA\Examples(example: "result", summary: "With Post Customer Object", value: ["code" => 1, "message" => "ci siamo!"])],
        )]
    )]
)]
class Controller
{
}
```

Putting that into a file and running swagger-php manually would look like this:
```shell
$ ./bin/openapi -b scratch/pos.php scratch/pos.php 
openapi: 3.0.0
info:
  title: EMP2.3
  description: EMP
  version: 0.1.1
paths:
  /emp/data2:
    post:
      tags:
        - EMP
      summary: 'Adds a new user - with oneOf examples'
      description: 'Return a list of Data'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/req_Data2'
            examples:
              result:
                summary: 'With Post Customer Object'
                value:
                  code: 1
                  message: 'ci siamo!'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - { $ref: '#/components/schemas/req_Data2' }
              examples:
                result:
                  summary: 'With Post Customer Object'
                  value: { code: 1, message: 'ci siamo!' }
      servers:
        -
          url: L5_SWAGGER_CONST_HOST_EMP
          description: EMP
components:
  schemas:
    req_Data2:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      type: object

```

**Comment by lucaele** [comment]
@DerManoMann, thanks a lot.
Your answer was really helpful.
And now all works.

After any change on this file, i used this command from terminal to generate the documentation and no one specific warning or error message is returned:
``
php artisan l5-swagger:generate documentation --all
``

It would be interesting to have warning when there are errors.
If you want i can make some erroneous tests to show you the error on the terminal.

**Comment by DerManoMann** [comment]
PRs are always welcome.

In terms of better error messages - sometimes it is just what it is. As I said above, the invalid named parameters to some of the PHP attributes should have been flagged by the IDE and also by PHP when executing the code.

The debug option might have helped on the command line, too.

**Comment by DerManoMann** [comment]
Closing as the original issues seems resolved.
