### ISSUE TITLE
externalValue return "string" instead of json content

### ISSUE THREAD

**Issue by lucaele** [zircote/swagger-php#1350]
I'm looking to load "large" external json file on OA\Response.

```
new OA\Response(
     response: 200,
     description: "Success",
     content: [
           new OA\JsonContent(
           examples: [
                 new OA\Examples(example: "result", summary: "Response complete",  externalValue: "http://test.domain.com/api/json/emp/res_Data.json"),
                ]
           ),
     ]
)
```

The file "res_Data.json" is online,
but on swagger documentation on "response" block there is only "string" instead of json file content.

What's wrong or there are another way?
Thanks

**Comment by DerManoMann** [comment]
I do not think there is anything wrong here.

The spec defines it as `string` here: https://spec.openapis.org/oas/v3.0.3#example-object

I would suspect its up to the tool you use to browse the spec (swagger-ui, etc) to do something with the url.

**Comment by DerManoMann** [comment]
Closing as working as expected.
