### ISSUE TITLE
OneOf and inheritance causes circular reference

### ISSUE THREAD

**Issue by momala454** [zircote/swagger-php#1355]
I have a method that can return multiple type of responses. To show the possibilities, i created a class AbstractTest with a "oneOf" to show on openApi what classes it can be.
But when generating the openapi file, it is making a circular reference, with Test1 and Test2 also getting the "oneOf" of AbstractTest, which is causing problems.

If I don't put the "oneOf" on AbstractClass, then on swagger it won't show me  the possibilities

```php
#[\OpenApi\Attributes\Schema(
    oneOf:[
        new \OpenApi\Attributes\Schema(type: Test1::class),
        new \OpenApi\Attributes\Schema(type: Test2::class),
    ],
)]
abstract class AbstractTest
{
}

#[\OpenApi\Attributes\Schema(
)]
abstract class Test1 extends AbstractTest
{
}

#[\OpenApi\Attributes\Schema(
)]
abstract class Test2 extends AbstractTest
{
}

```

```
"AbstractTest": {
                "oneOf": [
                    {
                        "$ref": "#\/components\/schemas\/Test1"
                    },
                    {
                        "$ref": "#\/components\/schemas\/Test2"
                    }
                ]
            },
            "Test1": {
                "allOf": [
                    {
                        "$ref": "#\/components\/schemas\/AbstractTest"
                    }
                ]
            },
            "Test2": {
                "allOf": [
                    {
                        "$ref": "#\/components\/schemas\/AbstractTest"
                    }
                ]
            },
```

**Comment by momala454** [comment]
setting allOf: [] to Test1 and Test2 doesn't change anything, swagger is still showing AbstractTest in allOf

**Comment by DerManoMann** [comment]
swagger-php will follow PHP inheritance and reflect that in the generated schemas.
My recommendation would be to move the AbstractTest schema annotations to a separate class that is not part of your PHP class hierachy.

**Comment by momala454** [comment]
ok thank you. I will use a dummy class just for openapi

**Comment by DerManoMann** [comment]
Closing as the question seems answered.
