### ISSUE TITLE
[Question] Is it possible to define default responses for all endpoints ?

### ISSUE THREAD

**Issue by ruscon** [zircote/swagger-php#1356]
For example, we want to define a 500 default HTTP status for all API methods.
Without the need to specify it every time for each API method.

**Comment by DerManoMann** [comment]
There is nothing in the library at the moment but my project https://github.com/DerManoMann/openapi-router has a `Controller` annotation that allows to define defautl responses on controller level (but not the whole API). Might be something worth porting...

**Comment by ruscon** [comment]
I don't see the point in additional libraries for this.

It's more of a question, was this library made initially strictly following the Open IP specs or is the main developer agreeing to add some additional features?

Therefore, we personally lack a couple of chips on our project.

1. Common responses for all endpoints (500 http status)
2. `Tags at the controller level, so that tags would be automatically passed to all controller methods 
```php
#[Tags(Model::class, 'another-tag')]
class SomeClass {}
```
3. [`$ref` as `Model::class`](https://github.com/zircote/swagger-php/issues/1357)

**Comment by DerManoMann** [comment]
> I don't see the point in additional libraries for this.

Well, that is exactly my point. These things you are asking for are not part of swagger-php at the moment. The library is staying very close to the specs where possible. 

I am not sure that watering down the library with nice-to-have features is good so moving some stuff into an additional library seems like the right thing to do.

Your feature requests are all good ideas so I hope those will find their way into a new `extras` library soon.

**Comment by ruscon** [comment]
@DerManoMann Ok, thanks

**Comment by DerManoMann** [comment]
The `Controller` annotation of the https://github.com/DerManoMann/openapi-extras project would be able to help with that. Still early days and room for improvements...
