### ISSUE TITLE
[Question] Is it possible to define global header endpoints?

### ISSUE THREAD

**Issue by Buzka91** [zircote/swagger-php#1358]
I got custom header that defines language of text in responses. Is it possible to add such thing globally? Back in the day `security` headers were visible at beginning of docs, but nowadays it "copy" header spec to methods that use specific security type...

**Comment by DerManoMann** [comment]
Are these headers request or response headers? How would you imagine those annotations could look like?

**Comment by DerManoMann** [comment]
I've started a new project https://github.com/DerManoMann/openapi-extras to collect a few reusable annotations that are out of scope for swagger-php itself.

The `Controller` annotation could be extended to also share headers I suppose.

**Comment by DerManoMann** [comment]
Closing here. Further discussion should happen in the [openapi-extras](https://github.com/DerManoMann/openapi-extras) project.
