### ISSUE TITLE
DeprecatedCreation of dynamic property OpenApi\Context showing when generating the openapi.yaml file

### ISSUE THREAD

**Issue by WendellAdriel** [zircote/swagger-php#1372]
I have a Laravel 9 project that I updated to PHP 8.2
After the update when I run this command

```
php ./vendor/bin/openapi --bootstrap ./tools/swagger-constants.php --output ./public/swagger ./config/swagger.php ./app
```

I got a lot of error messages:
![image](https://user-images.githubusercontent.com/11641518/209826127-eafd0a2b-fd29-4b0f-ac18-c3d5d9cb52f7.png)

How can I fix those error messages?

The package version installed is 3.3.6

**Comment by DerManoMann** [comment]
Should be fixed in 3.3.7
