### ISSUE TITLE
Add support for `doctrine/annotations` ^2.0

### ISSUE THREAD

**Issue by mbabker** [zircote/swagger-php#1374]
The `doctrine/annotations` package got a [2.0 release](https://github.com/doctrine/annotations/releases/tag/2.0.0) just before the new year.  Unfortunately, the release has a bit of impact on this package as the `OpenApi\Generator` class [relies on the deprecated `Doctrine\Common\Annotations\AnnotationRegistry::registerLoader()`](https://github.com/zircote/swagger-php/blob/e505bce612a86fe90f8fd50917e0848afc5d2ba8/src/Generator.php#L93-L113) to throw a targeted exception message to help with migrating from older versions (first introduced in https://github.com/zircote/swagger-php/commit/dddf1cf5bafe047dfc59fa3f2901c7a5138b1db0).

It's easy to add a `method_exists()` check to the existing [`class_exists()` check](https://github.com/zircote/swagger-php/blob/e505bce612a86fe90f8fd50917e0848afc5d2ba8/src/Generator.php#L89), but looking at the code and its purpose (also realizing that I've only been using this package since some point after 4.0 was released), a part of me wonders if this block of code even needs to exist moving forward as it looks like its entire purpose was to help catch issues with the namespace migration between 2.x and 3.x.

**Comment by DerManoMann** [comment]
Correct on both. I think I'll keep the code in there for now as with PhpCSFixer not allowing ^2.0 yet its mostly decoration.
I'll mark the code block as deprecated so we can remove it at a later time.
