### ISSUE TITLE
4.5.4 breaks \OpenApi\Attributes\Schema extends

### ISSUE THREAD

**Issue by momala454** [zircote/swagger-php#1386]
The following works and generate a valid openapi schema on 4.5.3, but not on 4.5.4, where nothing is generated

It could be caused by https://github.com/zircote/swagger-php/issues/1359
Reverting the pull does indeed fixes it

```php
#[\Attribute(\Attribute::TARGET_CLASS | \Attribute::TARGET_METHOD | \Attribute::TARGET_PROPERTY)]
class HelloWorld extends \OpenApi\Attributes\Schema
{
}


#[HelloWorld]
class MyClass
{
}

```

**Comment by DerManoMann** [comment]
@momala454 would you be able to test the PR and let me know if that is ok?

**Comment by momala454** [comment]
Thank you, it works !

By the way, the version 4.5.5 is not published on packagist.

Also can you please check my solution for another problem there https://github.com/zircote/swagger-php/issues/1338#issuecomment-1326465000
So i don't have to manually patch swagger-php at every update ?
