### ISSUE TITLE
Found 'oneOff' in the code

### ISSUE THREAD

**Issue by ganehag** [zircote/swagger-php#1392]
https://github.com/zircote/swagger-php/blob/795be27b3b3bacc8353350cacc663ac5cbcd05cc/src/Processors/Concerns/CollectorTrait.php#L39

https://github.com/zircote/swagger-php/blob/795be27b3b3bacc8353350cacc663ac5cbcd05cc/src/Processors/CleanUnusedComponents.php#L41

Am I wrong in thinking this should be "oneOf" and is a typo?

**Comment by DerManoMann** [comment]
Ha! Good one; yes 'oneOf' would look better
