### ISSUE TITLE
Call to undefined function Swagger\scan()

### ISSUE THREAD

**Issue by Rajamalli** [zircote/swagger-php#1406]
I have php 5.6 and swagger-php 2.0
When i try to run http://local-server-name/index.php/Documentation/control i get the following error

**PHP message: PHP Fatal error:  Call to undefined function Swagger\scan()**

The script is executing fine from command line.
The code in /Documentation/control

`<?php`
`header('Access-Control-Allow-Origin: *');`
`require("vendor/autoload.php");`
`$swagger = \Swagger\scan($_SERVER['DOCUMENT_ROOT'].'/application/controllers');`
`header('Content-Type: application/json');`
`echo $swagger;`

**Comment by DerManoMann** [comment]
Looks like an autoloader problem then. Do you have the vendor folder in the he right place? IE next to the index.php?
You could try to require the autoloader script with an absolute path: `__DIR__ . '/vendor/autoload.php'`

**Comment by Rajamalli** [comment]
Thank you. It works now!!
