### ISSUE TITLE
Call to undefined function Swagger\scan() Error

### ISSUE THREAD

**Issue by stone89son** [zircote/swagger-php#1413]
Hi every one.
I use swagger-php with Codeigniter 4.
I created controller SwaggerD will make home page for api doc.
and code of SwaggerD controller:
```
<?php

namespace App\Controllers;

use Zircote\SwaggerPhp\Swagger;
header('Access-Control-Allow-Origin: *');

require(APPPATH . '../vendor/autoload.php');

class SwaggerD extends BaseController
{
    public function index()
    {
        
        $swagger = \Swagger\scan(APPPATH . 'Api\V1');
        header('Content-Type: application/json');
        echo $swagger;
    }
}
```
When i run reviced to error:
![testaa](https://user-images.githubusercontent.com/6795515/218367297-5a8daa04-2bd9-4be2-b411-273f85b59224.PNG)

I other trying but not works!

**Comment by DerManoMann** [comment]
Your code seems to be based on some very old documentation.
Have a look at the readme here for something more up to date.
Something like https://github.com/zircote/swagger-php#usage-from-php

**Comment by stone89son** [comment]
thank for reply. worked. but why not show swagger ui?
![image](https://user-images.githubusercontent.com/6795515/218453218-0130bda0-debc-4223-b6d2-aacb9fd7d94a.png)

**Comment by DerManoMann** [comment]
Swagger ui is a separate project to display the Jason/yaml generated by swagger-php. You will need to download and set up the UI separately.

**Comment by stone89son** [comment]
thank for help me.
