### ISSUE TITLE
Call to undefined method [SomeAnnotation]::isRoot()

### ISSUE THREAD

**Issue by eigan** [zircote/swagger-php#1415]
```
Error: Call to undefined method Symfony\Component\Serializer\Annotation\DiscriminatorMap::isRoot()

/vendor/zircote/swagger-php/src/Analysis.php:341
/vendor/zircote/swagger-php/src/Processors/ExpandClasses.php:35
/vendor/zircote/swagger-php/src/Analysis.php:425
/vendor/zircote/swagger-php/src/Generator.php:458
```

This can happen if you have a different annotation on an `@OA\Schema`.

```php
/**
 * @OA\Schema(title="Some DTO", required={"title", "data_type"})
 * @Serializer\DiscriminatorMap(typeProperty="data_type", mapping={
 *     "foo"="bar",
 * })
 */
abstract class SomeDto {}
```

The line in Analysis seems to just assume that all annotations on the class has the `isRoot` method. 
```php
if ($annotation->isRoot(OA\Schema::class) && !$annotation->_context->is('generated')) {
```

Seems to be related to https://github.com/zircote/swagger-php/commit/e449670473d7ecaff75dff744e8e9be68a79a44c https://github.com/zircote/swagger-php/pull/1403

**Comment by DerManoMann** [comment]
Have you tried upgrading swagger-php ? I tried creating a testcase and it looks like the latest code should be ok with this.

**Comment by eigan** [comment]
Sorry, I should have provided better example.


```php
<?php
require "vendor/autoload.php";

use OpenApi\Annotations as OA;

/**
 * @Annotation
 */
class CustomAnnotation {}

/**
 * @OA\Schema
 * @CustomAnnotation
 */
class SomeParent {}

/**
 * @OA\Schema
 */
class Child extends SomeParent {}

$generator = new \OpenApi\Generator();

$generator->generate([
    __FILE__
]);
```

**Comment by DerManoMann** [comment]
Interesting - things change depending on whether there is a namespace used or not :waffle:

**Comment by eigan** [comment]
Thank you for the quick fix! 🙂

**Comment by akalineskou** [comment]
FYI this is also happening in https://github.com/zircote/swagger-php/blob/47922894170ca3c51703230e0d9417e22edcefd4/src/Processors/AugmentSchemas.php#L27 also

`Call to undefined method OpenApi\\Attributes\\JsonContent::isRoot()`

Adding the same `$schema instanceof OA\Schema` check seems to get rid of the error, but I'm not sure if that is the correct solution

**Comment by DerManoMann** [comment]
I am not sure what is going on there - `JsonContent` definitly shoudl have `AbstractAnnotation` as parent somewhere and that has the `isRoot` method.

**Comment by akalineskou** [comment]
@DerManoMann You are correct, the function should be there but isn't... something went haywire with my vendor folder, re-installed everything and it works.
