### ISSUE TITLE
Conditional Options

### ISSUE THREAD

**Issue by dlavineway** [zircote/swagger-php#1427]
Not an issue more of a question or enhancement;

Is it possible to add conditions around the operations
```
/**
 * @if (DEBUG_ENV)
 * @OA\Get(
 *     path="/my-endpoint",
 *     summary="My endpoint",
 *     @OA\Response(
 *         response="200",
 *         description="Success"
 *     ),
 *     @OA\Response(
 *         response="404",
 *         description="Resource not found"
 *     )
 * )
 * @endif
 */

**Comment by DerManoMann** [comment]
Fair question but the answer is no.

This would need to be handled by the doctrine annotations library and I cannot see that happening with most of the focus being on PHP 8+ attributes.
