### ISSUE TITLE
Unable to render this definition The provided definition does not specify a valid version field.

### ISSUE THREAD

**Issue by rsplsk** [zircote/swagger-php#1433]
Hello Team,

I am facing below issue and not able to find solution for it. 

Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).

Not getting where I need to pass version field. I have tried to pass into API doc but still getting error? Could you please help me on it?

**Comment by DerManoMann** [comment]
I am reading this as resolved, so closing..
