### ISSUE TITLE
API with no endpoints throws exception Required @OA\\PathItem() not found

### ISSUE THREAD

**Issue by savedario** [zircote/swagger-php#1449]
If there are no endpoints defined either with @OA\<method> or with @OA\PathItem, the swagger page shows no output and the application logs the exception:

Required @OA\\PathItem() not found at /project/vendor/zircote/swagger-php/src/Loggers/DefaultLogger.php:31

which is a rather misleading message.

Note: other annotations are in use (Info, Server, SecurityScheme, Flow) that were obviously referring to yet-to-be-developed endpoints, but that does not seem to be a problem just to generate the swagger page.

**Comment by DerManoMann** [comment]
The spec ifself just describes endpoints. Whether those endpoints exist or not does not really matter here. They might be password protected, behind a firewall or not yet exist.

However, for an OpenAPI spec to make sense it needs to contain endpoints (as that is the main point).

If you already have other annotations that describe yet to be developed  features, why not also add a (simple/dummy) endpoint to get things going?

**Comment by savedario** [comment]
My original intention was not to ask a question but to signal an issue that could be fixed by either:

- throwing an exception with a more descriptive message when no endpoints are detected or...
- consider that OpenAPI (in my case `league/openapi-psr7-validator`) allows to define an API with no endpoints (whether that make sense or not) and leave that part of the page just... empty ?

**Comment by potsky** [comment]
Upgrading from 4.7.16 to 4.8.1 produces the same problem on our Laravel installation but all PHP files have a `@OA<method>`...

I tried to find from where comes this problem but without any success 😢

**Comment by DerManoMann** [comment]
As of 4.8 the doctrine/annotations package is optional, which also causes this error - as no annotations are parsed.
Maybe the error message could be improved.

**Comment by potsky** [comment]
Thank you @DerManoMann, indeed, adding `"doctrine/annotations": "^2.0"` to our `composer.json` works 🎉
