### ISSUE TITLE
generic types

### ISSUE THREAD

**Issue by LTaooo** [zircote/swagger-php#1451]
Does it support generic types? For example, I have a PageResponse that is compatible with CatSchema and DogSchema

**Comment by DerManoMann** [comment]
The code does handle inheritance of schemas, but there are limits. Do you have some sample code?

**Comment by LTaooo** [comment]
> The code does handle inheritance of schemas, but there are limits. Do you have some sample code?

Thank you for your answer. I have found an elegant way to use swagger.
