### ISSUE TITLE
Grouping request in single class to single tag?

### ISSUE THREAD

**Issue by hsnfirdaus** [zircote/swagger-php#1452]
How can i group all request in single class to single tag? When i use like this:
![image](https://github.com/zircote/swagger-php/assets/38871578/d17d816d-81b3-4638-a6a7-e6a09b153b44)
It doesn't work:
![image](https://github.com/zircote/swagger-php/assets/38871578/874b7293-beb9-42bc-b941-22c09a25a730)
But, when i add tags to all my request it's work.
![image](https://github.com/zircote/swagger-php/assets/38871578/37025c5c-5787-485b-8145-882639a4da8c)
![image](https://github.com/zircote/swagger-php/assets/38871578/96275fa5-737e-4f5f-a3c7-b32cbbe632c1)

Can i just declare tag in class attribute?

**Comment by DerManoMann** [comment]
That is outside the scope of this library.

https://github.com/DerManoMann/openapi-extras does have a `Controller` annotation that allows to share a url prefix and responses. Adding tags would be not too hard, I suppose.

**Comment by hsnfirdaus** [comment]
> That is outside the scope of this library.
> 
> https://github.com/DerManoMann/openapi-extras does have a `Controller` annotation that allows to share a url prefix and responses. Adding tags would be not too hard, I suppose.

Oh i see, but in that repository i think for now there is no such things as "tag" in controller?

**Comment by DerManoMann** [comment]
No, but there it would be easy to add.
