### ISSUE TITLE
Q: using class in x- property definition

### ISSUE THREAD

**Issue by mroeling** [zircote/swagger-php#1453]
Hi,

I'm looking for a way to improve type hinting/checking on the x- property of an OA/Property definition:
```php
    #[OA\Property(
        type: 'string',
        format: 'date-time',
        x: [
            'config' => new PropertyConfigurationAttribute( // Could have proper types via the construct definition of the class
                anyBooleanProperty: true,
                anyStringProperty: "valid string",
            ),
        ],
    )]
```
    
This specific case is not working. Is there a way to get this to work with the current code?

**Comment by DerManoMann** [comment]
Sorry, but something like this is not supported.
The main question here is what would the spec look like? I do not think OpenAPI does support types or anything else on x- properties.
