### ISSUE TITLE
Excluding some cases in enum

### ISSUE THREAD

**Issue by momala454** [zircote/swagger-php#1465]
I have an enum where certain values are "internal" and are not supposed to be on the swagger.
It is not currently possible to exclude certain cases.

Do you think it's a good idea to add an attribute to exclude

by example 
```php
enum Test
{
    #[\OpenApi\Exlude]
    case Internal;
    case Hello;
}
```

**Comment by DerManoMann** [comment]
I feel that this would be a too special case to have room in this library, sorry.
