### ISSUE TITLE
If I set Nullable to true, the generated document will lose the title

### ISSUE THREAD

**Issue by LTaooo** [zircote/swagger-php#1471]
![image](https://github.com/zircote/swagger-php/assets/28125259/fb9aaf9c-f8ca-46d4-ad77-00266e2c792a)
![image](https://github.com/zircote/swagger-php/assets/28125259/9dcb7d41-d728-4582-9fc9-a86bac9e4cf0)

**Comment by DerManoMann** [comment]
Is this for OpenApi 3.1.0?

**Comment by LTaooo** [comment]
> Is this for OpenApi 3.1.0?

yes
