### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Attempting to use non-attribute class "OpenApi\Annotations\Info" as attribute

### ISSUE THREAD

**Issue by kkozlik** [zircote/swagger-php#1482]
I am new to swagger-php so I am not sure whether I am doing something wrong,  but when I try to use Attributes instead of Annotations I get following error:

```
PHP Fatal error:  Uncaught Error: Attempting to use non-attribute class "OpenApi\Annotations\Info" as attribute in vendor/zircote/swagger-php/src/Analysers/AttributeAnnotationFactory.php:42
```

I use PHP 8.2.7

With annotations it works fine.

My code is pretty simple:
```php
<?php
use OpenApi\Annotations as OA;

#[OA\Info(title: "My First API", version: "0.1")]
class my_class {
}
```

I have no experience with using attributes, but from what I have learned, I would say the `Info` class (and also other classes from the `Annotations` namespace shall be declared with an attribute, should not they? Check e.g. here: https://blog.shalvah.me/posts/php-8-attribute-quirks

**Comment by DerManoMann** [comment]
Annotations and attributes are separate classes.
You need to import the attributes:
```
Use OpenApi\Attribues as OA;
```

**Comment by kkozlik** [comment]
:facepalm: Oh, silly me. I completely overlooked this detail. Thanks for pointing on this.
