### ISSUE TITLE
`enum_exists()` is called in `ExpandEnums::expandSchemaEnum()`

### ISSUE THREAD

**Issue by karelvasicek** [zircote/swagger-php#1484]
https://github.com/zircote/swagger-php/blob/99b04b5cabf524c05f9428955af8406755ab183c/composer.json#L47 but https://github.com/zircote/swagger-php/blob/99b04b5cabf524c05f9428955af8406755ab183c/src/Processors/ExpandEnums.php#L87 is used.

`enum_exists()` method was added in PHP8.

**Comment by DerManoMann** [comment]
Hi @karelvasicek - could you give the linked PR a try?

**Comment by DerManoMann** [comment]
.. although there is some weirdness in there yet :/

**Comment by karelvasicek** [comment]
@DerManoMann , thanks for such quick resolution, I updated `composer.json` accordingly and yes, the PR fixes the actual issue.

**Comment by karelvasicek** [comment]
I'm not sure how the whole `enum_exists()` logic is supposed to work, though. In any case, it does not work with https://github.com/symfony/polyfill-php81/blob/7581cd600fa9fd681b797d00b02f068e2f13263b/bootstrap.php#L26-L28 . We have f.ex. `["123"]` enum example in our code and `class_exists($enum)` used in the Symfony Polyfill library linked above invokes autoloading `123` class that apparently does not exist.

**Comment by DerManoMann** [comment]
wow. not shure how to take the last comment - is there anything to do on my side or not.
Sounds complicated and related to 3rd party libraries that we have not much control over.

Having siad that, it might be interesting to debug that sort of scenario. If you feel up to it, a little repo to reproduce the issue would be great.
If not, let me know if there is anything else you need for this to be resolved or not.

**Comment by karelvasicek** [comment]
@DerManoMann 

> wow. not shure how to take the last comment

Sorry for confusion. First I thought that it was related to PHP Swagger lib, but it was not. It's related most to the Yii (v1) class autoloader and logic how it handles not existing files (autoloaded classes). But as I wrote, it can be (and should be) resolved by the actual autoloader (autoloader can be configured accordingly).

> debug that sort of scenario

There is not much to debug, the autoloader just tries  to `include()` a file no matter if it exists or not. So the autoloader setting must be adjusted.

Anyway, thanks for that quick fix, everything works as intended IMO.
