### ISSUE TITLE
php 8.1 annotations error | requestBody

### ISSUE THREAD

**Issue by janwittkamp** [zircote/swagger-php#1494]
When I use psalm I get an error when I use the following php 8.1 annotations.

Should requestBody content allow JsonContent and MediType combined or do I read the docs wrong?

Environment:
php 8.1
zircote/swagger-php: 4.7.15

`Argument 2 of OpenApi\Attributes\RequestBody::__construct expects OpenApi\Attributes\Attachable|OpenApi\Attributes\JsonContent|OpenApi\Attributes\MediaType|OpenApi\Attributes\XmlContent|array<array-key, OpenApi\Attributes\MediaType>|null, but array{OpenApi\Attributes\JsonContent, OpenApi\Attributes\MediaType} provided (see https://psalm.dev/004)`

```php
 #[OAT\Post(
        path: '/api/v1/test123',
        operationId: 'test1',
        description: 'xyz,
        requestBody: new OAT\RequestBody(
            required: true,
            content: [
                new OAT\JsonContent(
                    type: 'object',
                    required: [
                       ...
                    ],
                    allOf: [
                        new OAT\Property(
                            ref: SchemaY::class
                        ),
                    ],
                ),
                new OAT\MediaType(
                    mediaType: 'multipart/form-data',
                    schema: new OAT\Schema(
                        type: 'object',
                    ),
                ),
            ],
        ),
        tags: ['test']
    )]
```

**Comment by DerManoMann** [comment]
Hmm, should work.

A workaround would be to not use `RequestBody` at all (still, looks like a bug to me).

Since `content` accepts `JsonContent` directly you could pass that in directly (although you would probably loose the `required` property)

**Comment by DerManoMann** [comment]
I just tried running your example and on its own it fails with two syntax errors.

One is the `...` is the `required` list. The other is a missing single quote `'` on the `Post` `description`.

Once fixed things start to work:

To reproduce:


`request_body.php`:
```php
<?php

use OpenApi\Attributes as OAT;

#[OAT\Post(
        path: '/api/v1/test123',
        operationId: 'test1',
        description: 'xyz',
        requestBody: new OAT\RequestBody(
            required: true,
            content: [
                new OAT\JsonContent(
                    type: 'object',
                    allOf: [
                        new OAT\Property(
                            ref: SchemaY::class
                        ),
                    ],
                ),
                new OAT\MediaType(
                    mediaType: 'multipart/form-data',
                    schema: new OAT\Schema(
                        type: 'object',
                    ),
                ),
            ],
        ),
        tags: ['test']
    )]
class Controller {}

```

Running
```shell
 ./bin/openapi -b request_body.php request_body.php 
```

provides the following output:
```yaml
openapi: 3.0.0
paths:
  /api/v1/test123:
    post:
      tags:
        - test
      description: xyz
      operationId: test1
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
          application/json:
            schema:
              type: object
              allOf:
                -
                  $ref: SchemaY

```

**Comment by janwittkamp** [comment]
@DerManoMann  Thanks for the quick reply. Sorry for the misleading pieces of information, I just cropped my annotations down, this problem only occurs if I use my CI (psalm) to check for any errors in my code.
The generated openapi output is fine, only the phpDoc is misleading and says you could not use it.


/src/Attributes/RequestBody.php:17
`   @param array<MediaType>|MediaType|JsonContent|XmlContent|Attachable|null $content`
This should be correct if I'm not wrong:
`   @param array<MediaType|JsonContent|XmlContent|Attachable>|MediaType|JsonContent|XmlContent|Attachable|null $content`

**Comment by DerManoMann** [comment]
Meh. I could also have spent a bit more time reading your message properly 😞

**Comment by janwittkamp** [comment]
@DerManoMann Please keep in mind that the previous one still works and if you changed it only to array<...>|null you need to wrap it in an array.

If you make this change I get the following error.

`
Argument 2 of OpenApi\Attributes\RequestBody::__construct expects array<array-key, OpenApi\Attributes\Attachable|OpenApi\Attributes\JsonContent|OpenApi\Attributes\MediaType|OpenApi\Attributes\XmlContent>|null, but OpenApi\Attributes\JsonContent provided (see https://psalm.dev/004)
`

```php
  #[OAT\Post(
        path: '/api/v1/test123',
        operationId: 'test1',
        description: 'test',
        requestBody: new OAT\RequestBody(
            required: true,
            content: new OAT\JsonContent(
                type: 'object',
                allOf: [
                    new OAT\Property(
                        ref: SchemaY::class
                    ),
                ],
            ),
        ),
        tags: ['test'],
    )]
```
