### ISSUE TITLE
Fatal error Psr\Log\AbstractLogger::emergency

### ISSUE THREAD

**Issue by igor-davidov** [zircote/swagger-php#1498]
1. This is on PHP 8.3 on Debian GNU/Linux 12 (bookworm)
2. Installed "zircote/swagger-php": "^4.7"
3. Run \OpenApi\Generator::scan(['/var/www/mydir']);
4. Error: `Fatal error: Declaration of Psr\Log\AbstractLogger::emergency(Stringable|string $message, array $context = []): void must be compatible with Psr\Log\LoggerInterface::emergency($message, array $context = []) in /var/www/mydir/vendor/psr/log/src/LoggerTrait.php on line 23`

**Comment by igor-davidov** [comment]
I removed all declarations `string|\Stringable` from /psr/log/src/LoggerTrait.php. For example `public function emergency(string|\Stringable $message, array $context = []): void` became `public function emergency($message, array $context = []): void`

I guess I'm too tired now to seek why there is incompatibility because I want to test swagger. If someone finds better solution I would be thankfull.

**Comment by DerManoMann** [comment]
What version of Psr\Log and Monolog have you got installed?
Downgrading should fix this, I think.
