### ISSUE TITLE
Broken links in https://zircote.github.io/swagger-php/

### ISSUE THREAD

**Issue by Itee** [zircote/swagger-php#1501]
Hi there, just a little feedback

The link to OpenApi in the top right menu is broken and finish to a 404.
The target is: https://oai.github.io/Documentation/

Some others broken links that i found:

- In https://zircote.github.io/swagger-php/guide/#what-is-swagger-php the [OpenAPI documentation](https://oai.github.io/Documentation/specification.html)

- In https://zircote.github.io/swagger-php/guide/annotations.html#doctrine the [doctrine style annotations](https://www.doctrine-project.org/projects/doctrine-annotations/en/latest/index.html)

- In https://zircote.github.io/swagger-php/related-projects.html the [Swagger Explained](https://bfanger.nl/swagger-explained/)

Hope this help,
Itee

**Comment by xuanyanwow** [comment]
I created a pr to fixed this issue. https://github.com/zircote/swagger-php/pull/1506
