### ISSUE TITLE
Remove server URL below @OA\Info

### ISSUE THREAD

**Issue by RobertEcker** [zircote/swagger-php#1505]
Hi, 

it's a question and not a bug ...
how can I remove the server URL within @OA\Info.
e.g., I am using below source to attribute a class.

```
/**
 * @OA\Info(title="API live test My First API", version="0.1", 
         license ={"name": "Lic", "url": "http://www.example.com/lice"},
         termsOfService ="http://example.com/terms/", 
         contact={"name": "API Support", "url": "http://www.example.com/support"})
 */
```

![screenshot](https://github.com/zircote/swagger-php/assets/6156052/91075be2-5567-4f80-baa5-4e5171c5427d)

Thank you!

**Comment by DerManoMann** [comment]
Processing your example I do get this output:
```yaml
openapi: 3.0.0
info:
  title: 'API live test My First API'
  termsOfService: 'http://example.com/terms/'
  contact:
    name: 'API Support'
    url: 'http://www.example.com/support'
  license:
    name: Lic
    url: 'http://www.example.com/lice'
  version: '0.1'
```

Nothing in there looks like the url you have highligted. I suspect that swagger-ui adds this?

**Comment by RobertEcker** [comment]
mh - I guess so too - thanks - I will ask in swagger-ui
