### ISSUE TITLE
Php 8

### ISSUE THREAD

**Issue by verschoof** [zircote/swagger-php#1509]
Hi,

Can I use this lib for php 8.3?
I see in the composer require its for >=7.2

I seen some issues talking about 8.2 but I don't understand how to use it if the composer require doesn't allow php 8 (https://github.com/zircote/swagger-php/issues/1494)

**Comment by DerManoMann** [comment]
Yes, swagger-php doe work with anything from 7.2 upwards, including PHP 8.x

**Comment by verschoof** [comment]
ok thanks!
