### ISSUE TITLE
Serialization of data using swagger-php attributes

### ISSUE THREAD

**Issue by MattyRad** [zircote/swagger-php#1514]
I noticed there is a [Serializer](https://github.com/zircote/swagger-php/blob/master/src/Serializer.php) class, which does a lot of deserialization, but not a lot of serialization.

It would be really nice to serialize an object directly from swagger-php attributes using a function that is provided by the library. For example: 

```php
use OpenApi\Attributes as OpenApi;

class Sample
{
    #[OpenApi\Property(
        property: 'greeting',
    )]
    public function getGreeting(): string
    {
        return 'hello world';
    }
}

class BasicsSerializeTest extends \PHPUnit\Framework\TestCase
{
    /** @test */
    public function basic_openapi_serialization(): void
    {
        $sample = new Sample;

        $serialized = Api::openapiSerialize($sample);

        $this->assertEquals(['greeting' => 'hello world'], $serialized);
    }
}
```

We currently have the function `openapiSerialize` implemented, and it has been great!

> (`openapiSerialize` as we have it is quite large and unwieldy, hence posting the test and not the implementation).

Serializing from swagger-php attributes ensures that the API documentation *necessarily* matches the API response- i.e. you cannot add/adjust a response format without also adding/adjusting a swagger-php attribute.

I am planning on creating a repo which provides `openapiSerialize` and explaining why it's valuable, but if there is interest in me making a PR to this repo on the Serializer class (instead of a separate repo), then please let me know and I will make a PR.

Thanks for the excellent library!

**Comment by DerManoMann** [comment]
There is an alternative way which is implemented here: https://github.com/DerManoMann/openapi-verifier

Basically it takesan API response and validates it against the spec. The code takes advantage of the fact that the spec is a JSON schema and therefore the API response data can be validated against the schema.

The project needs some love, though :{
