### ISSUE TITLE
Error for generating swagger.json file from PHP 8.1.25 in xampp environment.

### ISSUE THREAD

**Issue by protappro** [zircote/swagger-php#1525]
Warning: Skipping unknown \AirportApi in C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Loggers\DefaultLogger.php on line 31

Warning: Skipping unknown \Database in C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Loggers\DefaultLogger.php on line 31

Fatal error: Uncaught Error: Class "Symfony\Component\Console\Command\Command" not found in C:\xampp\htdocs\airport_guide_api\vendor\symfony\yaml\Command\LintCommand.php:37 Stack trace: #0 C:\xampp\htdocs\airport_guide_api\vendor\composer\ClassLoader.php(576): include() #1 C:\xampp\htdocs\airport_guide_api\vendor\composer\ClassLoader.php(427): Composer\Autoload\{closure}('C:\\xampp\\htdocs...') #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...') #3 C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Analysers\ReflectionAnalyser.php(87): class_exists('Symfony\\Compone...') #4 C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Analysers\ReflectionAnalyser.php(62): OpenApi\Analysers\ReflectionAnalyser->analyzeFqdn('Symfony\\Compone...', Object(OpenApi\Analysis), Array) #5 C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Generator.php(493): OpenApi\Analysers\ReflectionAnalyser->fromFile('C:\\xampp\\htdocs...', Object(OpenApi\Context)) #6 C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Generator.php(490): OpenApi\Generator->scanSources(Object(Symfony\Component\Finder\Finder), Object(OpenApi\Analysis), Object(OpenApi\Context)) #7 C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Generator.php(455): OpenApi\Generator->scanSources(Array, Object(OpenApi\Analysis), Object(OpenApi\Context)) #8 C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Generator.php(407): OpenApi\Generator->generate(Array, Object(OpenApi\Analysis), true) #9 C:\xampp\htdocs\airport_guide_api\documentation\api.php(4): OpenApi\Generator::scan(Array) #10 {main} thrown in C:\xampp\htdocs\airport_guide_api\vendor\symfony\yaml\Command\LintCommand.php on line 37

**Comment by DerManoMann** [comment]
Closing in favour of #1526
