### ISSUE TITLE
Warning: Skipping unknown | Warning: Required @OA\PathItem()  | not found Warning: Required @OA\Info() not found when generating the swagger.json files

### ISSUE THREAD

**Issue by protappro** [zircote/swagger-php#1526]
Warning: Skipping unknown \AirportApi in C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Loggers\DefaultLogger.php on line 31

Warning: Skipping unknown \Database in C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Loggers\DefaultLogger.php on line 31

Fatal error: Uncaught Error: Class "Symfony\Component\Console\Command\Command" not found in C:\xampp\htdocs\airport_guide_api\vendor\symfony\yaml\Command\LintCommand.php:37 Stack trace: #0 C:\xampp\htdocs\airport_guide_api\vendor\composer\ClassLoader.php(576): include() #1 C:\xampp\htdocs\airport_guide_api\vendor\composer\ClassLoader.php(427): Composer\Autoload\{closure}('C:\\xampp\\htdocs...') #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...') #3 C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Analysers\ReflectionAnalyser.php(87): class_exists('Symfony\\Compone...') #4 C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Analysers\ReflectionAnalyser.php(62): OpenApi\Analysers\ReflectionAnalyser->analyzeFqdn('Symfony\\Compone...', Object(OpenApi\Analysis), Array) #5 C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Generator.php(493): OpenApi\Analysers\ReflectionAnalyser->fromFile('C:\\xampp\\htdocs...', Object(OpenApi\Context)) #6 C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Generator.php(490): OpenApi\Generator->scanSources(Object(Symfony\Component\Finder\Finder), Object(OpenApi\Analysis), Object(OpenApi\Context)) #7 C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Generator.php(455): OpenApi\Generator->scanSources(Array, Object(OpenApi\Analysis), Object(OpenApi\Context)) #8 C:\xampp\htdocs\airport_guide_api\vendor\zircote\swagger-php\src\Generator.php(407): OpenApi\Generator->generate(Array, Object(OpenApi\Analysis), true) #9 C:\xampp\htdocs\airport_guide_api\documentation\api.php(4): OpenApi\Generator::scan(Array) #10 {main} thrown in C:\xampp\htdocs\airport_guide_api\vendor\symfony\yaml\Command\LintCommand.php on line 37

## from command line
C:\xampp\htdocs\airport_guide_api>openapi c:\xampp\htdocs\airport_guide_api\airport_api.php -o c:\xampp\htdocs\airport_guide_api\swagger.json
Warning: Skipping unknown \AirportApi
Warning: Required @OA\PathItem() not found
Warning: Required @OA\Info() not found

**Comment by DerManoMann** [comment]
swagger-php does neet autoloading as it depends on using reflection on the code it analyses.
Have a look at
https://zircote.github.io/swagger-php/guide/faq.html#warning-required-oa-info-not-found
or
https://zircote.github.io/swagger-php/guide/faq.html#skipping-unknown-someclass

In particular you might need to use the `-b` option to get things working.

**Comment by protappro** [comment]
1. _https://zircote.github.io/swagger-php/guide/faq.html#skipping-unknown-someclass
In particular you might need to use the -b option to get things working._

Neither its working in my system.

2. _https://zircote.github.io/swagger-php/guide/faq.html#warning-required-oa-info-not-found_
I wrote everything from this url but didn't work.
when I run api.php its return skipping error along with Warning: Required @OA\PathItem() | not found Warning: Required @OA\Info() not found

**Comment by DerManoMann** [comment]
Looks like your classes don't use any namespaces; have you set up composer class loading correctly?
Also, did you see the note about doctrine/annotations now being optional?
(Obviously doesn't apply if you are using attributes)
Apart from that this is hard to debug without some self-contained examples of how to replicate the issue.

**Comment by protappro** [comment]
I got my answer.
Actually the problem is the **_"zircote/swagger-php": "^3.2.0"_**
I have php version 8.1.25 and I installed zircote/swagger-php : 4.8.0, so that latest version is not perfectly supported by PHP < 7.4 
I change that version from 4.8.0 to 3.2.0 and then update the composer.
Finally its works fine.

**Comment by DerManoMann** [comment]
> latest version is not perfectly supported by PHP 7.4 < 8.2

Happy you found something that works for you, but this is definitly not correct.
