### ISSUE TITLE
Dereferencing refs in the output openapi document

### ISSUE THREAD

**Issue by MattyRad** [zircote/swagger-php#1527]
It would be nice to be able to add a (cli/PHP) flag to dereference `$ref`s, producing a completed (if repetitive) json/yaml document. [Stackoverflow example](https://stackoverflow.com/questions/65549855/openapi-specification-yml-yaml-all-refs-replace-or-expand-to-its-definition).

Aside from being easier for humans to read, my use case is that I'd like to experiment with using an OpenAPI spec as [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS) data- enabling generic frontends (similar to the [Swagger UI](https://petstore.swagger.io/)). Dereferencing would make that a lot easier.

```json
{
    "openapi": "3.0.0",
    "paths": {
        "/endpoint": {
            "post": {
                "requestBody": {
                    "$ref": "#/components/requestBodies/SomeRequest"
                },
            }
        }
    }
}
```

```json
{
    "openapi": "3.0.0",
    "paths": {
        "/endpoint": {
            "post": {
                "requestBody": {
                    "description": "No refs, cool",
                    "required": true
                },
            }
        }
    }
}
```

I am happy to look in to and do the work of adding this feature to swagger-php myself, but it'd be nice to get some initial thoughts about whether this is a worthwhile feature or if there are hard blockers.

**Comment by DerManoMann** [comment]
Not sure this needs a flag. I would think the way to implement this is to write a custom processor - which can alreay be added on the CL.

**Comment by MattyRad** [comment]
Excellent, thanks for the tip!
