### ISSUE TITLE
Required @OA\\PathItem() not found

### ISSUE THREAD

**Issue by phygineer** [zircote/swagger-php#1539]
Getting error with message: 

Required @OA\\PathItem() not found

**Comment by phygineer** [comment]
This issue is due to recent update & specific to doctrine/annotations. My api doc was not gettong generated due to this.

Turns out as of version 4.8 the [doctrine annotations](https://www.doctrine-project.org/projects/annotations.html) library is optional and no longer installed by default.

This is a breaking change.

Issue got fixed after I installed the library separately.


`composer require doctrine/annotations`

**Comment by winternet-studio** [comment]
Oh my gosh, I just wasted SO much time on this!! This wasn't in the migration documentation! :( And why can't swagger-php let me know that it's missing?!
