### ISSUE TITLE
dynamic basePath fro swagger-php

### ISSUE THREAD

**Issue by PavloPoliakov** [zircote/swagger-php#154]
Hi,

Here is the part of my local documentation:

```
/**
 * Quests controller
 * 
 * @SWG\Resource(
 *     apiVersion="0.1",
 *     swaggerVersion="1.2",
 *     resourcePath="/resources/quests",
 *     basePath="http://mydomain.com"
 * )
 */
```

How can I make it dependent on my local url?
So when I'm on domain local.domain.com , it would consider that domain as basePath.

Any thoughts are appreciated, thanks in advance.

**Comment by VardgesK** [comment]
I have tried to define in AppServiceProvider boot method, its works for me!

Code example

App\Http\Controller.php
```
/**
 * @OA\OpenApi(
 *     @OA\Info(
 *         title="My API",
 *         version="1.0.0"
 *     ),
 * ),
 * @OA\Server(
 *     url=**SWAGGER_BASE_PATH**,
 *     description="API server"
 * )
 */
```
App\Providers\AppServiceProvider.php

```
    public function boot(): void
    {
        define('SWAGGER_BASE_PATH', config('of-swagger.host'));
    }
```
