### ISSUE TITLE
Documentation of enum property in Property attribute with a null value

### ISSUE THREAD

**Issue by veylib** [zircote/swagger-php#1547]
There is an issue with the enum type documentation. `phpstan` is indicating that you cannot set null as an array value in the enum property of the OpenApi\Attributes\Property attribute.

A basic example is provided below:

```
use OpenApi\Attributes as OA;
use Symfony\Component\Validator\Constraints as Assert;

class MyChoice
{
        #[Assert\Choice(choices: ['Choice1', 'Choice2', null])]
        #[OA\Property(enum: ['Choice1', 'Choice2', null], example: 'Choice1', nullable: true)]
        public ?string $choice = null,
}
```

Phpstan is reporting: 

> Parameter $enum of attribute class OpenApi\Attributes\Property constructor expects array<bool|float|int|string|UnitEnum>|class-string|null, array<int, string|null> given.

While this report is technically correct according to the phpdoc documentation and the type definition of the enum property in the Property attribute, it presents a conflict because I am required to declare the null value, whereas phpstan is indicating that it is incorrect.

![image](https://github.com/zircote/swagger-php/assets/22482223/ff5d09a5-168d-4ace-a68e-b2e7675425f9)

**Comment by DerManoMann** [comment]
@veylib could you please try #1548 - I would think that that should fix the issue (sorry, this project only validates at level 5 ;)
