### ISSUE TITLE
Examples property of different object

### ISSUE THREAD

**Issue by sintro** [zircote/swagger-php#1560]
According to https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#fixed-fields-20, 'example' property was renamed to 'examples' (I think the same right for schema``s properties, but this is not clear enough from spec).
Anyway, with 3.1.0 version of Generator it renders 'example' property:
```
openapi: 3.1.0
info:
  title: 'Test'
  version: '1'
components:
  schemas:
    import_props:
      title: 'Import props'
      required:
        - data
        - entity_id
        - mode
      properties:
        data:
          description: 'Data'
          type: string
          format: binary
      example:
        -
          example: 'Example 1'
          summary: 'Example 1'
          value:
            mode: create
            entity_id: 1
            data: data
        -
          example: 'Example 1'
          summary: 'Example 1'
          value:
            mode: update
            entity_id: 1
            data: data
```

This is produced with code inside OA\Schema
```
#[OA\Schema(
        ...
        example: [
            new OA\Examples(
                example: 'Example 1',
                summary: 'Example 1',
                value: [
                    'mode' => 'create',
                    'entity_id' => 1,
                    'data' => 'data'
                ]
            ),
            new OA\Examples(
                example: 'Example 1',
                summary: 'Example 1',
                value: [
                    'mode' => 'update',
                    'entity_id' => 1,
                    'data' => 'data'
                ]
            ),
        ],
        ...
```

The same happens with OA\Property`s 'example' prop.

**Comment by DerManoMann** [comment]
Created a scratch test illustrating the use, see #1561.

The spec says `example` is deprecated, not renamed. You can use either ATM, however for multiple examples `examples` is the preferred way.

Should be:
```php
#[OA\Schema(
        ...
        examples: [
            new OA\Examples(
                example: 'Example 1',

```

**Comment by sintro** [comment]
Thank for answer, but as I can see from you code you showed the usage of 'examples' attribute of QueryParameter class, which was not problem in this particalar issue. The problem is that there are no same attributes in Schema class and its Property class, only single example attributes:
https://github.com/zircote/swagger-php/blob/d3265da27c8983345190123378f4cfda59c2fb41/src/Attributes/Schema.php#L59
https://github.com/zircote/swagger-php/blob/d3265da27c8983345190123378f4cfda59c2fb41/src/Attributes/Property.php#L60
How is it possible to produce "examples" for Schema and schema`s properties with "example" attribute?

**Comment by DerManoMann** [comment]
Ha! Got me there. I suppose `Schema` should then also get an `examples` property I suppose. However, the spec does not show one, so either that is an oversight in the spec or intentional.

Using [spectral](https://github.com/stoplightio/spectral/blob/develop/docs/reference/openapi-rules.md) it seems `examples` is only available in a schema in `3.1.0`.

Did some more surgery on the PR - should work now.

**Comment by sintro** [comment]
Still, validator from https://editor-next.swagger.io/ tells "property "example" is deprecated, use "examples" instead" for Schema`s properties also.

**Comment by DerManoMann** [comment]
None of the snippets [here](https://spec.openapis.org/oas/v3.1.0.html#info-object-example) show `examples` as array so I think it is just fair to treat them the same everywhere.

[spectral](https://github.com/stoplightio/spectral) is happy with the current implementation, so I guess it will be hard to keep everyone happy, unless someone has the definite source of truth.
