### ISSUE TITLE
Dynamically creating schema's based on model properties

### ISSUE THREAD

**Issue by JamieCee20** [zircote/swagger-php#1594]
Is it possible to take the model properties and populate it automatically. As well as maybe generating the responses based on the models toArray() function.

**Comment by JamieCee20** [comment]
@DerManoMann 

Basically we generate a swagger doc to supply our front end team. And we are looking to automate the generation to save time on building.

So im looking to be able to take models, get the properties and generate the model Schema based on those properties.
Ideally will be looking to generate the routes inside the controllers as well, but step at a time.

**Comment by DerManoMann** [comment]
Ok, so you want to basically run swagger-php just without annotations? If that is the case then the simplest solution would be to write some code to generate annotations based on your model classes. The annotations do not have to be attached to the original model classes, so you could create a shadow hierachy with a different namespace perhaps and then run swagger-php against that.

**Comment by DerManoMann** [comment]
Maybe it is even possible to wrap that in a custom processor if there was a custom annotation added to models to be treated that way.

**Comment by JamieCee20** [comment]
> Maybe it is even possible to wrap that in a custom processor if there was a custom annotation added to models to be treated that way.

Yeah apologies, I probably should have added an update. 

So my issue was thinking that I had to add it all as annotations, but I went down the custom processor route and began adding into the component and its currently seeming to do the trick. Now it's still early days into building what I need, but so far so good.
