### ISSUE TITLE
How to create the Restful API documentation from PHP file

### ISSUE THREAD

**Issue by meetmehdi** [zircote/swagger-php#161]
I have downloaded the swagger-php-master from git and in swagger-php-master\Examples\Petstore\Resources folder i have made my own php file now it to get executed to give me the json which i can use with the swagger-ui component please can anyone tell me how.

I have look into this link http://zircote.com/swagger-php/using_swagger.html but to no worth also i tried this one http://stackoverflow.com/questions/16359223/swagger-php-for-generating-json-file-for-swagger-ui but still couldn't be able to do that. 

Later i made the hard coded JSON file and integrated with Swagger UI which i working fine but now i want to make a PHP file like Pet.php and i did it, i have the PHP file but i don't know how to execute the PHP file to get the JSON so that i can integrate it with Swagger UI.

Please help me to understand how. Thank you so much.

**Comment by tranglt6080** [comment]
I can't download swagger.phar. That show page not found.

**Comment by bravo-kernel** [comment]
@tranglt6080 https://github.com/zircote/swagger-php/issues/302
