### ISSUE TITLE
[Feature]: Append "tags" list via Operation attribute

### ISSUE THREAD

**Issue by mazumba** [zircote/swagger-php#1610]
We use vacuum to validate our swagger file and for the api to be valid, the list of used tags is required.
```yaml
tags:
  - name: Some Tag
    description: Description of said tag
```
If we only define the tags within a controller attribute, the endpoints are still correctly grouped by their tags but no `tags` list is added to the `api-docs` file.
```php
#[OA\Get(
        operationId: 'uniqueEndpointId' ,
        description: 'Explanation for the endpoint in detail',
        summary: 'Explanation for the endpoint in short',
        tags: ['Some Tag'],
        ...
)]
```
My proposal now is to always add the `tags` list to the `api-docs` file, whenever the `tags` parameter is used in any `Operation` attribute. And when someone wants to add a description to a tag, the `Tag` attribute can be used as it already is.

**Comment by mazumba-nx** [comment]
Thank you! 🔥

**Comment by DerManoMann** [comment]
> This has broken our API docs by [Redocly](https://github.com/Redocly/redoc). I'm not sure yet why but for now we're unsetting the tags property before we save it. `unset($openapi->tags);`

Interesting - if you ever find out let me know. The latest change does remove unused ones - maybe that is the issue?
