### ISSUE TITLE
Validation fails with repeated tags since v4.10.1

### ISSUE THREAD

**Issue by rasmuscnielsen** [zircote/swagger-php#1621]
Updating to the latest release, our CI starts failing with "repeated tags".

![image](https://github.com/zircote/swagger-php/assets/8465957/c4b3e049-0367-4ee1-98ac-d1c695e222ee)

I'd assume it's related to the introduction of "AugmentTags" processor.

Interestingly, It seems that the examples also have duplicated tags in https://github.com/zircote/swagger-php/pull/1615/files .

Is this a valid approach, or should they be filtered to only have unique tags? Our CI validates swagger files using https://validator.swagger.io/validator/debug which fails

**Comment by DerManoMann** [comment]
Nah. Reading this I remember thinking about uniqueness, but somehow I lost it.

**Comment by DerManoMann** [comment]
Deng! Wifi not working at hotel - will have to wait until tomorrow 😕

**Comment by rasmuscnielsen** [comment]
Thanks a ton @DerManoMann  ! It works 🎉
