### ISSUE TITLE
Filtering not done as expected

### ISSUE THREAD

**Issue by caixingyue** [zircote/swagger-php#1624]
![image](https://github.com/zircote/swagger-php/assets/39073687/3728dca3-8077-4b59-a73b-4ea32f9f6903)

When all interfaces in a tag are filtered out, the tag should also be removed because it does not have any effect when displayed here.

As shown by the blue line in the figure, no api appears when I click to expand, so it should not continue to exist.

```
new Processors\PathFilter([], ['/api/']),
new Processors\CleanUnusedComponents(true),
```

**Comment by DerManoMann** [comment]
This might be something to be added to the new `AugmentTags` processor...

**Comment by momala454** [comment]
it still doesn't work. I see tags from removed path still listed
![image](https://github.com/user-attachments/assets/6c7f0927-8407-45d5-8d39-ac4b925ef5ac)

**Comment by DerManoMann** [comment]
What can I say.
Any chance you could post a single file reproducer?
