### ISSUE TITLE
Fatal error "Nesting level too deep - recursive dependency?"

### ISSUE THREAD

**Issue by odyswise** [zircote/swagger-php#1631]
Version 4.10.5
Error thows in AugmentTags.php on 50 line. For solving this error I added strict = true in array_search function call.

**Comment by DerManoMann** [comment]
I think I know what you mean. Would you have some sample annotations that trigger this issue so I can reproduce it?

**Comment by odyswise** [comment]
Nelmio Bundle yaml settings:
`  areas: # to filter documented areas
    default:
      disable_default_routes: true
      path_patterns: [ ^/(?!api) ]
    internal:
      disable_default_routes: true
      path_patterns: [ ^\/((?!\/api\/v1)(?!external).)*$ ]
      documentation:
        components:
          securitySchemes:
            oauth2:
              type: oauth2
              name: Authorization
              flows:
                authorizationCode:
                  authorizationUrl: "%env(OAUTH_URL)%%env(OAUTH_AUTHORIZE_URL)%"
                  tokenUrl: "%env(OAUTH_URL)%%env(OAUTH_TOKEN_URL)%"
                  scopes: { }
        security:
          - oauth2: [ ]
        tags:
          - name: oauth
            description: Авторизация`

Action code is next:

`    #[OA\Tag(name: 'oauth')]
    #[OA\Get(
        responses: [
            new OA\Response(
                response: HttpResponse::HTTP_OK,
                description: '',
                content: new OA\JsonContent(
                    ref: new Model(
                        type: Response::class,
                    ),
                    type: 'object',
                ),
            ),
            new OA\Response(
                ref: '#/components/responses/Unauthorized',
                response: HttpResponse::HTTP_UNAUTHORIZED,
            ),
            new OA\Response(
                ref: '#/components/responses/Forbidden',
                response: HttpResponse::HTTP_FORBIDDEN,
            ),
            new OA\Response(
                ref: '#/components/responses/UnsupportedMediaType',
                response: HttpResponse::HTTP_UNSUPPORTED_MEDIA_TYPE,
            ),
        ],
    )]
    #[Route('/me', name: 'me', methods: [Request::METHOD_GET])]
    public function __invoke(Request $request): JsonResponse
    {
        $user = $this->authService->getUser($this->tokenResolver->resolve($request));

        return new JsonResponse(
            data: new Response($user),
        );
    }`
