### ISSUE TITLE
Documentation: say which parameters are required

### ISSUE THREAD

**Issue by fulldecent** [zircote/swagger-php#1650]
This is valid

```
#[OA\Info(
    title: "Pacific Medical Training API", 
    version: "1.0.0",
)]
```

but this is invalid:

```
#[OA\Info(
    title: "Pacific Medical Training API", 
)]
```

---

I don't see this fact reflected in documentation at https://zircote.github.io/swagger-php/reference/attributes.html#info

**Comment by DerManoMann** [comment]
Reopened as the additional information are only generated for annotations, not attributes :/

**Comment by DerManoMann** [comment]
Nevermind - looked like caching issue on my side :}
