### ISSUE TITLE
Enumeration needs to add description

### ISSUE THREAD

**Issue by caixingyue** [zircote/swagger-php#1661]
This is my current definition method:

` #[Property(property: 'gender', description: "Gender (0:Secret; 1:Male; 2:Female)", type: 'string', enum: Gender::class, example: Gender::Secret)]`

I want to get `(0:Secret; 1:Male; 2:Female)` from the enum class, That is to say, you only need to write the following to achieve the above results.

` #[Property(property: 'gender', description: "Gender", type: 'string', enum: Gender::class, example: Gender::Secret)]`

This will reduce my maintenance costs.

**Comment by DerManoMann** [comment]
I think this is a very specific use case that should not be the responsibility of the core library.
However, it should be reasonably simple to write a new processor that could perform this conversion. In that case, however, I'd suggest `description: Gender:class` so the processor can check if a given description denotes a know enum.

**Comment by caixingyue** [comment]
> I think this is a very specific use case that should not be the responsibility of the core library. However, it should be reasonably simple to write a new processor that could perform this conversion. In that case, however, I'd suggest `description: Gender:class` so the processor can check if a given description denotes a know enum.

Yes, you are right. This is indeed what the processor should handle. I have tried to use the processor to handle this problem, but the enumeration I got is an array, not an enumeration class. I want to get the relevant enumeration information through the description of the enumeration class. I don't know if this is possible.

ps: Except for the implementation through x, I think I can directly use the key value of the existing enum

**Comment by DerManoMann** [comment]
If you have some work in progress code that you could post I'd be happy to help - sounds like a good addition to the processor examples :)

**Comment by caixingyue** [comment]
> If you have some work in progress code that you could post I'd be happy to help - sounds like a good addition to the processor examples :)

This allows you to pass enum data directly to the processor when calling it. For example, if I pass the enumeration class name, I should get the enumeration class name. If I need to get all the data of the enumeration, I can use enum_exists to determine whether it is an enumeration class and then get the data myself.

**Comment by DerManoMann** [comment]
@caixingyue I've created a PR in `openapi-extras` that adds a new processor :) You can either use that or copy the processor, I suppose...

**Comment by caixingyue** [comment]
I have seen this processor, which is great, but it may not be in line with the business. The data obtained should be (Cat: 猫).

Such data is needed because sometimes it is necessary to describe the enumeration value for the localized language, and the enumeration key=> value cannot be used directly.

**Comment by caixingyue** [comment]
In my case, I would write an enum like this:

` #[Property(property: 'gender', description: "性别", type: 'string', enum: Gender::class, example: Gender::Secret)]`

```
enum Gender: string
{
    case Male = 'M';
    case Female = 'F';
    case Secret = 'S';

    public function description(): string
    {
        return match($this) {
            self::Male => '男',
            self::Female => '女',
            self::Secret => '保密',
        };
    }
}
```

The description obtained is: 性别 (M:男; F:女; S:保密)

**Comment by DerManoMann** [comment]
I guess you could adapt the processor for your needs. Alternatively, I suppose the processor could allow for some customisation.

**Comment by caixingyue** [comment]
It may not be a good idea to modify the processor of the software package directly, but customization is a good way.

Suggestion: In the previous global configuration, I think a closure processor can be added to make it easier to handle customization functions. What do you think?

**Comment by DerManoMann** [comment]
Yeah, a customizer would work too. Closing this issue here - if needed I'd prefer to have a ticket at https://github.com/DerManoMann/openapi-extras
