### ISSUE TITLE
Is responses reusing supported?

### ISSUE THREAD

**Issue by hotrush** [zircote/swagger-php#1673]
As described here - https://swagger.io/docs/specification/v3_0/describing-responses/#reusing-responses

**Comment by Kiina** [comment]
Yes by just using a ref.

In the examples here is a response defined:

https://github.com/zircote/swagger-php/blob/master/Examples/using-refs/OpenApiSpec.php#L75-L79


And here is the response used in a get:

https://github.com/zircote/swagger-php/blob/7df10e8ec47db07c031db317a25bef962b4e5de1/Examples/using-refs/ProductController.php#L16-L23

**Comment by hotrush** [comment]
Yeah, finally made it work, thanks
