### ISSUE TITLE
Support for swagger 2.0

### ISSUE THREAD

**Issue by dersteve** [zircote/swagger-php#174]
Do you plan on supporting swagger spec version 2.0?

**Comment by inakianduaga** [comment]
:+1:

**Comment by daedeloth** [comment]
:+1:

**Comment by bfanger** [comment]
For the brave, an pre-alpha version is available in the [2.x branch](https://github.com/zircote/swagger-php/tree/2.x)

**Comment by webron** [comment]
That's great news, Bob! Please let me know if you need any assistance with the spec.

**Comment by inakianduaga** [comment]
Sweeet! 

One question that's actually more of a composer question, is it possible to use different versions of swagger simultaneously in the same application (I mean to include the regular Swagger 1.2 under say the usual namespace, and alias Swagger 2.0 to another namespace).

**Comment by bfanger** [comment]
@webron No questions so far, the swagger-spec project does a great job.

@inakianduaga You would have to create a fork of the swagger-php project and replace all namespace references. but mixing different versions is will only be confusing, I recommend either upgrading the docs to 2.0 or keep using 1.2

**Comment by bfanger** [comment]
swagger-php 2.x is feature-complete, I'd like to hear your feedback.

**Comment by skyzyx** [comment]
Sweet! I'll start my migration this week!

**Comment by webron** [comment]
@bfanger - since my knowledge of PHP is nonexistent, do you have a few sample JSON/YAML output produced for 2.0? I could probably provide some feedback on that.

**Comment by dmyers** [comment]
:+1:

**Comment by dmyers** [comment]
This is now complete with a new release! :+1:

Great work @bfanger!
