### ISSUE TITLE
PSR-2 Compliance

### ISSUE THREAD

**Issue by adammbalogh** [zircote/swagger-php#175]
Do you plan to make this pakcage PSR-2 Compliant?

**Comment by bfanger** [comment]
[phpcs](https://github.com/squizlabs/PHP_CodeSniffer) still has some complaints:

> Constants must be uppercase; expected 'SWAGGER\UNDEFINED' but found 'Swagger\UNDEFINED'

The constant *is* uppercase, it seams phpcs doesn't take namespaces into account.
> Line exceeds 120 characters; contains ... characters

I'm okey with long lines.
> Property name "..." should not be prefixed with an underscore to indicate visibility

Properties with an underscore are used to avoid naming collisions between swagger-php and the swagger output/spec.

But the code is now mostly PSR-2 compliant, thanks to @mpajunen and [php-cs-fixer](http://cs.sensiolabs.org).
