### ISSUE TITLE
Partial allow inheritiance of other model

### ISSUE THREAD

**Issue by michaelboke** [zircote/swagger-php#177]
I am trying to create multiple models with shared sets of properties, I thought the partial option is a nice solution but i found a  awkward behavior.

What i do, i make partial of a model and try to add it as partial to a other model to render the properties and then add my extra properties.
But merging of the same type of partials results in loss of properties/partial rendering.
I find it a bit hard to explain so i will try to explain it with a example.

Example partial:
@SWG\Model(
 partial="test_partial",
 @SWG\Property(name="first_attribute",type="string"),
)

Inherit the partial (this works) it will be exact the same as test_partial
@SWG\Model(
  id="test_usepartial",
  @SWG\Partial("test_partial"),
)

But as soon as i add a property or a extra partial the partial "test_partial" is not rendered (included) any more.
@SWG\Model(
  id="test_usepartial",
  @SWG\Partial("test_partial"), <-- property first_attribute is lost
  @SWG\Property(name="extra_attribute",type="string"),
)

I do think this is due to a internal overwrite of the model. It would be nice if the partial is used as a base template, and all next partials of the same type and or attributes will append its properties.

what do you think?

**Comment by bfanger** [comment]
The swagger-specification v2.0 has support for references `$ref` which are like client-side partials. @SWG\Partial is therefor omitted from swagger-php 2.x
