### ISSUE TITLE
Partials do not fully inherit

### ISSUE THREAD

**Issue by araines** [zircote/swagger-php#178]
Whilst attempting to use Partials, I'm finding that some fields do not inherit properly.

For example, I have the following in our base controller:
```
    /**
     * @SWG\Operation(
     *   partial="Operation/list",
     *   nickname="index",
     *   method="GET",
     *   summary="Read all existing entries",
     *   authorizations={},
     *   type="array",
     *   @SWG\Produces("application/json"),
     *   @SWG\ResponseMessage(code=400, message="Invalid input"),
     * )
     */
```

In our sub-class controller:
```
    /**
     * @SWG\Api(
     *   path="/periods",
     *   @SWG\Operation(
     *     @SWG\Partial("Operation/list"),
     *     @SWG\Items("Period"),
     *   ),
     * )
     */
```

And I get the following error messages:
```
Required field "nickname" is missing for "@SWG\Operation()" in SubController.php on line 16
Unexcepted items for type "" in @SWG\Operation(), expecting "array"
```

This suggests that neither "nickname" nor "type" is being inherited properly via the Partial.

**Comment by bfanger** [comment]
The swagger-specification v2.0 has support for references `$ref` which are like client-side partials. @SWG\Partial is therefor omitted from swagger-php 2.x
