### ISSUE TITLE
Competing description not taking 'POST' or 'GET' into account

### ISSUE THREAD

**Issue by Stephentoe** [zircote/swagger-php#180]
In writing out the blocks for an API, whenever I generate the docs, swagger throws an [INFO] error, saying that there is a 'competing description' for various function that have the same path. The reason these functions have the same path is that one is a 'POST' method, another is 'GET', etc...

Is this a bug, or are we doing something wrong in our documentation?

**Comment by dubcanada** [comment]
Also got this, I am using an exact copy of the Petstore documentation and getting this error.

If I comment out the `Logger` line everything works fine.

**Comment by dubcanada** [comment]
nvm I had another item in the comment that was causing the issue.

**Comment by mpetkov** [comment]
I am having the exact same issue.  So I have a resourceful controller that accepts both GET and POST.  So even thought the summary is different, as @bfanger described, it still shows me the following error "Competing description for...".

 Here is the SWG comment code:
<pre class="source">
/**
* @SWG\Api(path="/projects",
*		@SWG\Operation(method="GET",summary="Find all projects", type="array", @SWG\Items("Model"))
* )
*  
*/
public function index()
{}


/**
* @SWG\Api(path="/projects",
*		@SWG\Operation(method="POST",summary="Add a new project",
*	        @SWG\Parameter(name="project_name", required=true, paramType="form", type="string", description="Project name")
*		)
* )
* 
*/
public function store()
{}
</pre>

**Comment by koenbetsens** [comment]
@mpetkov, after looking in the [source](https://github.com/zircote/swagger-php/blob/master/library/Swagger/Annotations/Resource.php) (119), I solved/hacked the issue by repeating the same description in each "competing" SWG/Api annotation. You could try that...

**Comment by mpetkov** [comment]
@koenbetsens  LOL!  Ya that "fixed" it.  I wonder if this is expected functionality or just a hack like you say.  Oh well, thanks for helping me out!

**Comment by bfanger** [comment]
Merging annotations has improved in swagger-php 2.x
