### ISSUE TITLE
Header Parameter

### ISSUE THREAD

**Issue by adammbalogh** [zircote/swagger-php#182]
How about a header parameter?

**Comment by bfanger** [comment]
swagger-php 2.x `@SWG\Parameter(in="header")`  which is beter documented.

**Comment by anish274** [comment]
How can I define header in Definition? I want to pass headers in all APIs and want a common Definition  which can be called from Definition  directly

**Comment by matheushf** [comment]
For whom is new here, it changed. Use it with `in="header"`

```
 *     @SWG\Parameter(
 *         name="x-id",
 *         in="header",
 *         description="ID",
 *         required=true,
 *         type="string",
 *     ),
```

**Comment by naffan2014** [comment]
> How can I define header in Definition? I want to pass headers in all APIs and want a common Definition which can be called from Definition directly

have u solve this problem?
