### ISSUE TITLE
Custom model: nesting error

### ISSUE THREAD

**Issue by jacobweber** [zircote/swagger-php#183]
I created a custom model annotation (which extends Swagger\Annotations\Model) and a custom processor for it (which implements Swagger\Processors\ProcessorInterface). I call Swagger\Swagger->addProcessor() to add it, before calling Swagger\Swagger->scan().

This worked in 0.9.0, but when I upgraded to 0.9.6, I started getting errors from Swagger\Processors\NestingProcessor. Every time I used my custom annotation, it said that it "is not placed inside an annotation".

It seems like the whitelist inside NestingProcessor can't be changed. I had to manually remove the processor using Swagger\Swagger->setProcessors(), which is kind of messy.

Is there a better way to allow this?

**Comment by bfanger** [comment]
In swagger-php 2.x the validation for the nesting is based on public static properties $parents and $nested. This allows you update swagger-php nesting logic to add your custom annotation.

swagger-php 2.x doesn't have a canonical way of registering custom processors (yet), 
currently you'll have to duplicate the code in functions.php which is also kind of messy.

**Comment by bfanger** [comment]
Let me know if you'll experience any issues using custom annotations/processors in 2.x

**Comment by jacobweber** [comment]
Is there an example I can look at? I'd like to add a custom annotation that extends "Definition", but I'm not sure where to add it anymore, or what exactly I'd need to add.

It would need to know the name of the PHP class it's in, perform some custom processing, and add some "Properties".
