### ISSUE TITLE
Got [ERROR] no valid resources found

### ISSUE THREAD

**Issue by rauljuarez** [zircote/swagger-php#186]
Hi, im getting this message on a project that its running swagger, till the last few months this works perfectly, without any bumps. Now that im making some changes on the Docs, and im trying to check locally the changes on the swagger json docs, i got this, im excecuting the same command on the command line to see if the docs are ok, and nothing.

Any clues?

The error:

```
Swagger-PHP 0.9.6
-----------------
[ERROR] no valid resources found
```

**Comment by bfanger** [comment]
Looks like swagger is unable to find the annotations, any updates on this issue?

**Comment by bfanger** [comment]
Closed due to inactivity
