### ISSUE TITLE
Model: extending across namespaces does not generate correct properties

### ISSUE THREAD

**Issue by daedeloth** [zircote/swagger-php#187]
If I extend models across namespaces, only the properties of the models within the same namespace are generated.

Example code here:
https://github.com/daedeloth/swagger-php-bug

**Comment by daedeloth** [comment]
Update: only is an issue when making use of the "use" statement.
If using fully qualified names in the model declaration itself, it works fine.

**Comment by bfanger** [comment]
swagger-php 2.x uses the fully qualified name for inheritance 0b2c657ee19af584d5a7221f164e43c2897b9a0a.
