### ISSUE TITLE
More issues with partial inheritance

### ISSUE THREAD

**Issue by xiehan** [zircote/swagger-php#188]
This is related to #177 and #178; we are trying to do similar things. Also, for reference, we are using the 0.9 (dev) branch, which I realize is not stable/official but it seems to have fixed a large portion of the buggy behavior the users reporting those issues noted. However, we came across a few 'new' issues within the realm of partials, so I figured I'd create a new ticket.

Here's what I originally wanted to do:

    @SWG\Model(partial="UserDocument",
        id="UserDocument",
        @SWG\Property(name="data", type="UserDataObject", description="Object; see description of a user object below"),
        ... // other properties truncated for lack of relevance
    )
    
    @SWG\Model(
        @SWG\Partial("UserDocument"),
        id="UserWithTokenDocument",
        @SWG\Property(name="data", type="UserDataObjectWithToken", description="Object; see description of a user object below")
    )

In effect, I wanted `UserWithTokenDocument` to extend `UserDocument`, overriding its `id` and `data` properties. I have 2 API operations that return a `UserDocument` and 2 other API operations that return a `UserWithTokenDocument`; the two models are pretty much identical except for one tiny difference in their respective `data` property, so I was trying to minimize the amount of copy-pasting as much as possible.

Anyway, this didn't work because Swagger-PHP doesn't allow anything marked as a `partial` to be a standalone. That is, all of this compiles and produces valid JSON, but it only creates a `UserWithTokenDocument` in its list of models. `UserDocument` isn't included in the JSON output because it's a partial, because Swagger-PHP seems to think I'd never want to use a partial as a model in and of itself. But I feel like this is a valid use case.

So then I changed it to the following, which isn't pretty but I thought would do the job:

    @SWG\Model(partial="AbstractUserDocument",
        @SWG\Property(name="data", type="UserDataObject", description="Object; see description of a user object below"),
        ... // other properties truncated for lack of relevance
    )
    
    @SWG\Model(
        @SWG\Partial("AbstractUserDocument"),
        id="UserDocument"
    )
    
    @SWG\Model(
        @SWG\Partial("AbstractUserDocument"),
        id="UserWithTokenDocument",
        @SWG\Property(name="data", type="UserDataObjectWithToken", description="Object; see description of a user object below")
    )

This works in the sense that it correctly creates both a `UserDocument` and `UserWithTokenDocument`. However, it doesn't override the `data` property for `UserWithTokenDocument` -- it gives me the the property as declared in `AbstractUserDocument` and not the (desired) overwritten version.

I ended up having to do:

    @SWG\Model(partial="AbstractUserDocument",
        ... // other properties truncated for lack of relevance
    )
    
    @SWG\Model(
        @SWG\Partial("AbstractUserDocument"),
        id="UserDocument",
        @SWG\Property(name="data", type="UserDataObject", description="Object; see description of a user object below")
    )
    
    @SWG\Model(
        @SWG\Partial("AbstractUserDocument"),
        id="UserWithTokenDocument",
        @SWG\Property(name="data", type="UserDataObjectWithToken", description="Object; see description of a user object below")
    )

...which works but again isn't ideal.

After trying this, I assumed that overriding properties declared in a partial just doesn't work, but then I tried the following:

    @SWG\Parameter(partial="platformParam",
        name="platform", description="The platform which this application is running on",
        paramType="query", required=true, allowMultiple=false, type="string",
        enum="['IPHONE', 'ANDROID', 'CRMAPP', 'WINDOWPH', 'CLOUDCAR', 'ROKU', 'EMAIL', 'BOSCH']"
    )

    @SWG\Parameter(
          @SWG\Partial("platformParam"),
          description="The platform to be used in the recommendation URLs. Optional, but if not included then no recommendation URL or ratings array will be included in the output",
          required=false
     )

What's interesting is that this partially works; the description successfully gets overwritten. The `required` property, however, does not.

**Comment by bfanger** [comment]
The `@SWG\Partial` is removed in swagger-php 2.0 in favor of the refs feature which are part of the spec.
