### ISSUE TITLE
Cannot use partials declared in a different file if manually specifying filenames in Swagger()

### ISSUE THREAD

**Issue by xiehan** [zircote/swagger-php#189]
If you give a directory to `new Swagger(...)` it by design only checks for `.php` and `.phtml` files. Our project uses `.inc` files so initially we worked around this by specifying the individual files to check in an array.

However, when we did this, we found that we couldn't declare partials in one file (eg. `A.inc`) and then actually use/reference them in a different file (eg. `B.inc`), no matter how we arranged the order of the files in the array. If we listed `B.inc` before `A.inc` it would give an error saying that the code is trying to reference a partial that hasn't been declared, and if we listed `A.inc` before `B.inc` it would give an error saying a partial was declared but hasn't been used. No combination would produce valid output.

We worked around this by switching to the directory version of the `new Swagger(...)` invocation and forking Swagger-PHP to add `.inc` to the array of file extensions it checks for, but maybe a better design is to allow the user to specify those filetypes. Using different file extensions is pretty common in PHP-world; I doubt we're the only ones doing this.

**Comment by bfanger** [comment]
swagger-php 2.x  crawles all files by default, `Swagger->crawl()` uses [Symfony\Finder](http://symfony.com/doc/current/components/finder.html)  under the hood, which allows for fine control over which files are scanned.

The swagger-specification v2.0 has support for references `$ref` which is like client-side partials. `@SWG\Partial` is therefor omitted from swagger-php 2.x
