### ISSUE TITLE
Top-level apiVersion shouldn't be coming from the individual resources

### ISSUE THREAD

**Issue by xiehan** [zircote/swagger-php#190]
This is my interpretation of the [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md), and I may be wrong, but:

The 1.2 spec currently allows you to specify an `apiVersion` in two places: at the very top level of the API (the "resource listing"), as well as on the individual resource level. Nowhere does it say that they have to be the same, and for our project, we are giving the individual resources their own version numbers, as well as giving the overall top-level API its own version number. As far as we can tell, the spec supports that.

However, Swagger-PHP doesn't (for as far as I can tell) allow you to specify the top-level `apiVersion` at all; all it does is check its child resources, and it sets the top-level `apiVersion` to the first valid value it encounters (or `null` if none of its child resources have a version specified). It makes a blanket assumption that all of the `apiVersion` values across resources will be the same, which I don't think is valid because nowhere in the spec does it say that that is a requirement.

I know there are probably different interpretations of the spec and everyone handles versioning differently, but either way this strikes me as something that should be addressed, particularly because the Swagger 2.0 spec ***only*** supports adding a version at the top level, and not on the individual resources.

**Comment by bfanger** [comment]
In swagger-php  2.x versioning is no longer supported per resource, the v2 specification doesn't have the concept of a resource. You'll specify the version in the `@SWG\Info()` annotation.

In your scenario it might make sense to create multiple swagger.json files, each with its own title and versioning.
