### ISSUE TITLE
Model isn't added to list of models if it's only used inside of an array

### ISSUE THREAD

**Issue by xiehan** [zircote/swagger-php#191]
We have a Swagger model called `RatingDocument`. It is only used in a single place.

This works:

    @SWG\Parameter(
          name="body",
          description="An object which contains data about a rating such as the id of the content, the rating value, elapsed time and more.",
          type="RatingDocument",
          required=true,
          paramType="body"
     )

The `RatingDocument` model is correctly added to the Swagger-output JSON's `models` property, and Swagger-UI renders everything as expected.

However, this doesn't work: (and is actually what we need, considering the value is expected to be an array)

    @SWG\Parameter(
          name="body",
          description="An object which contains data about a rating such as the id of the content, the rating value, elapsed time and more.",
          type="array",
          @SWG\Items("RatingDocument"),
          required=true,
          paramType="body"
     )

The Swagger JSON produced is:

                        {
                            "paramType": "body",
                            "name": "body",
                            "type": "array",
                            "required": true,
                            "description": "An array of objects which contains data about ratings such as the id of the content, the rating value, elapsed time and more.",
                            "items": {
                                "$ref": "RatingDocument"
                            }
                        }

However, `RatingDocument` isn't present in the `models` array, so this is referencing nothing, and our Swagger-UI doesn't render it.

**Comment by OPM87** [comment]
To render the model in an array as parameter...
at the end of #152

**Comment by bfanger** [comment]
swagger-php 0.9/1.x tries to detect with models are used inside a resource. (which it failed to do in this scenario)

swagger-php 2.x renders only one json, it contains all ~~models~~ definitons it can find, even if it isn't used in by an operation, it is therefor doesn't have this bug .
