### ISSUE TITLE
Another problem with Swagger + other annotations

### ISSUE THREAD

**Issue by mirfilip** [zircote/swagger-php#193]
I have a very similar problem to #119. Namely, my model classes consist of Swagger and ZF2 form annotations:
```
/**
 * @Form\Name("category")
 * @Form\Object("Api\Entity\CategoryEntity")
 * @Form\Hydrator("Api\Hydrator\EntityHydrator")
 *
 * @SWG\Model(id="CategoryEntity")
 */
class CategoryEntity {
...
}
```
When I generate json, I get:
`[WARN] [Semantical Error] The annotation "@Zend\Form\Annotation\Name" in (...) does not exist, or could not be auto-loaded.`
I'm aware that this problem has already been tackled with [this pull request](https://github.com/doctrine/annotations/pull/25), but it seems `setIgnoreNotImportedAnnotations` still does not work.

In similar issues, people had problems with Swagger annotations when doing Doctrine stuff and the workaround was to register Swagger classes with `AnnotationRegistry::registerAutoloadNamespace`. In my scenario, it's the other way around, ZF2 annotations get into way when doing Swagger stuff. I tried registering ZF2 namespace in Swagger bootstrap, but it does not work. When I tinker with [Parser.php source code](https://github.com/zircote/swagger-php/blob/master/library/Swagger/Parser.php#L201) and put namespace registration in there, it works.

So,
1. Am I right that it's still a Doctrine Annotations bug ?
2. Shouldn't it work with Swagger bootstrap ?
3. Are there any other workarounds ? 
@bfanger what do you think ?

**Comment by bfanger** [comment]
The fix for #119 was rejected, but does not apply to your situation because Swagger\Parser detects the `use Zend\Form\Annotation as Form;` statement and registers that as import. 

Registering Zend classes with registerAutoloadNamespace should work in when using a swagger bootstrap, double check if the absolute paths are correct and are registered before parsing.

**Comment by mirfilip** [comment]
You were right, it was a matter of wrong absolute paths. Thank you @bfanger !

**Comment by SimonDevelop** [comment]
This solution does not work for me 😭

My EntityManager :
``` php
<?php
    $config = \Doctrine\ORM\Tools\Setup::createAnnotationMetadataConfiguration(
        ["app/src/Entity"],
        true
    );
    \Doctrine\Common\Annotations\AnnotationRegistry::registerAutoloadNamespace("OpenApi", dirname(__DIR__) . '/vendor/zircote/swagger-php/library');
    \Doctrine\Common\Annotations\AnnotationRegistry::registerAutoloadNamespace("OA", dirname(__DIR__) . '/vendor/zircote/swagger-php/library');
    $reader = new \Doctrine\Common\Annotations\AnnotationReader();
    $reader::addGlobalIgnoredNamespace("OpenApi");
    $reader::addGlobalIgnoredNamespace("OA");
    $config->setMetadataDriverImpl(
        new \Doctrine\ORM\Mapping\Driver\AnnotationDriver(
            $reader,
            ["app/src/Entity"]
        )
    );
    $config->setMetadataCacheImpl(
        new \Doctrine\Common\Cache\FilesystemCache(
            dirname(__DIR__)."/storage/cache/doctrine"
        )
    );
    $em = \Doctrine\ORM\EntityManager::create($connection, $config);
```

My entity : 
``` php
<?php
<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use OpenApi\Annotations as OA;

/**
 * @OA\Schema()
 *
 * @ORM\Entity(repositoryClass="App\Entity\CustomerRepository")
 * @ORM\Table(name="customers")
 */
class Customer
{
....
```

yet I have this error : 
```
"@OpenApi\Annotations\Schema" in class App\Entity\Customer does not exist, or could not be auto-loaded.
```

I have researched and tested many things, I can not...
I am not an expert in annotation, I may have done something wrong. If anyone can enlighten me!

**Comment by SimonDevelop** [comment]
Ok, I find a solution to my problem since [this gist](https://gist.github.com/gtnsimon/8a657e0a29e674677a2c65c0ba07deff).
