### ISSUE TITLE
[2.x branch] swagger.phar file

### ISSUE THREAD

**Issue by Ynk33** [zircote/swagger-php#195]
Hello,

Where can I find a swagger.phar file for the Swagger-php 2.x branch ?
I can't find how to create a documentation with Swagger 2.0 spec on the Swagger-php 2.x branch.

Thanks for your help

**Comment by bfanger** [comment]
The CLI is one of the features that is currently missing from 2.x
For now, to generate documentation just create a php file with:

```php
<?php
require("vendor/autoload.php");
$swagger = \Swagger\scan('/path/to/project');
echo $swagger;
```

I'm probably not going to build a phar for 2.x but use `composer global require` like [laravel/installer](http://laravel.com/docs/5.0#install-laravel) which would simplify the installing and updating process.

**Comment by Ynk33** [comment]
Okay thanks ! It helped a lot :)

**Comment by AngelLG** [comment]
@bfanger Where should I put the PHP file with that code? I'm not very experienced yet ):
