### ISSUE TITLE
Update annotations documentation to 2.0

### ISSUE THREAD

**Issue by Ynk33** [zircote/swagger-php#196]
Is it possible to do an update of this documentation ? It would be really nice.

Thanks for your help

**Comment by jaoued** [comment]
:+1:

**Comment by bfanger** [comment]
I've created interactive swagger.json documentation: http://bfanger.github.io/swagger-explained
Which list the swagger-php annotation and the swagger-spec per json level.

**Comment by bfanger** [comment]
https://github.com/zircote/swagger-php/tree/2.x/docs
