### ISSUE TITLE
Conflicts with Laravel route annotations

### ISSUE THREAD

**Issue by hackel** [zircote/swagger-php#198]
I'm getting the following error when trying to run swagger-php on my classes that use LaravelCollective/annotations:

`[WARN] [Semantical Error] The annotation "@App\Http\Controllers\BaseController" in ./app/Http/Controllers/API/AuthController.php on line 7 does not exist, or could not be auto-loaded.`

This is causing the SWG\Resource() call not to be registered, and later SWG\API calls fail.
Example Code:
```php
use App\Http\Controllers\BaseController as Controller;

/**
 * @SWG\Resource(
 *  basePath="http://example.com/api"
 * )
 *
 * @Resource("auth", only={"index", "store"})
 * @Controller(prefix="api")
 */
class AuthController extends Controller {
```
If I remove the "@" from "@Controller", everything runs fine, but this completely breaks my application.  These annotations are not namespaced, so it's getting confused.  Isn't the point of using the SWG namespace that it should only be looking at those annotations?

**Comment by bfanger** [comment]
This is fixed in the 2.x branch,you could try backporting https://github.com/zircote/swagger-php/commit/571029cc96e74f005ec19006aec944b2a81c8fd8 to 0.9.x or start using 2.x

**Comment by hackel** [comment]
Thanks, I've tested 2.x and it seems to have fixed the issue for me.
