### ISSUE TITLE
Add Tag class

### ISSUE THREAD

**Issue by cwt137** [zircote/swagger-php#199]
The branch that implements the Swagger 2.0 spec is missing the tag branch

**Comment by bfanger** [comment]
Doctrine supports arrays. `@SWG\Swagger(tags={"premium","pricey"})`

Doesn't that cover tags, or am i missing somerhing?

**Comment by cwt137** [comment]
For the Operation object, you can use the doctrine array, but for the Swagger object, the Tag object works better because it has more than one property.
