### ISSUE TITLE
command line invocation creates flat files but looks for directories

### ISSUE THREAD

**Issue by spyrospph** [zircote/swagger-php#201]
Hi, 

I have the following code:

/**
 * @SWG\Resource(
 *    apiVersion="1.0",
 *    swaggerVersion="2.0",
 *    resourcePath="abc",
 *    basePath = "http://localhost:6001",
 *      @SWG\Api(
 *        path="abc",
 *        description="Operations for Metrics",
 *        @SWG\Operation(
 *            method="GET", summary="List all metrics", notes="Lists all metrics data as stored in the db",
 *            type="ABC", nickname="abc/index",
 *        )
 *      )
 * )
 */
/**
 *
 * @SWG\Model(id="ABC")
 */

Running a command line invocation 

php swagger.phar <myfiles> -u swagger/ -o swagger/

creates two files in swagger directory:
api-docs.json and abc.json

However inside api-docs.json file it has the following:
{
    "basePath": "swagger/",
    "apiVersion": "1.0",
    "swaggerVersion": "2.0",
    "apis": [
        {
            "path": "/abc.{format}",
            "description": "Operations for Metrics"
        }
    ]
}

However abc.json is created in the same directory with api-docs.json and therefore  "path": "/abc.{format}", can not be found.

**Comment by bfanger** [comment]
Your "swaggerVersion" is incorrect swagger-php 0.9x outputs 1.2 of the spec, which uses multiple files.
If you want to generate a 2.0 spec output use the [2.x branch](https://github.com/zircote/swagger-php/tree/2.x)

if i recall correctly swagger.phar also generates a index.php which can be used to serve the spec.
