### ISSUE TITLE
[Swagger 2.0] A few issues with the generated definitions

### ISSUE THREAD

**Issue by webron** [zircote/swagger-php#202]
Hello,

@marcinskubala opened an issue on swagger-ui - https://github.com/swagger-api/swagger-ui/issues/1055 - related to an issue we have, and shared his Swagger definition that was generated by the new version of swagger-php. I assume it's redacted, but I believe the general structure is coming from swagger-php. This is the shared definition:

```json
{
    "swagger": "2.0",
    "info": {
        "title": "XXX",
        "version": "XXX"
    },
    "host": "XXX",
    "basePath": "XXX",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application\/x-www-form-urlencoded"
    ],
    "produces": [
        "application\/json",
        "application\/xml"
    ],
    "paths": {
        "\/media": {
            "post": {
                "tags": [
                    "Media Operations"
                ],
                "summary": "Create a new media",
                "parameters": [
                    {
                        "name": "title",
                        "in": "formData",
                        "description": "Media title",
                        "required": false,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Media Response",
                        "schema": {
                            "$ref": "#\/definitions\/Media"
                        }
                    },
                    "Default": {
                        "description": "Default Error",
                        "schema": {
                            "$ref": "#\/definitions\/Error"
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "schema": {
							"type": "array",
							"items": {
								"$ref": "#\/definitions\/ValidationError"
							}
						}
                    }
                }
            }
        }
    },
    "definitions": {
		"Media": {
            "required": [
				"id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "Error": {
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                }
            }
        },
        "ValidationError": {
            "required": [
                "field"
            ],
            "properties": {
                "field": {
                    "type": "string"
                }
            }
        }
    }
}
```

The definition above has three issues I can point out. I'm not sure whether these are generated errors or user errors, but I wanted to bring them to your attention.

- Strings seem to be unnecessarily "escaped". For example, `"application\/json"` vs `"application/json"`, `"\/media"` vs `"/media"` and `""#\/definitions\/ValidationError"` vs `"#/definitions/ValidationError"`. While parsing of these works fine, it makes it difficult to read and really doesn't add anything.

- The `default` response should be spelled like that instead of `Default` (case matters).

- Definitions of models should be accompanied with `"type": "object"`, so the `Error` model above would be:

```json
       "Error": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                }
            }
        }
```

**Comment by bfanger** [comment]
> Strings seem to be unnecessarily "escaped". 

Fixed, PHP has a quirky default.

> The default response should be spelled like that instead of Default (case matters).

The user typed "default" wrong, added validation to force "default" or a http status code.

> Definitions of models should be accompanied with "type": "object"

Adding this broke the unittests that generate the [examples in the swagger-spec](https://github.com/swagger-api/swagger-spec/tree/master/examples/v2.0/json)
which also omit the type. it seems to be an optional field which could be inferred by the presence of the "properties" property.

**Comment by webron** [comment]
Thanks for the quick response!

I'll have to update those examples, thank you for pointing out. Let me get back to you on the inference, which I'd rather be a fallback than a main solution.
