### ISSUE TITLE
Not all swagger docs get parsed with 2.0 branch

### ISSUE THREAD

**Issue by nostah** [zircote/swagger-php#203]
I have project with multiple api calls, models, etc. After switching to 2.0 branch and updating @SWG annotations most of the code is not visible in swagger.json.

I have several routes defined and documented. Each route has its own swagger comment block but only first two get parsed. Also none of the models that are stored in separate files can be found in resulting json file.

I had to merge all the documentation into one giant phpdoc block and it started working but it is not maintainable in the long run.

Can this be somehow fixed?

**Comment by bfanger** [comment]
This should just work in 2.x, can you provide a codesample?

**Comment by nostah** [comment]
I've created this quick sample with models bundled in: https://gist.github.com/nostah/d610459d50564c729c56

You can observe this strange behaviour where only first two methods get documented.

I've put it into some directory and run swagger-php on it with following command:

php ./vendor/bin/swagger /tmp/api/ -o ../apidoc/swagger.json

**Comment by bfanger** [comment]
You'te using tabs for indentation, which doctrine-annotation sadly doesn't like. Please file a bug there.

**Comment by bfanger** [comment]
Fixed with workaround (replace tabs with spaces before handing the comment-block to the doctrine parser),

**Comment by nostah** [comment]
oh boy, what a bug...

thanks for workaround - it works now :)
