### ISSUE TITLE
allOf object composition does not work

### ISSUE THREAD

**Issue by nostah** [zircote/swagger-php#205]
Resulting object is empty. This problem can be observed on original examples from swagger-php repo. Generate documentation from it with:

php ./vendor/bin/swagger vendor/zircote/swagger-php/Examples/swagger-spec/petstore-with-external-docs/ -o ../apidoc/swagger.json

and look at POST /pet parameter ("pet") - it has

NewPet {
}

contents.

**Comment by bfanger** [comment]
Weird, on my machine it generates
```
"NewPet": {
    "allOf": [
        {
            "$ref": "#/definitions/Pet"
        },
        {
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        }
    ]
},
```
What version of doctrine/annotations is installed?

My `composer info` configuration is:
doctrine/annotations v1.2.4
doctrine/lexer       v1.0.1
symfony/finder       v2.6.6
zircote/swagger-php  2.x-dev eb52c97

**Comment by nostah** [comment]
I have doctrine/annotations v1.2.3 and other components at the same versions. Not sure if this changes anything...

**Comment by nostah** [comment]
updated my project and have now doctrine/annotations v1.2.4 and zircote/swagger-php 2.x-dev 0b2c657. While it generates json properly (at least I don't see errors there) it is not displayed in swagger-ui, so maybe problem is there.

**Comment by bfanger** [comment]
Might be related to https://github.com/swagger-api/swagger-ui/issues/1055

**Comment by anmolagar** [comment]
I am facing the same issue. 
For schemas i am getting:
[
  {}
]

Can somebody please let me know, what is the fix for this.
I am able to create json file successfully and as expected from php. So problem is not in annotations or php but with swagger-ui i think
