### ISSUE TITLE
Supporting parameters reuse in 2.0@dev branch

### ISSUE THREAD

**Issue by mgvirtzm** [zircote/swagger-php#206]
Hello,

I'm trying to reuse parameter definitions so it passes swagger-tools validation, and did not succeed, while trying a couple of variations.

In the **first attempt**, I defined a reusable parameter  like this:

    /**
         * @SWG\Parameter(name="ItemName", in="path", type="string", required=true, description="protected item name", maxLength=256)
     * @SWG\Get(
     *   path="/pi/{item_name}", summary="Get protected item", operationId="getProtectedItem",
     *   @SWG\Parameter(name="item_name", in="path", type="string", required=true, @SWG\Schema(ref="#/parameters/ItemName")),
     * )
     */

NOTE: I was requested (and got Exceptions, if not done) to use `name`, `in`, and `type` properties, although they are duplicating the model parameter.

Following that, `swagger-tools validate` complained about the resulting `parameters` section:

    #/parameters: Expected type object but found type array

Here the generated parameters section:

    "parameters": [
         {
            "name": "ItemName",
            "in": "path",
            "description": "protected item name",
            "required": true,
            "type": "string",
            "maxLength": 256
        },
    ]

After manually converting it to object like this:

    "parameters": {
         "ItemName": {
            "name": "ItemName",
            "in": "path",
            "description": "protected item name",
            "required": true,
            "type": "string",
            "maxLength": 256
        }
    }

I got a complaint from `swagger-tools validate` about the path:

    Additional properties not allowed: type,schema,in,name

Seems that I was expected to have just `schema` and `required` properties when reusing the parameter, but was forced to add other properties?

In the **second attempt**, I tried to use `partial` definitions like I found referenced at one of the recent issues:

    /**
         * @SWG\Parameter(partial="ItemName", name="ItemName", in="path", type="string", required=true, description="protected item name", maxLength=256)
     * @SWG\Get(
     *   path="/pi/{item_name}", summary="Get protected item", operationId="getProtectedItem",
     *   @SWG\Parameter(name="item_name", in="path", type="string", required=true, @SWG\Partial("#/parameters/ItemName")),
     * )
    */

And I got an exception:

    Unexpected field "partial" for @SWG\Parameter()

I will appreciate your advice on correct way of reusing parameters.

Thanks,
Michael.

**Comment by bfanger** [comment]
Use a $ref directly directly inside `@SWG\Parameter()`.

```php
/**
 * @SWG\Get(
 *   path="/pi/{item_name}",
 *   summary="Get protected item",
 *   @SWG\Parameter(ref="#/parameters/ItemName")
 * )
*/
```
```php
/**
 * @SWG\Parameter(name="ItemName", in="path", type="string", required=true, description="protected item name", maxLength=256)
 */
```

I'll need to update the annotation mapping, `@SWG\Parameter` annotations inside a `Operation object`  must be an array, but `@SWG\Parameter` inside `@SWG\Swagger` or @`SWG\Path` should indeed be objects.

I'll might also need to introduce a new field ('key', 'identifer','parameter', or ...) for the mapping the `@SWG\Parameter` annotations to an object, so you could define multiple parameter definitions with the same name ('id', 'idOptional', etc).

@SWG\Partial is deprecated and only works in swagger 1.x, because the 2.x spec has refs which solve most D.R.Y. use-cases.

**Comment by mgvirtzm** [comment]
Thank you for the explanation, it helped.

In any case, will be glad to download new version with updated mapping.

**Comment by bfanger** [comment]
I've updated the annotation object mapping.

**Comment by mgvirtzm** [comment]
Thanks!
