### ISSUE TITLE
Sub types and discriminator

### ISSUE THREAD

**Issue by reva2** [zircote/swagger-php#207]
Hello guys.

Does the latest stable version (0.9.6) support "subTypes" and "discriminator" fields ([Docs](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#527-model-object)) in Model object? If so, please give me example of how it can be defined.

**Comment by bfanger** [comment]
0.9 / 1.x does not support "subTypes" and "discriminator", because those properties are not defined in https://github.com/zircote/swagger-php/blob/master/library/Swagger/Annotations/Model.php

**Comment by mkeefe** [comment]
I realize this ticket is closed, but does php-swagger intend to support subTypes?

**Comment by bfanger** [comment]
I'll accept pull requests for 0.9 / 1.x, but i'll won't be working on it myself.
