### ISSUE TITLE
How to generate separate api-docs.json for each of my API versions

### ISSUE THREAD

**Issue by rachelyelin** [zircote/swagger-php#208]
Hi,

I'm specifying my API version using SWG apiVersion property.
In order to divide my Swagger-UI according to this property, is there a way to tell swagger-php to generate api-docs.json for each apiVersion? 
So each api-docs.json would include only Resources of the requested apiVersion?

Thanks.

**Comment by bfanger** [comment]
swagger-php has no build-in facilities for filtering and splitting, but you can mutate the datastructure to get the desired effect, an example of that is the  [tests/SwaggerTests/FilterResourceTest.php](https://github.com/zircote/swagger-php/blob/master/tests/SwaggerTests/FilterResourceTest.php)

**Comment by rachelyelin** [comment]
Thanks.
