### ISSUE TITLE
noob issue?   The annotation "@Swagger\Annotations\Resource"  does not exist, or could not be auto-loaded.

### ISSUE THREAD

**Issue by peteclark3** [zircote/swagger-php#209]
Hey folks, I'm using codeigniter and would like to use swagger to document my RESTful api.  Ultimately the output is going to be used by swagger-ui, but so far I'm not having much luck.  I tried swagger 1.2, and that seems to generate the json files fine without error, but swagger-ui doesn't seem to parse through to my test method (have tried pointing to api-docs.json , generated index.php, etc)... always end up with a JS error in swagger-ui or an "ERROR" on the rendered page with a blank base_uri (I am making sure I specify swaggerVersion:1.2 in the generated api-docs.json file) .... so I wanted to move up to version 2.0 which the pet store example uses successfully, however I am not having any luck generating the swagger.json file using 2.0 from the command line...  

Here's the output from when I run swagger to generate the documentation.. 

$ sudo ./vendor/zircote/swagger-php/bin/swagger application/controllers/api/ --output ./api-docs/

Swagger-PHP 2.0.0-dev
---------------------
[WARN] [Semantical Error] The annotation "@Swagger\Annotations\Resource" in blabla/user.php on line 6 does not exist, or could not be auto-loaded.

[WARN] [Semantical Error] The annotation "@Swagger\Annotations\Api" in \User->list_get() in blabla/user.php on line 535 does not exist, or could not be auto-loaded.

-----------------------
0 operations documented
-----------------------
Written to /blabla/api-docs/swagger.json

.. code excerpt from user.json...
```php
<?php

use Swagger\Annotations as SWG;

/**
 * @package
 * @category
 *
 * @SWG\Resource(
 *   apiVersion="1.0.0",
 *   basePath="http://foo.bar.net/api",
 *   resourcePath="/user",
 *   description="User methods"
 * )
 */

class User extends REST_Controller {

.........

/**
     * @SWG\Api(
     *   @SWG\Operation(
     *     method="POST",
     *     summary="Get list of users",
     *     notes="",
     *     type="User",
     *     nickname="getUserList",
     *     authorizations={},
     *     @SWG\Parameter(
     *       name="username",
     *       description="The name that needs to be fetched. Use user1 for testing.",
     *       required=true,
     *       type="string",
     *       paramType="path",
     *       allowMultiple=false
     *     )
     *   )
     * )
     */
    public function list_get() {
        $ret = $this->db->query("select * from foousers");
        return $ret;
    }
}
```

**Comment by bfanger** [comment]
Thanks for your question, i've updated the error message to link to the [migration guide](https://github.com/zircote/swagger-php/blob/2.x/docs/Migrating-to-v2.md) because `@SWG\Resource()` doesn't exist in 2.x. 

A good starting point for working with swagger-php 2.x is the [Getting started guide](https://github.com/zircote/swagger-php/blob/2.x/docs/Getting-started.md)
Let me know if there is something missing or unclear.
