### ISSUE TITLE
Swagger 2.0 - Model definitions?

### ISSUE THREAD

**Issue by peteclark3** [zircote/swagger-php#212]
Just curious if there are any examples available as to how I'd need to annotate in PHP such that it would create the json input model as such: http://petstore.swagger.io/#!/user/createUser

I think a few more examples in the documentation would go a long way, if possible..

**Comment by bfanger** [comment]
Yes, in fact the swagger.json you see in  http://petstore.swagger.io/ is [one of the examples](https://github.com/zircote/swagger-php/tree/2.x/Examples/petstore.swagger.io) in [Examples folder](https://github.com/zircote/swagger-php/tree/2.x/Examples).

The `/user/createUser` is annotated in [Examples/petstore.swagger.io/controllers/UserController.php](https://github.com/zircote/swagger-php/blob/2.x/Examples/petstore.swagger.io/controllers/UserController.php#L7-L24) which references the model defined in [Examples/petstore.swagger.io/models/User.php](https://github.com/zircote/swagger-php/blob/2.x/Examples/petstore.swagger.io/models/User.php)

**Comment by peteclark3** [comment]
My apologies; I was google searching and ended up here.. http://zircote.com/swagger-php/
