### ISSUE TITLE
Swagger 2.0 - Manually defining model properties

### ISSUE THREAD

**Issue by lasselehtinen** [zircote/swagger-php#215]
Hi,

I am using Fractal to control the output of my JSON API. So the logical place for the Swagger annotations would be in the transformer. However seems like in 2.0 you have adopted this automatic system which sniffs the variable name under the annotation. Is there any way I could do the model properties manually? I could find anything in the examples.

Also, Fractal namespaces the stuff under data, how can I do this with swagger-php 2.0?

```json
{
   "data":{
      "api_token":"91324bf6b50b9ff609c4885d371af651",
      "id":1,
      "email":"joe@doe.com",
      "first_name":"Joe",
      "last_name":"Doe",
      "permissions":[

      ]
   }
}
```

**Comment by bfanger** [comment]
If you provide a name in the `@SWG\Property(name="use_this")` that name should be used instead of the inferred one.

The swagger v2 spec allows third-party data in the json with a 'x-' prefix, which can be generated with:

 ```
@SWG\Property(name="use_this", x={
  "data": {
    "id": 1,
    "email": "joe@doe.com"
  }
})
```
would output:
```json
{
  "name": "use_this",
  "x-data": {
    "id": 1,
    "email": "joe@doe.com"
  }
}
```
I'm not familiar with Fractal, so i'm not sure if this answers your question.

**Comment by lasselehtinen** [comment]
Thanks, this would be pretty much exactly what I would need. But seems like the "name" property is not allowed? I get the following error:

```
Unexpected field "name" for @SWG\Property(), expecting "property", "ref", "title", "description", "maxProperties", "minProperties", "required", "properties", "type", "format", "items", "collectionFormat", "default", "maximum", "exclusiveMaximum", "minimum", "exclusiveMinimum", "maxLength", "minLength", "pattern", "maxItems", "minItems", "uniqueItems", "additionalItems", "enum", "multipleOf", "discriminator", "readOnly", "xml", "externalDocs", "example", "allOf", "anyOf", "oneOf", "not", "definitions", "additionalProperties", "patternProperties", "x" in\Models\User->email in app/Models/User.php on line 18
```

Am I doing something wrong here? Here is the full code:

```php
<?php namespace SchillingRest\Transformers;

use League\Fractal\TransformerAbstract;
use SchillingRest\Models\User;
use Swagger\Annotations as SWG;

/**
 * @SWG\Definition(required={"email", "password"}, @SWG\Xml(name="User"))
 */

class UserTransformer extends TransformerAbstract
{
    /**
    * @SWG\Property(name="user", x={
    * "data": {
    *     "api_token": "ffdca087b7f97117330824ceea948a99",
    *     "id": "1",
    *     "email": "joe@doe.com",
    *     "first_name": "Joe",
    *     "last_name": "Doe"
    * }
    * })
    */

    public function transform(\Cartalyst\Sentry\Users\Eloquent\User $user)
    {
        return [
            'api_token'     => $user->api_token,
            'id'            => $user->id,
            'email'         => $user->email,
            'first_name'    => $user->first_name,
            'last_name'     => $user->last_name,
        ];
    }
}
```

**Comment by lasselehtinen** [comment]
Any updates on this? I would love to convert my old Swagger 1.1 specifications to 2.0.

**Comment by bfanger** [comment]
`name` changed to `property` in a91990fe67a3590c4aa583c29a435c3a5ff80df8 for a more uniform naming convention, i've updated the example.

**Comment by pavarnos** [comment]
Thanks. We are doing exactly the same. I wasted half a day trying to figure this out by myself. How far away is the 2.0 release?

**Comment by bfanger** [comment]
It's released!

**Comment by bhavikac** [comment]
hello 
i am using below property code
/**
     * @SWG\Property(property="signup_data", x={
     * "data": {
     *     "created_at": "ffdca087b7f97117330824ceea948a99",
     *     "updated_at": "1",
     *     "account_status": "joe@doe.com",
     *     "timezone": "Joe",
     * }
     * })
     */

to get 

    "signup_data": {    
            "created_at": "1234567890",
            "updated_at": "1234567890",
            "account_status": "ACTIVE",
            "timezone": "Asia/Phnom_Penh"
        }


but i m not finding this type of json in Model Schema of swagger-ui please let me know how i should write annotation event i need below json structurer in Model Schema of swagger-ui please let me know how i can do that


{
    "signup_data": {
        "profile": {
            "first_name": "Innovify",
            "last_name": "Agile",
            "email": "innovifytesting@gmail.com",
            "phone_number": "1234567890",
            "profile_pic_url": "https://lh4.googleusercontent.com/-B46681r3E3Y/photo.jpg"
        },
       "timezone" : "Asia/Phnom_Penh"
 }
}
