### ISSUE TITLE
Can not genrate documentation for multiple resporces - Via PHP

### ISSUE THREAD

**Issue by vaibhavmalushte** [zircote/swagger-php#219]
Hi,

Thank you for developing swagger-php and making it open sourse :)
I have installed everything as instructed and its working well so far when use commandline tool, however when I am trying to do it in Via PHP, I am not able to produce the documentation for multiple resources, 

use Swagger\Swagger;
$swagger = new Swagger('/projects/my_project');
header('Content-Type: application/json');
echo $swagger->getResource('/subscriptions', array('output' => 'json'));
echo $swagger->getResource('/account', array('output' => 'json'));

It is only genrating documentation for 'account', I've also tried 
echo $swagger->getResourceList( array('output' => 'json')); 
but it only genrates the list and can not expand it.
Am I missing anything? Please advice.

Thank you,
Vaibhav

**Comment by bfanger** [comment]
When you generate the json from php, you can only output 1 thing per request.

For the url you place in swagger-ui
```php
use Swagger\Swagger;
$swagger = new Swagger('/projects/my_project');
header('Content-Type: application/json');
echo $swagger->getResourceList( array('output' => 'json')); 
```
swagger-ui will try to load an additional json per resource in the list (check the network tab in chrome)

For example a the `http://my-server.com/api-doc.php/subscriptions` url which should respond with:
```php
use Swagger\Swagger;
$swagger = new Swagger('/projects/my_project');
header('Content-Type: application/json');
echo $swagger->getResource('/subscriptions', array('output' => 'json'));
```
