### ISSUE TITLE
Swagger 2.0 - which branch for oauth2?

### ISSUE THREAD

**Issue by peteclark3** [zircote/swagger-php#220]
Trying to use the oauth2 annotations... getting this..  is there a better place to ask questions other than in github issues?

Swagger-PHP 2.0.0-dev
---------------------
[WARN] [Semantical Error] The annotation "@Swagger\Annotations\Authorization" in application/controllers/api/api.php on line 3 does not exist, or could not be auto-loaded.

**Comment by bfanger** [comment]
What are you trying to output?

You might find the [security.php petstore.swagger.io example](https://github.com/zircote/swagger-php/blob/2.x/Examples/petstore.swagger.io/security.php) useful. As it contains an oauth2 example.

**Comment by peteclark3** [comment]
Trying to output a swagger.json.. (?)  Maybe I misunderstand the question. 

I used the petstore oauth2 example verbatim and replaced with my values.. am I using the wrong branch?

**Comment by peteclark3** [comment]
any update?

**Comment by dmyers** [comment]
@peteclark3 I was able to do OAuth pretty easy with the new 2.0 release.

Here's how you do it for the swagger root definition:

```php
 * @SWG\Swagger(
 *     @SWG\SecurityScheme(
 *         securityDefinition="oauth2", type="oauth2", description="OAuth2 Implicit Grant", flow="implicit",
 *         authorizationUrl="https://example.org/oauth/authorize",
 *         tokenUrl="https://example.org/oauth/token",
 *         scopes={
 *             "basic": "The default scope.",
 *             "*": "Allow access to all Client scopes.",
 *             "oauth": "Manage Oauth clients and authorization codes.",
 *             "usersetup": "Manage user setup tokens.",
 *             "accounts": "Read-only access to accounts.",
 *             "users": "Read-only access to users.",
 *             "users:write": "Write access to users.",
 *             "user:email": "Allow access to user email addresses.",
 *             "user:password": "Manage user passwords and forgot password tokens.",
 *             "account:lookup": "Various methods to locate an account."
 *         }
 *     )
 * )
```

Then for each of your routes/controller actions you do:

```php
 * @SWG\Get(
 *     path="/resource", summary="List resource",
 *     @SWG\Response(response="200", description="List of resources"),
 *     security={{"oauth2": {"scope"}}}
 * )
```

**Comment by peteclark3** [comment]
Ok, so I shouldn't use the "Authorization" annotation?

**Comment by dmyers** [comment]
Yeah you won't need to use that with the changes to the Swagger 2.0 specification it has been changed.

You can see a full list of the possible annotations you can use at:
https://github.com/zircote/swagger-php/tree/master/src/Annotations

**Comment by peteclark3** [comment]
Ok.  I thought the example I was using was 2.0 pet store but I guess not.  Thanks..
