### ISSUE TITLE
Swagger 2.0 Symfony dependency

### ISSUE THREAD

**Issue by dmyers** [zircote/swagger-php#222]
The new [Swagger 2.0 branch's composer](https://github.com/zircote/swagger-php/blob/2.x/composer.json#L27) requires Symfony's Finder 2.6 which is higher than [Laravel 4 requires which is 2.5](https://github.com/laravel/framework/blob/4.2/composer.json#L31).

Is there any way that this could be more compatible with existing projects and loosen the requirement in composer?

**Comment by dmyers** [comment]
@zircote Would there be an way to loosen the dependency?

**Comment by bfanger** [comment]
I'm disappointed that composer doesn't have a way of resolving version conflicts like bower does.

Changed the dependency to  `*` a.k.a. any version. Should now install without conflicts with L4  😀
