### ISSUE TITLE
Parameter Validation

### ISSUE THREAD

**Issue by mcheptea** [zircote/swagger-php#224]
Are there plans to implement a parameter validation helper class? I looked trough the repository and the documentation and this aspect seem to be missing.

I imagine the validator would take as the input the:
1. Parameter Value
2. Parameter definition (operationId:name)

And would return a boolean.

Example:

``` php
/**
 * @SWG\Put(
 *      tags={"api"},
 *      path="/do/something/{foo}",
 *      operationId="doSomething",
 *      @SWG\Parameter(
 *          name="foo", in="path", required=true, type="string",
 *          enum={"bar","baz","kaz"}
 *      )
 * )
 *
 * @param string $foo
 */
public function doSomething($foo){
    $fooValid = Swagger\Validator::valid($foo, "doSomething:foo"); // return a boolean
...
```

This is obviously an enhancement and I would like to know your thoughts on this.

**Comment by bfanger** [comment]
Swagger follows the [JSON Schema](http://json-schema.org/) specification, so you might want to try out the existing [PHP implementations](http://json-schema.org/implementations.html)
