### ISSUE TITLE
Maximum function nesting level reached

### ISSUE THREAD

**Issue by RenaudParis** [zircote/swagger-php#225]
Hi,

Here is what I got:

Swagger-PHP 0.9.6
-----------------

Fatal error: Maximum function nesting level of '200' reached, aborting! in phar://D:/wamp/www/myapp/lib/vendor/zircote/swagger-php/swagger.phar/library/Swagger/Parser.php on line 346

Call Stack:
    0.0010     279552   1. {main}() D:\wamp\www\myapp\lib\vendor\zircote\swagger-php\swagger.phar:0
    0.0020     328704   2. require('phar://D:/wamp/www/myapp/lib/vendor/zircote/swagger-php/swagger.phar/bin/swagger') D:\wamp\www\myapp\lib\vendor\zircote\swagger-php\swagger.phar:24
    0.0090     665408   3. Swagger\Swagger->__construct() phar://D:/wamp/www/myapp/lib/vendor/zircote/swagger-php/swagger.phar/bin/swagger:176
    0.0090     665824   4. Swagger\Swagger->scan() phar://D:/wamp/www/myapp/lib/vendor/zircote/swagger-php/swagger.phar/library/Swagger/Swagger.php:74
   27.1096    2999696   5. Swagger\Parser->__construct() phar://D:/wamp/www/myapp/lib/vendor/zircote/swagger-php/swagger.phar/library/Swagger/Swagger.php:245
   27.1096    2999648   6. Swagger\Parser->parseFile() phar://D:/wamp/www/myapp/lib/vendor/zircote/swagger-php/swagger.phar/library/Swagger/Parser.php:94
   27.1106    3500120   7. Swagger\Parser->parseTokens() phar://D:/wamp/www/myapp/lib/vendor/zircote/swagger-php/swagger.phar/library/Swagger/Parser.php:181
   27.1126    3574928   8. Swagger\Parser->nextToken() phar://D:/wamp/www/myapp/lib/vendor/zircote/swagger-php/swagger.phar/library/Swagger/Parser.php:217
   27.1126    3575376   9. Swagger\Parser->nextToken() phar://D:/wamp/www/myapp/lib/vendor/zircote/swagger-php/swagger.phar/library/Swagger/Parser.php:348
   27.1126    3575872  10. Swagger\Parser->nextToken() phar://D:/wamp/www/myapp/lib/vendor/zircote/swagger-php/swagger.phar/library/Swagger/Parser.php:356
   27.1126    3576320  11. Swagger\Parser->nextToken() phar://D:/wamp/www/myapp/lib/vendor/zircote/swagger-php/swagger.phar/library/Swagger/Parser.php:348
   27.1126    3576816  12. Swagger\Parser->nextToken() phar://D:/wamp/www/myapp/lib/vendor/zircote/swagger-php/swagger.phar/library/Swagger/Parser.php:356

I did nothing fancy, just ran Swagger-PHP after installing it

**Comment by RenaudParis** [comment]
Same thing with version 1.0.0 :


$ php lib/vendor/swagger-php/swagger.phar ./ -o doc/api/swagger/
Swagger-PHP 1.0.0
-----------------

Fatal error: Maximum function nesting level of '100' reached, aborting! in phar://D:/wamp/www/myapp/lib/vendor/swagger-php/swagger.phar/library/Swagger/Parser.php on line 346

Call Stack:
    0.0020     279408   1. {main}() D:\wamp\www\myapp\lib\vendor\swagger-php\swagger.phar:0
    0.0020     328480   2. require('phar://D:/wamp/www/myapp/lib/vendor/swagger-php/swagger.phar/bin/swagger') D:\wamp\www\myapp\lib\vendor\swagger-php\swagger.phar:24
    0.0090     675016   3. Swagger\Swagger->__construct() phar://D:/wamp/www/myapp/lib/vendor/swagger-php/swagger.phar/bin/swagger:176
    0.0090     675432   4. Swagger\Swagger->scan() phar://D:/wamp/www/myapp/lib/vendor/swagger-php/swagger.phar/library/Swagger/Swagger.php:74
   27.2856    3042456   5. Swagger\Parser->__construct() phar://D:/wamp/www/myapp/lib/vendor/swagger-php/swagger.phar/library/Swagger/Swagger.php:242
   27.2856    3042408   6. Swagger\Parser->parseFile() phar://D:/wamp/www/myapp/lib/vendor/swagger-php/swagger.phar/library/Swagger/Parser.php:94
   27.2866    3542656   7. Swagger\Parser->parseTokens() phar://D:/wamp/www/myapp/lib/vendor/swagger-php/swagger.phar/library/Swagger/Parser.php:181
   27.2886    3617488   8. Swagger\Parser->nextToken() phar://D:/wamp/www/myapp/lib/vendor/swagger-php/swagger.phar/library/Swagger/Parser.php:217
   27.2886    3617936   9. Swagger\Parser->nextToken() phar://D:/wamp/www/myapp/lib/vendor/swagger-php/swagger.phar/library/Swagger/Parser.php:348
   27.2886    3618432  10. Swagger\Parser->nextToken() phar://D:/wamp/www/myapp/lib/vendor/swagger-php/swagger.phar/library/Swagger/Parser.php:356
   27.2886    3618880  11. Swagger\Parser->nextToken() phar://D:/wamp/www/myapp/lib/vendor/swagger-php/swagger.phar/library/Swagger/Parser.php:348
   27.2886    3619376  12. Swagger\Parser->nextToken() phar://D:/wamp/www/myapp/lib/vendor/swagger-php/swagger.phar/library/Swagger/Parser.php:356

**Comment by bfanger** [comment]
Does 2.x also have this issue?

**Comment by bfanger** [comment]
I was unable to reproduce the issue.
