### ISSUE TITLE
Resource grouping

### ISSUE THREAD

**Issue by aqlx86** [zircote/swagger-php#227]
how to I group my resource? right now its just default

**Comment by aqlx86** [comment]
is it tags?

**Comment by mcheptea** [comment]
Yes. In the swagger 2.0 spec tags are used to group operations. Note that the concept of ***resource*** disappeared as it was known in swagger 1.* (a grouping entity).

Note that by using multiple tags you can create various groupings to fit you business logic. In swagger-ui this will mean that the same operation will be listed multiple times - once per tag.

*Swagger-php Example:*

```
    /**
     * @SWG\Post(
     *      tags={"mygroup"},
     *      path="/path/to/operation/{foo}/{bar}",
     *      description="Description here....",
...
```

*Json:*

```
...
"paths": {
        "/path/to/operation/{foo}/{bar}": {
            "post": {
                "tags": [
                    "mygroup"
                ],
                "description": "Description here....",
....
```

**Comment by aqlx86** [comment]
great, thanks @mcheptea
