### ISSUE TITLE
Dynamic annotation variables values during scanning

### ISSUE THREAD

**Issue by dmyers** [zircote/swagger-php#229]
Is there a way to possibly pull in set values that could be used in place of hard coded values? A few examples are say the host I would like to set it dynamically based on production and dev and my OAuth scopes I would like to have in an array to be reused in several places that could be referenced without duplication.

This could be me not being as familiar with Doctrine annotations, but wanted to ask and maybe others might be curious and could be something to add to readme and docs if possible and useful.

What do you think @bfanger? Thanks for the hard work in releasing the new 2.0 release, I was really wanting to utilize Swagger and have begun setting it up and it is really amazing.c

**Comment by bfanger** [comment]
You can use constants inside doctrine annotations.

```php
  define("API_HOST", ($env === "production") ? "example.com" : "localhost");
```

```php
/**
 * @SWG\Swagger(host=API_HOST)
 */
```

When you're using the CLI you'll need to include the php file with the constants using the `--bootstrap` options:
```
$ swagger --bootstrap constants.php
```

**Comment by aschwin** [comment]
Bob, would it be possible to pass variables when calling definitions? Like, when you have a sort of template where only one part of the final definition name is different, it would be welcome to be able to call the definition with a variable/parameter.

Like in the examples beneath, the only difference should be CustomerList in CustomerPaginated and Address in AddressPaginated. But this is not possible in the current setup I guess?

This is just one example and our application is littered with this repeated pattern for each paginated result.

If you could help us out, that would be very welcome. Thanks.

 ```
     * @SWG\Definition(
     *   definition="CustomerPaginatedResponse",
     *   type="object",
     *   allOf={
     *     @SWG\Schema(ref="#/definitions/Pagination"),
     *     @SWG\Schema(ref="#/definitions/CustomerEmbedded")
     *   }
     * )
     *
     * @SWG\Definition(
     *    definition="CustomerEmbedded",
     *    @SWG\Property(property="_embedded", type="array", @SWG\Items(ref="#/definitions/CustomerItems"))
     * )
     *
     * @SWG\Definition(
     *    definition="CustomerItems",
     *    @SWG\Property(property="items", type="array", @SWG\Items(ref="#/definitions/CustomerPaginated"))
     * )
     *
     * @SWG\Definition(
     *    definition="CustomerPaginated",
     *    type="object",
     *    allOf={
     *      @SWG\Schema(ref="#/definitions/CustomerList"),
     *      @SWG\Schema(ref="#/definitions/SelfLink")
     *   }
     * )
```

```
     * @SWG\Definition(
     *   definition="AddressPaginatedResponse",
     *   type="object",
     *   allOf={
     *     @SWG\Schema(ref="#/definitions/Pagination"),
     *     @SWG\Schema(ref="#/definitions/AddressEmbedded")
     *   }
     * )
     *
     * @SWG\Definition(
     *    definition="AddressEmbedded",
     *    @SWG\Property(property="_embedded", type="array", @SWG\Items(ref="#/definitions/AddressItems"))
     * )
     *
     * @SWG\Definition(
     *    definition="AddressItems",
     *    @SWG\Property(property="items", type="array", @SWG\Items(ref="#/definitions/AddressPaginated"))
     * )
     *
     * @SWG\Definition(
     *    definition="AddressPaginated",
     *    type="object",
     *    allOf={
     *      @SWG\Schema(ref="#/definitions/Address"),
     *      @SWG\Schema(ref="#/definitions/SelfLink")
     *   }
     * )
```
