### ISSUE TITLE
Error with trying to Define Trait

### ISSUE THREAD

**Issue by Arilas** [zircote/swagger-php#230]
I've use v2.0 Swagger-php
When you have trait, that you want to annotate, you receive error:
```php
Trying to get property of non-object
        // Merge unmerged @SWG\Property annotations into the @SWG\Definition of the class
        $unmergedProperties = $analysis->unmerged()->getAnnotationsOfType('\Swagger\Annotations\Property');
        foreach ($unmergedProperties as $property) {
            $classContext = $property->_context->with('class'); 
            if ($classContext->annotations) { // <------- This line
                $definition = false;
```
Is there's ability to Define trait?

**Comment by bfanger** [comment]
Thanks for reporting the bug. 
I've fixed the error, and added minimal support for traits.

For better trait support you could take a look at the [fork based on reflection](https://github.com/zircote/swagger-php/pull/214) by @mpajunen
