### ISSUE TITLE
Annotations documentation refers to now-deprecated annotation types

### ISSUE THREAD

**Issue by curtisgibby** [zircote/swagger-php#231]
http://zircote.com/swagger-php/annotations.html (derived from https://github.com/zircote/swagger-php/blob/gh-pages/docs/annotations.rst ) 

This should probably be updated to have the same information that the Migrating-to-v2 readme file has, with regard to `@SWG\Path` vs. `@SWG\Api`, `@SWG\Get` vs. `@SWG\Operation`, etc.

**Comment by YarekTyshchenko-awin** [comment]
The docs for annotations are awful.

This is an complain-o-reminder btw

**Comment by xtinagodwin** [comment]
+1

I am finding it nearly impossible to find up to date documentation for the newest version of Swagger.

**Comment by bravo-kernel** [comment]
What's stopping you from pressing `Fork` and submitting PRs? 

Complain issues are so 1980's :space_invader:

**Comment by bestog** [comment]
The documentation is useless. Where is the documentation and annotation-rules for the stable version?

**Comment by bfanger** [comment]
https://github.com/zircote/swagger-php/tree/master/docs
