### ISSUE TITLE
ref doesn't work 

### ISSUE THREAD

**Issue by ildarka1** [zircote/swagger-php#232]
Hello! 
Here is my controller's annotations:
```php
class ActivityController extends Resource {

    protected $identifierName = 'activity';

    /**
     * @SWG\Get(
     *  path="/api/1/pickup/{Pickup}/activity",
     *  description="Returns list of Pickup`s Activity",
     *  operationId="pickupActivityList",
     *  tags={"Pickup", "Activity"},
     * @SWG\Parameter(type="integer", in="path", name="Pickup", parameter="Pickup", description="Id of Pickup", @SWG\Schema(ref="#/definitions/Pickup")),
     * @SWG\Response(
     *      response="200",
     *      description="List of Activity",
     *      @SWG\Schema(ref="#/definitions/Activity")
     * ),
     * @SWG\Response(
     *      response="403",
     *      description="Permission Denied",
     *      @SWG\Schema(ref="#/definitions/ErrorResult")
     * )
     * )
     * @param Pickup $delivery
     * @param ActivityList $activityListResponse
     * @return $this
     */
    public function getList(Pickup $delivery, ActivityList $activityListResponse)
    {
        return $activityListResponse->map($delivery);
    }
}
```

Here is my model's annotations:
```php
/**
 * Class Activity
 * @package Issue\Entity
 * @ORM\Entity(repositoryClass="Issue\Repository\ActivityRepository")
 * @ORM\Table(name="case_activity")
 * @ORM\HasLifecycleCallbacks()
 * * @SWG\Definition(
 * definition="Activity",
 * @SWG\Property(property="id", type="integer"),
 * @SWG\Property(property="creator", ref="#/definitions/User"),
 * @SWG\Property(property="createdAt", type="string", format="date-format"),
 * )
 */
class Activity implements EntityInterface, \JsonSerializable
{..........}
```

Here is the translated annotations in editor:
```yaml
 '/api/1/pickup/{Pickup}/activity':
        get:
            tags:
                - Pickup
                - Activity
            description: 'Returns list of Pickup`s Activity'
            operationId: pickupActivityList
            parameters:
                -
                    parameter: Pickup
                    name: Pickup
                    in: path
                    description: 'Id of Pickup'
                    schema:
                        $ref: '#/definitions/Pickup'
                    type: integer
            responses:
                200:
                    description: 'List of Activity'
                    schema:
                        $ref: '#/definitions/Activity'
                403:
                    description: 'Permission Denied'
                    schema:
                        $ref: '#/definitions/ErrorResult'
```
But in swagger editor  response in my controller doesn't relate with my model.
Perhaps i have mistake in my annotations. Please help to solve this problem.

**Comment by bfanger** [comment]
`@SWG\Parameter(type="integer", name="Pickup", .@SWG\Schema(..` 
**type="integer"** doesn't have a schema.

As the description mentions "Lists of" you'll probably wanted an array:

```php
/**
 * @SWG\Get(...
 *   @SWG\Response(response="200", description="List of Activity",
 *     @SWG\Schema(type="array", @SWG\Items(ref="#/definitions/Activity"))
 *   )
 * )
 */
```

**Comment by ildarka1** [comment]
@bfanger I change my annotation, but problems doesn't disappear 

/**
     * @SWG\Get(
     *  path="/api/1/pickup/{Pickup}/activity",
     *  description="Returns list of Pickup`s Activity",
     *  operationId="pickupActivityList",
     *  tags={"Pickup", "Activity"},
     * @SWG\Parameter(type="integer", in="path", name="Pickup", parameter="Pickup", description="Id of Pickup"),
     * @SWG\Response(
     *      response="200",
     *      description="List of Activity",
     *      @SWG\Schema(type="array", @SWG\Items(ref="#/definitions/Activity"))
     * ),
     * @SWG\Response(
     *      response="403",
     *      description="Permission Denied",
     *      @SWG\Schema(ref="#/definitions/ErrorResult")
     * )
     * )
     * @param Pickup $delivery
     * @param ActivityList $activityListResponse
     * @return $this
     */
    public function getList(Pickup $delivery, ActivityList $activityListResponse)
    {
        return $activityListResponse->map($delivery);
    }
![screenshot from 2015-08-20 18 07 44](https://cloud.githubusercontent.com/assets/11726235/9386986/e6880704-4766-11e5-9d3d-27b487612745.png)

Also i have this error in swagger editor
![screenshot from 2015-08-20 18 12 20](https://cloud.githubusercontent.com/assets/11726235/9387026/0764ff22-4767-11e5-8319-c85ba94b2b13.png)
