### ISSUE TITLE
Support for multiple tags and name, description in tags 

### ISSUE THREAD

**Issue by huksley** [zircote/swagger-php#235]
Current syntax in swagger-php is
```
@SWG\Get(... tags={"pet"}, .. )
```
But in documentation it is possible to specify multiple tags with both name and definition:

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#tagObject

**Comment by bfanger** [comment]
You can, for multiple just add more:
```php
/**
 * @SWG\Get(... tags={"pet","store","user"}, .. )
 */
```
tags inside an operation (like `@SWG\Get`) is an array of strings.
To use the tagObject place a `@SWG\Tag` annotation:

```php
/**
 *@SWG\Tag(name="pet", description="a domesticated animal")
 */
```
An example can be found [here](https://github.com/zircote/swagger-php/blob/master/Examples/petstore.swagger.io/tags.php)

**Comment by huksley** [comment]
Thank for help! But I can`t attach @SWG\Tag to operation somehow.

**Comment by bfanger** [comment]
`tags={"pet"` in the operation is sufficient to "attach" it to the tag `@SWG\Tag(name="pet")`

**Comment by huksley** [comment]
Thanks! Got it.
