### ISSUE TITLE
Reverse generation

### ISSUE THREAD

**Issue by kleijnweb** [zircote/swagger-php#239]
I much prefer to write the initial spec in standard Swagger YAML. Any way to generate the annotations from a swagger doc?

**Comment by kleijnweb** [comment]
I developed [swagger-bundle](https://github.com/kleijnweb/swagger-bundle) to accomplish my goals and more. Closed.

**Comment by bfanger** [comment]
:+1: An alternative workflow for the php / swagger ecosystem.
