### ISSUE TITLE
Generate the php client library

### ISSUE THREAD

**Issue by chaitanyab25** [zircote/swagger-php#240]
is their any alternative methods or ways to generate the php client library 
or Request posing to the json file.
as i seen in js
i want a sample code in php   window.swagger = new SwaggerApi({
    url: "http://petstore.swagger.wordnik.com/api/api-docs",

 <script src='lib/shred.bundle.js' type='text/javascript'></script>
<script src='lib/swagger.js' type='text/javascript'></script>
<script type="text/javascript">
  // initialize swagger, point to a resource listing
  window.swagger = new SwaggerApi({
    url: "http://petstore.swagger.wordnik.com/api/api-docs",
    success: function() {
      if(swagger.ready === true) {
        // upon connect, fetch a pet and set contents to element "mydata"
        swagger.apis.pet.getPetById({petId:1}, function(data) {
          document.getElementById("mydata").innerHTML = data.content.data;
        });
      }
    }
  });

</script>

**Comment by bfanger** [comment]
swagger-php is not about generating a rest server or client from a swagger document, but the opposite, generating a swagger-documentation from (annotations in) your php code.

Maybe you want to give https://github.com/swagger-api/swagger-codegen or https://github.com/kleijnweb/swagger-bundle a try.
