### ISSUE TITLE
Support for @SWG\Head

### ISSUE THREAD

**Issue by itecedor** [zircote/swagger-php#242]
I tried to document a head operation with @SWG\Head and got the following error:
````
Warning: [Semantical Error] The annotation "@Swagger\Annotations\Head" in \Api_AssessmentsController-&gt;_headAssessments() in /srv/www/kindling/src3/controllers/Api/AssessmentsController.php on line 100 does not exist, or could not be auto-loaded.
````

I see that HEAD is a supported operation in the swagger documentation: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#operationObject

I tried forking swagger-php and adding a Annotations/Head.php class, but then I got a merge error when I switched to my fork:

````
Notice: Unable to merge @SWG\Head() in \Api_AssessmentsController-&gt;_headAssessments() in /srv/www/kindling/src3/controllers/Api/AssessmentsController.php on line 100
````

Is supporting HEAD possible or was it excluded intentionally? If you can point me in the right direction I'm happy to PR it back up.

**Comment by bfanger** [comment]
It wasn't excluded intentionally, I've simply didn't document any HEAD (or OPTIONS) requests in any of my projects.
Thanks for pointing it out, `@SWG\Head` will be available in the next release.
