### ISSUE TITLE
Dynamic Rendering of JSON throwing error

### ISSUE THREAD

**Issue by mattclements** [zircote/swagger-php#248]
[README.md](https://github.com/zircote/swagger-php#usage-from-php)
```php
<?php
require("vendor/autoload.php");
$swagger = \Swagger\scan('/path/to/project');
header('Content-Type: application/json');
echo $swagger;
```

[Documentation Site](http://zircote.com/swagger-php/using_swagger.html#via-php)
```php
<?php
use Swagger\Swagger;
$swagger = new Swagger('/projects/my_project');
header('Content-Type: application/json');
echo $swagger->getResource('/pet', array('output' => 'json'));
```

Neither of which seem to work throwing PHP Errors - is either/both still supported, or is there a new syntax?

**Comment by bfanger** [comment]
The documentation site is outdated (swagger-php 0.4 - 1.x)

Which error does the readme version throw?

**Comment by mattclements** [comment]
Apologies - not sure what I was doing but the README.md file is now fine.

Will see if I get some time to update the documentation as I use the project.
