### ISSUE TITLE
Is it possible to define an enum parameter with swagger-php?

### ISSUE THREAD

**Issue by pietervogelaar** [zircote/swagger-php#25]
The status query parameter at http://petstore.swagger.wordnik.com/#!/pet/findPetsByStatus_get is an ENUM kind of field.

The JSON for that is:

{

```
"name": "status",
"description": "Status values that need to be considered for filter",
"paramType": "query",
"defaultValue": "available",
"allowableValues": {
    "valueType": "LIST",
    "values": [
        "available",
        "pending",
        "sold"
    ]
},
"required": true,
"allowMultiple": true,
"dataType": "string"
```

}

But is it possible to define this with swagger-php annotations?

**Comment by Maykonn** [comment]
Where this is documented? I can't find on docs.

**Comment by bfanger** [comment]
Documented here: http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.23

Example here: https://github.com/zircote/swagger-php/blob/d191b5fca4f08786605316895f0542938bacb4a8/Examples/petstore.swagger.io/controllers/PetController.php#L65

**Comment by Maykonn** [comment]
Thanks!

**Comment by pakcybershagufta** [comment]
> ```
> /**
>  * @SWG\Parameter(
>  *   name="status",
>  *   in="query",
>  *   type="string",
>  *   enum={"pending", "failed", "completed"}
>  * )
>  */
> ```
> 
> Documented [here](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.23) and used in the petstore example [here](https://github.com/zircote/swagger-php/blob/d191b5fca4f08786605316895f0542938bacb4a8/Examples/petstore.swagger.io/controllers/PetController.php#L65)

Thank you ..great job

**Comment by pakcybershagufta** [comment]
How set default value in enum and please tell me also how set multi select also like cfor colors select multiple colors

**Comment by pakcybershagufta** [comment]
HOw we use anyOf etc preperty exact format please?

**Comment by itsAnuga** [comment]
@pakcybershagufta and everyone else:

	 *   @OA\Parameter(
	 *     @OA\Schema(
	 *       default="value1",
	 *       type="string",
	 *       enum={
	 *         "value1",
	 *         "value2",
	 *       },
	 *     ),
	 *     description="Value Values.",
	 *     example="value1",
	 *     in="query",
	 *     name="values",
	 *     required=true,
	 *   ),

Creates a Select with Options, where one value must be chosen, `value1` is selected by default.

**Comment by dhruvpaobs** [comment]
How can I add any of this to Schema?

x-enumNames
x-enumnames
x-enum-varnames

**Comment by DerManoMann** [comment]
The `ExpandEnums` processor supports defining a `x-` name to add enum names to the spec: https://zircote.github.io/swagger-php/reference/processors.html#expandenums

This can be done via the CLI or programmatically: https://zircote.github.io/swagger-php/reference/processors.html#processor-configuration

In this case you want something like
```shell
./vendor/bin/openapi -c expandEnums.enumNames=enum-varnames
```

Or 
```php
(new Generator())
    ->setConfig([
        'expandEnums.enumNames' => 'enum-varnames',
    ]);
```

**Comment by dhruvpaobs** [comment]
Thanks for the help. In L5 Swagger, we were able to add it this way:
x={"enumNames": ["NAME1", "NAME2"]}

`
  @OA\Schema(
      schema="Role",
      type="integer",
      description="User role ID",
      enum={1, 2, 3, 4, 5},
      example=1,
      x={
          "enumNames": ["Admin", "Residential", "Property Managers", "Maintaining Staff", "Security Staff"]
      }
  )
`
