### ISSUE TITLE
Is it possible to change default value in schema?

### ISSUE THREAD

**Issue by Nicarim** [zircote/swagger-php#257]
Hi,
I'm trying to make documentation to not-so-RESTful API, it's partially restful due to back-compatibility that I cannot change. I'm trying to document responses from API, there are few types of codes that API can return in its body like so ![img2](http://bit.ly/1GUWuQ0). Is there a way to make it the same in swagger here: ![img](http://bit.ly/1GUW8ZA), so developers that read doc know what to expect from API?

**Comment by bfanger** [comment]
**Yes,** with `example`, as in [Examples/petstore.swagger.io/models/Pet.php](https://github.com/zircote/swagger-php/blob/master/Examples/petstore.swagger.io/models/Pet.php#L18) 

On http://petstore.swagger.io/ you can see `name: "doggy"` in the pet responses instead of the default `name: "string"`.
