### ISSUE TITLE
Update or change stable composer version?

### ISSUE THREAD

**Issue by bravo-kernel** [zircote/swagger-php#258]
Any chance on updating/changing the latest stable packagist version or an ETA?

I'm no expert but the currenct stable 2.0.3 commit is f6624cc067d7894ec32943f5b94cf282c683f7c7 which behind on some current patches.

Changing the minimum-stability on my root project is not an option so I can't really fall back to using `dev-master`.

**Comment by bfanger** [comment]
Released 2.0.4

**Comment by bravo-kernel** [comment]
Much obliged Mr. @bfanger
