### ISSUE TITLE
Use constant to set enum

### ISSUE THREAD

**Issue by birbird** [zircote/swagger-php#260]
This is the enum syntax
```
    /**
     * @var string
     * @SWG\Property(enum={"available", "pending", "sold"},)
     */
```
It seems it was like this before
```
    /**
     * @var string
     * @SWG\Property(enum="['available', 'pending', 'sold']",)
     */
```

Is it possible to use constant as enum array now?

**Comment by bfanger** [comment]
Yes, the newer doctrine-annotations library supports arrays using the `{` `}` notation, so our json hack in swagger-php 0.9/1.x was no longer needed in 2.x

**Comment by birbird** [comment]
@bfanger thanks a lot for you attention.
I am new to php, I think I can use a php constant as enum array with the old version.
But how to do this if it use brace like enum={"available", "pending", "sold"}.
Could you please give some hints? Thank you in advance.
