### ISSUE TITLE
Support for diacritic in description

### ISSUE THREAD

**Issue by jurosh** [zircote/swagger-php#261]
After I added character "ž" into Info block it fails to render.

```
* @SWG\Info(
 *	  title="MyAPI",
 *	  version="1.0",
 *    description="ž"
 * )

```

Error:
`[RECOVERABLE_ERROR] Method Swagger\Annotations\Swagger::__toString() must return a string value in /home/vagrant/Code/.../vendor/zircote/swagger-php/src/Annotations/Swagger.php on line 149`

**Comment by bfanger** [comment]
On my machine it generates:
```json
{
    "swagger": "2.0",
    "info": {
        "title": "MyAPI",
        "description": "\u017e",
        "version": "1.0"
    },
    "paths": {},
    "definitions": {}
}
```
Make sure you saved the php file as UTF-8

**Comment by jurosh** [comment]
Thanks - I missed that. It's working just fine after conversion of PHP file to UTF-8.
