### ISSUE TITLE
3 Response questions

### ISSUE THREAD

**Issue by mrgarbage** [zircote/swagger-php#262]
1. Hello I would like to know how to properly use headers in @SWG\Response. I would like to add authorization header in response but I failed to do so, and I can't find any example on that...
Something like this:

 @SWG\Response(
   response="200",
   description="Unprocessable Entity.",
   headers = "Authorization", "bearer: token"
    )

2. I would like to format my response to look like this:

  {
    "message": "Unprocessable Entity.",
     "errors": {
      "first_name": [
      "The first name field is required."
       ],
      "last_name": [
       "The last name field is required."
       ],
       "email": [
        "The email has already been taken."
       ],
       "phone": [
        "The phone field is required."
        ],
        "photo": [
        "The photo field is required."
         ],
        "language": [
         "The language field is required."
         ],
        "location": [
         "The location field is required."
         ],
        "find_out": [
         "The find out field is required."
          ],
        "type": [
         "The type field is required."
         ]
         },
        "status_code": 422
}

I tried to do it with @SWG\Schema inside @SWG\Response but failed to do so, so some help would be appreciated.

3.Is it possible to have multiple responses with same status code for same operation but with different messages? 

I managed to do it like this:

@SWG\Response(
    response="401",
    description="Failed to authenticate because of bad credentials or an invalid authorization header.<br>-----------------------------------------------------------------------<br>Wrong number of segments.<br>-----------------------------------------------------------------------<br>Token Signature could not be verified.<br>-----------------------------------------------------------------------<br>Could not decode token. The token is an invalid JWS.<br>-----------------------------------------------------------------------<br>Token has expired"
   )

But I would like to do it in nicer approach if exists.

**Comment by bfanger** [comment]
### 1. Using headers in @SWG\Response
Use the @SWG\Header inside the @SWG\Response an example is in [Examples/swagger-spec/petstore/PetsController.php](https://github.com/zircote/swagger-php/blob/master/Examples/swagger-spec/petstore/PetsController.php#L20)

### 2. I would like to format my response.
@SWG\Schema is the right choice, swagger-ui sometimes has trouble detecting a nested schema and prefers a $ref.
Swagger is used to describe the **shape** of the request and the responses not the exact values.
So you wouldn't put `"The first name field is required."` inside swagger, but specify `type="string"`
Personally I would even document all possible keys inside the errors object, but just say the the response has an message property as string and an errors property as object.
An example of an error response can be found in [Examples/swagger-spec/petstore/api.php](https://github.com/zircote/swagger-php/blob/master/Examples/swagger-spec/petstore/api.php#L14)

### 3. Is it possible to have multiple responses with same status code for same operation but with different messages?
No,swagger allows only 1 response shape per http-status-code. Your REST api has  "Token Signature could not be verified." as output, but in swagger you just say its a string. Again describe the shape, don't specify the contents.
