### ISSUE TITLE
Support Swagger extensions for AWS API Gateway 

### ISSUE THREAD

**Issue by dmulter** [zircote/swagger-php#264]
The Amazon API Gateway Importer tool (https://github.com/awslabs/aws-apigateway-importer) supports two extensions to a Swagger spec. Not sure if these are in the spec also, but at least they are in the importer tool. Anyway, there are 2 extensions:

- x-amazon-apigateway-integration
- x-amazon-apigateway-auth

I would like to extend my current PHP annotations to also specify values for these 2 new extensions.

**Comment by bfanger** [comment]
Swagger PHP has support for vendor properties (x-***)

`@SWG\Info(x={"amazon-apigateway-auth"=12345})`

**Comment by dmulter** [comment]
Awesome. I was hoping it was there and I just couldn't find it. 

Thanks,
David

**Comment by jreyn003** [comment]
How can I do this in .NET.  I think I would have to add it in the SwaggerConfig.cs file as an OperationFilter but not sure how.
