### ISSUE TITLE
Set base path via annotation

### ISSUE THREAD

**Issue by poul-kg** [zircote/swagger-php#265]
in `swaggervel.php` I have basepath defined as

`"default-base-path" => '/api/v2',`

But I have controller, which have 2 methods, and one of methods requires `/api/v3` base path, is there way to re-define base path for given controller method only?

**Comment by bravo-kernel** [comment]
Not using swaggervel myself but you could easily set the required fields at runtime: https://github.com/alt3/cakephp-swagger/blob/3f2e0c5e433ae57fdc9f715fa7a8f39937892e6e/src/Controller/DocsController.php#L66.

**Comment by bfanger** [comment]
No, the **basePath** must be the same for all requests.
In your case the basePath can be "/api" and update requests by adding either "v2/" or "v3/"
