### ISSUE TITLE
Examples for composition and inheritance from Swagger v2.0 spec

### ISSUE THREAD

**Issue by Leammas** [zircote/swagger-php#267]
Could you add new examples for [this](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#composition-and-inheritance-polymorphism) part of spec? 
I found it impossible to implement even basic Pet->Cat example using existing documentation.

**Comment by bfanger** [comment]
A example of an `allOf` composition can be found in the [PetWithDocsController.php](https://github.com/zircote/swagger-php/blob/81f4935de731829869452be21d791029539adcce/Examples/swagger-spec/petstore-with-external-docs/controllers/PetWithDocsController.php#L11) a very limited example, but it can help you on your way.
