### ISSUE TITLE
Code block in description

### ISSUE THREAD

**Issue by FelixMalfait** [zircote/swagger-php#271]
Hi,
I can't manage to add code blocks to the description.
I've tried something like this:

``````
 *      @SWG\Info(
 *         #JSON Response
 *         ``` 
 *          // Item
 *          [
 *              'foo' => 'bar'
 *          ];
 *         ```
``````

And many different variation. But none seems to work.

Anyone could please help me on this?

Thanks a lot!

---

Edit : Okay finally found a way to make it "work" by removing the stars.
The reason I didn't try this at first is that it generates a huge red block in my php editor, the code is linted as if there was an error. And when I save, php beautifier messes up with the formatting because it doesn't detect it's a comment either. Any workaround ? Thanks

**Comment by bfanger** [comment]
I havent seen codeblocks in annotations before, but you should ask the https://github.com/doctrine/annotations guys. (That's what swagger-php uses to parse the annotations.)

**Comment by mcheptea** [comment]
@FelixMalfait  you can create your own custom "comment" annotation, ie. `@comment`. See http://stackoverflow.com/a/13198342/2853903
