### ISSUE TITLE
Adding required tag to a ref'd definition

### ISSUE THREAD

**Issue by robertdown** [zircote/swagger-php#272]
Perhaps it is outside of the scope of the spec, but I am attempting to reference a definition as a parameter (body) and mark a field in the ref'd definition as required only in this specific context.

```
@SWG\Post(
     path="/stream",
     description="Create a new stream",
     @SWG\Parameter(
         in="body",
         name="body",
         @SWG\Schema(
             ref="#/definitions/Stream",
             required={"stream_id"}
         )
     ),
```

This would ideally render the Stream definition (which it does) and mark `stream_id` as required (which it is not). Expected behavior **does** occur when adding the required array to the definition object

**Comment by bfanger** [comment]
Using a ref combined with other properties is sadly not supported in the current spec.

**Comment by bfanger** [comment]
Should work since 2.0.8 (which includes #301 )
