### ISSUE TITLE
Remove oneOf and other invalid schema properties

### ISSUE THREAD

**Issue by xiehan** [zircote/swagger-php#273]
I was super stoked to discover the `oneOf` property in the Schema definition, since we have a major use case for it in our API, but then I discovered just now that the Swagger 2.0 spec doesn't support it: OAI/OpenAPI-Specification#525

The discussion at OAI/OpenAPI-Specification#333 reveals that the list of unsupported properties is:
- id
- $schema
- additionalItems
- definitions
- patternProperties
- dependencies 
- anyOf
- oneOf
- not

Rather than confuse others who, like me, might jump on the chance to use this and then find their Swagger docs breaking validation, it would probably be better to remove all unsupported properties from [@SWG\Schema](https://github.com/zircote/swagger-php/blob/master/src/Annotations/Schema.php).

**Comment by bfanger** [comment]
Bummer, the spec is very vague about which subset is or isn't supported. I hoped the swagger-ui team would just implement support.
