### ISSUE TITLE
Problem with SecurityScheme?

### ISSUE THREAD

**Issue by ti0rafa** [zircote/swagger-php#275]
Hello

I maybe wrong, but I think there is something wrong with SecurityScheme. Im trying to set the name of the api key when used as a query param, but it appears that is ignoring it.

@SWG\SecurityScheme(
    type="apiKey",
    securityDefinition="token",
    in="query",
    name="token"
 )

This will do something like http://url.com?api_token=xxxxx, but i was expecting to be something like http://url.com?token=xxxxx, or at least I think that the OpenApi-Specification states that when name is provided it should set to what ever value is set, in this case "token".

I'm using the latest swagger-ui 2.1.4

BTW im not sure what does securityDefinition should do.

**Comment by bfanger** [comment]
Last time i checked swagger-ui didn't use securityDefinition. You might need to modify the index.html in your swagger-ui installation to set up the correct authentication.
