### ISSUE TITLE
How to deserialize a json string to Swagger\Annotations\Swagger?

### ISSUE THREAD

**Issue by csimplestring** [zircote/swagger-php#276]
Hi, I found the a Swagger\Annotations\Swagger object can serialize into a json, but is there a way to deserialize a json string into a Swagger\Annotations\Swagger object? That will be great convenience for me.

**Comment by bfanger** [comment]
Nope, but I'd gladly merge a pull request that adds this feature. 😉

**Comment by csimplestring** [comment]
Thanks for reply. I'll try.

**Comment by csimplestring** [comment]
I made a PR, please check.

**Comment by adambro** [comment]
I guess it was #290 so issue can be closed?

**Comment by bravo-kernel** [comment]
It can indeed. Thans for pointing this out Mr. @adambro

**Comment by MelbourneDeveloper** [comment]
Swagger can't be serialized or deserialized to or from Json because it allows illegal character variable names like backslash.

**Comment by bfanger** [comment]
Slashes are not illegal in json, they might have to be escaped, but that is handled by php’s json_encode() just fine.

Deserializing json into swagger is now build-in, see the 
“Usage from the Deserializer” in the readme for more info.
