### ISSUE TITLE
Required @SWG\Info() not found

### ISSUE THREAD

**Issue by challgren** [zircote/swagger-php#277]
I'm using version 2.0.5 installed from composer and following the example on the Readme.md in the repo and I'm getting the following error ```Notice (1024): Required @SWG\Info() not found [ROOT\Vendor\zircote\swagger-php\src\Logger.php, line 38]```

**Comment by bfanger** [comment]
That means swagger-php could find the comment with the @SWG\Info annotation in the *.php files it scanned

Download and try scanning https://github.com/zircote/swagger-php/blob/master/Examples/swagger-spec/petstore/api.php to see if the problem is with scanning. If that works, compare it to your file and you might spot the difference that causes the issue.

**Comment by challgren** [comment]
Thanks after tinkering around that was gonna be my guess since I have put any swagger comments in my code.

**Comment by shantanuaggarwal2695** [comment]
I am facing the same issue 
PHP Notice:  Required @OA\PathItem() not found in /home/shantanu/vendor/zircote/swagger-php/src/Logger.php on line 39
PHP Notice:  $ref "#/components/schemas/Pet" not found for @OA\Items() in ../php-swagger/demo.php on line 15 in /home/shantanu/vendor/zircote/swagger-php/src/Logger.php on line 39
How should I resolve it?

**Comment by KeitelDOG** [comment]
@shantanuaggarwal2695 , I had the same problem, but once you defined one OA Endpoint annotation it's ok. Like before an Action in Laravel or other places. Example for listing Projects :

    /**
     * @SWG\Get(
     *      path="/projects",
     *      operationId="getProjectsList",
     *      tags={"Projects"},
     *      summary="Get list of projects",
     *      description="Returns list of projects",
     *      @SWG\Response(
     *          response=200,
     *          description="successful operation"
     *       ),
     *       @SWG\Response(response=400, description="Bad request"),
     *       security={
     *           {"api_key_security_example": {}}
     *       }
     *     )
     *
     * Returns list of projects
     */
    public function index() {
        //
    }
