### ISSUE TITLE
Is there a way to represent inherited API methods?

### ISSUE THREAD

**Issue by jfoliveira** [zircote/swagger-php#278]
Hi,

On my API I have a `BaseController` that implements common methods such as `count` and `exists`.

So let's suppose I have two resource controllers, `Users` and `Projects,` inheriting from `BaseController`. Without any code being added to these controllers the following endpoints routes are created and work:

```
users/count
users/{id}/exists
```

```
projects/count
projects/{id}/exists
```

As `count` and `exists` methods are only implemented in `BaseController`, what would be the Swagger-PHP syntax to have those inherited methods automatically added to all controllers/resources in Swagger-UI as above?

**Comment by bfanger** [comment]
You can reuse a Response by placing `@SWG\Response(response="count", ...)`  outside an operation _(for example in the BaseController)_ and use that specification elsewhere by reference `@SWG\Response(ref="#/responses/count")` _(for example inside the `@SWG\Get` of the User and Project controllers)_.

I don't know how to implement controller inheritance in a framework agnostic way, but if you want to automate that by building a Processor.
Your Processor can augments the annotations from the resource controllers with the annotation from the base controller. The [InheritProperties](https://github.com/zircote/swagger-php/blob/master/src/Processors/InheritProperties.php) Processor does something similar for the @SWG\Definitions.

```php
\Swagger\Analysis::registerProcessor(function ($analysis) {
 // augments resource controllers here...
});
```

**Comment by jfoliveira** [comment]
Thanks!

> I don't know how to implement controller inheritance in a framework agnostic way

Could you point to any controller inheritance implementation example, no matter the framework, so I can get a better understanding of how it works?
I'm still trying to figure out how the `registerProcessor` works so more examples would definitely help.

The first part of your advice about Response re-usage worked just fine. Thanks a lot!
Pasting here to help others searching for the same topic.

`Global/common definitions`:
```php
/**
 *  @SWG\Definition(
 *      definition="CountResponse",
 *      required={"count"},
 *      @SWG\Property(
 *          property="count",
 *          type="integer"
 *      )
 *  )
 *
 *  @SWG\Definition(
 *      definition="ExistsResponse",
 *      required={"exists"},
 *      @SWG\Property(
 *          property="exists",
 *          type="boolean"
 *      )
 *  )
 *
 *  @SWG\Response(
 *      response="count",
 *      description="Success",
 *      @SWG\Schema(ref="#/definitions/CountResponse")
 *  )
 *
 *  @SWG\Response(
 *      response="exists",
 *      description="Success",
 *      @SWG\Schema(ref="#/definitions/ExistsResponse")
 *  )
 */
```

Re-using `count` response on `Users` controller:

```php
    /**
     *  @SWG\Get(
     *      produces={"application/json"},
     *      path="/users/count",
     *      tags={"Users"},
     *      summary="Get count of elements in the collection",
     *      @SWG\Response(ref="#/responses/count", response=200)
     * )
     */
```
