### ISSUE TITLE
Issue when a single class has multiple resources. 

### ISSUE THREAD

**Issue by facultymatt** [zircote/swagger-php#28]
Hello, I'm running into another issue implementing swagger-php in a Codeiginiter build (although I believe this issue appear in other php frameworks as well.)

Here are the basics, I have a number of controllers, each of which is a class, ie: `class Users extends MY_Controller`. Controllers might contain methods that map to different endpoints.  The endpoints are defined in a routes file. This creates the need to declare multiple resources in the same class... however this causes unexpected results - they often overwrite each other - the last one taking precedence. Furthermore, the same resource might have functions in different controllers, but adding the same resource declaration to multiple classes again casuses un-expected results. 

Here is some example code:

```
/**
 * @Resource(
 *  apiVersion="1",
 *  swaggerVersion="1.1",
 *  resourcePath="/users", // also contains resourcePaths for /posts
 *  basePath="http://localhost:8888/myapp/"
 * )
 */
class Posts extends MY_Controller {
    // @api path="/poasts"
    function list_all() { } 
    // @api path="/users/{user_id}/posts"
    function list_by_user($user_id) { } 
    // @api path="/posts/{post_id}"
    function show($post_id) { } 
    // @api path="/posts/create"
    function create() {} 
}

/**
 * @Resource(
 *  apiVersion="1",
 *  swaggerVersion="1.1",
 *  resourcePath="/users", // second class declared with resourcePath = 'users'
 *  basePath="http://localhost:8888/myapp/"
 * )
 */
class Users extends MY_Controller {
    function create() { }
}
```

```
$routes['posts'] = 'posts/list_all';
$routes['posts/(:num)'] = 'posts/show/$1';
$routes['users/(:num)/posts'] = 'posts/list_all/$1';
$routes['signup] = 'users/create';
// note above that @resourcePath posts/1 and users/123/posts 
// both share the same class
```

Any thoughts. Is it possible to support a setup like this? 

I was thinking of a few possible solutions: 
- Support declaring multiple resourcePaths in a single @resource declaration. 
- OR
- Support declaring multiple @resources before a class, and scanning for each one separately (rather then having the last one rule)

Then, swagger-php would build apis for each resource by either:
- parsing the beginning of @api( path="/poasts/create" ), ie: using explode('/', $path)
- OR
- add a param to @api that allows for setting of the resource for said api. ie: @api( path="/poasts/create", resourcePath="/poasts" )

From my experience this would solve the issue, although I'm not sure it's the best approach. Any thoughts? 

Thanks for your hard work on swagger-php!

**Comment by hajarrashidi** [comment]
has anyone solved the possiblity to use multiple resource

**Comment by DerManoMann** [comment]
@hajarrashidi This issue is discussing the outdated OpenApi v2 `@SWG` annotations and those are no longer supported.
If you have an issue with the OpenAPI v3 implementation (ie. the `@OA` annotations), please open a new issue for that.
