### ISSUE TITLE
swagger dynamic generate swagger-docs/swagger.json  yii2-rest

### ISSUE THREAD

**Issue by bhavikac** [zircote/swagger-php#280]
hello,
i have downloaded  yii2-rest with swagger-ui, swagger-doc and swagger-api.
it is loading   swagger-docs/swagger.json when we run ui of swagger api, i have problem regarding that how can dynamically general this swagger.json file please help

**Comment by bfanger** [comment]
To generate a swagger.json with swagger-php you'll need to add annotation to your code as described in the https://github.com/zircote/swagger-php/blob/master/Readme.md and https://github.com/zircote/swagger-php/blob/master/docs/Getting-started.md guide.

**Comment by Khayrabadi** [comment]
i have same issue. instead of routing swager ui to a static file i want to route it to a swagger-gen.php file. 
 in this file i have written:
`$swagger = \Swagger\scan('app/v2/method');
echo json_encode($swagger);`

but swagger ui says:

> Failed to load spec.
