### ISSUE TITLE
Potential miscommunication bug with Swagger Editor in emum

### ISSUE THREAD

**Issue by dpesios** [zircote/swagger-php#282]
Hello,

To cut a long story short, I annotated my code in order to produce the JSON file using Swagger-PHP 2.0 via the CLI.
My annotation is as follows:
```

 @SWG\Path(
	path="/{table}.{format}",
	@SWG\Get(
		summary="Expose a table in the specified format",
     		description="Table to be fetched from database in given format",
		operationId="Retrieve table in specified format",
		@SWG\Parameter(
     			name="table",
     			in="path",
     			required=true,
			description="The given table to be fetched form database",
     			type="string",
		       enum="['Users', 'Addresses', 'Companies']"
 		),
 		@SWG\Parameter(
     			name="format",
     			in="path",
     			required=false,
			description="The given format to send to the client",
     			type="string",
			enum="['xml', 'html', 'json']"
 		),
		@SWG\Response(
			response=200,
			description="A table with values"
		),
		@SWG\Response(
			response="default",
			description="an ""unexpected"" error"
		)
 	)	
 )

```

The output JSON file in part, is as follows:
```
	"paths": {
        "/{table}.{format}": {
            "get": {
                "summary": "Expose a table in the specified format",
                "description": "Table to be fetched from database in given format",
                "operationId": "Retrieve table in specified format",
                "parameters": [
                    {
                        "name": "table",
                        "in": "path",
                        "description": "The given table to be fetched form database",
                        "required": true,
                        "type": "string",
                        "enum": "['Users', 'Addresses', 'Companies']"
                    },
                    {
                        "name": "format",
                        "in": "path",
                        "description": "The given format to send to the client",
                        "required": false,
                        "type": "string",
                        "enum": "['xml', 'html', 'json']"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "A table with values"
                    },
                    "default": {
                        "description": "an "unexpected" error"
                    }
                }
            }
        }

```
The issue, I think, is in enum. If you take a closer look, you will observe that enum values are enclosed in quotation marks ("").
The editor, in order to produce the static documentation (especially in the preview "Try this operation"), does not accept this format.

It accepts,however, something like this:
....
"enum": ["xml", "html", "json"]
....

I attempted to alter my annotations in many ways as this:
....
enum="[""xml"", ""html"", ""json""]"

But quotation marks so that Swagger-PHP produce the JSON are required, as far as I am concerned.

Is this some kind of miscommunication bug between Swagger-PHP and Swagger Editor or am I missing something ?
Can you suggest a workaround for me to do, so that when I jump into the automatic generation of documentation 
in the future, to overcome this issue ? That is somehow manipulate the produce JSON file on-the-fly and correct it.

Any suggestion would be highly appreciated. Thanks in advance, have a nice weekend.

**Comment by bfanger** [comment]
The notation `enum="['Users', 'Addresses', 'Companies']"` from swagger-php 1.x is deprecated and doesn't work in swagger-php 2.x
Since v2 has adopted the array notation from Doctrine-annotations: `enum={'Users', 'Addresses', 'Companies'}`

**Comment by dpesios** [comment]
Thanks again!
To be more precise, in my case perhaps,  it accepts it as:

`enum={"Users", "Addresses", "Companies"}`
