### ISSUE TITLE
Multilavel json property in swagger annotation

### ISSUE THREAD

**Issue by bhavikac** [zircote/swagger-php#283]
hello
i am using below property code
/**
- @SWG\Property(property="signup_data", x={
- "data": {
- "created_at": "ffdca087b7f97117330824ceea948a99",
- "updated_at": "1",
- "account_status": "joe@doe.com",
- "timezone": "Joe",
- }
- })
  */
  to get
  "signup_data": {  
      "created_at": "1234567890",
      "updated_at": "1234567890",
      "account_status": "ACTIVE",
      "timezone": "Asia/Phnom_Penh"
  }

but i m not finding this type of json in Model Schema of swagger-ui please let me know how i should write annotation event i need below json structurer in Model Schema of swagger-ui please let me know how i can do that

{
"signup_data": {
"profile": {
"first_name": "test",
"last_name": "test",
"email": "test@gmail.com",
"phone_number": "1234567890",
"profile_pic_url": "https://lh4.googleusercontent.com/-B46681r3E3Y/photo.jpg"
},
"timezone" : "Asia/Phnom_Penh"
}
}

**Comment by kapishmalik** [comment]
Could you please help to write Swagger Annotation for above case. I am also facing the same issue. I want to pass arguments in query in form of above format.

**Comment by bhavikac** [comment]
hello 

i am able to construct below json format but not able to add "signup_data" key
{
  "profile": [
    {
      "first_name": "string",
      "last_name": "string",
      "email": "string",
      "phone_number": "string",
      "profile_pic_url": "string"
    }
  ],
  "device": [
    {
      "id": "string",
      "os_name": "string",
      "os_version": "string"
    }
  ],
  "location": [
    {
      "address": "string",
      "latitude": "string",
      "longitude": "string",
      "city": "string",
      "state": "string",
      "country": "string",
      "postcode": "string",
      "country_code": "string"
    }
  ],  
  "timezone": "string"
}

by using annotation of models i have on parent model User and 3 embedded models Profile,Device and Location each has attributes.  @kapishmalik  i am pasting below code may be it helps you :) .

User model annotation

class User extends ActiveRecord {
/**
     * @SWG\Property(name="profile",type="array",@SWG\Items(ref="#/definitions/Profile"))
     */
    public $profile;

    /**
     * @SWG\Property(name="device",type="array",@SWG\Items(ref="#/definitions/Device"))
     */
    public $device;

    /**
     * @SWG\Property(name="location",type="array",@SWG\Items(ref="#/definitions/Location"))
     */
    public $location;
}

**Comment by kapishmalik** [comment]
Hi Bhavika ,

Thanks for your prompt reply. I am very new to Swagger Annotation. 

I was trying to pass {"User":{"username":"admin","password":"admin1234"}} in the request as parameter in formData. Could you please suggest annotation to pass this. 
 @SWG/Parameter() will have ?

**Comment by bhavikac** [comment]
Hello kapishmalik

i have used below parameters for above formate 

 *   @SWG\Parameter(
     *     in="body",
     *     name="body",
     *     description="List of user object",
     *     required=true,
     *     @SWG\Schema(
     *       type="array",
     *       @SWG\Items(ref="#/definitions/User")
     *     )
     *   )

**Comment by kapishmalik** [comment]
I need to pass in="formData" and for that it requires input Type.

**Comment by bfanger** [comment]
You can't describe nested/json as formData parameters.
If you use `<input name="User[username]">` will be converted to an array in php.
So you document that as `@SWG\Parameter(in="formData",name="User[username]", type="string")`

**Comment by kapishmalik** [comment]
Thanks for the response @bfanger
