### ISSUE TITLE
Documentation site not compatible with 2.0 version

### ISSUE THREAD

**Issue by adambro** [zircote/swagger-php#294]
Documentation for swagger-php that I've googled is not compatible with 2.0 version. I guess it is leftover from 1.1 version. Update or pull it down, please. It's confusing.
http://zircote.com/swagger-php/

**Comment by fezfez** [comment]
:+1:

**Comment by adambro** [comment]
Ah, haven't noticed #231 issue. Duplicated.

**Comment by bravo-kernel** [comment]
Closing in favor of #231. Feel free to submit PR(s) for documentation improvements mr. @adambro.
