### ISSUE TITLE
Not working when short open tag "<?" is used

### ISSUE THREAD

**Issue by kop** [zircote/swagger-php#295]
Swagger-PHP version: `2.0.6`

When short open tag `<?` is used instead of `<?php`, `\Swagger\scan()` is unable to locate any annotations.

**Comment by mcheptea** [comment]
@kop make sure you have the short tags enabled in your php.ini, ie. `short_open_tag=On`

Swagger-php uses the zend lexical scanner (via token_get_all) to retrieve the doc blocks. If the `short_open_tag` is turned off the lexical analyzer will not recognize the file as a valid php source and the parser will ignore it.

In any case is highly recommended to not use the short opening tag.

**Comment by bravo-kernel** [comment]
I second the remark by Mr. @kop, using the short opening tag is **not recommended** (in most cases).

**Comment by kop** [comment]
@mcheptea, @bravo-kernel first of all, why you think that `short_open_tag` is bad? Agreed, it was bad long time ago (before PHP 5.4, when this directive affected `<?=` tags), but now it's enabled by default. Plus who really cares if I have full control over config?

**Comment by kop** [comment]
@mcheptea,

> make sure you have the short tags enabled in your php.ini

Yes, it's enabled. I'm using PHP 7.0, so it's enabled by default.

**Comment by bravo-kernel** [comment]
@kop I believe the advised road is to not use the short open tag for the php-file-first-line (since that rule could be interpreted as anything, e.g. xml). Using short open tag after that first line is perfectly ok, I do too.

**Comment by kop** [comment]
@bravo-kernel, well I believe it's something about developer comfort and code style, but I don't think this discussion is somehow related to the issue.

There is a feature that supported by PHP and is not supported by this package. That's it.

**Comment by bravo-kernel** [comment]
Even though the explanation by @mcheptea makes sense I hear you. Feel free to PR. 

> Swagger-php uses the zend lexical scanner (via token_get_all) to retrieve the doc blocks. If the short_open_tag is turned off the lexical analyzer will not recognize the file as a valid php source **and the parser will ignore it**.

**Comment by mcheptea** [comment]
@kop I tested this with PHP 5.4 and 5.6 I'll test later with 7.0. It would have been good to mention the version from the start.

> Yes, it's enabled. I'm using PHP 7.0, so it's enabled by default.

Please note that PHP 7 doesn't come with the `short_open_tag=On` by default as per http://php.net/manual/en/language.basic-syntax.phptags.php, unless compiled with `--enable-short-tags`.

It is also possible your cli php and you apache/nginx interpreter use different php.ini files (as seen in some xampp/wamp stacks). It might be worth checking this case.

As @bravo-kernel mentioned an alternative analyzer is very welcome. However I do believe this will be quite an undertaking.

**Comment by kop** [comment]
@mcheptea, I'm very sorry, but I was wrong and there is no issue. I just noticed that `short_open_tag` wasn't enabled for CLI. So I enabled it and it works just fine. The issue can be closed.
