### ISSUE TITLE
Schema required definition seems odd

### ISSUE THREAD

**Issue by TesseractG** [zircote/swagger-php#296]
Current, the required property in the Schema annotation is defined like this:

```
/**
 * An object instance is valid against this property if its property set contains all elements in this property's array value.
 * @var string[]
 */
 public $required;
```

This seems very odd and also breaks if I add a required=true in Parameter annotation (inherited from Schema). It states that 'required is a "boolean", expecting "[string]"'. If I do set it to a valid string[], like ["1"], the parameter still shows up as optional in the final documentation.

I think the type for $required should be a boolean, not a string[], as that makes no sense.

**Comment by bfanger** [comment]
Agreed, but swagger-php doesn't define the spec. Although "no sense" is depends on the context.

In a `@SWG\Schema(type="object")` the `required` defines which properties are required, and because a `@SWG\Property` inside a schema can also be of type object

**Comment by TesseractG** [comment]
Thanks for the feedback, I will look into it!
