### ISSUE TITLE
Swagger.phar file not found

### ISSUE THREAD

**Issue by jyotsanakhannu** [zircote/swagger-php#302]
I am unable to find swagger.phar file.Can you please provide the swagger.phar file so that I can resolved the swagger implementation in my project.
Thanks in advance.

**Comment by bfanger** [comment]
swagger-php **2.x** doesn't have a phar file as it uses [composer](http://getcomposer.org/) for global installation: `composer global require zircote/swagger-php`

The swagger.phar is still available in the unsupported [1.x tag](https://github.com/zircote/swagger-php/tree/1.0.0) version

**Comment by jyotsanakhannu** [comment]
Thanks for your response
