### ISSUE TITLE
Add support for Specification Extensions

### ISSUE THREAD

**Issue by michellesanver** [zircote/swagger-php#304]
The Swagger specification supports extension with the x- definition. This is from the docs directly:

"While the Swagger Specification tries to accommodate most use cases, additional data can be added to extend the specification at certain points.

The extensions properties are always prefixed by "x-" and can have any valid JSON format value.

The extensions may or may not be supported by the available tooling, but those may be extended as well to add requested support (if tools are internal or open-sourced)."

I was unable to see this in SwaggerPHP and would love support for them, now I'm wondering what the best way would be to implement this?

**Comment by bfanger** [comment]
Swagger-PHP already has support for extensions, but it is indeed not well documented. 

All annotation have a `x` property which will unfold into "x-" properties:
```php
/**
 * @SWG\Info(
 *   title="Example",
 *   version=1,   
 *   x={"some-name":"a-value", "another": 2}   
 * )
 */
```

Generates:

```json
"info": {
    "title": "Example",
    "version": 1,
    "x-some-name": "a-value",
    "x-another": 2
},
```

**Comment by michellesanver** [comment]
I missed that. Is there any documentation that I'm not finding on what annotations you can use where? If not, is this something I can help with? Thanks!

**Comment by bfanger** [comment]
The previous version of swagger-php had a [document on annotations](http://zircote.com/swagger-php/1.x/annotations.html) , if you would convert that for 2.x into docs/annotations.md that would be greatly appreciated.

I did create http://bfanger.github.io/swagger-explained/, but that it takes the json output as the starting point, so is a bit backwards documentation-wise.

**Comment by bfanger** [comment]
Just added some documentation to the Getting started page e6dc561e4d17ab94146920b663e7d34d4ab9bf9a

To create "#/x-operationTypes" you can place the information on the `@SWG\Swagger()` annotation:

```php
/**
 * @SWG\Swagger(
 *   x={"operationTypes": {
 *      "IssueList": {"parameters": ... }
 *   }}   
 * )
```
