### ISSUE TITLE
Field "schema" is required

### ISSUE THREAD

**Issue by javiertrejo** [zircote/swagger-php#305]
When i run the command-line swagger to generate the JSON file the program return this:

[INFO] Field "schema" is required when @SWG\Parameter(name="data",in="body") is in "body" in /opt/BM3/api/src/Encompass/Sources/Screen.php on line 173

This is not correct because, when the parameter is in="body" and the type is "file" the schema is not necesary.
`
@SWG\Parameter(description="contenido del archivo",
                               in="body",
                               name="data",
                               required=true,
                               type="file"
                               ),
`

**Comment by bfanger** [comment]
Thanks, but [the spec](http://swagger.io/specification/#parameterObject) doesn't mention this exception, shouldn't the `@SWG\Parameter->in` be `formData` when the `@SWG\Parameter->type`='file' ?

**Comment by javiertrejo** [comment]
Thanks for the explanation. The "error" was not in the swagger generator. Is in the swagger-ui and how display the mentioned workaround.

Regards,
