### ISSUE TITLE
Properties in snake_case format

### ISSUE THREAD

**Issue by wildpascal** [zircote/swagger-php#306]
Is there a possibility to configure properties in snake_case format?

`
/**
- @SWG\Property(property="this_is_example")
- @Type("integer")
- @var int
  */
  private $thisIsExample;
  `

Would be nice if we don´t have to set the property by hand for every properties.

**Comment by bfanger** [comment]
Yes, you could write a [Processor](https://github.com/zircote/swagger-php/tree/master/src/Processors) and change all the properties to snake_case.

I'd gladly accept such a processor as a pull request (as long as the processor is not enabled by default)

**Comment by hpatoio** [comment]
I was able to acheive this by changing the like here https://github.com/zircote/swagger-php/blob/master/src/Processors/AugmentProperties.php#L57 to

{code}
                $property->property = strtolower(preg_replace('/[A-Z]/', '_\\0', $context->property));
{code}

I can write a processor but how do you tell `swagger-php` to enable it ?
