### ISSUE TITLE
Does Path support optional ending

### ISSUE THREAD

**Issue by andreidiaconescu** [zircote/swagger-php#307]
hello,

Can you please help with a hint:
- does the "path" attribute support optional parts?
- example:
  -- got path="/users/{user_id}/locks/{id}", i need "locks/{id}" to be optional
- is it possible ?

**Comment by bfanger** [comment]
Sadly no, as far as i know thats not supported in the spec. 
You'd have to create 2 paths, one for "/users/{user_id}/locks/{id}" and one for "/users/{user_id}"

You can make use of refs to point to the first operation to avoid some duplication, but I agree it's not an elegant solution.
