### ISSUE TITLE
Nested Directory Annotation Detection is not working.

### ISSUE THREAD

**Issue by atapatel** [zircote/swagger-php#309]
Hi there, i am trying to generate swagger file. but Swagger/scan only work for current directory. it is not going to scan other directory listed in it.

**Comment by bfanger** [comment]
`Swagger\scan("/path/to/project")` should just work

**Comment by atapatel** [comment]
@bfanger my mistake actually others nested directories are symlinked so its not working..

**Comment by bfanger** [comment]
You can pass a `Symfony\Component\Finder\Finder` object instead of a `string` to `\Swagger\scan()` there is probably an option to let it follow symlinked directories.
But be careful so you don't create an directory-structure with infinite subdirectories.
