### ISSUE TITLE
The annotation "@Swagger\Annotations\Resource" in class TestTask\PhotosBundle\Controller\ApiController does not exist, or could not be auto-loaded.

### ISSUE THREAD

**Issue by NadaBen** [zircote/swagger-php#312]
Hello,
i'm trying to use zircote/swagger.php to generate swagger specification of an api that i'm coding with symfony 2, i installed swagger-php with the composer : 
`"zircote/swagger-php": "*"`
when i add this annotation to my controller like : 
`use Swagger\Annotations as SWG;
/**
 *
- @SWG\Resource(
-     apiVersion="1",
-     basePath="/",
-     resourcePath="/apiv1"
- )
  */
  class ApiController extends FOSRestController`

is shows me this error:
`[Semantical Error] The annotation "@Swagger\Annotations\Resource" in class TestTask\PhotosBundle\Controller\ApiController does not exist, or could not be auto-loaded in TestTask\PhotosBundle\Controller\ApiController (which is being imported from "C:\wamp\www\test\app/config\routing.yml").`

**Comment by bfanger** [comment]
`"zircote/swagger-php": "*"` installs the latest version of swagger-php (v2.x) but you're using the older v1.x annotations.

**Comment by NadaBen** [comment]
So what's the new annotation please ?

**Comment by bfanger** [comment]
I recommend checking out the examples: https://github.com/zircote/swagger-php/tree/master/Examples/swagger-spec/petstore

**Comment by NadaBen** [comment]
Okey thank you, but when i try to execute this command in the terminal 
`C:\wamp\www\test\vendor\zircote\swagger-php\bin>swagger -help`
it gives me swagger command is not found

**Comment by bfanger** [comment]
On windows run `php swagger --help` instead of `swagger --help`
