### ISSUE TITLE
Solution for issue#245

### ISSUE THREAD

**Issue by kingjh** [zircote/swagger-php#314]
We encountered the same issue as issue #245 
https://github.com/zircote/swagger-php/issues/245

We found it's because the statement 'Swagger\Annotations\Property' => ['properties', 'property'],' is missing in $_nested in \zircote\swagger-php\src\Annotations\Items.php
After changing $_nested as below, the issue was fixed
    public static $_nested = [
        'Swagger\Annotations\Items' => 'items',
        'Swagger\Annotations\Property' => ['properties', 'property'],
    ];

Please include this fix in future enhancement.

**Comment by huami-cloud** [comment]
Look forward to tag 2.0.7

**Comment by bfanger** [comment]
2.0.7 is released
