### ISSUE TITLE
Response examples can be an array.

### ISSUE THREAD

**Issue by Somebi** [zircote/swagger-php#316]
Only one example is taken from an array of examples. It should pick all examples.

```
 *   @SWG\Response(
 *     response=200,
 *     description="If ugame is returned, team is successfully joined, else see errors list.",
 *     examples={
 *          "application/json":{
 *              "game_id":1,
 *              "ugame":2,
 *              "room_count":1
 *          },
 *          "application/json":{
 *              "err":2,
 *              "msg":"Not allowed to pick more than 6 players from one team."
 *          },
 *          "application/json":{
 *              "err":5,
 *              "msg":"Game already started or even finished."
 *          },
 *          "application/json":{
 *              "err":101,
 *              "msg":"Max entries reached."
 *          }
 *      }
 *   ),
```

Producing only this:

```
                "200": {
                    "description": "If ugame is returned, game is successfully edited, else see errors list.",
                    "examples": {
                        "application/json": {
                            "err": 5,
                            "msg": "Game already started or even finished."
                        }
                    }
                },
```

**Comment by Somebi** [comment]
/**
     * An example of the response message.
     * @var array
     */
    public $examples;


Is an array in your code. Parser doesn't throw exception saying there should be one example either.
Please add more examples in the response object.

**Comment by bfanger** [comment]
You can't have multiple entries for the same key as:
```php
['key1' => 'value1', 'key1' => 'value2']
```
will results in:
```php
['key1' => 'value2']
```
It's not allowed in json either, I think the output you wan't is generated with:
```php
/**
 * @SWG\Response(
 *    response=200,
 *    description="If ugame is returned, team is successfully joined, else see errors list.",
 *    examples={
 *      { 
 *        "application/json":{
 *            "game_id":1,
 *            "ugame":2,
 *            "room_count":1
 *        }
 *      }, {
 *        "application/json":{
 *            "err":2,
 *            "msg":"Not allowed to pick more than 6 players from one team."
 *        }
 *      }, {
 *        "application/json":{
 *            "err":5,
 *            "msg":"Game already started or even finished."
 *        }
 *      }, {
 *        "application/json":{
 *            "err":101,
 *            "msg":"Max entries reached."
 *        }
 *      }
 *    }
 * )
 */
```
note the additional level of `{` and `}`

**Comment by Somebi** [comment]
Ugh my bad. probably overworked for today. Anyway it's kinda weird. How to add multiple 200 response example? For example i have various 200 response codes with different errors.

**Comment by Somebi** [comment]
I have tried to change application/json into example1 and example2 but it just puts example1 and example2 into content_type.

**Comment by Somebi** [comment]
I'm using apiary.io after your generated json.

**Comment by bfanger** [comment]
I'm closing this issue as it's more of a [specification](https://github.com/OAI/OpenAPI-Specification) issue than an issue in swagger-php.

**Comment by zhaoqidong1994** [comment]
when i want to use examples like this 
 * @SWG\Response(
 *   response=200,
 *   description="...",
 *    examples={
 *      { 
 *        "application/json":{
 *            "game_id":1,
 *            "ugame":2,
 *            "room_count":1
 *        }
 *      }}


it is not show in my swagger-ui

**Comment by zhaoqidong1994** [comment]
my swagger json like this


`{
swagger: "2.0",
paths: {
/store/order/{orderId}: {
get: {
tags: [
"store"
],
summary: "Find purchase order by ID",
description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions",
operationId: "getOrderById",
produces: [
"application/xml",
"application/json"
],
parameters: [
{
name: "参数字段名称",
in: "query",
description: "描述",
required: false,
type: "integer",
format: "int64",
maximum: 10,
minimum: 1
}
],
responses: {
200: {
description: "...",
examples: [
{
application/json: {
game_id: 1,
ugame: 2,
room_count: 1
}
}
]
}
}
}
},
/hahaha/order/{orderId}: {
get: {
tags: [
"hahaha"
],
summary: "接口功能",
description: "接口功能描述",
produces: [
"application/json"
],
parameters: [
{
name: "orderId",
in: "path",
description: "描述",
required: true,
type: "integer",
format: "int64",
maximum: 10,
minimum: 1
}
],
responses: {
200: {
description: "...",
examples: {
application/json: {
orderId: "Puma",
type: "Dog",
color: "Black",
gender: "Female",
breed: "Mixed"
}
}
},
default: {
description: "an "unexpected" error",
schema: {
$ref: "#/definitions/user"
}
}
}
}
},
/api/photo: {
get: {
tags: [
"photo"
],
summary: "图片集管理",
description: "列表",
produces: [
"application/json"
],
parameters: [
{
name: "id",
in: "query",
description: "id",
required: false,
type: "integer",
format: "int64"
},
{
name: "user_id",
in: "query",
description: "user_id",
required: false,
type: "integer",
format: "int64"
},
{
name: "user_id",
in: "query",
description: "user_id",
required: false,
type: "integer",
format: "int64"
},
{
name: "user_id",
in: "query",
description: "user_id",
required: false,
type: "integer",
format: "int64"
}
]
}
}
},
definitions: {
user: {
allOf: [
{
properties: {
id: {
type: "integer",
format: "int64"
},
name: {
type: "integer",
format: "int64"
}
}
}
]
}
}
}`

**Comment by bfanger** [comment]
Looks like you can't use an array of examples, your example only uses one, so simply removing the outer `{` `}` and it should work with swagger-ui.
