### ISSUE TITLE
Swagger-PHP and Silex

### ISSUE THREAD

**Issue by DerManoMann** [zircote/swagger-php#317]
Hi there,

This is not so much an issue but shameless self promotion....

I've created a library that allows to use silex annotations together with swagger-php to generate swagger JSON from the (mixed) annotations: https://packagist.org/packages/radebatz/silex2swagger.

If it turns out to be useful (I use it a lot...) it would be great if perhaps there could be a reference to it somewhere in your docs.

Cheers, mano

**Comment by bfanger** [comment]
Something like [this](https://github.com/zircote/swagger-php/blob/master/docs/Related-projects.md) ?

**Comment by DerManoMann** [comment]
:+1:
