### ISSUE TITLE
No annotations found

### ISSUE THREAD

**Issue by pantaoran** [zircote/swagger-php#320]
I cannot get this package to work at all. I started with a Lumen project to create an API, but now at last I'm testing just this package specifically with nothing else, and it just does not work.

I work on Ubuntu 14.04. I made a new directory and ran `composer create-project zircote/swagger-php` to install this, then I navigated to `swagger-php/Examples/swagger-spec/petstore-simple` and ran bin/swagger.

First there are lots of warnings like this:

`[WARN] [Semantical Error] The class "Swagger\Annotations\Definition" is not annotated with @Annotation. Are you sure this class can be used as annotation? If so, then you need to add @Annotation to the _class_ doc comment of "Swagger\Annotations\Definition". If it is indeed no annotation, then you need to add @IgnoreAnnotation("SWG\Definition") to the _class_ doc comment`

I found in #125 that you said this type of problem could be circumvented by using your own fork of the DocParser.php class in Doctrine, so I also tried to use that and the warnings went away.

However, the main problem remains: at the end there is always this line

`[INFO] Required @SWG\Info() not found`

and the resulting swagger.json file is always "empty", like no annotations were found at all. At first I spent a lot of time trying to find what was wrong with my custom annotations, but eventually I'm now trying to run this on the example provided with this package and it doesn't work.

Any idea what could be going wrong?

Ubuntu 14.04
php-fpm 5.6.3

[PHP Modules]
apc
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
enchant
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
json
ldap
libxml
mbstring
mcrypt
memcached
mhash
mongo
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xhprof
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by bfanger** [comment]
Are you using a php setting that strips php-doc comments or affects reflection, it look like doctrine was unable to extract the `@Annotation` [which it has](https://github.com/zircote/swagger-php/blob/master/src/Annotations/Definition.php#L10), maybe apc or opcache ?

php-fpm is for webservers, maybe there something wrong with the php-cli version or config.
Try running the `echo Swagger\scan( '/projects/swagger-php/Examples/swagger-spec/petstore-simple')` from a webpage. 

I'm getting the expected output:
```
$ cd /projects/swagger-php/Examples/swagger-spec/petstore-simple
$ /projects/swagger-php/bin/swagger 

Swagger-PHP 2.0.7
-----------------
Scanning files in '/projects/swagger-php/Examples/swagger-spec/petstore-simple' ...
    get /pets
   post /pets
    get /pets/{id}
 delete /pets/{id}
-----------------------
4 operations documented
-----------------------
Written to /projects/swagger-php/Examples/swagger-spec/petstore-simple/swagger.json
```

**Comment by pantaoran** [comment]
Thanks for your reply. I will look into it again later but it's probably going to be a few days. 
Project pressure forced me to write a swagger.json by hand instead, and for right now that will have to do.

**Comment by anasinnyk-atb** [comment]
It's problem actual for me. We use swagger on our application based on lumen framework

**Comment by bfanger** [comment]
I can't reproduce this issue. 
If this issue is still affecting you, reopen and provide steps to reproduce the bug.
