### ISSUE TITLE
Build fails with HHVM on TravisCI

### ISSUE THREAD

**Issue by ovr** [zircote/swagger-php#324]
Hey!

https://travis-ci.org/zircote/swagger-php/jobs/138811425#L276

![image](https://cloud.githubusercontent.com/assets/572096/16340031/ca07aa1a-3a60-11e6-8ee3-0daa4dc7534d.png)

Why it's not fixed?

Thanks

**Comment by bfanger** [comment]
Ask HHVM, they should make constants work like they do in "normal" php.

Or convince the PSR-2 style checker (squizlabs/php_codesniffer) to allow lowercase characters in a namespaced constant definition.

Ps. HHVM is not a supported platform, but you could try if the #319 patch.
