### ISSUE TITLE
GFM bold feature does not working

### ISSUE THREAD

**Issue by Somebi** [zircote/swagger-php#325]
description	string	A verbose explanation of the operation behavior. GFM syntax can be used for rich text representation.

http://www.markdowntutorial.com/lesson/1/

Bold is not working. Could you please check. Whether that is problem on your side or it's swagger inner problem.

Could you please check all others features of GFM syntax features.

Thank you.

**Comment by bfanger** [comment]
Swagger-php only has json as output, report any display issues  to the viewer repository.
