### ISSUE TITLE
Annotation Deprecrated Notice points to 404 link

### ISSUE THREAD

**Issue by drakej** [zircote/swagger-php#330]
https://github.com/zircote/swagger-php/blob/2.x/docs/Migrating-to-v2.md

This link is provided via a PHP Warning. E.G.

PHP Warning:  The annotation @SWG\\Model() is deprecated. Found in [REDACTED] on line 12\nFor more information read the migration guide: https://github.com/zircote/swagger-php/blob/2.x/docs/Migrating-to-v2.md in /usr/share/php/composer/vendor/zircote/swagger-php/src/Logger.php on line 38

**Comment by bfanger** [comment]
Ah, i've removed the git branch "2.x", which had been merged into master some time ago.
I've updated the link to https://github.com/zircote/swagger-php/blob/master/docs/Migrating-to-v2.md

Thanks for the report.
