### ISSUE TITLE
Do not use the silence operator `@`

### ISSUE THREAD

**Issue by Tobion** [zircote/swagger-php#331]
You are silencing errors instead of checking for existing indexes, e.g. `@$options['analyser']`.
This is really bad practice and creates alot of error logs in our app.
Please replace those with `isset` checks or similar.

**Comment by bravo-kernel** [comment]
Feel free to submit a PR mr. @Tobion

**Comment by hkulekci** [comment]
@Tobion @bravo-kernel I sent a pr for this issue.

**Comment by bfanger** [comment]
Fix #335  is merged 009dbf7 into master
