### ISSUE TITLE
Example for how to use extensions (e.g., `x-code-samples`)

### ISSUE THREAD

**Issue by skyzyx** [zircote/swagger-php#333]
Can't figure it out from reading the code. Any clues would be helpful. Thanks!

**Comment by bfanger** [comment]
Swagger-PHP already has support for extensions, but it is indeed not well documented.

All annotation have a x property which will unfold into "x-" properties:

/**
 * @SWG\Info(
 *   title="Example",
 *   version=1,   
 *   x={"some-name":"a-value", "another": 2}   
 * )
 */
Generates:

"info": {
    "title": "Example",
    "version": 1,
    "x-some-name": "a-value",
    "x-another": 2
},#304

**Comment by sbuckpesch** [comment]
Here is a working example of how to use an x-code-sample Annotation in a GET request:

```/**
	 * @SWG\Get(
	 *     path="/matches",
	 ...
         *     produces={"application/json"},
	 *     x={
	 *          "code-samples":{
	 *              {"lang":"JavaScript", "source":"console.log('Hello World');"},
	 *              {"lang":"PHP", "source":"var_dump($test)"}
	 *          }
	 *     },
	 *     @SWG\Parameter(ref="#/parameters/appId"),
	 ....
```
