### ISSUE TITLE
Swagger UI not generated

### ISSUE THREAD

**Issue by manishkvaish** [zircote/swagger-php#334]
Hi
I am getting all json arrays as the output

won't i get any UI ?

**Comment by bravo-kernel** [comment]
This library is solely responsible for generating the json arrays (used by the UI) so you won't get any UI.

For the UI either download it manually or take a look at one of the [Swagger UI implementations](http://swagger.io/open-source-integrations/), php section.

**Comment by manishkvaish** [comment]
Hi 
Thanks for the valuable information.I have generated the UI using the repository received from
https://github.com/swagger-api/swagger-ui
thanks
