### ISSUE TITLE
Hide Pet Store

### ISSUE THREAD

**Issue by EPICmynamesBG** [zircote/swagger-php#337]
This isn't so much of an issue with the source code, but HOW do you disable the Pet Store examples from being generated? I have the base info defined and a few of my endpoints, but I have not been able to figure out how to prevent the Scanner from generating the Pet Store. Any and all help appreciated!

**Comment by alexeyshockov** [comment]
I think that you generate Swagger schema for your project's root directory, including `vendor`. If true, it's not correct to do so, because, yes, you include all the examples.

Try to specify a directory with your files

```
$ ./vendor/bin/swagger ./src -o swagger.json
```

or to exclude `vendor`.

**Comment by bravo-kernel** [comment]
Yes, either that or UI is auto loading the remote pet store definitions (if no endpoint URL is provided)

**Comment by EPICmynamesBG** [comment]
Ahh, thank you alexeyshockov. Per my script, it was the root issue. I'm using Slim framework everywhere else but this script, I'll just embed it in a src folder and change my scan to `./src` . I'm posting my snippet below for future reference
And thanks bravo-kernel. I did check that in the swagger-ui.js file and change it to my endpoint to make sure it wasn't pulling the remote, that's how I knew I was generating it.
Thanks everyone!
```php
<?php
require("vendor/autoload.php");
$swagger = \Swagger\scan('.');
header('Content-Type: application/json');
echo $swagger;
```
