### ISSUE TITLE
is there any way i can add autocompletion feature for swagger php annotation in phpstrom?

### ISSUE THREAD

**Issue by atapatel** [zircote/swagger-php#341]
is there any way i can add autocompletion feature for swagger php annotation in phpstrom?

**Comment by alexeyshockov** [comment]
Just install "PHP Annotations" plugin. If your project includes swagger-php in usual way (via Composer), it should work without any configuration.

**Comment by atapatel** [comment]
@alexeyshockov i just follow your instruction but no luck :(

**Comment by bfanger** [comment]
I've just tried it, and it only works when you're using the full classname. 
For example `@Swagger\Annotations\Get(su` shows the completion for _**su**mmary_ and _con**su**mes_.
Also <kbd>command</kbd>+<kbd>click</kbd> on the annotation navigated to the Get annotation class.

Doctrine-annotation allow using shorter annotations by importing a namespace: `use Swagger\Annotations as SWG;`
_(swagger-php tricks the doctrine-annotation parser that all php-files have this line)_

Sadly this doesn't get picked up  by the PHP Annotation plugin [yet](https://github.com/Haehnchen/idea-php-annotation-plugin/issues/65).

**Comment by bfanger** [comment]
I'm closing this issue because this project doesn't affect phpstorm's feature set.
