### ISSUE TITLE
AWS api-gateway-swagger-extensions

### ISSUE THREAD

**Issue by aluferraz** [zircote/swagger-php#342]
Any way to accomplish the AWS Swagger extensions ?

http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html

I would like to produce something like this:

``` json
"/usuarios-vendedor/{cpf}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "cpf",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/Empty"
            }
          }
        },
        "x-amazon-apigateway-integration": {
          "responses": {
            "default": {
              "statusCode": "200"
            }
          },
          "requestParameters": {
            "integration.request.path.cpf": "method.request.path.cpf"
          },
          "uri": "https://api.dynamicssales.com.br/api/v1/usuarios-vendedor/{cpf}",
          "passthroughBehavior": "when_no_match",
          "httpMethod": "GET",
          "type": "http"
        }
      }
    }
```

**Comment by bfanger** [comment]
Yes, swagger-php supports extensions, see #333 for an example.

Is also possible to create your own annotations and inject them into the swagger-php pipeline. It's not easy to do, but would improve the documentation experience with AWS.

**Comment by aluferraz** [comment]
Hello @bfanger, thanks a lot for your reply ! 

In the example at #333 we have the output bellow : 

`"info": {
    "title": "Example",
    "version": 1,
    "x-some-name": "a-value",
    "x-another": 2
},
`
We have the "x-some-name" parameter inside of an Info session. But actually I need to generate the follwing output:

` "x-amazon-apigateway-integration": {
          "responses": {
            "default": {
              "statusCode": "200"
            }
          },
          "requestParameters": {
            "integration.request.path.cpf": "method.request.path.cpf"
          },
          "uri": "https://api.dynamicssales.com.br/api/v1/usuarios-vendedor/{cpf}",
          "passthroughBehavior": "when_no_match",
          "httpMethod": "GET",
          "type": "http"
        }`

I need to create somehow a "x-amazon-apigateway-integration" session.. The only way to do that is to create my own annotations ?

Thanks a lot !

**Comment by bfanger** [comment]
No custom annotations are required, to generate the snippet in your example, write the docblock like this:

```php
/**
 * @SWG\Path(
 *   path="/usuarios-vendedor/{cpf}",
 *	 x={"amazon-apigateway-integration": { 
 *  	 "responses": {
 *       "default": {
 *         "statusCode": "200" 
 *       }
 *     }, 
 *     "requestParameters": { 
 *       "integration.request.path.cpf": "method.request.path.cpf" 
 *     }, 
 *     "uri": "https://api.dynamicssales.com.br/api/v1/usuarios-vendedor/{cpf}",
 *     "passthroughBehavior": "when_no_match",
 *     "httpMethod": "GET",
 *     "type": "http" 
 *   }},
 *   @SWG\Get(
 *      @SWG\Parameter(name="cpf", in="path",required=true, type="string"),
 *      produces={"application/json"},
 *      @SWG\Response(
 *        response=200, 
 *        description="200 response",
 *        @SWG\Schema(ref="#/definitions/Empty")
 *      )
 *   )
 * )
 */
```
