### ISSUE TITLE
Custom Annotations

### ISSUE THREAD

**Issue by dbsr** [zircote/swagger-php#343]
Hi,

I have written some custom annotations which are  intended to avoid writing the same swagger definitions over and over again.

For example we've recently implemented HAL and I have extended the `\Swagger\Annotations\Property` annotation which allows me to use:

`@SWG\EmbeddedProperty(resources={"territories" = "#/definitions/Territory"})`

which (thanks to some very hacky code) results in:

```
{
    "swagger": "2.0",
    "paths": {},
    "definitions": {
        "Product": {
            "properties": {
                "_embedded": {
                    "type": "object",
                    "properties": {
                        "territories": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Territory"
                            }
                        }
                    }
                }
            },
            "type": "object"
        }
    }
}
```

I can enable this custom annotation by bootstrapping a php file which first requires all the necesarry swagger annotations and after that requiring the custom annotation class itself.

I was wondering if there is a better method to implement custom annotations.

Thanks a lot for your great work!

**Comment by bfanger** [comment]
You can use your own namespace and let Composer do some of the autoloading.
In the php comments, you'd then use `@Dsbr\ EmbeddedProperty()` for example.

But some bootstrapping will always be required to add your namespace to the [Analyser::$whitelist](https://github.com/zircote/swagger-php/blob/master/src/Analyser.php#L38) or write your own [AnnotationRegistry::registerLoader](
https://github.com/zircote/swagger-php/blob/master/src/Analyser.php#L14) and you'd probably also need to patch some Annotation::$_nested arrays.

I've you know technique or pattern to make custom annotation easier let me know.
