### ISSUE TITLE
define constant error

### ISSUE THREAD

**Issue by jacobcyl** [zircote/swagger-php#346]
when I use : define("API_HOST", "localhost");
It comes the error: [Semantical Error] Couldn't find constant API_HOST

**Comment by bfanger** [comment]
That means you are using `API_HOST` before php has executed `define("API_HOST", "localhost");`

swagger-php **parses** your php scripts, but doesn't _execute_ them.

If you're using the command line add the `--bootstrap` options. 
`$ swagger --bootstrap my-constants.php my-project`

If you're calling swagger from code, make sure you've included the php file that declares the constant before calling any swagger functions.
