### ISSUE TITLE
Proposal for annotations inheritance

### ISSUE THREAD

**Issue by mitalcoi** [zircote/swagger-php#348]
There is one great feature that is really needed in a large application - parser should parse annotations not only in target class, but also in class it is extending. Example:

```php
namespace swagger\definitions\job;

use swagger\definitions\BaseDefinition;

/**
 * @SWG\Definition(definition="JobDashboardResponse")
 */
class JobDashboardResponse extends BaseDefinition
{
    /**
     * @var array
     * @SWG\Property(@SWG\Items(ref="#/definitions/JobItem"))
     */
    public $items;
} 
```
And:
```php
namespace swagger\definitions;

/**
 * @SWG\Definition(definition="BaseDefinition")
 */
class BaseDefinition
{
    /**
     * @var object
     * @SWG\Property()
     */
    public $_links;

    /**
     * @var object
     * @SWG\Property()
     */
    public $_meta;

    /**
     * @var object
     * @SWG\Property()
     */
    public $_labels;
} 
```

**Comment by bfanger** [comment]
This is what the [InheritProperties processor](https://github.com/zircote/swagger-php/blob/master/src/Processors/InheritProperties.php) is suppose to do.

Could you provide a testcase when it fails to detect the inheritance?

**Comment by mitalcoi** [comment]
Seems good, but I don't understand how use it :)

**Comment by jfiala** [comment]
@bfanger IMHO the inheritance works (the properties are merged from the parent into the child in one single model).
However, the required attribute from the Definition is not merged from the parent, so it has to be defined in both the parent and in the child (for the parent as well).
It would be great if the required-Attribute is merged as well.
Pls let me know if I should open a separate issue for this?

**Comment by bfanger** [comment]
I'd prefer a pull request. Make sure to set the required property to UNDEFINED, that makes it easy to check if the required value was set in the child class. And only inherit when it wasn't.

**Comment by jfiala** [comment]
In fact I think it would be a lot easier to defined the required at @SWG\Property, not at the @SWG\Definition. I know that in the swagger contract it is rendered that way, but usually I think it should belong to the property and only be rendered in the contract that way.
Then it would also be easy to override the required as necessary.

So for the easy solution I'm with you to have required at the Definition of the child class override the required attribute from the parent class.
Maybe for the future it would be nice to have required at the property level?

**Comment by jfiala** [comment]
As the whole required topic has nothing to do with the initial topic (that inheritance doesn't work in general, which it does actually), I'd suggest having a new issue for this and then have the PR on that?

**Comment by bfanger** [comment]
No new issue would have to be created, just create the PR. 
The PR may reference this issue, but that is optional as the PR should describe what it does.
