### ISSUE TITLE
url parameters with underscodes on Put method raises Exception: Unable to merge @SWG\Put()

### ISSUE THREAD

**Issue by vrubiella** [zircote/swagger-php#349]
```php
 Fine:
    /**
     * @SWG\Put(
     *
     *   path="/products/{product}/apps/{app}",
)
*/
Error "Unable to merge @SWG\Put()":
    /**
     * @SWG\Put(
     *
     *   path="/products/{id_product}/apps/{id_app}",
)
*/
```

Underscores on path parameters runs fine on other methods (POST for example)

**Comment by vrubiella** [comment]
Closing issue, sorry!, problem is related to duplicate "paths" to same method . I have two puts with same path defined.

**Comment by BenMorel** [comment]
Just encountered the same message, you saved me some debugging, thanks.
It would be nice to have a more explicit error message here, the current one is very confusing!
