### ISSUE TITLE
View Error 

### ISSUE THREAD

**Issue by rainying** [zircote/swagger-php#354]
I follow the example code.

but the result is not what I want.

I can not think of a solution.....

Why?

code

```
<?php

require("../vendor/autoload.php");
$swagger = Swagger\scan('document/test.yaml');
header('Content-Type: application/json');
echo $swagger;
```

view 

```
{
    "swagger": "2.0",
    "paths": {},
    "definitions": {}
}
```

**Comment by bfanger** [comment]
The purpose of swagger-php is to generate a swagger.json by extracting the annotations you've have added to your php code. But in your example you're scanning a yaml file.

If you've already created a swagger document and want to generate code look into the [swagger-codegen](https://github.com/swagger-api/swagger-codegen/)
