### ISSUE TITLE
composer install by Laravel project can not success

### ISSUE THREAD

**Issue by hbclare** [zircote/swagger-php#358]
my laravel vesion is 5.1
run script content:

Using version ^2.0 for zircote/swagger-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing symfony/finder (v3.2.1) Loading from cache
  - Installing doctrine/lexer (v1.0.1) Loading from cache
  - Installing doctrine/annotations (v1.3.1) Loading from cache
  - Installing zircote/swagger-php (2.0.8) Loading from cache
    Skipped installation of bin bin/swagger for package zircote/swagger-php: name conflicts with an existing file
Writing lock file
Generating autoload files
> php artisan clear-compiled
> php artisan optimize-separated

                                                
  [InvalidArgumentException]                    
  Command "optimize-separated" is not defined.  
                                                

Script php artisan optimize-separated handling the post-update-cmd event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by bfanger** [comment]
This is not a problem with swagger-php, but with laravel/composer. 

Looks like the artisan command "optimize-separated" has been removed. Remove or update the post-update-cmd hook in your composer.json
