### ISSUE TITLE
swagger.phar

### ISSUE THREAD

**Issue by gitstercode** [zircote/swagger-php#361]
Hi,
- In many  tutorials, people are specifying about swagger.phar in swagger-php directory.
- like http://blog.nbostech.com/2016/01/integrating-swagger-ui-for-php-application/#respond
http://www.slideshare.net/meshkorea/20141104-jongsunyi-swagger
- But I dont find swagger.phar in the repo.
- Please help me out an alternative way, or suggest me a tutorial that can guide me step-by-step.
- I am a newbie and trying to build swagger documentation for my legacy php controllers.

**Comment by bfanger** [comment]
swagger-php version 2.x no longer has a swagger.phar.
Building the phar for every release was tedious and didn't have an updating system.

`composer global require zircote/swagger-php`
Installs swagger-php cli to ~/.composer/bin/swagger

Composer offers an easy way to install, upgrade and uninstall.

I not aware of a step-by-step tutorial for v2, if you find/write one let me know I'll gladly link to it from the readme.

**Comment by gitstercode** [comment]
Thankyou, I was able to get it done.

**Comment by gitstercode** [comment]
Hi @bfanger , I created a simple quickstart page for beginners. You can find the page in this link https://gitstercode.github.io
