### ISSUE TITLE
How to handle different versions of APIs and their specs? 

### ISSUE THREAD

**Issue by nazarhussain** [zircote/swagger-php#362]
I am working on a Laravel project which exposing Swagger API specification. I want to know if there any mechanism that `swagger-php` support for handling multiple versions of APIs on path level and generate specs differently. So if we can call `/api/v1/spec.json` and `/api/v2/spec.json`

**Comment by bfanger** [comment]
No, nothing built-in, but if you can generate a big swagger.json containing both versions it should be trivial to split it based on path. It's just a json file.
