### ISSUE TITLE
How to escape the " (double quotes) character on Parameter Description

### ISSUE THREAD

**Issue by praditha** [zircote/swagger-php#363]
Hi all,
I have a question about writing description on swagger-php.
For example I have the following parameter description:
```
* ...
* @SWG\Parameter(
*          name="products",
*          in="formData",
*          type="string",
*          description="set of json from products eg:<br>'{ '0' : { 'id' : '1', 'sku' : 'SKU00614803', 'name' : 'Oncom Gondrong', 'image' : 'oncom.jpg', 'price' : '100000' }, '1' : { 'id' : '2', 'sku' : 'SKU00614804', 'name' : 'Tempe Bacem', 'image' : 'tempe.jpg', 'price' : '150000' }}'",
*          required=true
*      ),
* ...
```

I want to write the JSON sample to one of the parameter. Actually if I wrote the sample like above, the swagger can be generated successfully, but that is the wrong JSON format. JSON should be use `"` (double quotes) character instead of `'` (single quote).
But if I replace all the `'` to `"`, I cannot generate the swagger. I says an error: 

> [Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'id' in...

Anybody know how to solve my problem,.?

thanks

**Comment by bfanger** [comment]
Use `"` to escape a "

`<br>'{ ""id"" : 0,`

**Comment by wraycode** [comment]
how do you get rid of the backslash it adds to the example?
 example="{""code"":""3088"",""quantity"":""2""},{""code"":""3089"",""quantity"":""1""}",

ends up as

  "items": "{\"code\":\"3088\",\"quantity\":\"2\"},{\"code\":\"3089\",\"quantity\":\"1\"}"

**Comment by rwese** [comment]
I am running into the same issue.

Due to this the swagger ui generates the request like:
`{
  "query": {
    "params": "{ \"ci_id\": 12 }"
  }
}`

**Comment by zl-kolev** [comment]
Trying to put this string `<SchemaDefinition schemaRef="#/components/schemas/Order" />` inside a `description` to get a `yaml` output like this:
```yaml
description: |
    <SchemaDefinition schemaRef="#/components/schemas/Order" />
```
I'm escaping double quotes `"` by prefixing them with `\"` like this:
```
<SchemaDefinition schemaRef=\""#/components/schemas/Order\"" />
```
according to [this](https://yaml.org/spec/1.2/spec.html#id2787109) and I get this error:
```
@OA\Tag()->description is a "array", expecting a "string"
```
Anyone been through this?
