### ISSUE TITLE
Semver?

### ISSUE THREAD

**Issue by skyzyx** [zircote/swagger-php#367]
Does this project follow semantic versioning?

I ask because I noticed the release notes for [v2.0.9](https://github.com/zircote/swagger-php/releases/tag/2.0.9) included “…dropped support for PHP 5.5 and below”.

For people running 5.5.x, isn't this a breaking change? And if it's a breaking change, doesn't that mean the version should get bumped to 3.0? Alternatively, if a major version bump is unwarranted, shouldn't all versions of 2.x support the same versions of PHP?

Genuine question. Not sure how much you have/haven't thought about these implications.

**Comment by curry684** [comment]
No, it's not considered a breaking change. The `composer.json` was modified to require `php>=5.6`, thus not *breaking* things for users of older PHP versions, but simply stopping the upgrade path - they will remain stuck at `2.0.8`.

See the Semver definition, bullet 8:
> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API.

A change is only considered breaking if upgrading will cause historic code to no longer work, which isn't the case here.

**Comment by skyzyx** [comment]
Fair enough. Thanks for the explanation.
