### ISSUE TITLE
Enable github.com wiki

### ISSUE THREAD

**Issue by mbaynton** [zircote/swagger-php#368]
I'm looking for examples of some things not covered in Examples/. Some I'm finding in closed issues, some in tests, etc, but I'm thinking it might be really helpful to build up additional examples in the wiki. Could you consider enabling it on this repository?

**Comment by bfanger** [comment]
I think that would a good idea. We should then import the files from the docs folder into the wiki to avoid confusion.

@zircote what do you think?

**Comment by bfanger** [comment]
I've launched a new [documentation website](http://zircote.com/swagger-php/) which is generated from the markdown files in the [docs](https://github.com/zircote/swagger-php/tree/master/docs) folder.

If you feel documentation is missing, this is the place to add it.
