### ISSUE TITLE
Deserialize error with property contain "$", such as $ref

### ISSUE THREAD

**Issue by phuongmathy** [zircote/swagger-php#369]
use Swagger\Serializer;

$serializer = new Serializer();
$swagger = $serializer->deserialize($jsonString, 'Swagger\Annotations\Swagger');
echo $swagger;

Notice: Unexpected field "$ref" for @SWG\Schema(), expecting "ref", "title", "description", "maxProperties", "minProperties", "required", "properties", "type", "format", "items", "collectionFormat", "default", "maximum", "exclusiveMaximum", "minimum", "exclusiveMinimum", "maxLength", "minLength", "pattern", "maxItems", "minItems", "uniqueItems", "enum", "multipleOf", "discriminator", "readOnly", "xml", "externalDocs", "example", "allOf", "additionalProperties", "x" in \Swagger\Serializer->doDeserialize() in /vagrant/library/vendor/zircote/swagger-php/src/Serializer.php on line 98 in /vagrant/library/vendor/zircote/swagger-php/src/Logger.php on line 38

**Comment by ivoba** [comment]
should be fixed in https://github.com/zircote/swagger-php/commit/3e319bddbeae6cf76790c59474d081cfca0d1d03

**Comment by bfanger** [comment]
Fixed in v2.0.10
