### ISSUE TITLE
Parsing my annotations instead of swagger default ones?

### ISSUE THREAD

**Issue by dakorpar** [zircote/swagger-php#372]
I'm new to swagger, in what way should I look to be able to support my own annotations instead of swagger ones?
I have annotations that looks like:
```
	/**
	 * get product
	 * @method GET
         * @path products/{id}
	 * @param int $id
	 * @return MyNamespace\ProductEntity|MyNamespace\ErrorResponse
	 */
```
So I have all info needed here to generate json, but in different format then swagger requires, is it possible to customize this, or should I write my own processor that will generate json file from this?
I found this much more readable then default swagger annotations....

**Comment by bfanger** [comment]
Nice syntax, we would like that as an optional alternative syntax.

Looking forward to your processor.

**Comment by dakorpar** [comment]
Since in it is to hard to create it generic I made a support only for mine project so it's locked with my project. Don't really have time to do it properly for everyone
