### ISSUE TITLE
Missing definitions not detected

### ISSUE THREAD

**Issue by monzol** [zircote/swagger-php#373]
Thanks for sharing this lib.

One problem I bumped into: 
If I have a reference to a definition that doesn't exist, the processor will not detect this and won't issue a warning or error.

For example, I have the following annotation for property $images inside a Product class:
```
    /**
     * @SWG\Property(
     *     type="array",
     *     @SWG\Items(ref="#/definitions/productImage")
     * )
     */
     public $images;
```

But the image class is called ProductImage (uppercase 'P'), so the definition will be 
```
"definitions": {
    ...
    "ProductImage" : {
        ...
    }
    ...
}
```

But it's not just a case sensitivity issue. I tried with different names or even removing all the annotations from the ProductImage class and the processor completes without an error.

Is this a bug or a feature waiting to be implemented?

**Comment by bfanger** [comment]
The next version (2.0.11) will validate internal references. b7a0fb0989cc686f85191763cd3f0fbbb3a0f627

Thanks for the suggestion.
