### ISSUE TITLE
Swg\Property - redefine enum in subclass

### ISSUE THREAD

**Issue by jfiala** [zircote/swagger-php#377]
Release: swagger-php 2.0.9

(How) is it possible to redefine the enum values for a SWG\Property without redefining the property itself?

``` php
/**
 *
 * @SWG\Definition(description="Generic Response", required={"statusCode"})
 */
class GenericResponse
{
 /**
    * @SWG\Property(type="string",enum={"SUCCESS", "ERROR"},description="Status-Code")
    */
    private $statusCode;
...
}
``` 

Currently it seems it is necessary to override the property to use custom subclass enum values:
``` php
/**
 *
 * @SWG\Definition(description="Generic Response Subclass ")
 */
class GenericSubResponse extends GenericResponse
{
 /**
    * @SWG\Property(type="string",enum={"SUCCESS", "ERROR", "CUSTOM_SUB_ERROR"},description="Status-Code for GenericSubResponse ")
    */
// the statusCode itself has to redefined to be able to attach the custon enumeration values?
    private $statusCode;
...
}
``` 
Or is there another solution?

**Comment by bfanger** [comment]
You can add the @SWG\Property() inside the @SWG\Definition() annotation, that way you don't need another php property. 
You might even reuse the setting of the original by using ref

**Comment by jfiala** [comment]
Thanks for the hint, that nearly did it.
The @SWG\Property has to be added after the @SWG\Definition.

This is the working solution (swagger-php 2.0.9):
```php 
/**
 *
 * @SWG\Definition(description="Generic Response Subclass "),
 * @SWG\Property(property="statusCode",type="string",enum={"SUCCESS", "ERROR",   "CUSTOM_SUB_ERROR"},description="Status-Code for GenericSubResponse ")
 */
class GenericSubResponse extends GenericResponse
{
  // statusCode has no longer to be redefined.
}
```

The following points could be improved:
* type and description have to be defined again, they are not merged from the parent
* All enum values have to be enumerated, they are not merged from the parent

**Comment by bfanger** [comment]
There is no "one-size-fits-all" solution for how inheritance in php will affect the rest api.
So redefining them without automatic merging is the safest and predicable way.
