### ISSUE TITLE
--quick option

### ISSUE THREAD

**Issue by okneloper** [zircote/swagger-php#379]
Can a `--quick` command line option or something similar be added that would only parse the files that were parsed previously or even files that were modified since?

This would substantially speed up documentation development.

**Comment by bfanger** [comment]
Technicly possible, the annotation objects already have a _context object which contains the filename.

if you'd write a pull request which implement this feature I'll gladly merge it.

**Comment by okneloper** [comment]
Yeah, realized I was doing exactly that - scan included the vendor forlder. 

Actually it runs pretty quick when properly configured with paths and excludes. 

No need for this option, sorry.

Btw, the help message doesn't state you can include multiple paths.

**Comment by bravo-kernel** [comment]
@okneloper feel free to PR a better message

**Comment by okneloper** [comment]
Sure, no problem
