### ISSUE TITLE
Dynamic host

### ISSUE THREAD

**Issue by okneloper** [zircote/swagger-php#383]
Since it's all (definitions) are written in comments, I am hardcoding the `host` property of the root Swagger definition (ie API host) and swagger ui makes requests to that URL. I would like to test swagger on my local environment. Is there a way to dynamically define the host?

If I remove the host property, swagger ui seems to use the domain, but not sure how this will work with swagger ui hosted elsewhere and swagger.json does not seem to validate because of this.

**Comment by oliver-ignitiondigital** [comment]
You could define a constant based on the environment, e.g. `define("SWAGGER_API_HOST", "your.current.host");` and then use that in the definition: `host=SWAGGER_API_HOST,`
