### ISSUE TITLE
Add support for OpenAPI 3.0

### ISSUE THREAD

**Issue by prodikl** [zircote/swagger-php#384]
Hey there,

I'm not sure if this is in the works already but after reading this post: 
https://blog.readme.io/an-example-filled-guide-to-swagger-3-2/

I wanted to add an issue regarding support for OpenAPI / Swagger 3.0.

Specifically, the HATEOAS implementation would be very helpful for my team.

Please let me know if any work has started on this already, otherwise I'd be happy to fork and start contributing.

Thanks in advance

**Comment by bfanger** [comment]
I'm not working on this. community contributions are welcome.

**Comment by morsok** [comment]
Hello there,

We also use swagger-php and would really need the 3.0 support of anyOf and oneOf keywords, how could we help implement that ? Did you start working on it @prodikl ?

**Comment by bfanger** [comment]
I've **not** started working on this, but I've made a [3.x branch](https://github.com/zircote/swagger-php/tree/3.x) to make contributions easier, as a target for future pull-requests.

The branch includes the oneOf & anyOf patch from  @morsok and I've done some basic find-and-replace-all stuff.

I think creating pull requests to 3.x and mentioning this issue is nice way to bundle the community efforts.

To try it out as-is: `composer require zircote/swagger-php 3.x-dev`

**Comment by prodikl** [comment]
@morsok Hey so I just kept on using swagger-php 2.0.x with swagger-ui v3.0.x

I'm not attempting to use anyOf or oneOf, just using allOf for my composite models. 

Sorry I can't be of more help!

**Comment by ricardovanlaarhoven** [comment]
My API works except the security schema.
when pressing execute its not sending the header autorizations with the request.

` *     @SWG\SecurityScheme(
 *         securityDefinition="Bearer",
 *         type="apiKey",
 *         name="Authorization",
 *         in="header"
 *     ),`

**Comment by ricardovanlaarhoven** [comment]
My API works except the security schema.
when pressing execute its not sending the header autorizations with the request.

@SWG\SecurityScheme( securityDefinition="Bearer", type="apiKey", name="Authorization", in="header" ),

or @bfanger am i doing something wrong in my annotation?

**Comment by bfanger** [comment]
@ricardovanlaarhoven  In [v3.0](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#components-object) it's `securitySchemes` while swagger-php hasn't been updated and still generates `securityDefinitions`.

Go make it work and create pull requests to projects where it doesn't work according to the (draft/proposed) specification. ;)

**Comment by danydev** [comment]
Hey guys, is there a list of TODO items before we can have 3.0 released?

**Comment by davidsoderberg** [comment]
Hey, when will 3.0 be released?

**Comment by bfanger** [comment]
It will be released when it can generate json files compatible with the 3.0 spec.

Work on swagger-php is not “planned”. Start contributing to the 3.x branch to make swagger-php 3.0 release a reality

**Comment by davidsoderberg** [comment]
👍 do you have a todo list for 3.x branch?

**Comment by bfanger** [comment]
Not a list, try to generate one of the [v3 examples](
https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v3.0) or start using v3 in a project and implement what is missing.

I’ve implemented and [unittested](https://github.com/zircote/swagger-php/blob/3.x/tests/ExamplesTest.php) the link-example.

**Comment by bfanger** [comment]
Thanks to great work done by @sonrac the 3.x branch is in good shape, try it out and report issues if you'll find any.

**Comment by ddanielroche** [comment]
Can launch an alpha version to be able to test it in [lichunqiang/yii2-swagger](https://github.com/lichunqiang/yii2-swagger)

**Comment by bambamboole** [comment]
Any news on the 3.0 release?

**Comment by bfanger** [comment]
It is ready, i think i've made all the breaking changes i wanted to make

I've changed a lot the last few days. So i'm keeping an eye on the PR/issues this week and then release v3
