### ISSUE TITLE
swagger API versionning

### ISSUE THREAD

**Issue by FirasGL** [zircote/swagger-php#388]
Hello,
I am working on improving a swagger documentation with Symfony, and I want to know how I can handle the versioning of the API. 
Thank you

**Comment by AdrienCS** [comment]
That would be great.

**Comment by bfanger** [comment]
"API versioning" is a broad and complex problem space.
http://stackoverflow.com/questions/389169/best-practices-for-api-versioning is closed as "primarily opinion-based" for a reason.

**swagger-php** only job is to generate the latest documentation based on the annotations it finds in the php-code.
How you want to solve the versioning is up to you.
