### ISSUE TITLE
Add support for email", "uuid", etc.,  Types.

### ISSUE THREAD

**Issue by druidamix** [zircote/swagger-php#389]
Hello,

I tried using uuid, however it gives an error.

Would be possible add some of those types?
Thanks.

Swagger documentation says:

Primitives have an optional modifier property format. Swagger uses several known formats to more finely define the data type being used. However, the format property is an open string-valued property, and can have any value to support documentation needs. Formats such as "email", "uuid", etc., can be used even though they are not defined by this specification. Types that are not accompanied by a format property follow their definition from the JSON Schema (except for file type which is defined above).

**Comment by bfanger** [comment]
I've just tried:

```php
 * @SWG\Parameter(
 *   name="id",
 *   in="path",
 *   type="string",
 *   format="uuid"
 * )
```
And it generated a swagger.json without any errors.
