### ISSUE TITLE
Groups support for different model views

### ISSUE THREAD

**Issue by pietervogelaar** [zircote/swagger-php#39]
I'm currently working for a company that uses Symfony 2 for its API. They also use the JMSSerializerBundle to serialize the response, but to also support different views for an entity: 
http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#creating-different-views-of-your-objects

Let me explain this better with the following example for Doctrine entities. A entity Car has a OneToMany association with the enity Part. With the API "/cars/1.json" I want to ->find() Car entity with ID one that also fetched al its childs like the Part entity. The Car entity can be put in the serializer and it will be returned. The controller for "/cars/1.json" will set the groups "Car" and "CarDetails". Because the Car entity has properties with @SER\Groups("Car") annotation and the Part entity has properties with the @SER\Groups("CarDetails") annotation, they will be returned both in the response.

But lets say we want to show a list of cars with the API call "/cars.json". Then we only want to display the car name and some other fields, but not all parts. So the controller action that handles that call with set only the group "Car" on the serializer, so only the entities and their properties that have this group will be returned.

At the moment the discoverer of swagger-php doesn't support this. It would be awesome if besides the responseClass attribute a responseGroups attribute could be added that can contain multiple values. A groups attribute could be added to a model property, to include this property of this model only if the API controller action has this Model ID as responseClass but also corresponding responseGroups.

Because models are reused in Swagger UI over mulitple APIs and we want to use the same model with different views, I'm not sure yet about how to implement this.

I hope you understand the issue and have some genius input on this :) Let me know what you think!

**Comment by bravo-kernel** [comment]
:+1:

**Comment by ketseran** [comment]
+1

**Comment by michellesanver** [comment]
Is this something that is still in the planning? If not, it could be something I could possibly contribute. I like this library but this is a possible deal breaker for using it in most API's I write that include serializer groups.

**Comment by bravo-kernel** [comment]
I've been following this group for quite some time now and have not seen anything indicating any plans @michellesanver but PRs are actively being merged so I would say "go for it". Maybe @bfanger can confirm.

**Comment by aminal** [comment]
+1

**Comment by michellesanver** [comment]
Sorry I haven't acted on this, I do not have time at the moment (expecting a baby in 3 - 4 weeks and it's taking all my energy). If someone else wants to do this, that'd be cool. 

We found a workaround for now that works in our specific application (models are not always 100% correct at the moment but not the end of the world)

**Comment by makanikki** [comment]
+1

**Comment by ThibautAlgrin** [comment]
+1

**Comment by DanielBragg817** [comment]
+1

**Comment by jokersoft** [comment]
+1

**Comment by thebitrock** [comment]
+1

**Comment by dmitry-pro** [comment]
+1

**Comment by bfanger** [comment]
A lot can be solved with $refs and [model composition](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/)

Adding an additional grouping / splitting system will complicate using swagger-php.
The better the annotations map to the output, the simpler it is to write and debug those annotations.

Feel free to experiment and create a swagger-php plugin, i'll gladly add that to the [related projects](http://zircote.com/swagger-php/Related-projects.html) page
