### ISSUE TITLE
Merge few directories

### ISSUE THREAD

**Issue by wojcikcp** [zircote/swagger-php#391]
Is there any possibility to merge an json from few directories? E.g. I want to separate dirs for Mobile and Web APIs and both of them has in the same parent folder. When I use `merge`, there is some error about `@Info` missing.

**Comment by bfanger** [comment]
You can scan multiple directories at once, no manual merging is required.

**Comment by wojcikcp** [comment]
Thank you for response. Can you provide some code example of it? Should it be in placed in the annotations 'path' property?

**Comment by bfanger** [comment]
`Swagger\scan(['path/to/webapi', '/path/to/mobile'])`

But one directory must contain the `@SWG\Info()` annotation.

**Comment by wojcikcp** [comment]
Thank you very much. It works perfectly.
