### ISSUE TITLE
[tool] A little something to make Definition writing easier

### ISSUE THREAD

**Issue by AaronJan** [zircote/swagger-php#400]
I had lots of complex `Definitions` in my projects, writing them is a huge pain for me (especially the `Example` part). 

So I wrote a little tool to ease that pain for me, and now I made it as an open-source project named [Kobe](https://github.com/AaronJan/Kobe). It only handle the `Definitions` part in `Swagger` response, must be used with `swagger-php` basically.

Advertise it here may not be appropriate 😉 , but it helped me. And I think it may help other people who using `swagger-php`.

The goal is to make `Swagger` writing easier, let's discuss it !

**Comment by bfanger** [comment]
Thanks i've added it to the [Related projects](https://github.com/zircote/swagger-php/blob/master/docs/Related-projects.md) page.
