### ISSUE TITLE
How to define a dynamic object key?

### ISSUE THREAD

**Issue by WenXuanYuan** [zircote/swagger-php#401]
I want to create a api for order, I post the shopping cart data as cart like this:
<pre>
{
    sku_id: order_quantity,
    ....,
}

example:
cart: {
    23: 1,
    34: 2
},
</pre>

The sku_id represent product id, order_quantity means the number user want to book. And I write my swagger code like this.
<pre>
@SWG\Parameter(
    name="cart",
    description="cart data",
    type="object",
    required=true,
    ??? How to define the object key here?
)
</pre>
Would you please teach me How to define the object key? Thank you.

**Comment by bfanger** [comment]
The JSON spec has [patternProperties](https://spacetelescope.github.io/understanding-json-schema/reference/object.html#pattern-properties)

But this isn't supported in the [Swagger v2.0 specification](http://swagger.io/specification/).

If you change the request into:
```json
"cart":[
  { "product_id": 23, "amount": 1 },
  { "product_id": 34, "amount": 2 }
]
```
You'd be able to document that with:
```php
* @SWG\Parameter(
 *   name="body",
 *   in="body",
 *   description="cart data",
 *   required=true,
 *   @SWG\Schema(
 *       type="object",
 *       @SWG\Property(
 *         property="cart",
 *         type="array",
 *         @SWG\Items(
 *           type="object",
 *           @SWG\Property(property="product_id", type="integer"),
 *           @SWG\Property(property="amount", type="integer")
 *         )
 *       )
 *     )
 *   )
 * ),
```

**Comment by WenXuanYuan** [comment]
@bfanger I know how to do now, thank you.

**Comment by erickhuang17** [comment]
@WenXuanYuan How do you solve this problem?

**Comment by WenXuanYuan** [comment]
Changed object model
