### ISSUE TITLE
Non-required parameter property in Parameter object

### ISSUE THREAD

**Issue by foxycode** [zircote/swagger-php#405]
I have many listing methods in API, each with same `fields` query parameter but with different enum values:

```
/**
 * @var array
 *
 * @SWG\Parameter(
 *     parameter="affilFormLeadsFields",
 *     name="fields",
 *     in="query",
 *     description="A list of fields to return.",
 *     required=false,
 *     type="array",
 *     items=@SWG\Items(
 *         type="string",
 *         enum={"id", "campaignId", "bannerId", "publisherId", "dateCreated", "data"}
 *     )
 * )
 */
public $fields;
```

I need to add `parameter` property to `@SWG\Parameter` on eaach of them, or notice is returned:
```
@SWG\Parameter(name="fields",in="query") is missing key-field: "parameter" in \App\ApiV2Module\Validators\AffilFormsDefaultValidator->fields in /home/liquid/projects/ehub/api/app/ApiV2Module/Presenters/..//Validators/AffilFormsDefaultValidator.php on line 26
```

I believe it is because you make global definitions from each parameter, but is isn't needed for this use case. Would it be possible to use `@SWG\Parameter` without `parameter` property?

**Comment by haydenk** [comment]
@foxycode Did you ever find a workaround for this other than having to actually add the parameter key?

Nelmio API Doc bundle apparently doesn't bother creating the key in the annotation and I have 250 controllers with at least two actions this would need to be added to.

**Comment by foxycode** [comment]
@haydenk No, I don't have other workaround than having all parameters named, which is nonsense for me. I am still using my own implementation on most of my apps.

**Comment by bfanger** [comment]
Parameters inside an operation or path don't need the parameter key. But documenting them outside does, that way you can reference them with ref="#/parameters/affilFormLeadFields" inside a path or operation.

What's the use-case here?

**Comment by haydenk** [comment]
@bfanger Really, I was just looking for the proper way to setup the annotations. When I was using it with the Nelmio API Doc Bundle, it was getting the error about the missing key field. I've since moved on to using this library on its own, I suspect nelmio isn't using it properly.

**Comment by foxycode** [comment]
@bfanger It's not my use case. I have it inside path:

```php
/**
 * @SWG\Get(
 *     path="/campaigns",
 *     summary="Get campaign list",
 *     description="The campaigns endpoint returns list of all campaigns that could be viewed by user.",
 *     externalDocs=@SWG\ExternalDocumentation(
 *         url="http://docs.ehub.apiary.io/#reference/0/get-campaign-list/get-campaign-list"
 *     ),
 *     responses={
 *         @SWG\Response(
 *             response=200,
 *             description="Campaign list",
 *             schema=@SWG\Schema(ref="#/definitions/Campaigns")
 *         )
 *     }
 * )
 */
final class CampaignsDefaultValidator extends AbstractValidator
{
    /**
     * @var array
     *
     * @SWG\Parameter(
     *     parameter="CampaignsFields",
     *     name="fields",
     *     in="query",
     *     description="A list of fields to return.",
     *     required=false,
     *     type="array",
     *     items=@SWG\Items(
     *         type="string",
     *         enum={"id", "type", "status", "name", "description", "dateInserted", "cookieLifetime"}
     *     )
     * )
     */
    public $fields;
}
```

**Comment by foxycode** [comment]
@sonrac Thanks fot the tip.
