### ISSUE TITLE
Add definition to all requests

### ISSUE THREAD

**Issue by hpatoio** [zircote/swagger-php#409]
I need to add a group of propretary headers to all requests. At the moment I add a block like

```
     *     @SWG\Parameter(
     *         ref="#/parameters/X-Version",
     *     ),
     *     @SWG\Parameter(
     *         ref="#/parameters/X-Currency",
     *     ),
``` 

This is very verbose and not easily maintainable. I'm wondering if is possible to add an annotation like

```
     *     @SWG\GlobalParameter
``` 

That basically add a set of definitions to an endpoint.

**Comment by bfanger** [comment]
Yes, it should be possible to to create your own annotation which generates regular swagger annotations by building a processor.

For example `@MyCompany\DefaultHeaders()`

Sadly, although swagger-php allows third-party processors and annotations, it isn't documented and I don't know of any examples.
Let me know if you encounter any issues.

**Comment by naffan2014** [comment]
he want to add definition to all requests. not ask if can create his own annotation.
