### ISSUE TITLE
PHP DOC Annotations are not getting used for generating swagger doc

### ISSUE THREAD

**Issue by jitenderrawal** [zircote/swagger-php#410]
I have existing project with phpdoc annotations but they are completely ignored and only if i add doctrine annotation in the form of @SWG that the document is getting generated,.

**Comment by bfanger** [comment]
Could you elaborate, please provide:
1. What you did.
2. What happend
3. What you expected to happen.

I'm confused about what you mean with "form of @swg"  and what form you used before.

**Comment by jitenderrawal** [comment]
Hi @bfanger ,

We already have a project with PHP Doc Annotation in our code. We want to leverage existing annotation so that we can avoid rewriting all annotation. Here is a sample of what we have in our code.

 /**
     * getByName
     * Returns static text details for an AOP
     *
     * @param string name Name of AOP to search for
     * @return void
     */

I installed swagger-php and tried to generate the doc but it is not parsing the above annotations. Just to test i added doctrine type annotation and then it worked.  Here is a sample of what i added and then it worked. I wanted to know if php doc annotations are supported and if yes then am i missing any config setting to make it work. We just want to avoid annotating all the endpoints again with new format

This worked

@SWG\Swagger(
 *     schemes={"http"},
 *     host="api.company.com",
 *     basePath="/v3")

Also, Since we using Laravel we choose to use https://github.com/DarkaOnLine/L5-Swagger which in turn is using swagger-php. 

Please let me know if any thing is not clear. Thanks again!

**Comment by bfanger** [comment]
Ignoring docblocks without @swg annotations is the expected behavior, this is by-design.
To generate swagger documentation you'll have to write specific annotations in a specific way.

swagger-php expects you to annotate the endpoints again, but is extendable to allow for custom annotations, but then you're basically building your own swagger-library.
Maybe `L5-Swagger` can help, but that is outside the scope of the swagger-php project.

**Comment by wapmorgan** [comment]
But in project readme: _Extracts information from code & existing phpdoc annotations._
Does this mean specific **swg** annotations only?

**Comment by wapmorgan** [comment]
I've written simple converter for my project, this is really very project-specific work.

**Comment by wapmorgan** [comment]
I thinking about writing a converter, with fully configurable interface to make it possible use it on your project with it's specific. 
Does anyone find this useful library?

**Comment by ap-coder** [comment]
> I've written simple converter for my project, this is really very project-specific work.

Can you please share your converter?

**Comment by wapmorgan** [comment]
@ap-coder Yes, ofc.
It needs a CodeScraper (exist for Yii2 and Slim) for your project before usage.

 https://github.com/wapmorgan/OpenApiGenerator
