### ISSUE TITLE
adding x-nullable to property doesn't work

### ISSUE THREAD

**Issue by El-Sam** [zircote/swagger-php#411]
Hi, I have this integer property which can be null : 
```php
 /** 
 * @SWG\Property(minimum=0)
 * @var int
 */
 private $subscribed;
```
and I found that the AbstractAnnotation annotation has the **x**, How can I use it to have **x-nullable=true** added to the property when generating the swagger.json file.

any help ?

**Comment by bfanger** [comment]
Properties starting with `x-` or ["Extension properties"](https://github.com/zircote/swagger-php/blob/master/docs/Getting-started.md#vendor-extensions) are supported in swagger-php:

```php
/**
 * @SWG\Property(
 *   minimum=0,
 *   x={"nullable": true}
 * )
 */
```

**Comment by El-Sam** [comment]
:+1: Thank you for supporting these extensions. It worked.
