### ISSUE TITLE
Problem with dapperdox constants

### ISSUE THREAD

**Issue by pvermeil** [zircote/swagger-php#412]
Hello everyone.
I just added dapperdox-specific values to my swagger-php annotations, but when running swagger in CLI I have the following output  : 
[WARN] [Semantical Error] Couldn't find constant x, /home/httpd/retention/www/public/index.php on line 68.

Here is my head documentation : 
https://pastebin.com/fP3RwjZV
(I don't know how to cleanly paste PHP syntax right here :) )
I suppose that my CLI swagger tool in vendor isn't recognizing the constants like x-navigateMethodsByName=true, but I need it to generate a json that is suitable for dapperdox integration. Dapperdox is about presenting your API specs in a nice UI with menus and all.

Otherwise I'll have to touch the JSON after it was generated from annotation, which is dirtier. What to do ? Thanks for your time ! :+1:

**Comment by bfanger** [comment]
You can't use `-` in a propertyName of an annotation. 
swagger-php does support generating `x-` properties check the [vendor-extensions docs](https://github.com/zircote/swagger-php/blob/master/docs/Getting-started.md#vendor-extensions)

**Comment by pvermeil** [comment]
Thanks for the hint !
