### ISSUE TITLE
How to translate Example object in annotation ?

### ISSUE THREAD

**Issue by pvermeil** [zircote/swagger-php#416]
Hello to the team :)
Everything is in the title. I checked getting started guide here : 
https://github.com/zircote/swagger-php/blob/e6dc561e4d17ab94146920b663e7d34d4ab9bf9a/docs/Getting-started.md

I have seen annotation available here : https://bfanger.nl/swagger-explained/

And of course the Swagger specification, but I can't find how to have example fields right from PHP annotations to avoid touching the JSON after it was generated. This is for payload and response examples purpose. Thanks a lot.

**Comment by sevameyer** [comment]
I have the same question. Any solution?

**Comment by almost-online** [comment]
```php
define('MY_EXAMPLE', Translator::translate('my example'));
/**
 * @SWG\Property(property="my_property", example=MY_EXAMPLE)
 */

```
