### ISSUE TITLE
Annotation to specify request and response body

### ISSUE THREAD

**Issue by jake142** [zircote/swagger-php#417]
Is there an annotation to use if I want to just specify the request and response body (json data) instead of using definitions in my model?

What I aim for is the possibillity to paste a json string in the annotation as request and response body.

**Comment by bfanger** [comment]
Using models ( `@SWG\Definition()` ) is optional, but you can't paste a json-string as request or response. 

You still need to describe these using swagger's DSL: 
```
@SWG\Schema(
    type="object",
    @SWG\Property(...)
)` etc.
