### ISSUE TITLE
Error with doctrine/annotations (v1.5)

### ISSUE THREAD

**Issue by CesarCasanova** [zircote/swagger-php#419]
New Version of doctrine/annotation (1.5) is generating some problems with the json generation of this library:
`EXCEPTION] Return value of Doctrine\Common\Annotations\AnnotationRegistry::registerLoader() must be an instance of Doctrine\Common\Annotations\void, none returned in /apps/neoauto.concessionaire.com/app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 117`

I suggest use the previous version of that library in your composer.json: 1.4; I tried with that version and this error does not occur

**Comment by bfanger** [comment]
I'm not experiencing this issue on `PHP 7.1.7` on macOS 10.12.6

https://travis-ci.org/zircote/swagger-php/builds/257931704 also looks good, are you also running composer with `--ignore-platform-reqs` ?

**Comment by jaccborn** [comment]
hello, guys , i have the same question when i  run  composer update, the exception:
Type error: Return value of Doctrine\Common\Annotations\AnnotationRegistry::registerLoader() must be an instance of Doctrine\Common\Annotations\void, none returned
I guess it's because the upgrade causes the problem。and i run composer require doctrine/annotations:1.4   the problem is soloved, thanks.

**Comment by fgreinus** [comment]
Maybe forcing a specific version of the doctrine/annotation would be better here. Because when you take a look at any statistics on which versions of php are used, php7.1 is not heavily adopted (for now).

**Comment by mpajunen** [comment]
Forcing a specific version is not a great fix, as it would actually prevent anyone from using newer version of Annotations with swagger-php. As has been mentioned, that by itself is no problem.

There are at least two ways to prevent the problem in your project:

1. Configure your PHP version properly and don't use `--ignore-platform-reqs`.
1. Use a specific version of Annotations in your project.
