### ISSUE TITLE
How do I use the JSON parameter

### ISSUE THREAD

**Issue by ownfire** [zircote/swagger-php#421]
I want to parse such a URL:
`http://www.domain.com/query/uri?abc=1321&params={"start":0, "perpage":15, "role_id":135}&bcd=sdfjio`

so i want to use like this
```
/**
 *     @SWG\Parameter(
 *         name="params",
 *         in="query",
 *         description="json params",
 *         required=true,
 *         type=json,
 *         default={"start":0, "perpage":15, "role_id":135}
 *     ),
 */

```
In fact, how should I use it to achieve that results?
does it support?

**Comment by bfanger** [comment]
A parameter with `in="query"` (any value other than "body") has [restrictions on the type](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject). But you can specify a [non-standard format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#dataTypeFormat).

`type="string", format="json"`

But you won't get any additional support, as far as swagger is concerned it's just a string

**Comment by kamil-kielczewski** [comment]
I have similar problem - with escape in square brackets :(

https://stackoverflow.com/questions/47566656/escape-character-for-sqare-brackets-in-php-swagger-annotation-json-property
