### ISSUE TITLE
string type

### ISSUE THREAD

**Issue by xralphack** [zircote/swagger-php#425]
I used swagger-php with laravel

```
    /**
     *
     * @SWG\Post(path="/api/v1/article",
     *   tags={"article"},
     *   summary="title",
     *   @SWG\Parameter(
     *     in="formData",
     *     name="title",
     *     type="string",
     *     description="title for article",
     *   ),
     *   @SWG\Response(response="default", description="success")
     * )
     */
```
after submit 

SQLSTATE[HY000] [2002] Connection refused (SQL: insert into `article` (`title`, `updated_at`, `created_at`) values (11111, 2017-08-09 10:09:15, 2017-08-09 10:09:15))

why string type not work, anyone can help?

**Comment by bfanger** [comment]
That's a database error, swagger-php **doesn't do anything** at runtime.

Make a working API endpoint first, then (use swagger-php annotation to) document the input and output of the endpoint.
