### ISSUE TITLE
swagger-ui version?

### ISSUE THREAD

**Issue by endingman** [zircote/swagger-php#432]
which swagger-ui version can I use?

**Comment by bfanger** [comment]
If you're using  swagger-php 1.x use swagger-ui 2.2.10 or earlier versions (these are compatible with the swagger v1 spec)
For swagger-php 2x (current version) use swagger-ui 2.1.5 or latest versions (these are compatible with the swagger v2 spec)

**I recommend using latest swagger-ui version (currently 3.1.7)**

The compatiblity chart is listed on https://github.com/swagger-api/swagger-ui
