### ISSUE TITLE
Add "writeOnly" option to the Property

### ISSUE THREAD

**Issue by BilosCage** [zircote/swagger-php#434]
Hi all
Nice work on this Library!

I saw that the Swagger Specification has a "writeOnly" option for the property (https://swagger.io/specification/#fixed-fields-100) which in my case would be perfect to use for a password field.

But I can't find this option in your library. Is there a plan to add it?
(As I see the "readOnly" option is already in.)

**Comment by bfanger** [comment]
`writeOnly` is a new feature in the 3.0 spec.

Feel free to create a pull request to the 3.x branch with an updated Schema object.

**Comment by bfanger** [comment]
I've added writeOnly in the [3.x branch](https://github.com/zircote/swagger-php/blob/3.x/src/Annotations/Schema.php)
