### ISSUE TITLE
A way to specify multiple responses with same code

### ISSUE THREAD

**Issue by DmitryLanda** [zircote/swagger-php#436]
hi,
i am interesting if there is a way to specify different responses with same code
like through `anyOf` and `oneOf` in swagger spec

Probably it looks like an error in my API - but I have to respond with pretty different responses (depends on internal state)

**Comment by patrickomeara** [comment]
I've also hit this issue, did you find a solution @DmitryLanda ?

**Comment by DmitryLanda** [comment]
@patrickomeara nop, sorry
I did some refactoring and changed my model for response (to use same for that cases). It looks much better for me now :wink:

**Comment by bfanger** [comment]
Yep, using `oneOf` or `anyOf` is the solution for multiple responses for the same http code..

**anyOf**: At least one schema  
**oneOf**: Exactly one schema


Probably `anyOf` for when responses overlap (normal error + addition info).
