### ISSUE TITLE
In response / Schema 'ref' will override the 'Property' setting

### ISSUE THREAD

**Issue by oliverCJ** [zircote/swagger-php#440]
hi
my setting

    @SWG\Response(
              response=200,
              description="success",
              @SWG\Schema(
                  ref="#definitions/BaseResponse",
                  @SWG\Property(
                      property="data",
                      ref="#definitions/BaseFields"
                  )
               )
          )

It will be resolved into

    "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "properties": {
                                "data": {
                                    "description": "fields",
                                    "$ref": "#definitions/BaseFields"
                                    }
                                }
                            "$ref": "#definitions/BaseResponse"
                            }
                        }
                    }
                }

the "$ref" was put in the end,it causes the swagger-ui to not correctly display the data property's settings

I modified and tested the json

    "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "properties": {
                                "$ref": "#definitions/BaseResponse",
                                "data": {
                                    "description": "fields",
                                     "$ref": "#definitions/BaseFields"
                                    }
                                }
                            }
                        }
                    }
                }

It works fine.
So I think maybe you can solve the problem.

**Comment by kevupton** [comment]
I believe ref should be used in the case that you do not modify any fields, as it expects the object to be exactly like that. 

swagger-php has some extending functionality which can allow you to extend a reference, importing all attributes over. 

Try:

#### Example

```php
<?php

/**
 *
 * @SWG\Info(
 *   version="1.0.0",
 *   title="Example of using references in swagger-php",
 * )
 *
 * @SWG\Response(
 *     response="BaseResponse",
 *     description="base response",
 *     @SWG\Schema(
 *          @SWG\Property(
 *              property="status",
 *              type="string"
 *          )
 *     )
 * )
 *
 *
 * @SWG\Response(
 *     response=200,
 *     description="success",
 *     ref="$/responses/BaseResponse",
 *     @SWG\Schema(
 *          @SWG\Property(
 *              property="data",
 *              ref="#definitions/BaseFields"
 *          )
 *      )
 * )
 */
```

#### Output
```json
{
    "swagger": "2.0",
    "info": {
        "title": "Example of using references in swagger-php",
        "version": "1.0.0"
    },
    "paths": {},
    "definitions": {},
    "responses": {
        "BaseResponse": {
            "description": "base response",
            "schema": {
                "properties": {
                    "status": {
                        "type": "string"
                    }
                }
            }
        },
        "200": {
            "description": "success",
            "schema": {
                "properties": {
                    "status": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#definitions/BaseFields"
                    }
                }
            }
        }
    }
}

```

I have made a pull request to create some more documentation surrounding this #463
