### ISSUE TITLE
The annotation "@Swagger\Annotations\Resource" in class TestTask\PhotosBundle\Controller\ApiController does not exist, or could not be auto-loaded.

### ISSUE THREAD

**Issue by hanaking** [zircote/swagger-php#441]
Hello,
i'm trying to use zircote/swagger.php to generate swagger specification of an api that i'm coding with symfony 3, i installed swagger-php with the composer :
 "zircote/swagger-php": "^2.0"
when i add this annotation to my controller like :

<?php

namespace AppBundle\Controller;

use AppBundle\Entity\User;
use AppBundle\Manager\ImportUsers\ImportUserParserResult;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use \Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Form\Form;
use AppBundle\Manager\UserManager;

/**
 * @SWG\Resource(
 *  basePath="http://test.dev/api",
 *  resourcePath="/vps",
 *  @SWG\Api(
 *   path="/vps",
 *   @SWG\Operation(
 *    method="GET",
 *    type="array",
 *    summary="Fetch vps lists",
 *    nickname="vps/index",
 *    @SWG\Parameter(
 *     name="expand",
 *     description="Models to expand",
 *     paramType="query",
 *     type="string",
 *     defaultValue="vps,os_template"
 *    )
 *   )
 *  )
 * )
 */
class TestsController extends Controller
{
}

**Comment by bfanger** [comment]
Resource is a swagger-php 1.x annotation. Upgrade your annotations to the 2.x notation.
