### ISSUE TITLE
Add documentation on how to @SWG\Schema ref another class namespace

### ISSUE THREAD

**Issue by angrygreenfrogs** [zircote/swagger-php#442]
Hello!

I'm having a lot of trouble figuring out how to use an object that is in another namespace.

All of the example code seems to assume that everything lives in the same namespace, which isn't how my Symfony code is normally structured.

For example, I'm trying to do something like this:
```
namespace AppBundle\Controller\Api;
use Swagger\Annotations as SWG;
class UserController
{
...
     *     @SWG\Response(
     *         response="200",
     *         description="Success",
     *         @SWG\Schema(ref="#/definitions/AppBundle/ApiOutputModels/User/Login")
     *     ),
```
My Login object looks like:

```
namespace AppBundle\ApiOutputModels\User;
use Swagger\Annotations as SWG;

/**
 * @SWG\Definition()
 */
class Login
{
    /**
     * Security token to be sent on subsequent API requests.
     *
     * @var string
     * @SWG\Property()
     */
    protected $token;
....
```

I've tried every variation I can think of, and I can't find anything in the documentation that tells you how to reference a class in another namespace. I'd like to suggest adding that to the docs/examples as well as it must be a common issue for others using any of the standard MVC frameworks out there.

Thanks!

**Comment by angrygreenfrogs** [comment]
Oh, for clarity, I mean to say that my attempt to do ```ref="#/definitions/AppBundle/ApiOutputModels/User/Login"``` definitely doesn't work.

All the doc examples are in the same namespace like ```@SWG\Schema(ref="#/definitions/Login")``` which works fine.

I tried doing that with ```use AppBundle\ApiOutputModels\User\Login;``` at the top of my controller, but it still doesn't work.

**Comment by bfanger** [comment]
swagger is about describing a json structure and doesn’t care about namespaces or classes.

swagger-php does try to use the information from a class when it can. As you can see in the json the definitions object now has a property “Login” as if you'd written `@SWG\Definition(definition="Login")`
```json
{
  "swagger": "2.0",
  ...
  "definitions": {
    "Login": {
      ...
    }
  }
}
```

To (re)use that definition use path in the json, so "#/definitions/Login" in this case.

**Comment by angrygreenfrogs** [comment]
Thanks for the reply! Hmmm, you know what, I think I get what you're saying now after further consideration.

I think the real base issue is that the swagger-php Symfony integration bundle I'm using (Nelmio) must not be scanning all of my PHP files and isn't finding the annotations that I have in other parts of the source tree like AppBundle\ApiOutputModels\User

Their documentation is very limited and this wasn't obvious to me that swagger-php just takes all the annotations from all of the php files , and doesn't really care about PHP namespaces, etc, etc,... you're just reading the annotations altogether in one big pile and that's it.

Might recommend if you feel like it adding an explanatory note to the Readme to that effect as I bet I'm not the only Symfony guy who missed that.

Thanks!

**Comment by chucky2305** [comment]
@angrygreenfrogs i feel it is very similar to my case: #444

**Comment by angrygreenfrogs** [comment]
It is.

It might be worth the author adding an explanation to the project documentation that explains the difference between this project and Nelmio, because they're completely different things.

Nelmio is what provides the @Model annotation that you're using in your example, and it really has nothing to do with swagger-php, it's totally a Nelmio thing.

After spending several days beating my head against the wall, I actually dropped Nelmio because it's too buggy and doesn't really work and found that it was much easier to just use swagger-bundle with Symfony:

https://github.com/TimeIncOSS/swagger-bundle

It doesn't try to put any extra functionality around swagger-php and basically it just searches all code recursively in a clearly stated list of folders and then you use the annotations only as specified here in this swagger-php project. This removes the entire namespace conversation completely from the picture since namespaces are not involved at all.. it just imports all files in those folders period.
