### ISSUE TITLE
Conflict of parameters in body and path

### ISSUE THREAD

**Issue by kopaygorodsky** [zircote/swagger-php#443]
It's not possible to define same name for parameters  in `body` and `path`, which are different parts of request. 
Example: 
```
     *  @SWG\Parameter(
     *      name="vacancy",
     *      in="body",
     *      description="updated vacancy information",
     *      required=true,
     *      @Model(type=VacancyType::class)
     *  ),
     *  @SWG\Parameter(
     *      description="id of vacancy to update",
     *      in="path",
     *      name="vacancy",
     *      required=true,
     *      type="string"
     *  )
```
The last GET parameter will be ignored and only first one will be handled.

**Comment by kopaygorodsky** [comment]
If I understood correctly the problem is here:
https://github.com/zircote/swagger-php/blob/master/src/Processors/AugmentParameters.php#L31
I can create a PR to fix this issue.

**Comment by bfanger** [comment]
I'd like a PR, but not to "fix" this issue, but generate a better warning that you've got multiple `@SWG\Parameter` annotations with the same identifier, although the current notice
`@SWG\Parameter(name="vacancy",in="path") is missing key-field: "parameter"` does point you in the right direction.

```
* @SWG\Parameter(
*   property="requestBody", <- specify a unique property name, as the generated identifier based on name is not unique
*   name="vacancy",
*   in="body",
*   description="updated vacancy information",
*   required=true,
*   @Model(type=VacancyType::class)
* ),
```

**Comment by kopaygorodsky** [comment]
@bfanger actually I don't see any noticies. 
So it's not possible to have parameters in body and path with the same name?

**Comment by bfanger** [comment]
> A list of parameters that are applicable for this operation. If a parameter is already defined at the Path Item, the new definition will override it, but can never remove it. The list MUST NOT include duplicated parameters. A unique parameter is defined by a combination of a name and location. The list can use the Reference Object to link to parameters that are defined at the Swagger Object's parameters. There can be one "body" parameter at most.

Source: [Swagger Specification 2.0 (Operation Object)](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operationObject)

It is allowed by the spec as long as the location is different.

What do you mean by "The last GET parameter will be ignored and only first one will be handled."
- Not not visible in the swagger client (swagger-ui)
- Not in the json output? (in this case a notification should be given)

I see you're using `@Model` so maybe the NelmioApiDocBundle is hiding the error.

**Comment by kopaygorodsky** [comment]
@bfanger sorry, I was wrong, this issue has to be related to swagger-ui since both params are present in json output. 
<img width="457" alt="screen shot 2017-10-11 at 2 00 26 am" src="https://user-images.githubusercontent.com/2415637/31414714-fb8c0cfc-ae27-11e7-9038-e8f1e1238cc1.png">
