### ISSUE TITLE
Fatal error: Maximum function nesting level of '256' reached, aborting!

### ISSUE THREAD

**Issue by tot-ra** [zircote/swagger-php#445]
Seems there is a recursion at `vendor/zircote/swagger-php/src/StaticAnalyser.php on line 276`

Checked out latest version **2.0.11**, ran it through ./vendor/bin/swagger against project that has no annotations and got error in title

Upd. Seems that its caused by consecutive comments with `//` that are more than 256 lines long — cleaning up project from `//` to `/* lots of lines */` helped

**Comment by bfanger** [comment]
PHP doesn't have a `Maximum function nesting level`, however when you enable the `xdebug` extension you do.

I've fixed the issue in the 3.x branch, for 2.x a quick fix would be to set the limit to a larger number.
`xdebug.max_nesting_level=1000`
