### ISSUE TITLE
Removing property from annotations

### ISSUE THREAD

**Issue by hpatoio** [zircote/swagger-php#448]
I'm writing my custom processor. I need to remove some `Property` from those parsed by `swagger-php`.

Here the code I write so far

```
class CustomRemoverProcesso
{
    public function __invoke(Analysis $analysis)
    {
        foreach ($analysis->annotations as $k => $annotation) {
            if ($annotation instanceof Property) {
                if (here my condition) {
                   $analysis->annotations->detach($annotation);
                }
            }
        }
    }
}
```
But doesn't seems to work. Any hint ?

**Comment by bfanger** [comment]
You'll need to remove the `Property` from the `properties` array in the parent annotation.
You can access parent via the `nested` property in the `_context`.

For an example of how to access the parent annotation take a look at the [MergeJsonContent proccessor](https://github.com/zircote/swagger-php/blob/3.x/src/Processors/MergeJsonContent.php)

**Comment by hpatoio** [comment]
I solved like this

```
$definitions = $analysis->getAnnotationsOfType('\Swagger\Annotations\Definition');
foreach ($definitions as $definitionKey => $definition) {
    foreach ($definition->properties as $propertyKey => $property) { 
        if ($myCondition) {
            unset($definition->properties[$propertyKey]);
        }
    }
}
```
