### ISSUE TITLE
Add example using form type

### ISSUE THREAD

**Issue by matrix818181** [zircote/swagger-php#449]
I would like to know if it's possible use FormType instead of entity in Post/Put action or do I have to rewrite all the properties on my controller's action ?

I don't want to expose all the properties of my entity. So, I'm using specific FormType so that we only need to submit specific data.

Thanks

**Comment by bfanger** [comment]
The `POST /pet/{petId` api from the petstore example uses formData: 

https://github.com/zircote/swagger-php/blob/2.0.11/Examples/petstore.swagger.io/controllers/PetController.php#L245

**Comment by matrix818181** [comment]
Thanks ! It's working but I was more looking for a way to not rewrite the whole FormType as Swagger annotation.

If it's not possible to use FormType, you can close this ticket. Thanks

**Comment by bfanger** [comment]
swagger-php is framework agnostic, so FormType integration is out of scope, but maybe 
https://symfony.com/doc/master/bundles/NelmioApiDocBundle/swagger-support.html does. (Disclaimer: I don’t use this bundle or symfony)

**Comment by imajim** [comment]
hello @matrix818181  !
Have you found a solution to use formType ?
thx.
