### ISSUE TITLE
Why is `items->object` not allowed in Parameter?

### ISSUE THREAD

**Issue by andrey-ognermedia** [zircote/swagger-php#454]
Hi, i need to describe query parameter like this:  
`sorters=[{'property':'col1','direction':'DESC'},{'property':'col2','direction':'ASC'}...]`  

```php
/**
 * @SWG\Parameter(
 *      name="sorters",
 *      in="query",
 *      type="array",
 *      description="Sort collection. For example, `sorters=[{'property':'name','direction':'DESC'}]`",
 *      @SWG\Items(
 *           type="object",
 *           @SWG\Property(property="property", type="string"),
 *           @SWG\Property(property="direction", type="string")
 *      )
 * )
*/
````

But i get error:  
`@SWG\Items()->type="object" not allowed inside a @SWG\Parameter() must be "string", "number", "integer", "boolean", "array"`

Why? And how to describe above parameter?

**Comment by bravo-kernel** [comment]
The list produced by the error adheres to version 2 of the specification, see [this list](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#items-object) and note that `object` is not listed next to the `type` field.

Version 3 of the spec does include `object` as you can see [here](https://swagger.io/docs/specification/data-models/data-types/).

As to the why; I guess SwaggerPHP supports version 2, not 3 (yet?).

**Comment by bravo-kernel** [comment]
As found on the SwaggerPHP readme list of features:

> Compatible with the Swagger 2.0 specification.

**Comment by nirmalgoswami** [comment]
still no support for swagger 3.0 ?
