### ISSUE TITLE
After updating to version 2.0.12, I am getting a failed to parse JSON everytime, doesn't happen on any of the older versions

### ISSUE THREAD

**Issue by sergiocha** [zircote/swagger-php#456]
I am working with alt3/cakephp-swagger

**Comment by bravo-kernel** [comment]
Thanks for reporting but I have a sense it might be more appropriate to report this issue on the cakephp-swagger project. If you agree please close this ticket, create a new one on cakephp-swagger, ideally with some debug information. I will pick it up from there.

**Comment by bfanger** [comment]
Most likely the newer version emits a notification that something is wrong, if this php notification is rendered before (of instead of) the normal json it results into invalid json file.

If 2.0.12 incorrectly reported an error, please open a new issue stating the error and why it’s invalid.
