### ISSUE TITLE
security missing from $_types in Operation

### ISSUE THREAD

**Issue by DerManoMann** [zircote/swagger-php#461]
Hi there,

Just wondering if there is a reason why security is missing from the $_types array in the Operation annotation class?

**Comment by bfanger** [comment]
It's because `security` is not a simple type (string, boolean, etc) or an array of a simple type.
```
*     security={
*       {"petstore_auth": {"write:pets", "read:pets"}}
*     }
```
Check the [validateType()](https://github.com/zircote/swagger-php/blob/master/src/Annotations/AbstractAnnotation.php#L482) to see which types it can currently validate.

**Comment by DerManoMann** [comment]
Fair enough - thanks.
