### ISSUE TITLE
basePath not working with incorrect indenting

### ISSUE THREAD

**Issue by mcvermeulen** [zircote/swagger-php#464]
I've setup swagger within my CakePHP project.
In my AppController i had the following block:
```
/**
@SWG\Swagger(
    basePath=BASE_PATH_SWAGGER,
    @SWG\Info(
          title="Backend",
          description="This backend......",
          version="1.0.0",
    )
)
*/
```
However the basePath isn't changed to the value defined in the BASE_PATH_SWAGGER constant.
If i change the title or whatever, i can see the change immidiatly.  

If i indent the @SWG\Swagger block with a tab it does work.
```
/**
    @SWG\Swagger(
         basePath=BASE_PATH_SWAGGER,
         @SWG\Info(
              title="Backend",
              description="This backend......",
              version="1.0.0",
         )
    )
*/
```

**Comment by bfanger** [comment]
What a weird bug, also no `[Semantical Error] Couldn't find constant BASE_PATH_SWAGGER` warning.

However this is not a bug in swagger-php, but in [doctrine/annotations](https://github.com/doctrine/annotations), please file the issue [there](https://github.com/doctrine/annotations/issues/new)
