### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by Somebi** [zircote/swagger-php#465]
/**
     * @SWG\Get(
     *     path="/api/v1/foo/bar",
     *     parameters={
     *         "name": "fooId",
     *         "in": "query",
     *         "type": "string",
     *         "required": true
     *     },
     *     @SWG\Response(response="200", description="Return something")
     * )
     */

Trying to get property of non-object in vendor/zircote/swagger-php/src/Processors/HandleReferences.php on line 108

**Comment by kevupton** [comment]
Try:

```php
/**
 * @SWG\Get(
 *     path="/api/v1/foo/bar",
 *     @SWG\Parameter(
 *          name="fooId",
 *          in="query",
 *          type="string",
 *          required=true
 *     ),
 *     @SWG\Response(response="200", description="Return something")
 * )
 */
```

`parameters` needs to be an array
