### ISSUE TITLE
How to include ref to reusable @SWG\Parameter into parameters?

### ISSUE THREAD

**Issue by Somebi** [zircote/swagger-php#466]
I have tried various variations, but none is working...
```
 * @SWG\Parameter(
 *   name="some-key",
 *   type="string",
 *   required=true,
 *   in="header",
 *   description="some key"
 * )


     *     parameters={
     *         $ref="#/parameters/some-key",

```

Is there some normal, full documentation for your project?
Have to guess how it should all fit there...

**Comment by Somebi** [comment]
How to make reusable header parameter?

**Comment by kevupton** [comment]
Yes I believe thats possible. Try this:

```php
/**
 * @SWG\Get(
 *     path="/api/v1/foo/bar",
 *     @SWG\Parameter(
 *          ref="#/parameters/fooId"
 *     ),
 *     @SWG\Response(response="200", description="Return something")
 * )
 *
 * @SWG\Parameter(
 *      name="fooId",
 *      in="query",
 *      type="string",
 *      required=true
 * )
*/
```

There are docs, however you may find some more help from the examples. 
[Examples Here](https://github.com/zircote/swagger-php/tree/master/Examples) 
or more precisely some examples on global parameters: [Using Refs](https://github.com/zircote/swagger-php/tree/master/Examples/using-refs)

**Comment by Somebi** [comment]
Aha! Thank you. So it just needs to be wrapped into @SWG\Parameter() to make ref working.
