### ISSUE TITLE
Multiple @SWG\Response() with the same response="403"

### ISSUE THREAD

**Issue by przemyslawlib-blueveery** [zircote/swagger-php#470]
So I have two distinct paths, and I have response defined in "responses" section.

I get above message for follwing annotations:
Path `A`
```
@SWG\Response(
     *         response=403,
     *         description="...",
     *         @SWG\Schema(ref="#/responses/ProductNotAllowedException"),
     *     )
```
Path `B`
```
@SWG\Response(
     *         response=403,
     *         description="...",
     *         @SWG\Schema(ref="#/responses/ProductNotAllowedException"),
     *     )
```

To make matters worse, despite labeling that error message as "[Info]", swagger-php is actually encountering serious error, and no further annotation will be processes for those paths.

How do I properly reuse response definitions for cases where multiple paths may return same response?
Isn't `response` just signaling HTTP response code?

PS: What I mean by "serious" is that output do not contain definitions equivalent to those annotations.

**Comment by kevupton** [comment]
Do you need the response defined twice ? 
Are they two different responses, Or is it just the description that is different ? 

What if you make one response and just reference it in each place ? 
Something like this:

```php
/**
 * @SWG\Response(
 *   response="403",
 *   description="...",
 *   @SWG\Schema(ref="#/responses/ProductNotAllowedException")
 * )
 *
 * @SWG\Get(
 *   tags={"Products"},
 *   path="/products/{product_id}",
 *   @SWG\Response(response="default", ref="#/responses/403")
 * )
 */
```

**Comment by przemyslawlib-blueveery** [comment]
@kevupton `response="default" is not an option for those paths. I have up to 5 responses on them, and default one is always success code path.

Swagger-php seam to expect unique `response` value if defined in `@SWG\Get\Post\Put\...".
Somehow `response=200` defined in all paths is OK, but as soon as I add two paths with `response=500', swagger-php will break on those annotations.

**Comment by przemyslawlib-blueveery** [comment]
UPDATE II:

I have seen how swagger-codegen handles multiple responses. There will be switch like functionality that decide how to hydrate response (and of what class it will be if it's OO language).

I also realized that while having error type reflected in Type of response would be good, we could push such info to just Value. (Meaning there is only single class/type of error response, and consuming code have to use getHttpCode or something to distinguish between potential reasons for errors).


So taking above into account I used `default` to provide single entry for all possible failures.
(path->response->schema)->(definitions->definition)

Instead of:
(path->response->schema)->(responses->response->schema)->(definitions->definition)

**Comment by bfanger** [comment]
I've updated the error level from `[INFO]` to `[WARN]`.
I'm not certain, but it looks like the problem was understood/solved and therefor closing the issue.

[Using $ref](https://swagger.io/docs/specification/using-ref/) is tricky and the swagger documentation somewhat limited. 
The [documentation on json-schema.org](https://json-schema.org/understanding-json-schema/structuring.html) has a little more on $ref a.k.a. **JSON Pointers**.

**Comment by DorelBesliu** [comment]
I have the same issue now for 2 different methods
`local.ERROR: ErrorException: Multiple @OA\Response() with the same response="200":
  \App\Http\Controllers\Student\EventsController->update() in /var/www/html/app/Http/Controllers/Student/EventsController.php on line 136
  \App\Http\Controllers\Student\EventsController->store() in /var/www/html/app/Http/Controllers/Student/EventsController.php on line 51 in /var/www/html/vendor/zircote/swagger-php/src/Logger.php:39`

**Comment by DorelBesliu** [comment]
And that problem is only on server side. I tried my local generated api-docs in https://editor.swagger.io/ and it works well

**Comment by Doqnach** [comment]
Please continue this discussion in #810
