### ISSUE TITLE
Pass a variable to a processor

### ISSUE THREAD

**Issue by hpatoio** [zircote/swagger-php#471]
Is it possible to pass a variable to a processor ? I need to pass a variable to from the CLI to the processor.

**Comment by bfanger** [comment]
A processor is just a function which gets an Analysis as its argument.

What you do inside that processor is up to you. Although reading from [$argv](http://php.net/manual/en/reserved.variables.argv.php) or [$_ENV](http://php.net/manual/en/reserved.variables.environment.php) inside the function makes it harder to test.

I recommend making a invokable class which you'll construct with the variable from the command line.
```
