### ISSUE TITLE
Line break in description support 

### ISSUE THREAD

**Issue by soulkoden** [zircote/swagger-php#474]
How do write line break in description? 

I have an enum field and I can't write line break for one.

Example 
```
@SWG\Property(
  type="enum",
  enum={1, 2}, 
  description="* `1` - active >>>???<<< * `2` - inactive",
)
```

I tried `\n` and it escaping to `\\n`. 
I tried it:
```
description="* `1` - active
* `2` - inactive"
``` 

and it view as: 
<ul>
<li>`1` - active<ul><li>`2` - inactive</li></ul></li></ul>

I tried it:
```
description="
* `1` - active
* `2` - inactive
"
```

and it view as:
<ul><li><ul>
<li>`1` - active</li><li>`2` - inactive</li></ul></li></ul>

**Comment by rlanvin** [comment]
I'm having the same issue. There is a workaround here: https://github.com/zircote/swagger-php/issues/326 which consists of removing the `*` at the start of line. However, that creates an issue with many text editors that consider it as an invalid DocBlock syntax.

Even Github will display the lines in red, example:

```php
/**
 * description="
- foo
- bar
 * "
 */
```

So if there is a real solution I'm interested as well.

**Comment by bfanger** [comment]
It annoying and it affects swagger-php, but it's an issue in [Doctrine Annotations](https://github.com/doctrine/annotations) library that swagger-php uses.

Please report the issue there.

If you've found a solution or workaround, feel free let us know.
