### ISSUE TITLE
Using array Constants 

### ISSUE THREAD

**Issue by eypsilon** [zircote/swagger-php#477]
Hello,

is it possible to use Constants with arrays as value in Swagger? Something like:
```

// config.api.php

define('Api', [
    'Routes' => [
        'Get' => [
            'Article' => [
                'List' => [
                    'Route' => '/article',
                    'OpID'  => 'getArticleList',
                ],
            ], 
        ],
    ],
]);

// and using it in Swagger

/**
  @SWG\Get(
    path=Api['Routes']['Get']['Article']['List']['Route'], 
    operationId=Api['Routes']['Get']['Article']['List']['OpID'],
  )
 */

```
Is there a way to use Constants like this?

**Comment by bfanger** [comment]
Since PHP 5.6, you can declare an array constant with const:

```php
const DEFAULT_ROLES = ['guy', 'development team'];
```


If you have PHP 7+, you can also use define():```

```php
define('DEFAULT_ROLES', ['guy', 'development team']);
```

**Comment by eypsilon** [comment]
Not really, following definition causes an error

```
/**
  @SWG\Definition(
    definition="example",
    type="object",      
    @SWG\Property(
        property="status", 
        type="integer",
        example=API['tables']['pages']['status'],        
    ),
  ),
 */
```

PHP error is

```
Warning: [Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, 
got '[' in \_Spec.php on line 116:24 in 
\vendor\zircote\swagger-php\src\Logger.php on line 38
```

I guess, i could fix it for me in \swagger-php\src\Logger.php, but what happens, when i update swagger-php?

**Comment by eypsilon** [comment]
I know, i can use straight Constants like

```
define('ApiGetRoutePages', '/pages');

// and using it later in a Swagger Definition File and in my API as well
@SWG\Property(
  property="PageRoute", 
  type="integer",
  example=ApiGetRoutePages,        
)
```

But i need a lot of Strings and Values, to Swagger everything i need with the same Config data i use in my API, and actually my dynamic "Swagger definition builder" counts around 1240 Constants, and that feels not really good and i'm not even done so far :)

**Comment by bfanger** [comment]
That are a lot of constants but they probably use a very predictable pattern, as long as you are able use those constants without problems, i wouldn't worry about it too much.

**Comment by eypsilon** [comment]
I'm not really worried about, at least everything runs fast, but it would be a bit more comfortable to use constants like the examples above.

I think it's easier to read and write 
```
Api['Routes']['Get']['Page']
```
instead of defining each element in the array individually
```
ApiRoutesGetPage
```

How would you handle, let's say 50-60 endpoints with repetitive, almost identical Responses (because of a very similar table structure overall)? I only need 4 classes to handle all the endpoints, but to swagger them all creates a lot of repetitive things. Even with use of constants and definitions.

**Comment by eypsilon** [comment]
Sorry, i just now figured out, how to use $ref. And i had asked me a couple days ago, if i can "define" someting like a variable. Yes, i can, Response.

https://github.com/zircote/swagger-php/tree/master/Examples/dynamic-reference

Looks good, i think, we can close this issue. And BTW, great Tool :)

**Comment by bfanger** [comment]
Thanks!
