### ISSUE TITLE
Is there a way to custom sort tags?

### ISSUE THREAD

**Issue by rromaniv** [zircote/swagger-php#478]

**Comment by bfanger** [comment]
No, i think sorting is more a feature for a swagger viewer.
But the output is just json, so writing your own sorting isn't that hard.

**Comment by fbsanchez** [comment]
For anybody like me who does not read documentation :sweat_smile: and reach here:

To alphabetically sort the methods from each API, check l5-swagger.php:

```php
         /*
         * Apply a sort to the operation list of each API. It can be 'alpha' (sort by paths alphanumerically),
         * 'method' (sort by HTTP method).
         * Default is the order returned by the server unchanged.
        */
        'operations_sort' => env('L5_SWAGGER_OPERATIONS_SORT', 'alpha'),
```

To sort each API in a custom way, you can (in laravel) define in Controller.php file:

```php
     * @OA\Tag(
     *   name="Tests",
     *   description="Some testing"
     * ),
     * @OA\Tag(
     *   name="Users",
     *   description="API Endpoints of Users"
     * ),
     * @OA\Tag(
     *   name="Jobs",
     *   description="API Endpoints of Jobs"
     * ),
```

Thanks!

**Comment by DerManoMann** [comment]
You can also easily write your own processor - I would think a one line change?
https://github.com/zircote/swagger-php/blob/master/Examples/processors/sort-components/SortComponents.php
