### ISSUE TITLE
API return a file

### ISSUE THREAD

**Issue by michaelchemani** [zircote/swagger-php#490]
I got an endpoint that returns a CSV file. I cannot manage to download that file from the documentation. 

here is my specification : 

```
	/**
	 * @SWG\Get(
	 *     tags={"Brands"},
	 *     path="/admin/brands/export",
	 *     summary="Export the brands list",
	 *     description="Return a file",
	 *     produces={"application/csv"},
	 *     @SWG\Parameter(ref="#/parameters/bearer_in_header"),
	 *     @SWG\Response(
	 *         response="500",
	 *         description="Something went very wrong",
	 *     ),
	 *     @SWG\Response(
	 *         response=200,
	 *         ????
	 *     ),
	 *     deprecated=false
	 * )
	 */
```

I know I am missing something in my response but I can't figure out what?

**Comment by bfanger** [comment]
You should add a `@SWG\Schema(type="file")` as is documented in the [Response object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject)
