### ISSUE TITLE
Pass a default parameter as Value for SecurityScheme

### ISSUE THREAD

**Issue by naretini** [zircote/swagger-php#491]
This is my General annotation:
` @SWG\Swagger(
      basePath="/api",
     @SWG\Info(
          version="1.0.0",
          title="My API",
      ),
      @SWG\SecurityScheme(
       securityDefinition="Bearer",
       type="apiKey",
       in="header",
       name="Authorization",
       description="Auth Bearer Token<br> Format as 'Bearer <access_token>'",
     )
  )

  )
`
My /api/documentation web route is behind User Authentication (then secured)

I wish to know if there's some way I could pass as default value in @SWG\SecurityScheme my previously generated Bearer token.

something like 
`@SWG\SecurityScheme(
value=MY_VAR,

...
)`
Where MY_VAR contains the value of a valid token generated

**Comment by bfanger** [comment]
That’s unusual, generally accestokens require authentication to obtain. I’d say adding one to the documentation introduces a security risk.

Swagger-ui has support for providing a token, but that one you’d enter manually in an inputfield, can edit the index.html and place an testaccount accesstoken there
