### ISSUE TITLE
Accept: application/json in OAS 3

### ISSUE THREAD

**Issue by bitkill** [zircote/swagger-php#498]
Hi.
I'm looking for a way to define the "accept: " header via the OpenApiSpecification v3
In the old swagger (2) way this would be as simple as setting:
`produces={"application/json"},`

Now, upon changing to OAS 3, my requests send "accept: */*" as default, and the response is dependant upon setting the correct accept: header, so I get the wrong response.

I've searched in documentation, but I still haven't found a solution.

**Comment by music-mind** [comment]
Have you tried using media type? This seems to set the header to application/json for me.

```
  *     @OAS\RequestBody(
  *         description="text",
  *         required=true,
  *         @OAS\MediaType(
  *             mediaType="application/json",
  *             @OAS\Schema(
   *                 ref="#/components/schemas/..."
  *             )
  *         )
  *     ),
```

**Comment by bfanger** [comment]
**Update:**  
We've recently added JsonContent support for RequestBody.
(Still generates the MediaType and Schema under the hood, but is less verbose to write)
```
  *     @OA\RequestBody(
  *         description="text",
  *         required=true,
  *         @OA\JsonContent(ref="#/components/schemas/...")
  *     ),
```

**Comment by malkovro** [comment]
It seems that what you offered only set the **content-type** but not the **accept** header.
Am i wrong to thing this should not be closed  @bfanger ?
