### ISSUE TITLE
Required is not inherited

### ISSUE THREAD

**Issue by Acolyte** [zircote/swagger-php#504]
There is an InheritProperties processor that joins properties, but there isn't one for "required" annotation. An example would be a parent class with some required fields, and a child class that has its own required fields. These should be joined analogous to properties.

**Comment by bfanger** [comment]
Which fields are required an which aren't depend on the api.
There is no such thing as inheritance in a rest interface, therefor swagger-php doesn't join these as that could be wrong. Just supply the required value in the subclass.

**Comment by bfanger** [comment]
I'm oke with inheriting the required property from the superclass if no required is specified.
But automatic merging of required properties feels risky.

**Comment by olleharstedt** [comment]
Is there a way to _not_ merge required fields when inheriting schemas? The POST body might require some fields that are mandatory in the URL instead, for a PATCH-request.
