### ISSUE TITLE
SWAGGER-PHP error when generating .json I can not load the values from my model

### ISSUE THREAD

**Issue by otipip90** [zircote/swagger-php#505]
Hi guys I tried to eliminate this error that persists when I generate the swagger.json, the view in swagger-ui show me:
Resolver error at paths./v1/hosp/{id1}/hospnext/{id2}.put.parameters.2.schema.$ref
Could not resolve reference because of: Not Found.
IM WORKING WITH LUMEN, swagger-php v.2.0.13 and swagger-ui v.2.0.13 
...
     *   @SWG\Parameter(
     *     name="JSON update body",
     *     in="body",
     *     description="Model Hospital.",
     *     required=true,
     *     @SWG\Schema(ref="vendor/dir1/DAO/src/Model/Hospital.php/#/definitions/Hospital")
     *   )
...
 public function update($id1,$id2, Request $request){...}

when I check the json does not generate the definitions -> "definitions": {} my model defined it in the following way, I do not know if the problem is that my model is under a different namespace because it is defined as a vendor or something declarative that I lack:
```
/**
 * @SWG\Definition(definition="Hospital", type="object")
 */
class Hospital extends Model
{
    
    /**
     * @SWG\Property()
     * @var string
     */
    protected $name;
```

..and in my view of swagger  an ERROR appears {...} I think it's because it does not load the values of the model,Really I'm running out of resources with this despite looking pretty, thanks to who can help me

**Comment by ThibautAlgrin** [comment]
Hello,
Do you try with remove `definition` and `type` in `Definition` annotation

**Comment by bfanger** [comment]
Unable to reproduce this issue
