### ISSUE TITLE
Example value of parameter

### ISSUE THREAD

**Issue by PianistaMichal** [zircote/swagger-php#507]
I would like to be able to add example value to parameter like in title. This is available if I have value example in swagger.json file, then swagger-ui is reading this value and displaying, but auto generating from annotation is not available

**Comment by sonrac** [comment]
@PianistaMichal For swagger 2.0 use ```default``` for example value. In 3.0 version example are added. 
https://github.com/zircote/swagger-php/blob/master/src/Annotations/Parameter.php#L95
