### ISSUE TITLE
OAS Model Uses classname on load

### ISSUE THREAD

**Issue by music-mind** [zircote/swagger-php#508]
Using OpenAPI 3.0 version, and wanted to define a model schema. Followed the XML way as per the petstore example, and it was working except the class name was the title for the dropdown on pageload, then it changes to the title on click. (also rather avoid creating a bunch of new classes).

Is there a way for it to default to the schema title?

```
 * @OAS\Schema(
 *     type="object",
 *     description="Clients",
 *     title="Clients",
 *     @OAS\Xml(
 *         name="swagger_Client"
 *     )
 * )
```

**Comment by music-mind** [comment]
Solved via the "schema" property. It's not mentioned in the OpenAPI spec.

**Comment by sonrac** [comment]
@music-mind 
In OpenAPI spec schema object does not have property "schema" or "name"

For Swagger Annotation we usage "schema" property as schema name in components object.
