### ISSUE TITLE
The conflict between dependent component and php version

### ISSUE THREAD

**Issue by lvshuang** [zircote/swagger-php#510]
We use the swagger of version ^2.0，when we executed the command `composer update`, we found the composer install the symfony/finder fo version 4.0.6; But the symfony/finder of version 4.0.6 require php version >= 7.1, and our php version is 5.6, therefor, we get a fatal error! 

Is there some way to fix the problem? Thanks in advance!

**Comment by bfanger** [comment]
composer takes the php version in account when resolving dependancies.
Did you use: ` --ignore-platform-reqs` ?

To force a specific version you can add to your composer.json:
```json
"config": {
  "platform": {
    "php": "5.6.6"
  }
}
```

**Comment by lvshuang** [comment]
@bfanger  We didn't use `--ignore-platform-reqs`, I finally found the reason was the php on our build server had been upgrade to 7.1 ! Thanks very much!
