### ISSUE TITLE
Reference definition but exclude certain fields

### ISSUE THREAD

**Issue by benirose** [zircote/swagger-php#511]
Is there a way to use a definition reference but exclude certain fields from it? For example, I have a definition for a model, which includes things like `id`, `name`, `description`, but when defining the schema for my `POST` route to create this resource, I don't want `id` to be included. Am I forced to manually recreate the definition?

**Comment by Syndesi** [comment]
It looks like this is an ["old" issue](https://github.com/zircote/swagger-php/issues/468#issuecomment-348483744) and might be implemented in the future.
But I would like to use `exclude={"id"}` too :)
