### ISSUE TITLE
Swegger UI not showing

### ISSUE THREAD

**Issue by hassanuos** [zircote/swagger-php#512]
I am facing this issue in `laravel 5.2.*`

Below is the image. I run all these commands. All successfully executed. but I see the below page.

> l5-swagger
> l5-swagger:generate
> l5-swagger:publish
> l5-swagger:publish-assets
> l5-swagger:publish-config
> l5-swagger:publish-views

![capture](https://user-images.githubusercontent.com/13483548/38873863-33bf63f8-4270-11e8-93f7-dc28255876c3.PNG)

**Comment by bfanger** [comment]
This is a problem with swagger-php, create the issue in the l5-swagger repo
