### ISSUE TITLE
Feature request: ability to determine the order of the functions in the swagger.json file

### ISSUE THREAD

**Issue by tetrode** [zircote/swagger-php#515]
The swagger javascript app provided by swagger.io displays the API in the order that it is present in the swagger.io.
Feature request: have a non required command line option to influence the order of API functions that swagger-php writes out the json structures, e.g.:
```
swagger --order=somefile
```
where somefile contains the API functions as follows:
GET /my/api/functionA/{parameters}
POST /my/api/functionA/{parameters}
GET /my/api/functionC/{parameters}
DELETE /my/api/functionC/{parameters}
POST /my/api/functionB/{parameters}
DELETE /my/api/functionB/{parameters}

This will improve the swagger documentation so that it becomes more logical to browse through them. Functions not defined in this file should be put at the end.

For existing swagger-php documentation, it could be usefull to also have:
```
swagger --generate-order=somefile
```
to generate a new order file (or read the existing order file and add the new functions at the end)

**Comment by bfanger** [comment]
Related #478

**Comment by tetrode** [comment]
Agreed that this is (also) a viewer improvement.
If I write a PR would you consider it - just asking before I put some work in it.
Thanks!

**Comment by bfanger** [comment]
I’d merge a processor, but I wouldn’t enable it by default (or port it to 3.x myself)
