### ISSUE TITLE
Discriminator mapping

### ISSUE THREAD

**Issue by hotrush** [zircote/swagger-php#518]
https://github.com/zircote/swagger-php/blob/3.x/src/Annotations/Discriminator.php#L39

Here defined that discriminator's mapping should be [string], but it also can be an object to define mapping keys

https://swagger.io/specification/#discriminatorObject
https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

So, notice generated, but resulted json is valid. I am using v3

**Comment by bfanger** [comment]
Fixed, thanks for reporting the issue
