### ISSUE TITLE
How to request json params in body?

### ISSUE THREAD

**Issue by Blgrad** [zircote/swagger-php#520]
I'd like to write json params(body) in swagger-php.

This is the format what I wanna request using (application/json)body.
```json
{
  "A":"A",
  "B":0
}
```

This is following code.

```php
     *  @SWG\Post(
     ...
     *  @SWG\Parameter(
     *      ref="#/parameters/AA"
     *  ),
     *  @SWG\Parameter(
     *      ref="#/parameters/BB"
     *  ),
     *  @SWG\Parameter(
     *      ref="#/parameters/CC"
     *  ),
     *  @SWG\Parameter(
     *      name="bodyname",
     *      in="body",
     *      description="bodydesc",
     *      @SWG\Schema(
     *          @SWG\Property(property="A", type="string", example="A"),
     *          @SWG\Property(property="B", type="integer", example=0),
     *      ),
     *  ),
     ...
     )
```

This is response on Swagger-UI
-> Undocumented | TypeError: Cannot read property 'statusText' of undefined

When i removed body json parameter(name="bodyname") in code, It works fine.
I Tested this API using like Postman & curl on shell.

How to request json params in body?

Thanks in advance.

**Comment by bfanger** [comment]
I'm closing this issue, swagger-UI errors are out-of-scope for this project. swagger-php is only responsible for generating the json documentation based on the annotations. 
swagger-php doesn't handle api requests, it only describes them. 

If the generated swagger.json contains unexpected output let me know what you expected and why.
