### ISSUE TITLE
How to pass dynamic variables in swagger tags?

### ISSUE THREAD

**Issue by ramanjine** [zircote/swagger-php#526]
I want to render tag names dynamically based on my condition.I am Using php is ther any way.Whether if we used any variable it shows

["Expected PlainValue, got '$' "]

(https://stackoverflow.com/questions/50559143/how-to-pass-dynamic-variables-in-swagger-tags)

**Comment by bfanger** [comment]
Filtering is outside the scope of the swagger-php, but the output is just json.
Writing you own logic should be trivial.

**Comment by ramanjine** [comment]
it is possible to pass any variable in tags?`

>  *     tags={"Employees"},

it always shows only plain text  required

**Comment by bfanger** [comment]
Yes, you can use constants, see the "Using variables in annotations" section in the getting started documentation.
