### ISSUE TITLE
how to disable some accessors ?

### ISSUE THREAD

**Issue by florianajir** [zircote/swagger-php#528]
I have some methods in my models which I don't want to be serialized as properties, in my case I need to implement isEnabled function which check the status property equals value enabled. I already have a status property so I want to exclude parsed enabled generated property.

```
    /**
     * @return bool true if is enabled, false otherwise
     */
    public function isEnabled()
    {
        return $this->status === Status::ENABLED;
    }
```

Is there an annotation for this purpose ?

**Comment by bfanger** [comment]
We don't generate documentation for every property, you'll need to opt-in (add annotations) to expose a property. 

So simply ommit annotations from the properties you want to exclude.
