### ISSUE TITLE
How to define postfields for cURL Post?

### ISSUE THREAD

**Issue by MB34** [zircote/swagger-php#530]
I've got this PHP code to call my API:

    $fields = array(
        'id' => $this->cmpId,
        'ic'    => $ic
    ); 
    $fields_string = http_build_query($fields);

    $url = "localhost/API/GetInventory";
    $ch = curl_init();
    //set the url, number of POST vars, POST data
    curl_setopt($ch,CURLOPT_URL, $url);
    curl_setopt($ch,CURLOPT_POST, count($fields));
    curl_setopt($ch,CURLOPT_POSTFIELDS, $fields_string); 
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $response = curl_exec($ch);

How would I define the @SWG\Parameters for the above API call? This is how I currently have it and not sure if it is correct:

    /**
     *
     * @SWG\Post(
     *   path="/API/GetInventory",
     *   description="Gets inventory for passed ID/IC combination",
     *   produces={"application/json"},
     *   summary="Get inventory from ID/PKey", 
     *   @SWG\Parameter(
     *      in="path",
     *      name="id",
     *      type="string",
     *      description="ID to retrieve inventory for",
     *      required=false,
     *   ),
     *   @SWG\Parameter(
     *      in="path",
     *      name="ic",
     *      type="string",
     *      description="IC to retrieve inventory for",
     *      required=false,
     *   ),
     *   @SWG\Response(response=200,description="successful operation"),
     *   @SWG\Response(response=500,description="Internal error")
     *   )
     * )
     */

**Comment by bfanger** [comment]
Use `in="formData"`, because `in="path",` is for the url-path (for  id=123 `/users/{id}` becomes `/users/123`)

See https://swagger.io/docs/specification/2-0/describing-parameters/ for more info
