### ISSUE TITLE
Feature request: write description for @SWG\Info above it

### ISSUE THREAD

**Issue by codedokode** [zircote/swagger-php#538]
An API description is often a long text with markup. So I think it makes sense to allow write description for `@SWG\Info` in the comment above the annotation: 

```php
/**
 * Long API description with markdown.
 *
 * ## Example header
 *
 * Example text.
 * 
 * @SWG\Swagger(
 *     @SWG\Info(
 *         title="My API title",
 *         version="1.0"
 *     ),
 *     schemes={"https"},
 *     host="api.example.com",
 *     basePath="/"
 *  )
 */
```

I might try to make a pull request later if there are no objections.

Another solution could be to allow write parts of Swagger file as an YAML file and then merge it with data collected from annotations, but this one seems easier to implement.

**Comment by bfanger** [comment]
Makes sense, but i'd would expect it to work only when `@SWG\Info` is a standalone annotation, not when it's inside a `@SWG\Swagger`annotation like in the example.

**Comment by codedokode** [comment]
But as I understand, `@SWG\Info` is always used inside `@SWG\Swagger` and not by itself.

**Comment by bfanger** [comment]
Like other annotations like `@SWG\Get`,  `@SWG\Info` will also be automatically merged into the OpenApi annotation
