### ISSUE TITLE
Possible to generate annotations from existing swagger?

### ISSUE THREAD

**Issue by ccorliss** [zircote/swagger-php#541]
Would like to use this for a project that already has a swagger definition. Is there any way to generate annotations from the definition?

**Comment by sonrac** [comment]
@ccorliss Help me finished )) 
https://github.com/sonrac/swagger-json-to-comments
It's impossible now

**Comment by bfanger** [comment]
I't a good idea, but im closing this issue because it's outside the scope of this project.
