### ISSUE TITLE
how use json string for parameter default value

### ISSUE THREAD

**Issue by toxmc** [zircote/swagger-php#542]
*     @SWG\Parameter(
     *         name="query",
     *         in="query",
     *         description="查询参数",
     *         type="string",
     *         default={"ajax":"config"}
     *     ),

![image](https://user-images.githubusercontent.com/3990846/41951372-2f5e3fcc-79fd-11e8-8fb4-bc8c9bceee0e.png)

thk.

**Comment by bfanger** [comment]
As far as swagger is concerned it's a **string**, so the default value should also be documented as a string:

     *     @SWG\Parameter(
     *         name="query",
     *         in="query",
     *         description="查询参数",
     *         type="string",
     *         default="{""ajax"":""config""}"
     *     ),

**Comment by toxmc** [comment]
thank you very much.
