### ISSUE TITLE
Handle nullable properties when determining type

### ISSUE THREAD

**Issue by Tobion** [zircote/swagger-php#544]
Swagger automatically determines the type of a property based on the `@var` annotation. The problem is that this does not work as soon as the property is nullable, i.e. annotated with `@var string|null`. But this is often needed when fields are optional.

So the following code does not correctly generate the right swagger type for the property.

```php
    /**
     * @var string|null
     * @SWG\Property()
     */
    public $prop;
```

A workaround is to make it explicit like 

```php
    /**
     * @var string|null
     * @SWG\Property(type="string")
     */
    public $prop;
```

But that is really annoying and creates a lot of duplicate annotations esp. with class types like `@var MyClass|null`. So it would be good if swagger php ignores the `null` type and makes this work automatically.

**Comment by bfanger** [comment]
Agreed, could you creatie a pull-request?

explode() the type by `|` and remove `null` in the augment property processor should be double.

**Comment by DSB** [comment]
I just added PR 584 to solve this. See https://github.com/zircote/swagger-php/pull/584
