### ISSUE TITLE
It is not possible to re-use query parameters. Symfony Forms can not be used for query parameters too.

### ISSUE THREAD

**Issue by devXpro** [zircote/swagger-php#548]
In the old version, I could just write:   

    /**
     * @ApiDoc(
     *      section = "Some section",
     *      description = "Some description",
     *      input = {
     *          "class" = "CoreBundle\Form\Type\DatagridFormType",
     *          "name" = null,
     *     }
     * )
    **/

DatagridFormType - this is a form that includes all the necessary parameters for displaying the list, pagination, sorting, and filtering (This is very convenient, because I use the same form for mapping my request and decorating the query builder.)

In the new version, the form can only be used for parameters in the request body, and it's really crazy!
Well, I do as written in the documentation, I duplicate all the fields of my form in the annotation:

     /**
     * @SWG\Get(
     *     tags={"Projects"},
     *     description="Get all projects",
     *     consumes={"application/json"},
     *     @SWG\Parameter(
     *          name="search",
     *          in="query",
     *          type="string",
     *          description="Search by any fields in datagrid"
     *     ),
     *     @SWG\Parameter(
     *          name="sort_field",
     *          in="query",
     *          type="string",
     *          description="Name of sorting field"
     *     ),
     *     @SWG\Parameter(
     *          name="sort_order",
     *          in="query",
     *          type="string",
     *          description="asc or desc"
     *     ),
     *     @SWG\Parameter(
     *          name="limit",
     *          in="query",
     *          type="integer",
     *          description="limit"
     *     ),
     *     @SWG\Parameter(
     *          name="page",
     *          in="query",
     *          type="integer",
     *          description="page"
     *     ),
....

It's not such a big trouble, it's written once. But the most deadly thing is that I need to copy paste this anotation into all  routes with lists. This is total craziness. And there is no way to load the SWG\Parameter into a specific group and re-use it. Please explain to me what to do?

**Comment by bfanger** [comment]
There is no built-in way to do this.

However you could write a custom annotation or write a processor.
With a custom processor you can write something like:
`@SWG\Parameter(type="searchfields")`

And the processor can generate the parameter annotations, inject them into the operation annotation and then remove the placeholder annotation.
