### ISSUE TITLE
Where to put header definition for swagger security

### ISSUE THREAD

**Issue by AngelLG** [zircote/swagger-php#549]
I want to get some security in my swagger project, so I wanted to define an api-key for security. The problem is that I don't know where to put the api-key's name in my code, I just know how to put the swagger-php annotation.

My code for security is looking like this:

 * @swg\SecurityScheme(
 *	type="apiKey",
 *	securityDefinition="SuperAPI-Key",
 *	in="header",
 *	name="X-API-Key"
 * )

Where do I define X-API-Key ?

**Comment by bfanger** [comment]
The "X-API-Key" is given to you by your rest client as an http header.
Then in the rest server just look at the `$_SERVER['HTTP_X_API_KEY']` value.
