### ISSUE TITLE
Swagger ui global response content type

### ISSUE THREAD

**Issue by verschoof** [zircote/swagger-php#552]
When I look at; https://petstore.swagger.io/#/pet/getPetById
At the right top I can select what kind of response content type I want.

How to do this in Swagger PHP?

I noticed when I use the `MediaType` the `$mediaType` is required, I could not find this back in the specs, but I think when you have a `MediaType` to a `MediaType` swagger-ui will render a little box above the reponse.

Pet Store: (notice the right top corner)
<img width="1432" alt="screen shot 2018-07-17 at 09 04 21" src="https://user-images.githubusercontent.com/1527863/42801739-e533794a-89a0-11e8-9695-0e18aa886987.png">

Own example: (notice the select input near the response)
<img width="1427" alt="screen shot 2018-07-17 at 09 07 34" src="https://user-images.githubusercontent.com/1527863/42801740-e5514628-89a0-11e8-95f5-3fbc0c47c3c1.png">

When I inspect the pet store json I notice they got a key `produces`:
<img width="593" alt="screen shot 2018-07-17 at 09 10 26" src="https://user-images.githubusercontent.com/1527863/42801888-6885237a-89a1-11e8-8d87-e20bd51cbab3.png">

**Comment by bfanger** [comment]
`produces={"application/xml", "application/json"},`Like this: https://github.com/zircote/swagger-php/blob/2.x/Examples/petstore.swagger.io/controllers/PetController.php#L98

**Comment by verschoof** [comment]
@bfanger thanks for your reply.

I have api-wide only json, is there a way I can set this globally?

**Comment by bfanger** [comment]
You can set this globally in the [swagger object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object):
 `@SWG\Swagger(produces={"application/xml", "application/json"})`

**Comment by verschoof** [comment]
@bfanger I don't understand, I don't see any swagger object annotation:
https://github.com/zircote/swagger-php/tree/master/src/Annotations

**Comment by bfanger** [comment]
Not in the (not yet released) 3.x OpenApi version, (it's been renamed to OpenApi).
Look in the [2.x branch](https://github.com/zircote/swagger-php/tree/2.x/src/Annotations)

**Comment by verschoof** [comment]
Ah, I was already using the 3.x OpenApi version that explains :)

What is smart to do? Continue with the 3.x or change everything to 2.x?

**Comment by bfanger** [comment]
I suggest keep using 3.x. i'll probably release 3.0.0 next week or so.

**Comment by verschoof** [comment]
Ok thanks, I will wait for that! :)
