### ISSUE TITLE
Feature Request: Change Annotation classes to be reusable

### ISSUE THREAD

**Issue by gareth-ib** [zircote/swagger-php#554]
The current annotation classes have `extends AbstractAnnotation`.
So from what I can tell, they can't be directly reused by another Swagger system passing the swagger parsed content into the constructor.

If those object specific properties could be moved into a Trait to be used as..

```php
trait Parameter {
    public $ref;
    ....
}
```

```php
class Parameter extends AbstractAnnotation{
 use Parameter;
}
```

( or possibly another setup )

This style would allow direct usage (reusage) of the trait by other swagger extension concepts that want the proper object structure and validation ability without the constructor rules.

My current usage goal is for a SWG generation system that needs these object rules before having finalized full docs ready. And having a direct link to the true-north source so-to-speak would keep things in line a lot better for myself and any other potential 3rd party helper projects.

I can do literal tests but would want to get feedback on potential acceptance before starting implementation

thanks!

**Comment by bfanger** [comment]
Sorry, but the inheritance model works for us, changing this to traits adds overhead (mental overhead, more files and an invisible contract to external code) 

All annotation use the same constructor and it's not that difficult to create an "empty" annotation instance, using reflection is another option to "align to the true north"

The validation-system is not optimal and i'd rather see that code live outside of the annotation classes similar to the processors.

Let us known when your project is taking shape, we'll gladly link to it on the [Related projects](http://zircote.com/swagger-php/Related-projects.html) page.

**Comment by gareth-ib** [comment]
oh how do you make the empty instance? When looking at the `AbstractAnnotation` it looked like it required population data in the constructor

**Comment by bfanger** [comment]
You can polulate the values, but when you pass an empty array you'll get an empty annotation object.
(Only the _context wil be populated)
