### ISSUE TITLE
Unable to install package with @OAS instead of @Swg

### ISSUE THREAD

**Issue by rvkulikov** [zircote/swagger-php#555]
When I do `composer update` with `"zircote/swagger-php": "dev-master"` it installing not the latest version of package (commit 9baab653504cb5e665567f4e9890f9ed08703a2a) but previous (commit 66a1662068b6da3fbfa552d2fbbb1e8b3753c52c).

Packagist dev-master pointing to commit 66a1662068b6da3fbfa552d2fbbb1e8b3753c52c

So I can't use any of OpenApi annotations because there is different namespaces between this commits.
There is an error like `Class 'OpenApi\StaticAnalyser' not found`.
Am I doing something wrong?

comoser.json
```json
{
  "name": "project",
  "type": "project",
  "minimum-stability": "dev",
  "require": {
    "php": ">=7.2.0",
    "zircote/swagger-php": "dev-master",
  },
  "config": {
    "process-timeout": 1800,
    "fxp-asset": {
      "enabled": false
    }
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://asset-packagist.org"
    }
  ]
}
```

composer.lock
```json
{
  "name": "zircote/swagger-php",
  "version": "dev-master",
  "source": {
    "type": "git",
    "url": "https://github.com/zircote/swagger-php.git",
    "reference": "66a1662068b6da3fbfa552d2fbbb1e8b3753c52c"
  },
  "dist": {
    "type": "zip",
    "url": "https://api.github.com/repos/zircote/swagger-php/zipball/66a1662068b6da3fbfa552d2fbbb1e8b3753c52c",
    "reference": "66a1662068b6da3fbfa552d2fbbb1e8b3753c52c", // not the latest commit
    "shasum": ""
  },
  "require": {
    "doctrine/annotations": "*",
    "php": ">=7.0",
    "symfony/finder": ">=2.2"
  },
  "require-dev": {
    "phpunit/phpunit": ">=6.3",
    "squizlabs/php_codesniffer": ">=2.7",
    "zendframework/zend-form": "<2.8"
  },
  "bin": [
    "bin/swagger"
  ],
  "type": "library",
  "autoload": {
    "psr-4": {
      "Swagger\\": "src" // OpenApi Expected
    },
    "files": [
      "src/functions.php"
    ]
  },
  "notification-url": "https://packagist.org/downloads/",
  "license": [
    "Apache2"
  ],
  "authors": [
    {
      "name": "Robert Allen",
      "email": "zircote@gmail.com",
      "homepage": "http://www.zircote.com"
    },
    {
      "name": "Bob Fanger",
      "email": "bfanger@gmail.com",
      "homepage": "http://bfanger.nl"
    }
  ],
  "description": "Swagger-PHP - Generate interactive documentation for your RESTful API using phpdoc annotations",
  "homepage": "https://github.com/zircote/swagger-php/",
  "keywords": [
    "api",
    "json",
    "rest",
    "service discovery"
  ],
  "time": "2018-06-20T09:21:32+00:00"
}
```

**Comment by bfanger** [comment]
This looks like a bug in composer. (might be fixed, run `self-update` to use the latest composer.)

You can also try removing and reinstalling swagger-php instead of an update

**Comment by rvkulikov** [comment]
Updated composer, removed and installed for multiple times. The same bad result

```composer.json
{
  "type": "project",
  "minimum-stability": "dev",
  "require": {
    "php": ">=7.2.0",
    "zircote/swagger-php": "dev-master"
  }
}
```

Local machine:
![local](https://user-images.githubusercontent.com/21280882/43153829-0bc611dc-8f7b-11e8-92cf-cdbac0a0d56e.png)
Remove VPS:
![vps](https://user-images.githubusercontent.com/21280882/43153840-11668f18-8f7b-11e8-9d9f-2b5a1e6bdc45.png)

Both machines downloading old commit 66a1662068b6da3fbfa552d2fbbb1e8b3753c52c
And that is that packagist points to:
![Packagist](https://user-images.githubusercontent.com/21280882/43153921-4d646404-8f7b-11e8-93f5-93684f3ca461.png)

Could you please recheck packagist version of package?

**Comment by rvkulikov** [comment]
Maybe this could help https://github.com/composer/packagist/issues/587#issuecomment-142332424

**Comment by bfanger** [comment]
@zircote Could you add me as maintainer in packagist, so i can press the "update" button?

**Comment by zircote** [comment]
@bfanger done.

**Comment by rvkulikov** [comment]
Everything works fine now. Thanks to everyone.
