### ISSUE TITLE
The InheritProperties does not work as expected

### ISSUE THREAD

**Issue by penja** [zircote/swagger-php#556]
@bfanger The [InheritProperties processor](https://github.com/zircote/swagger-php/blob/master/src/Processors/InheritProperties.php) that was added by proposal https://github.com/zircote/swagger-php/issues/348 does not work correctly with `allOf` schema property. 
Example.
```
namespace OpenApiFixtures;

/**
 * @OA\Schema()
 */
class BaseModel {

    /**
     * @OA\Property();
     * @var string
     */
    public $baseProperty;
}
```
And
```
/**
 *  @OA\Schema(
 *   schema="ExtendedModel",
 *   allOf={
 *      @OA\Schema(ref="#/components/schemas/BaseModel"),
 *   }
 * )
 */
class ExtendedModel extends BaseModel
{

    /**
     * @OA\Property();
     * @var string
     */
    public $extendedProperty;
}
```
Generate 
```
{
	"schema": "BaseModel",
	"properties": {
		"baseProperty": {
			"type": "string"
		}
	}
}
```
And
```
{
	"schema": "ExtendedModel",
	"properties": {
		"baseProperty": {
			"type": "string"
		}
	},
	"allOf": [{
		"properties": {
			"extendedProperty": {
				"type": "string"
			}
		},
		"$ref": "#\/components\/schemas\/BaseModel"
	}]
}
```
As you see, we have an extra property `baseProperty` in `ExtendedModel`.

We must not inherit the properties of the base class if these properties are inherited by a openapi. That fields should be in existing list in `InheritProperties` processor.

Can you tell how get the annotation object `BaseModel` by reference `#/components/schemas/BaseModel`? And I will prepare a PR that will solve this problem.

**Comment by bfanger** [comment]
I suggest to following  behavior of the new InheritProperties processor:

- If the parent class doesn't have an annotation then inject/copy the properties into the  child (current behavior).

- If the parent class has an annotation and the allOf in the child is empty, create the allOf with a $ref to the parent.
  
- If the parent class has an annotation and the allOf in the child is set, do nothing and allow the author the flexibility to set it anything including an `[]`, perhaps hide the allOf in the output if it's empty.

> Can you tell how get the annotation object BaseModel by reference.

This is tricky but possible, you can get the annotation and look at its `_context`, this should allow us to generate the ref when the annotation has been placed in the tree. 
Adding a ref() function to `AbstractAnnotation` would be useful, we'd have to change the ref() function in in the OpenApi to just return "#/" when no arguments are given. 

If you've any questions let me know.

**Comment by penja** [comment]
@bfanger Thanks is a good suggestions. Will you fix it or should I prepare the PR?

**Comment by bfanger** [comment]
I'd greatly appreciate if you could create a PR.
