### ISSUE TITLE
Struggling with enums

### ISSUE THREAD

**Issue by verschoof** [zircote/swagger-php#558]
Hi,

I want to be able to select multiple enums.

```
 * @OAS\Parameter(
 *   parameter="tags",
 *   name="tags",
 *   in="query",
 *   description="Filter by multiple tags",
 *   required=false,
 *   @OAS\Schema(
 *     type="array",
 *     collectionFormat="multi",
 *     @OAS\Items(
 *       type="string",
 *       enum={"tag1", "tag2"}
 *     )
 *   )
 * ),
```

Result is that I can select the enums, looks good, but when I execute the query:
```
curl -X GET "http://localhost/v1/call?tag=tag1&tag=tag2" -H  "accept: application/json"
```
Since the tag is overridden by the last tag I only get 1 tag as string, while I expect an array..

I expect the following call:
```
curl -X GET "http://localhost/v1/call?tag[]=tag1&tag[]=tag2" -H  "accept: application/json"
```

How can I do this?

**Comment by bfanger** [comment]
Change the name to "tags[]"

**Comment by verschoof** [comment]
Ah nice one, still feels like a workaround :)
I would expect that the lib would do this, for example, multiple=true in the Parameter annotation so that will add the `[]` behind it? :)

Thanks @bfanger
