### ISSUE TITLE
User Notice: $ref not found for @OA\Response()

### ISSUE THREAD

**Issue by AlexBBBril** [zircote/swagger-php#566]
Hello! I used 3.x-dev swagger-php version.There are error notice for @OS\Response()

User Notice: $ref \"#/components/responses/400\" not found for @OA\\Response() in GetProfileAction.php on line 19

@OA\Response(response=400, ref="#/components/responses/400")

Response:
```
 * @OA\Response(
 *     response=400,
 *     @OA\MediaType(
 *         mediaType="application/json",
 *         @OA\Schema(ref="#/components/schemas/Error")
 *     )
 * )
```

Error:
```
 * @OA\Schema(
 *     schema="Error"
 * )
```

At the moment, i fixed it by setting a stub for the OpenApi\scan function
```
@scan([
   ...
])
```

Thanks!

**Comment by bfanger** [comment]
Fixed, thanks for reporting the issue.
