### ISSUE TITLE
Cannot run generate command

### ISSUE THREAD

**Issue by vitxd** [zircote/swagger-php#569]
Using the current 3-0 branch every time I run generate command it throws this error:

```
 $ref "#/components/schemas/@OA\UNDEFINED🙈" not found for @OA\Schema() in /var/www/vhosts/dev/app/Http/Requests/CreateRequest.php on line 7
```
But at line 7 of CreateRequest.php there is no usage of UNDEFINED🙈 constant.

The error has been introduced with commit 70316e3411a203b73dab270f180b0f25e25f22fe 

Thanks!

**Comment by bfanger** [comment]
Ah, since then all properties are _undefined_ by default. I've changed most checks but checking for _null_ can be done in multiple ways. looks like i missed one.

Can you provide an example that generates this bug?

**Comment by bfanger** [comment]
I tried but was unable to reproduce the issue.

Could you provide the annotations that lead to this bug?

**Comment by vitxd** [comment]
It's a weird scenario. I'm using l5-swagger to read through the code and it throws that error. however when I extract it and only use your library, everything works. Using it through the l5-swagger command I can remove the error by removing the properties in this schema:

```php
/**
 * @OA\Schema(
 *   schema="update_shop_request",
 *   description="Shop model",
 *   type="object",
 *   title="Shop model",
 *   @OA\Property(
 *     property="internal_shop_number",
 *     ref="#/components/schemas/Shop/properties/internal_shop_number",
 *   ),
 *   @OA\Property(
 *     property="ledger_number",
 *     ref="#/components/schemas/Shop/properties/ledger_number",
 *   ),
 *   @OA\Property(
 *     property="name",
 *     ref="#/components/schemas/Shop/properties/name",
 *   ),
 *   @OA\Property(
 *     property="district_id",
 *     ref="#/components/schemas/District/properties/id",
 *   ),
 *   @OA\Property(
 *     property="shop_type_id",
 *     ref="#/components/schemas/ShopType/properties/id",
 *   )
 * )
 */
```

**Comment by bfanger** [comment]
When I run your annotation I get:
```
$ref "#/components/schemas/Shop/" not found for @OA\Property() in /Users/bob/test.php on line 2
$ref "#/components/schemas/Shop/" not found for @OA\Property() in /Users/bob/test.php on line 2
$ref "#/components/schemas/Shop/" not found for @OA\Property() in /Users/bob/test.php on line 2
$ref "#/components/schemas/District/" not found for @OA\Property() in /Users/bob/test.php on line 2
$ref "#/components/schemas/ShopType/" not found for @OA\Property() in /Users/bob/test.php on line 2
```
It could be an issue with l5-swagger

**Comment by vitxd** [comment]
it might, but that means I cannot use this version for now and unfortunately I cannot put more time on this. I might come back once I finished this project :) Feel free to close this, I might re open it when I have more information

**Comment by bfanger** [comment]
👍
