### ISSUE TITLE
Unable to run command vendor/bin/openapi --help

### ISSUE THREAD

**Issue by shantanuaggarwal2695** [zircote/swagger-php#578]
I am unable to run the command vendor/bin/openapi --help as it is showing the error:
Exception: Class 'Doctrine\Common\Annotations\AnnotationRegistry' not found

![screenshot from 2018-09-03 13-21-07](https://user-images.githubusercontent.com/29815001/44974095-44cea900-af7c-11e8-9c20-949da532f031.png)

**Comment by bfanger** [comment]
Looks like the [doctrine annotations](https://github.com/doctrine/annotations) was not installed.

Did you use [composer](https://getcomposer.org) to install swagger-php?

**Comment by shantanuaggarwal2695** [comment]
Yes I used composer require zircote/swagger-php

**Comment by shantanuaggarwal2695** [comment]
![screenshot from 2018-09-03 13-36-23](https://user-images.githubusercontent.com/29815001/44974813-60d34a00-af7e-11e8-9785-d51b58f8b010.png)
Issue in line 14: unable to find this class

**Comment by bfanger** [comment]
Weird, composer should install that class and provide autoloading

**Comment by shantanuaggarwal2695** [comment]
![screenshot from 2018-09-03 14-31-59](https://user-images.githubusercontent.com/29815001/44977627-240b5100-af86-11e8-8595-71e7ccd9542e.png)

**Comment by shantanuaggarwal2695** [comment]
Should I reinstall the composer or vendor?

**Comment by bfanger** [comment]
I'm seeing a lot of **dev-master** ( unreleased / unstable ) versions. 

You'll need to look into your [prefer-stable](https://getcomposer.org/doc/04-schema.md#prefer-stable) and [minimum-stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) settings for composer.

**Comment by shantanuaggarwal2695** [comment]
![screenshot from 2018-09-03 17-30-52](https://user-images.githubusercontent.com/29815001/44985775-24641600-af9f-11e8-8831-e8bba058f660.png)
 This is the version of my doctrine annotations

**Comment by bfanger** [comment]
That's the same version as mine, that one has `vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php`
which should be autoloaded with psr4
my `vendor/composer/autoload_psr4.php` contains the correct autoloader configuration.
```php
'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib/Doctrine/Common/Annotations'),
```

Did you move the `src/bin/openapi`? Because it tries to include `vendor/autoload.php` from two locations.
Maybe that failed in you case, try debugging lines 119-125:
```php
    if (file_exists(__DIR__.'/../vendor/autoload.php')) {  // cloned / dev environment?
        require_once(__DIR__.'/../vendor/autoload.php');
    } else {
        require_once(realpath(__DIR__.'/../../../').'/autoload.php');
    }
```
to make sure composer was loaded.

**Comment by shantanuaggarwal2695** [comment]
My openapi file is in zircote/swagger-php/bin and I have the same script written in lines 119-125 
    if (file_exists(__DIR__.'/../vendor/autoload.php')) {  // cloned / dev environment?
        require_once(__DIR__.'/../vendor/autoload.php');
    } else {
        require_once(realpath(__DIR__.'/../../../').'/autoload.php');
    }
Do I need to debug these lines?

**Comment by bfanger** [comment]
Yep, if these lines are executed and include the autoload.php the issue lies in composer and there is nothing I can do.

Another thing you can try is removing the vendor folder and the composer.lock file, Update composer `composer self-update` and run `composer install`

**Comment by shantanuaggarwal2695** [comment]
I have debugged the issue.

Thanks
