### ISSUE TITLE
Documentation for the OA tags

### ISSUE THREAD

**Issue by layinka** [zircote/swagger-php#580]
Hi,
Is there somewhere i can find the documentation for the OA tags, like what tags are possible and how to use them.

**Comment by gjergjsheldija** [comment]
hi @layinka 
you can look in the docs folder which are also hosted here http://zircote.com/swagger-php/ and on the official swagger page https://swagger.io/specification/

**Comment by bfanger** [comment]
It would be nice if we could generate documentation similar to the [1.x docs](http://zircote.com/swagger-php/1.x/annotations.html) from the `src/Annotations/*.php` files.

Community contributions are highly encouraged.

For now the [open api docs](https://swagger.io/docs/specification/about/) and the [specification](https://swagger.io/specification/) are the recommended reads. The annotations map very closely to the specification so you'd quickly learn how to write annotations based on the spec.
