### ISSUE TITLE
On reloading Swagger UI, it is loosing the authentication

### ISSUE THREAD

**Issue by nahojj** [zircote/swagger-php#581]
It seems like the authentication be lost if you're reloading the browser for the L5 Swagger UI.

I'm using the securityScheme like this: 
`
         /** @SWG\SecurityScheme(
          *   securityDefinition="passport",
          *   type="oauth2",
          *   tokenUrl="/oauth/token",
          *   flow="password",
          *   scopes={}
          * ),
`

**Comment by bfanger** [comment]
This is not a bug in the swagger-php project.
Swagger-php is only responsible for generating the json.

My guess would be that swagger-ui doesn't persist the token between reloads.

IPlease investigate the issue and report it to the appropriate probect.
