### ISSUE TITLE
No response in SwaggerUI

### ISSUE THREAD

**Issue by shantanuaggarwal2695** [zircote/swagger-php#587]
While generating a response from the given URL, I am getting a network-type error.

Code and response has been attached.
![screenshot from 2018-09-27 11-55-44](https://user-images.githubusercontent.com/29815001/46126900-7d486680-c24c-11e8-8f5d-3e0367ac7771.png)
![screenshot from 2018-09-27 11-54-44](https://user-images.githubusercontent.com/29815001/46126901-7d486680-c24c-11e8-8d92-190cb7a4d8d4.png)

**Comment by bfanger** [comment]
swagger-php is only responsible for generating the yaml/json 

- Implementing the api, hosting, etc is up to you. 
- Bugs in swagger-ui should be reported to the swagger-ui project.
