### ISSUE TITLE
Mimicing parameter groups

### ISSUE THREAD

**Issue by nolanpro** [zircote/swagger-php#589]
Since there hasn't been any movement [on this issue at OAI](https://github.com/OAI/OpenAPI-Specification/issues/445), can this package mimic the functionality by looping over items in a kind of  "psudo group ref" annotation and outputting the parameters as regular parameter refs in the generated json document? (also requested here: https://github.com/zircote/swagger-php/issues/311)

Glad to submit a PR but was wondering what your opinion is before I work on it. Thanks!

**Comment by bfanger** [comment]
Try  creating that feature as a plugin, i'll gladly link to it from the [Related projects](http://zircote.com/swagger-php/Related-projects.html) page.

**Comment by nolanpro** [comment]
I'll look into doing it that way, thanks!
