### ISSUE TITLE
[RFC] Support callbacks for `Property::$enum`

### ISSUE THREAD

**Issue by phansys** [zircote/swagger-php#590]
I need a way to allow the `enum` property to resolve method callbacks in order to avoid hardcoding their return values. My proposal is something like this:
```
@SWG\Property(
    property="locale",
    enum=DateTimeZone::listIdentifiers(),
    type="string"
 )
```

Note that in this example I'm using [`DateTimeZone::listIdentifiers()`](https://php.net/manual/en/datetimezone.listidentifiers.php) instead of hardcoding a long array containg the method's result.

What do you think?

**Comment by bfanger** [comment]
Looks fine too me, but it's outside the scope of the swagger-php project, once implemented in doctrine-annotations (which swagger-php and others  use) it will become available.

Please submit to RFC there.
