### ISSUE TITLE
how to generate an empty array instead of an empty object?

### ISSUE THREAD

**Issue by jinseokoh** [zircote/swagger-php#591]
With the following annotations,

```
     * @OA\SecurityScheme(
     *     type="apiKey",
     *     in="header",
     *     securityScheme="api_key",
     *     name="api_key"
     * )
     * @OA\Post(
     *     path="/api/v1/create",
     *     security={
     *       {"api_key":{}}
     *     },
     *     @OA\Response(
     *         response="default",
     *         description="successful operation"
     *     )
     * )
```

it generates

```
      security:
        -
          api_key: {  }
```

while the expected output based on OpenApi v3 documentation is as follows:
```
    security:
      - api_key: [] 
```

How can I produce an empty array instead of empty object? This Doctrine annotation's pretty confusing.

**Comment by bfanger** [comment]
The bug was in the yaml conversion, that one converted the empty array to an empty object.

I've added the `Yaml::DUMP_EMPTY_ARRAY_AS_SEQUENCE` flag.
