### ISSUE TITLE
Does the library support the pattern option ?

### ISSUE THREAD

**Issue by sadokmtir** [zircote/swagger-php#594]
I could not see any result for using the pattern option on the requested parameter.

I wanted to have something like this in the OpenAPI: [Pattern Section]( https://swagger.io/docs/specification/data-models/data-types/ )

> The pattern keyword lets you define a regular expression template for the string value. Only the values that match this template will be accepted.

What I tried so far that did not work:
```
    /**
     * @SWG\Parameter(
     *     name="test",
     *     in="query",
     *     required=true,
     *     type="array",
     *     items=@SWG\Items(
     *         type="string",
     *         pattern ="^-\d{2}-\d{4}$"
     *     )
     * )
     */
```

**Comment by bfanger** [comment]
Yes, [we do](https://github.com/zircote/swagger-php/blob/2.x/src/Annotations/Schema.php#L133). But swagger-php is only responsible for generating the yaml/json.
It might not be supported in a client like swagger-ui or in the v2  spec. 
_(you've linked to v3 docs but use v2 annotations)_
