### ISSUE TITLE
Add any auth

### ISSUE THREAD

**Issue by MitinSany** [zircote/swagger-php#595]
Please, add in config a name of middleware, which add to routes. It will be used for add protection

**Comment by bfanger** [comment]
Swagger-php has support for documenting diff erent methods of authentication. 
But concepts as "middleware" , "routes" are outside the scope of swagger.

**Comment by floggle** [comment]
The OpenAPI spec specifies which auth types are permitted:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#securitySchemeObject

```
type	string	Any	REQUIRED. The type of the security scheme. Valid values are "apiKey", "http", "oauth2", "openIdConnect".
```
So this ticket is for the OpenAPI spec, not swagger-php
