### ISSUE TITLE
Root level Security requirement object

### ISSUE THREAD

**Issue by floggle** [zircote/swagger-php#598]
Is it possible to define a top/root level security requirement with swagger-php?

The OA3 Spec says by implication that it should be possible to have a top level security requirement:
"This definition overrides any declared top-level security." for the "security" field for Operation Objects
There are plenty of examples of hand-crafted OA files with this including - https://swagger.io/docs/specification/authentication/

But I can't seem to declare such an object in swagger-php.
I have tried all of:
`@OA\SecurityRequirementsObject
@OA\SecurityRequirements
@OA\SecurityRequirement
@OA\Security`
All give me "the annotation ... does not exist".

I've also looked at every occurrence of the word "security" that github brings up for a search in this project, and there are no instances of it being used at the top level as best I can tell.
A couple of files mention "Security Requirements Objects" (https://github.com/zircote/swagger-php/blob/26c9e75fdec48aa07ed7d6dc255ad2fa10250ece/src/Annotations/OpenApi.php), but as above I've not been able to use them as a top level item.

How is it done?

**Comment by bfanger** [comment]
You first define a `@OA\SecurityScheme` which you can then reference by name.

To use it at the root level you'll write:

```php
/**
 * @OA\OpenApi(
 *   security={"MyAuth":{"myScope"}}
 * )
 */
```
Which doesn't have an annotation because the properties are variable, which is why swagger-php uses  inline objects and arrays. It's a bit confusing because the `{` `}` are used for both objects and arrays.

**Comment by floggle** [comment]
@bfanger - Thanks. I'm a little late in replying, but this doesn't work.

It creates this as in the json:
```
    "security": {
        "api_key_query": [],
        "api_key_header": []
    },
```
which fails validation (both speccy, *and* swagger-cli). The spec is clear that it needs to be a "list" (array), but swagger-php is create an object (what both the lints say too). I can't seem to generate such a list with swagger-php - if I force square brackets in the @OA\OpenAPI it fails with a `PlainValue` expected error.

I expect the output to be:
```
    "security": [
        "api_key_query": [],
        "api_key_header": []
    ],
```

The result is meant to mean that one of api_key_query or api_key_header is required for all requests.

Examples of others using lists:
https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-6-defining-security/
https://idratherbewriting.com/learnapidoc/pubapis_openapi_step6_security_object.html

**Comment by bfanger** [comment]
Generating the output you expect Is impossible.
```json
  "security": [
        "api_key_query": [],
        "api_key_header": []
    ],
```
Is not valid json. Arrays and objects are different in javascript compared to php.

What you'll need is yet another `{` `}` wrapping the object into a list.

```php
/**
 * @OA\OpenApi(
 *   security={
 *     {
 *       "api_key_query": {},
 *       "api_key_header": {}
 *      }
 *   }
 * )
```
which generates:
```json
"security": [
        {
            "api_key_query": [],
            "api_key_header": []
        }
    ]
```

**Comment by kurt-wasabi** [comment]
Hi. I too am trying to get:
"security": [ { "bearerAuth":  [] } ]
to appear at root level, with absolutely no success. All I can get is:
"security": [ [] ]

I've tried all kinds of things in the annotations. My latest is shown below.

Any assistance would be greatly appreciated.

    /**
     *  @OA\Info(
     *      version="1.0.0",
     *      title="xxx",
     *      description="xxx",
     *      @OA\Contact(
     *          email="xxx"
     *      )
     *  ),
     * 
     *  @OA\Server(
     *      url=L5_SWAGGER_CONST_HOST,
     *      description="xxx"
     *  ),
     * 
     *  @OA\Components(
     *      @OA\SecurityScheme(
     *          securityScheme="bearerAuth",
     *          in="header",
     *          name="bearerAuth",
     *          type="http",
     *          scheme="bearer",
     *      ),
     *  )
     */

    /**
     * @OA\OpenApi(
     *  security={{"bearerAuth": {}}}
     * )
     */
