### ISSUE TITLE
Complex navigation panel with OpenAPI v3

### ISSUE THREAD

**Issue by waghanza** [zircote/swagger-php#599]
Hello,

I'm using `swagger-php` (and https://github.com/tobilg/api2html) to generate documentation from my `symfony` `4.1` based **API**

I find this API documentation very clear https://api.gocd.org/current/#agents, but I can't find any way to add `tocify-item` in the navigation panel.

Has anyonone created such as doc ?

Regards,

**Comment by bfanger** [comment]
This question is outside the scope of this project. 

Feel free to re-open when you know what kind of yaml (or json) api2html expects. (and you're having trouble writing the annotations to generate that output.)
