### ISSUE TITLE
formData not supported for 'in' attribute of a Parameter

### ISSUE THREAD

**Issue by matueranet** [zircote/swagger-php#600]
Thanks for a great library. I am incorporating it in a project, but running into a problem with the definition of POST parameters.

According to the OpenAPI specs, formData, should be used for parameters send via POST. Unfortunately swagger-php does not support this, it throws an error:

`Notice: @OA\Parameter(name="refreshToken",in="formData")->in "formData" is invalid, expecting "query", "header", "path", "cookie" ...`

Is there something I am overlooking here?

**Comment by matueranet** [comment]
Never mind, I see now that the referenced link was for OpenAPI version 2.0, 3.0 is different. (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject vs https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#parameterObject)

**Comment by bfanger** [comment]
formData was used in the older v2 spec.

See [Describing RequestBody](https://swagger.io/docs/specification/describing-request-body/) for more info
