### ISSUE TITLE
Vendor annotations

### ISSUE THREAD

**Issue by mfauveau** [zircote/swagger-php#601]
Is there a way to add vendor annotations at the root level? I'm talking about these: https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md

**Comment by mtveerman** [comment]
Same question here. I've been trying to get a vendor extension into the `Info` part. No luck, maybe because `Property` is not in the `nested` list of `Info`?

Also looking for this because I use ReDoc as well.

**Comment by mfauveau** [comment]
@mtveerman adding them to info is actually fairly simple. See:
```

**Comment by mtveerman** [comment]
@mfauveau Well, have been trying a lot of options except for that one. Thanks.

By the way, this worked for be, but I had to remove the quotes around the `x`: 

```
@OA\Info(
 x={
   "logo":{
      "url":"http://url-to-logo"
    }
  }
)
```

**Comment by bcshelton72** [comment]
This would be a good addition to the top level docs - how to accomodate extensions.

**Comment by bfanger** [comment]
Nobody reads the docs ;-) https://zircote.github.io/swagger-php/Getting-started.html#vendor-extensions
