### ISSUE TITLE
docker integration with docker automated build

### ISSUE THREAD

**Issue by axklim** [zircote/swagger-php#602]
I used docker:
> Generate the swagger documentation to a static json file.
> docker run -v "$PWD":/app -it tico/swagger-php --help

but now I needed in swagger-php v3.0.1. `tico/swagger-php ` - don't allow make it :(

**Comment by axklim** [comment]
https://github.com/zircote/swagger-php/pull/603

**Comment by rakshazi** [comment]
Fixed in latest commit

**Comment by axklim** [comment]
But who use older version ? Maybe on this repo build images ?

**Comment by rakshazi** [comment]
I cannot give you answer - I have no statistics.
We use it inside our company with private docker registry and image in it wasn't updated very long time. On public registry image updating every time when composer official image got update.
