### ISSUE TITLE
Organize docs based on title

### ISSUE THREAD

**Issue by kiddyatreides** [zircote/swagger-php#604]
Hi, currently I'm using Swagger v2.

I wanna ask, is it possible to organize the documentation based on name? As example I want to write API Docs about User and then I want to write API Docs about Products. I'm only see default title at the top. How could I organize the docs?

**Comment by bfanger** [comment]
You can use tags. See [Grouping Operations With Tags](https://swagger.io/docs/specification/2-0/grouping-operations-with-tags/) for more info
