### ISSUE TITLE
Could not open input file: ../vendor/bin/swagger

### ISSUE THREAD

**Issue by OdaiTu** [zircote/swagger-php#606]
thanks for great repo

i installed it but when run this command i got an error : 

`php ../vendor/bin/swagger --bootstrap ./swagger-constants.php --output ../public/swagger ./swagger-v1.php ../app/Http/Controllers
`

Could not open input file: ../vendor/bin/swagger

how to solve it.

**Comment by bfanger** [comment]
In version 3 `swagger` has been renamed to `openapi`

**Comment by jashan12345** [comment]
h

**Comment by jashan12345** [comment]
testing
