### ISSUE TITLE
Could swagger yaml file convert to php-swagger annotation?

### ISSUE THREAD

**Issue by herb123456** [zircote/swagger-php#608]
Hi, 

I want to convert my swagger yaml file(OpenAPI 3) to php annotation

how can I do this?

**Comment by bfanger** [comment]
As far a I know you'd have to convert it manually, but that would be a nice feature. 

Try creating such a utility i'd gladly link to it on the [Related projects]http://zircote.com/swagger-php/Related-projects.html) page

**Comment by valkedev** [comment]
> Hi,
> 
> I want to convert my swagger yaml file(OpenAPI 3) to php annotation
> 
> how can I do this?

did you find any solution?
