### ISSUE TITLE
why is additionalProp1

### ISSUE THREAD

**Issue by githubzhaoqian** [zircote/swagger-php#609]
```php
    /**
     * @OA\Post(
     *     path="/v1/login",
     *     summary="登录",
     *     tags={"user"},
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(
     *                     property="email",
     *                     type="string"
     *                 ),
     *                 @OA\Property(
     *                     property="password",
     *                     type="string"
     *                 ),
     *                 example={
     *                      "email": "dashen@q.com",
     *                      "password": "1234",
     *                  }
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *         response="200",
     *         description="OK",
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(
     *                     description="Code 0 正确",
     *                     property="code",
     *                     type="integer"
     *                 ),
     *                 @OA\Property(
     *                     description="信息",
     *                     property="msg",
     *                     type="object",
     *                     @OA\AdditionalProperties(
     *                         @OA\Property(
     *                             description="信息",
     *                             property="uid",
     *                             type="integer"
     *                         ),
     *                         @OA\Property(
     *                             description="信息",
     *                             property="aaa",
     *                             type="integer"
     *                         ),
     *                         @OA\Property(
     *                             description="信息",
     *                             property="bbb",
     *                             type="integer"
     *                         )
     *                      )
     *                 )
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *         response="201",
     *         description="OK",
     *         @OA\JsonContent(
     *             @OA\Property(
     *                 description="Code 1 错误",
     *                 property="code",
     *                 type="integer"
     *             ),
     *             @OA\Property(
     *                 description="信息",
     *                 property="msg",
     *                 type="string"
     *             )
     *         )
     *     )
     * )
     */
```

```json
{
  "code": 0,
  "msg": {
    "additionalProp1": {
      "uid": 0,
      "aaa": 0,
      "bbb": 0
    },
    "additionalProp2": {
      "uid": 0,
      "aaa": 0,
      "bbb": 0
    },
    "additionalProp3": {
      "uid": 0,
      "aaa": 0,
      "bbb": 0
    }
  }
}
```

**Comment by bfanger** [comment]
`additionalProp1` is not generated by swagger-php, and therefor outside the scope of this project.

**Comment by juanitoddd** [comment]
Hello, first of all thanks for developing and maintaining this library,

I have been trying to document a similar use case, where the API Response is something like:

`{ 
success: true,
  data: {
    Event: {
       id: 26,
       location_id: 4, 
       title: "Jazz Concert",
   },
   Location: {
       id: 4,
       name: "Piccolo Pub",
   }
}
`

Just for the sake of ask, have someone give me hint how to achieve this using php annotations ?

The documentation regarding Properties and AdditionalProperties is not that clear.

Thanks in advance

**Comment by bfanger** [comment]
https://json-schema.org/understanding-json-schema/reference/object.html has a nice section about additional properties, the type you're describing can be created using with a combination of allOf, anyOf

**Comment by maxgalbu** [comment]
Hi,
apparently we can override additionalProp1/2/x with either `propertyNames` or `patternProperties` with openapi version 3.1.0:

https://stackoverflow.com/questions/46552863/how-to-write-openapi-3-swagger-specification-for-property-name-in-map-object

> OpenAPI 3.1
> OAS 3.1 fully supports JSON Schema 2020-12, including [patternProperties](https://json-schema.org/understanding-json-schema/reference/object.html#pattern-properties). This keyword lets you define the format of dictionary keys by using a regular expression:
> ```
> "Parent": {
>   "type": "object",
>   "patternProperties": {
>     "^child\d+$": {
>       "$ref": "#/components/schemas/Child"
>     }
>   },
>   "description": "A map of `Child` schemas, where the keys are IDs that correspond to the child"
> }
> ```
> 
> Or, if the property names are defined by an enum, you can use [propertyNames](https://json-schema.org/understanding-json-schema/reference/object.html#id4) to define that enum:
> 
> ```
> "Parent": {
>   "type": "object",
>   "propertyNames": {
>     "enum": ["foo", "bar"]
>   },
>   "additionalProperties": {
>     "$ref": "#/components/schemas/Child"
>   }
> }
> ```

Is this supported by swagger-php?

**Comment by DerManoMann** [comment]
No. 3.1 support is sketchy.
Happy to look at it as feature request if you create a new issue, but no promises.
