### ISSUE TITLE
public static properties as variables

### ISSUE THREAD

**Issue by sredbull** [zircote/swagger-php#613]
Having global and class constants as variables are great but wouldn't it be nice if the parser supports public static properties like \App\Class::$variable and that the constructer is called of the class implementing a specific interface that contains your annotation. So you can dynamically set these properties while the \OpenApi\scan functions runs.

**Comment by bfanger** [comment]
This is outside the scope of the swagger-php project, we use the [Annotations Docblock Parser](https://github.com/doctrine/annotations) from [the doctrine project](https://www.doctrine-project.org) ask for this feature there.
