### ISSUE TITLE
How to return empty object (braces: {} )  in example response json

### ISSUE THREAD

**Issue by kamil-kielczewski** [zircote/swagger-php#614]
I have following json to return as example value of some POST request which create new object: 

```
{
  "name": "project",
  "items": [],
  "keys": {}
}
```

Using annotations I'm able to describe that:

```
/**
 *  @OA\Post(path="/entry", @OA\Response(response="200", description="new entry",
 *          @OA\JsonContent( type="json", example=
 *          {
 *              "name":"project", 
 *              "items":{} 
 *          } 
 *      )
 *  )
 */
```

This will result in swagger.json like below: 

```
{ 
    "name": "project", 
    "items": [] 
} 
```

So as we se, when in annotation we write braces: `"items":{}` then we get empty array `"items": []` as items value in swagger.json. 

But I don't know what to do to return field which value is `empty object`  -  `"keys": {}`. So the question is - for `type="json"`, in `example` attribute using annotations how describe field with `empty object` value ? 

Any idea how to describe field `"keys": {}` using annotations?

**Comment by bfanger** [comment]
You can't, its a limitation of doctrine/annotations and therefor swagger-php.
