### ISSUE TITLE
Problem with compiling json

### ISSUE THREAD

**Issue by bubblegumoff** [zircote/swagger-php#615]
Hi!
I add in file with API:
```
/**
 * @OA\Info(title="My First API", version="0.1")
 */

/**
 * @OA\Get(
 *     path="/api/resource.json",
 *     @OA\Response(response="200", description="An example resource")
 * )
 */
```
Next I add new file:
```
<?php
require("vendor/autoload.php");
$openapi = \Swagger\scan('api/v1.0');
header('Content-Type: application/x-yaml');
echo $openapi->toYaml();
```
Error:
```
Notice: Required @SWG\Info() not found in W:\domains\desdao\vendor\zircote\swagger-php\src\Logger.php on line 38

Warning: Cannot modify header information - headers already sent by (output started at W:\domains\desdao\vendor\zircote\swagger-php\src\Logger.php:38) in W:\domains\desdao\apiUp.php on line 4

Fatal error: Uncaught Error: Call to undefined method Swagger\Annotations\Swagger::toYaml() in W:\domains\desdao\apiUp.php:5 Stack trace: #0 {main} thrown in W:\domains\desdao\apiUp.php on line 5
```
Help pls

**Comment by bfanger** [comment]
`@SWG\Info` not found means you're using swagger-php 2.x but you're writing 3.x annotations.

When you've upgraded to 3.x and still have a `Required @OA\Info() not found` error, make sure the "api/v1.0" folder contains the php files with the annotations.

**Comment by bubblegumoff** [comment]
> `@SWG\Info` not found means you're using swagger-php 2.x but you're writing 3.x annotations.
> 
> When you've upgraded to 3.x and still have a `Required @OA\Info() not found` error, make sure the "api/v1.0" folder contains the php files with the annotations.

It's working! Thx!
