### ISSUE TITLE
Define BASE url

### ISSUE THREAD

**Issue by Doublemedia** [zircote/swagger-php#616]
Hello,

In the demo https://petstore.swagger.io/ under the h1 you see the following:

[ Base URL: petstore.swagger.io/v2 ]

For some reason I can't find how this is done? In the example code https://github.com/zircote/swagger-php/tree/master/Examples/petstore.swagger.io it not used anywhere. 

How can you define this with the OA annotations?

Kind regards,

Erwin

**Comment by Doublemedia** [comment]
That generates the following error.

Unexpected field "host" for @OA\OpenApi(), expecting "openapi", "info", "servers", "paths", "components", "security", "tags", "externalDocs", "x"

**Comment by delboy1978uk** [comment]
that's bizarre, because that's exactly what I'm using. Are you on v3? v2 had @SWG

**Comment by delboy1978uk** [comment]
It's definitely defined https://petstore.swagger.io/v2/swagger.json 
![image](https://user-images.githubusercontent.com/2684575/49231714-d1a9c700-f3f2-11e8-9875-b30a025490ef.png)

**Comment by bfanger** [comment]
In v2 you had `Base URL`, in v3 you have servers:  
https://swagger.io/docs/specification/api-host-and-base-path/

```php
/**
 * @OA\Server(url="https://api.example.com/v3")
 */
```
