### ISSUE TITLE
Auto Generate list of required properties in schema object

### ISSUE THREAD

**Issue by penja** [zircote/swagger-php#621]
The maintenance of the list of required properties in a schema is a little bit annoying. When you change property name you also have to change item in the required list.

I have proposal to add property `required=true|false` into `OpenApi\Annotations\Property` object. When this flag is set to `true` the separate processor will include such a property in the list of required properties of the schema.

If you agree I will prepare PR with tests.

**Comment by bfanger** [comment]
I rather see this feature be implemented in the openapi specificaton. (and then be supported in swagger-ui)

## Things to consider:
The `OA\Property` is a `OA\Schema` and already has a required property.
So if the Property is an object with required attributes `{"id","title"}`, can is itself also required.
Force to write all annotation with the required=Boolean approach, or use different property like `xRequired`?

Properties can be ref'ed, inherited and be used in multiple places, should the processor update all of them?
What if on one location you want to opt-out of the required, does the processor only generate required arrays if the required was null/UNDEFIINED.

It could be added in a future spec and have slightly differrent meaning than our implementation.

---
I'd like to write `required=true` so i'd be inclined to merge a PR that adds this feature, but as an optional processor, one that's not enabled by default.

**Comment by bfanger** [comment]
Let me know when you're ready to share this swagger-php-plugin, I'll gladly link to it on the [related projects](http://zircote.com/swagger-php/Related-projects.html) page
