### ISSUE TITLE
[docs] securityScheme

### ISSUE THREAD

**Issue by floggle** [zircote/swagger-php#625]
The security Scheme Object in the spec - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#securitySchemeObject

It does not have a "securityScheme" field, yet your examples do.

I appreciate that swagger-php is light on docs, and that's kind of ok because the spec is the doc, but for something that's different from the doc, it's probably worth documenting.

**Comment by bfanger** [comment]
Lots of swagger-php annotations have a fieldname with the same name as the class, this is used to map the array into an object. Examples: `@OA\Property(property="id")`,  `@OA\Header(header="X-Rate-Limit")`

This is a community-run project, feel free to add or clarify any missing documentation.

**Comment by floggle** [comment]
@bfanger - Thanks. The problem with my adding or clarify "any missing documentation" is - I'd have to understand it in the first place. The last people who can document something are the users.
