### ISSUE TITLE
No Error on bad response

### ISSUE THREAD

**Issue by floggle** [zircote/swagger-php#626]
I accidentally created a response with a ref to a component that didn't exist (copying the example code):
```
 *			ref="$/components/responses/Json",
```
I realised my mistake later, but I expected swagger-php would have pointed out the mistake.

**Comment by bfanger** [comment]
Thanks for the trust in the validation / errorhandling code.

`$/...` refs are part of a feature that are not ported to v3, i'll see if I can remove some exceptions in the validation code.
