### ISSUE TITLE
Test that doesn't work?

### ISSUE THREAD

**Issue by floggle** [zircote/swagger-php#628]
I copied and pasted all of the PHPDocs from here into my code to try and better understand the framework:
https://github.com/zircote/swagger-php/blob/5d96b7c4155549e32d2715807d0e8cc61020ab2a/tests/Fixtures/DynamicReference.php

But it turns out that that doesn't actually work!
If I try and run it through swagger-php I get:
     ←[31mError: [Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'XX' in

Which it turns out is because the response codes have strings in them. (1XX for instance).

**Comment by bfanger** [comment]
Good find, I'll remove the (dead) code related to DynamicReference as it was never ported to v3.

Relates to #625
