### ISSUE TITLE
Proposal excluding properties in schemas

### ISSUE THREAD

**Issue by sredbull** [zircote/swagger-php#630]
```
use OpenApi\Annotations as OA;

/**
 * @OA\Schema(
 *     schema="ExtendedBase"
 * )  // Will generate a Schema with all properties.
 * @OA\Schema(
 *    schema="ExtendedBaseExcluded",
 *    excluded="{"excludedProp", "excludedTest"}"
 * ) // Will generate a Schema with all properties except the ones defined in excluded.
*/
class ExtendedBase extends Base;
{
    /**
     * @var string
     * @OA\Property()
    */
    private $extendedBaseProp;

    /**
     * @var string
     * @OA\Property()
    */
   private $excludedTest;
}

class Base
{
    /**
     * @var string
     * @OA\Property()
    */
    private $baseProp;

    /**
     * @var string
     * @OA\Property()
    */
    private $excludedProp;
}
````

This will save me a bunch defining schema's with different response groups. Using OneOf or AllOf are just not the best in some use cases.

**Comment by awwal1999** [comment]
how do I define @OA\JsonContent(ref="#/components/schemas/User")
it gives me an error generating the documentation

**Comment by bfanger** [comment]
swagger-php 2.x had something like that https://github.com/zircote/swagger-php/pull/301
But it behaved unpredictable/buggy.

I've removed that feature in 3.x, generating Schemas based on other schemas is complex and the current direct mapping between annotations and generated specification simplifies not only the code but also reasoning about and writing the annotations.

That said, I also see the benefits of reducing the number of annotations you have to write. ( `@OA\JsonContent` and `@OA\Get` )

Try creating a swagger-php plugin by writing a processor and i'll gladly add your project to the [related projects page](http://zircote.github.io/swagger-php/Related-projects.html)
