### ISSUE TITLE
Discriminator issues

### ISSUE THREAD

**Issue by floggle** [zircote/swagger-php#632]
I'm unclear on how completely "discriminator" is supported, so maybe this is known. There are only four references to it in the code and no examples.

So, based on the OpenAPI3 spec, I tried the below (simplified from my actual spec) which is how I'd expect to use it:
```
...
@OA\JsonContent(
 *     	oneOf={
 *     		@OA\Schema(ref="#/components/schemas/service_1"),
 *     		@OA\Schema(ref="#/components/schemas/service_2"),
 *     		@OA\Schema(ref="#/components/schemas/service_3"),
 *     		@OA\Schema(ref="#/components/schemas/service_4"),
 *     	},
 *      @OA\Discriminator(propertyName="service_num")
 )
 
```
swagger-php runs fine, but the result doesn't have the word "discriminator" in it anywhere. Or "propertyname". It has disappeared entirely.

If I try putting the @OA\Discriminator object *inside* the OneOf array, that too runs through swagger-php just fine, but this time it outputs an invalid OpenAPI spec, with an array where the fifth item is 
```
                                        {
                                            "propertyName": "service_num"
                                        }
```

**Comment by bfanger** [comment]
The new Discriminator annotation worked inside a `@OA\Schema` annotation but not inside a `@OA\JsonContent` this will be fixed in the next release.
