### ISSUE TITLE
in="body" should be a valid paramter option

### ISSUE THREAD

**Issue by rtconner** [zircote/swagger-php#633]
From everything I see on the specification I think "body" should be valid param type.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#body-parameters

But, currently something like this gives an error ...

```
     *   @OA\Parameter(
     *     name="my_param",
     *     required=true,
     *     in="body",
     *     @OA\Schema(type="string")
     *   ),
```

```
ErrorException  : @OA\Parameter(name="name",in="body")->in "body" is invalid, expecting "query", "header", "path", "cookie" in (path/to/code)
```

**Comment by Dreiser** [comment]
@rtconner This package is compatible with OAI 3.0.0 and it newly describes request parameters using [Request Body Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#requestBodyObject)

[Implementation of Request body in zircote/swagger-php](https://github.com/zircote/swagger-php/blob/master/src/Annotations/RequestBody.php)

**Comment by rtconner** [comment]
Ok. Thanks. I guess I'm doing something wrong. 

If you have any example of what the annotations should look like in my code, I would love it. Not seeing any examples of the body in the [Examples Directory](https://github.com/zircote/swagger-php/tree/master/Examples/openapi-spec).

**Comment by Dreiser** [comment]
https://github.com/zircote/swagger-php/blob/master/Examples/petstore-3.0/models/RequestBody.php
