### ISSUE TITLE
No provision for vendor extensions

### ISSUE THREAD

**Issue by floggle** [zircote/swagger-php#639]
I'm trying to use the x-logo extension of ReDoc:
https://github.com/Rebilly/ReDoc/blob/a1aa49a3225c916280491be4946989ecdb654a32/docs/redoc-vendor-extensions.md

So something like this:
```
...
 *     termsOfService="https://www.example.com/",
 *     x-logo="this is meant to be a schema, but for now it's just a placeholder",
 *     @OA\Contact(
...
```

but it fails with:

```
←[31mError: [Semantical Error] Couldn't find constant x, E
```
I get that you're not able to support arbitrary extensions, but being more permissive in what's allowed in sections would be nice. Maybe a "warning" level event if there's an unknown type of item? (and they can be turned off too ideally)
Also - why is it looking for a "constant x"? How can you have a constant as a fieldname?

**Comment by bfanger** [comment]
Annotation is described in the [vendor extensions](http://zircote.com/swagger-php/Getting-started.html#vendor-extensions) chapter of the [getting started guide](http://zircote.com/swagger-php/Getting-started.html.)

Although I see the the annotation example is currently missing 😞

```php
*  x={"logo":"this is meant to be a schema, but for now it's just a placeholder"}
```


PS.
doctrine/annotations sees `x - logo` as 2 constants and a minus symbol.

**Comment by floggle** [comment]
Thanks. This works like a charm:
```
 *     x={
 * 			"logo": {
 * 				"url": "http://example.com/logo/logo-for-web.svg",
 * 				"background": "#ffffff",
 * 				"altText": "My Logo Logo",
 * 			}
 * 		},
```

If I may make a suggestion, maybe if you detect something beginning "x" as a fieldname like that, put up  a suggestion to the user "did you want to use a vendor option? See docs ... [link here] ". It might save you from more of these tickets. :-)
Thanks again.
