### ISSUE TITLE
Documenting virtual properties

### ISSUE THREAD

**Issue by games647** [zircote/swagger-php#642]
We use a PHP framework that adds virtual properties to a model class. For the purpose of documenting the available fields (for editors and IDEs), we add `@property` annotations to the top of the class, but this approach doesn't support the `@OA\Property` like described [here](http://zircote.com/swagger-php/Getting-started.html#detects-values-based-on-context).

In comparison to the example from `Getting started` guide, the data type and description isn't copied over to the swagger property. So we are forced to define it twice, which makes it harder to maintain it. The other solution is define private properties, but this would hide the existing ones and so isn't an option either.

**Do we missed something here** and is there a way to copy the data from the `@property` annotation or what do you think about adding this as a feature?

**Comment by waza-ari** [comment]
Hi,

I do have pretty much the same problem when using the Yii2 framework. What I usually do is to create a Schema for each virtual property and then "compose" my real schema like this:

```php
/**
 * User model
 *
 * @OA\Schema(
 *     schema="ApiUser_id",
 *     type="integer",
 *     format="int64",
 *     description="The unique ID of this user",
 *     example="1"
 * )
 * @property integer $id
 *
 * @OA\Schema(
 *     schema="ApiUser_username",
 *     type="string",
 *     description="The unique username of this user",
 *     example="admin"
 * )
 * @property string $username
 *
 * @property ApiToken[] $tokens
 *
 *
 * @OA\Schema(
 *  type="object",
 *  schema="ApiUser",
 *  description="My fancy description",
 *  properties={
 *    @OA\Property(property="id", ref="#/components/schemas/ApiUser_id"),
 *    @OA\Property(property="username", ref="#/components/schemas/ApiUser_username"),
 *    @OA\Property(property="tokens[]", ref="#/components/schemas/ApiToken")
 *  }
 * )
 */
class ApiUser extends User implements IdentityInterface
{
```

However, I'm not quite happy with it either. First I have to maintain the property type twice and secondly it creates one schema object per property which are later shown in the UI as well. Further, they'll probably get generated using swagger codegen later on.

Why am I using the schemas per property? The Yii framework has a concept called scenarios, which allow a different representation of the object (different fields) depending on the scenario.

There are the scenarios which are used when using the class to OBTAIN data (HTML form, POST request) where you can specify required fields and validation roles. Further, there is the field settings, where you can specify which fields should be RETURNED when querying the object.

Example:

```php
   /**
     * Define scenarios
     */
    const SCENARIO_LOGIN = 'login';

    ###########################################
    ########### Scenarios and Rules ###########
    ###########################################

    /**
     * @inheritdoc
     *
     * Choose which fields should be returned based on a scenario
     */
    public function fields()
    {
        switch ($this->getScenario()) {
            /**
             * @OA\Schema(
             *  type="object",
             *  schema="ApiUserLogin",
             *  description="Model to represent data returned after successful login",
             *  properties={
             *    @OA\Property(property="id", ref="#/components/schemas/ApiUser_id"),
             *    @OA\Property(property="username", ref="#/components/schemas/ApiUser_username"),
             *  }
             * )
             */
            case self::SCENARIO_LOGIN:
                return ['id', 'username'];
                break;
            default:
                return $this->attributes;
                break;
        }
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        $scenarios = parent::scenarios();

        /**
         * @OA\Schema(
         *  type="object",
         *  schema="ApiUserScenarioLogin",
         *  description="Model to represent data used to login a user",
         *  properties={
         *    @OA\Property(property="username", ref="#/components/schemas/ApiUser_username"),
         *    @OA\Property(property="password", ref="#/components/schemas/ApiUser_login_password")
         *  }
         * )
         */

        $scenarios[self::SCENARIO_LOGIN] = ['username', 'login_password', 'rememberMe'];
        return $scenarios;
    }
```

The idea behind that is to define as much logic as possible within the model and reuse those schemas in the controller code later. For getting data, I'll probably stick to that approach, for returning data I also could use the generic ApiUser model and simply don't populate all fields. I however somehow feel that would be dirty.

Hope that helps somehow, but I'm still looking for a good solution myself.

**Comment by SamuelWei** [comment]
I have the same problem with laravel, as most of the properties are loaded via magic methods.
For php documentation I added them with @property
Like @games647 said, it would save a lot of work and keep the code clean

**Comment by bfanger** [comment]
Runtime properties and framework specific support is outside the scope of this project. 

Try creating a swagger-php plugin for your framework by writing a processor.
