### ISSUE TITLE
Annotation classes instead of doc annotations

### ISSUE THREAD

**Issue by verschoof** [zircote/swagger-php#645]
Hi,

In our code base we have ENUMS, for example;

PaymentPeriod
```
/**
 * @OA\Parameter(
 *   parameter="paymentperiod",
 *   name="paymentperiod",
 *   in="query",
 *   description="Payment period",
 *   required=true,
 *   @OA\Schema(
 *     type="string",
 *     enum={"four_week", "eight_week", "month", "two_month", "three_month", "quarter", "two_quarter", "year", "two_year"}
 *   )
 * ),
 */
```

In our code, we also have a "ENUM", this is an object with constants that contain the same options, I can ask all those options with `PaymentPeriods::allAsString` and I have a array with strings of all the options. I would like to use this for my annotation reference, is this possible?

It would be nice to have a concept to make annotations in PHP instead of docs. Same for the `@info` annotation, I have some variables in there but I cannot apply that in the annotations.

To solve this, I created a workaround, I create the docs and add values "will be replaced", in the action to get the json output I first json_decode the result, I edit the info values and after that I encode it again and give it to the response. (bit nasty).

Is this possible to create a php annotation like my previous question?

**Comment by sonrac** [comment]
Hi! 
You can use bootstrap file and add custom processors for replacing variables.
Openapi & swagger support defined constants, but not support method/functions call

```
Usage: openapi [--option value] [/path/to/project ...]

Options:
  --output (-o)     Path to store the generated documentation.
                    ex: --output openapi.yaml
  --exclude (-e)    Exclude path(s).
                    ex: --exclude vendor,library/Zend
  --pattern (-n)    Pattern of files to scan.
                    ex: --pattern "*.php" or --pattern "/\.(phps|php)$/"
  --bootstrap (-b)  Bootstrap a php file for defining constants, etc.
                    ex: --bootstrap config/constants.php
  --processor       Register an additional processor.
  --format          Force yaml or json.
  --debug           Show additional error information.
  --help (-h)       Display this help message.
```
