### ISSUE TITLE
How to send a structure in swagger?

### ISSUE THREAD

**Issue by Andrej-Kiselev** [zircote/swagger-php#646]
Hi!
There's form with some inputs like 'firstName', 'lastName', etc. They are sent via post-request as array and it looks like:
```
passengers[0][firstName]
passengers[0][lastName]

passengers[1][firstName]
passengers[1][lastName].
```

I've tried to describe it like this:

     @SWG\Parameter(name="passengers[][lastName]", description="Passenger lastName", required=true, type="array", collectionFormat="multi", in="query",
          @SWG\Items(
              type="string"
          )
      ),
     @SWG\Parameter(name="passengers[][firstName]", description="Passenger firstName", required=true, type="array", collectionFormat="multi", in="query",
          @SWG\Items(
              type="string"
          )
      )
i expected to see in request
```
passengers[0][lastName]: Doe
passengers[1][lastName]: Smith
passengers[0][firstName]: John
passengers[1][firstName]: Ethan
```

but I got
```
passengers[][lastName]: Doe
passengers[][lastName]: Smith
passengers[][firstName]: John
passengers[][firstName]: Ethan
```

Can you please explain how to get expected result?

**Comment by bfanger** [comment]
I don't know., you could ask this question on the specification repository, they might be able to help you.

If swagger-php is unable to generate the json, let me know what the expected json/yaml is and i'll re-open the issue.
