### ISSUE TITLE
Run validation only

### ISSUE THREAD

**Issue by arxeiss** [zircote/swagger-php#649]
It's amazing, I like how quick and easy is to start using you tool. No settings, just run.

But I have 1 request to add command line attribute `--validate`. When we do git push to our repo, codesniffer and PHP STAN and other tools are running. I would like to validate also all annotations or just stop CI pipeline if there is a bug. No I can do

`./vendor/bin/openapi --output /dev/null  ./app/apiv3/` but it would be nice to do just `./vendor/bin/openapi --validate  ./app/apiv3/`

If there is no error, there will be success output, otherwise acts just like now.

What do you think?

**Comment by bfanger** [comment]
I think sending the output to `dev/null` is fine.

I myself use phpunit to verify my annotations are still valid.
```
<?php
use PHPUnit\Framework\TestCase;
use function OpenApi\scan;

class DocumentationTest extends TestCase
{
    
    public function testOpenapi()
    {
        $openapi = scan(base_path('app'));
        $this->assertTrue(true);
    }
}
```
