### ISSUE TITLE
Serialize nested properties as form-data

### ISSUE THREAD

**Issue by alupuleasa** [zircote/swagger-php#652]
Hi,

I have this code and `test` is encoded as `application/json`. I need to encode `test` as `multipart/form-data` by adding it inside `encoding={}`. How can I do that because I didn't found any example?
```
 * @OA\Post(
 *     path="/admin/test",
 *     summary="Create new Test",
 *     description="Will attempt to create a new Test",
 *     tags={"Admin Test"},
 *     @OA\RequestBody(
 *          @OA\MediaType(
 *              mediaType="multipart/form-data",
 *              encoding={}
 *              @OA\Schema(
 *                  type="object",
 *                  @OA\Property(
 *                      property="test",
 *                      type="object",
 *                      description="test"
 *                      ref="#/components/schemas/MyTestSchema"
 *                  )
 *              )
 *      )
```

**Comment by sonrac** [comment]
@alupuleasa 
Hi! 
You can use oneOf of allOf:
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

Examples:
https://github.com/zircote/swagger-php/blob/26c9e75fdec48aa07ed7d6dc255ad2fa10250ece/tests/Fixtures/InheritProperties/Extended.php#L8

https://github.com/zircote/swagger-php/blob/26c9e75fdec48aa07ed7d6dc255ad2fa10250ece/Examples/swagger-spec/petstore-with-external-docs/models/Pet.php#L27

**Comment by alupuleasa** [comment]
I think we're not on the same page here.
How can I get Swagger-ui to encode this as `multipart/form`  data instead of passing me a `json` (string).

**Comment by bfanger** [comment]
You can't.

A "multipart/form-data" request doesn't have support for objects.
It's an api endpoint for a simple webform with a flat array of fields.

You can use type="string" and use a `format=` to hint that it should be json, but that will result in a single input, not one per property.
