### ISSUE TITLE
 Hide internal and external api methods

### ISSUE THREAD

**Issue by rubencamacho** [zircote/swagger-php#658]
Hi,

 I would like to know how I could differentiate between internal and external use methods. I have an authentication oauth2 that works correctly, but now I want to hide the methods until the user validates.

On the other hand, I would also like to separate the methods in internal and external depending on who is logged in.

Sorry for my english, thanks

**Comment by rubencamacho** [comment]
Hi,

I solved it with openapi-filter

**Comment by bfanger** [comment]
Nice! i've added it to the [related projects page](http://zircote.github.io/swagger-php/Related-projects.html)
