### ISSUE TITLE
Can't generate Query Parameters automatically like I can request body

### ISSUE THREAD

**Issue by JoeyOverby** [zircote/swagger-php#663]
I am writing an OpenAPI spec and trying to generate my possible query parameters automatically (using swagger-php) from the annotations for a request route/path. I know that I can just type out all possible parameter options for each route, but I really need to be able to generate the possible parameters from the properties of a class automatically using annotations like I can do for the request body. (We will have tons of classes/paths and keeping it up to date most likely won't happen unless they are generated like the request body/JsonContent can be. Is this possible with swagger-php or even OpenAPI in general?

I got this to work with the put and the request body, but how do I do it for a get request that still uses the properties of the class?

I can do this for the request body:

```php
    /**
     * @return Response
     *
     * * @OA\Put(
     *     path="/persons",
     *     tags={"Person"},
     *     @OA\RequestBody(
     *          request="person",
     *          required=false,
     *          description="Optional Request Parameters for Querying",
     *          @OA\JsonContent(ref="#/components/schemas/Person")
     *      ),
     *     @OA\Response(
     *          response="200",
     *          description="Returns matching Person Object",
     *          @OA\JsonContent(
     *              type="array",
     *              @OA\Items(ref="#/components/schemas/Person")
     *          )
     *     )
     * )
     */
```

Writing out each parameter for 30+ classes will not be maintainable:

```php
     /** @OA\Get(
     *     path="/events",
     *     tags={"Events"},
     *     @OA\Parameter(
     *          name="eventID",
     *          in="query",
     *          required=false,
     *          description="The event ID specific to this event",
     *          @OA\Schema(
     *              type="string"
     *          ),
     *     ),
    *
   * ....etc
```

**Comment by bfanger** [comment]
Write the parameters outside the `@OA\Get` 
```
    /**
     * @OA\Parameter(
    *          parameter="event_id",
     *          name="eventID",
     *          in="query",
     *          required=false,
     *          description="The event ID specific to this event",
     *          @OA\Schema(
     *              type="string"
     *          )
     *     )
     */

And use a ref inside the `@OA\Get` to reference that parameter.

   /** @OA\Get(
     *     path="/events",
     *     tags={"Events"},
     *     @OA\Parameter(ref="#/components/parameters/event_id")
     *      ...
```

This allows you to document the parameters and re-use them multiple times. This is generally do-able. 

You can also look into writing a swagger-php plugin, a processor that generates parameter annotations based on the class information.

**Comment by JoeyOverby** [comment]
@bfanger , 
   Thank you for your response, but I don't believe this addresses my issue. I understood that I can manually go in and write all of the documentation. But at that point, why not just write the yml/json myself anyways? 

I believe that this is still an issue because I cannot do this automatically (like I can with the request body and inside of the class files themselves).

**Comment by DerManoMann** [comment]
@JoeyOverby this might get you started: https://github.com/zircote/swagger-php/pull/783
