### ISSUE TITLE
The UNDEFINED constant is incompatible with mbstring.func_overload

### ISSUE THREAD

**Issue by rgson** [zircote/swagger-php#665]
The `UNDEFINED` constant contains a multi-byte character which, for some reason, breaks the `substr` operation in `Context::phpdocDescription` when the `mbstring.func_overload` feature is active.

```
Fatal error:  Uncaught TypeError: trim() expects parameter 1 to be string, boolean given in [...]/vendor/zircote/swagger-php/src/Context.php:225
Stack trace:
#0 [...]/vendor/zircote/swagger-php/src/Context.php(225): trim(false)
#1 [...]/vendor/zircote/swagger-php/src/Processors/AugmentOperations.php(26): OpenApi\Context->phpdocDescription()
#2 [...]/vendor/zircote/swagger-php/src/Analysis.php(359): OpenApi\Processors\AugmentOperations->__invoke(Object(OpenApi\Analysis))
#3 [...]/vendor/zircote/swagger-php/src/functions.php(44): OpenApi\Analysis->process(Array)
#4 [...]/public/swagger.php(10): OpenApi\scan('..', Array)
#5 {main}
  thrown in [...]/vendor/zircote/swagger-php/src/Context.php on line 225
```

In my case, both `phpdocSummary` and `phpdocContent` were `UNDEFINED` (i.e. `"@OA\UNDEFINED🙈"`), but it's `phpdocContent` that matters.

The `mbstring.func_overload` feature is admittedly notorious and even deprecated as of PHP 7.2, so I'm guessing that this is not a high-priority issue. However, unless there's a reason for putting specifically a multi-byte character at the end of the constant's value, it's probably also an easy fix (i.e. changing to a different suffix).

My workaround for now is to reset `mbstring.func_overload` specifically for my affected URLs in my Apache virtual host config:
```apache2
<Location "/swagger.*">
	php_admin_value mbstring.func_overload 0
</Location>
```

**Comment by bfanger** [comment]
Thanks for reporting and describing a workaround. This helps others with the same error.

I'm closing this as wontfix as it deprecated in newer php version.
