### ISSUE TITLE
Deserializing additionalProperties: (boolean) fails

### ISSUE THREAD

**Issue by ian-zunderdorp** [zircote/swagger-php#668]
Given a sub-schema (created by swagger-php by manually creating annotations structure and then calling toJson on the OpenApi annotation):
```
"data": {
  "properties": {},
  "type": "object",
  "additionalProperties": true
}
```

Deserializing this should result into the annotation Property with $properties = [], $type = "object" and $additionalProperties = true.

Currently it fails on a recursion into doDeserialize, due to passing the boolean to it where a stdClass is expected.

**Comment by bfanger** [comment]
I've regret merging the deserialisation PR.
The goal of the project is to generate yaml/json from the annotations.

If you have time create a PR to make the deserialisation better.

**Comment by ian-zunderdorp** [comment]
Hi @bfanger ,

Just wondering whether you had a chance to look at the PR yet (less than 100 LoC change).
