### ISSUE TITLE
Property "collectionFormat"="multi" bug

### ISSUE THREAD

**Issue by lukepass** [zircote/swagger-php#669]
Hello,
I reported the bug on NelmioApiDocBundle but I think that it belongs to this PHP library.

I encountered a minor bug using collectionFormat. This is my action:

    /**
     * Creates a new product.
     *
     * @Rest\Post("/create")
     * @SWG\Response(
     *     response=200,
     *     description="Created product"
     * )
     * @SWG\Response(
     *     response=400,
     *     description="901 - Invalid input"
     * )
     * @SWG\Parameter(
     *     name="code",
     *     in="formData",
     *     type="string",
     *     required=true
     * )
     * @SWG\Parameter(
     *     name="image",
     *     in="formData",
     *     type="file"
     * )
     * @SWG\Parameter(
     *     name="machineries[]",
     *     in="formData",
     *     type="array",
     *     @SWG\Items(type="integer"),
     *     collectionFormat="multi",
     * )
     */
    public function createAction(Request $request)
    {
    }

This is the generated call:

`curl -X POST "http://mysite.local/app_dev.php/api/products/create" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "code=12345" -F "machineries[]="123","321""`

I would have expected the `machineries[]` parameter repeated 2 times instead of a single parameter with multiple values:

https://swagger.io/docs/specification/2-0/describing-parameters/#array-and-multi-value-parameters

Thanks.

**Comment by bfanger** [comment]
This is outside the scope of the swagger-php project.
(swagger-php doesn't generate curl calls) 
swagger-php is only responsible for generating the json based on the annotations, if you know what json you need to generate and was unable to do so with annotations open a new issue.

**Comment by andybutlermf** [comment]
Its not outside of the scope of the project, hes showed you the CURL the swagger produced from the JSON swagger-php produced.

**Comment by bfanger** [comment]
@andybutlermf We don't produce cURL, this lib produces the swagger.json and that contains the expected 
`"collectionFormat": "multi"`

**Comment by DerManoMann** [comment]
If there is indeed `"collectionFormat": "multi"` in the generated JSON then I think this is more a question for swagger-ui or whatever client you are using.

Looking at it the other way around the question could be "What should the JSON look like to make tswagger-ui create the 'correct' curl call?"
