### ISSUE TITLE
Poorly documenteted

### ISSUE THREAD

**Issue by hajar-jobtip** [zircote/swagger-php#672]
There is no documentation on lists of annotations or example ones. Ether you have to have past Swagger knowledge.  The examples like Pet Store is also lacking everything you have to know.

**Comment by Grafikart** [comment]
I have the same problem, is there a way to list every annotations available with the parameters available for each one ?

**Comment by Grafikart** [comment]
@hajar-jobtip if you are using an IDE you can use : 

```php
use OpenApi\Annotations as OA;
``` 

It helps a lot

**Comment by cbdelavenne** [comment]
> @hajar-jobtip if you are using an IDE you can use :
> 
> ```
> use OpenApi\Annotations as OA;
> ```
> 
> It helps a lot

I'm using PhpStorm. How does adding this `use` help exactly? 
I added it, but I don't see any suggestions or auto-complete while writing my OA phpdoc.
