### ISSUE TITLE
(OAS 3.0) Warning: @OA\Schema() is missing key-field: "schema"

### ISSUE THREAD

**Issue by cbdelavenne** [zircote/swagger-php#674]
Trying to understand what I'm doing wrong to generate this warning message:

```
Warning: @OA\Schema() is missing key-field: "schema" in ./protected/api/api.php on line 205
```

Snippet of the phpdoc:
```
...
 *     @OA\Parameter(
 *         in="path",
 *         name="id",
 *         schema=@OA\Schema(
 *             type="string"
 *         ),
 *         description="Example ID",
 *         required=true
 *     ),
...
```

Any suggestions? What is missing?

**Comment by cbdelavenne** [comment]
Well, seems like I found a solution that works:

```
...
 *     @OA\Parameter(
 *         in="path",
 *         name="id",
 *         schema={
 *             "type"={"string"}
 *         },
 *         description="Example ID",
 *         required=true
 *     ),
...
```

**Comment by hurokan** [comment]
i have faced this error  @OA\RequestBody() is missing key-field: "request"

in my documentation is like 

/**
     * @param Request $request
     * @return mixed
     * @OA\POST(
     *     path="/v1/cart/addtocart",
     *     tags={"Order Management API"},
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(
     *                     property="id",
     *                     type="integer"
     *                 ),
     *              @OA\Property(
     *                     property="attribute_id_1",
     *                     type="integer"
     *                 ),
     *              @OA\Property(
     *                     property="quantity",
     *                     type="integer"
     *                 ),
     *          example={ "id": "10" , "attribute_id_1": 27,"quantity":1}
     *           )
     *        )
     *     ),
     *  @OA\Response(response="201", description="Successful created")
     * )
     */

what the reason ?

**Comment by bhattaxay** [comment]
Hii @hurokan I found the solution that the line `OA\POST` which i change to `OA\Post` which works for me. Pls try it once

**Comment by hurokan** [comment]
Thanks

**Comment by aacassandra** [comment]
> Hii @hurokan I found the solution that the line `OA\POST` which i change to `OA\Post` which works for me. Pls try it once

work well. thankyou..

**Comment by scybulski** [comment]
I've had the same error when documenting a Laravel Request. Turned out I've put the `@OA\Schema` annotation into the `rules()` method comment block not the one of the whole class.
