### ISSUE TITLE
writeOnly and readOnly for property of type object

### ISSUE THREAD

**Issue by jeanatpi** [zircote/swagger-php#677]
Hi,

Seems that we cannot set up writeOnly or readOnly property in schema for object properties.
In the following example, the "object" property is always generated in POST/PUT requestBody.

Also confirm that nullable has no effect but it's already tracked in #670.

I'm using version 3.0.2

```
/**
 * 
 * @OA\Property(nullable=true, readOnly=true, allOf={ 
 *     @OA\Schema(ref="#components/schemas/Object")
 *     }
 * )
 */
private $object;

/**
 *
 * @OA\Property(nullable=true, writeOnly=true, type="string")
 */
private $objectId;

```

B.R

Jean

**Comment by bfanger** [comment]
swagger-php is only responsible for generating the yaml / json, the example annotations you've provided generates the expected output i.m.o.

If it "has no effect" that up to swagger-ui or the specification or your api code.
and outside the scope of this project.
