### ISSUE TITLE
Potential bug in Analysis::unmerged()

### ISSUE THREAD

**Issue by scaytrase** [zircote/swagger-php#678]
https://github.com/zircote/swagger-php/blob/master/src/Analysis.php#L308-L310

These lines looks strange. I'm trying to use `unmerged` but get all unmerged annotations back into resulting analysis. It looks like this code utilizes the same `OpenAPI` by reference instance and sets `_umerged` back into it, so it does no effect

**Comment by bfanger** [comment]
It could have effect, the `new Analysis` could do something with the unmerged array, there was probably a reason why I copy and restore the unmerged array.
I don't know if this is still the needed or wanted behaviour.

If this a problem create a PR with unittests which demonstrates the behaviour you expect.

**Comment by scaytrase** [comment]
i fully understand the reason you restore the unmerged array in original openapi object. But it is also restored for the result of this method, which breaks the logic of method documentation

**Comment by scaytrase** [comment]
@bfanger I've created a failing test case at #693. It's a bit straightforward to simplify setup, but both assertions are failed at the moment. either openapi is the same for both analysis and `unmerged` array is not empty when calling `::merged()` to get only merged annotations which I consider to be a bug.

**Comment by scaytrase** [comment]
Also I've added a quick-fix
