### ISSUE TITLE
[Question] Namespacing for #ref

### ISSUE THREAD

**Issue by slushpuppy** [zircote/swagger-php#679]
Hi, is it possible to specify a namespace for ref schema? I tried it out but received a not found error

E.g.?
ref="#/components/schemas/namespace/child/ClassResponse"

**Comment by bfanger** [comment]
It is not possible to specify namespace/path for a Schema.
All standalone Schema annotations are placed in #/components/schemas/

Properties of a schema are also schema's, so a ref to #/components/schemas/Responses/properties/NotFound is also possible.

But nesting doesn't have any benefit, you're better off using a manual prefix. Schema(schema="namespace_child_ClassResponse")
