### ISSUE TITLE
Using discriminator together with allOf

### ISSUE THREAD

**Issue by gayansanjeewa** [zircote/swagger-php#680]
What is the correct way of using discriminator together with `allOf`. From #518 I got to know it's supported in v2 but I cannot find an example to correctly use it.

For now came up something like this and it's not working and the doc is not generated 

    /**
    * @SWG\Definition(
    *      definition="model:FooBar",
    *      type="object",
    *      discriminator="type",
    *      required={"type"},
    *      @SWG\Property(property="type", type="string")
    * )
    *
    * @SWG\Definition(
    *      definition="model:foo",
    *      allOf={
    *          @SWG\Schema(ref="#/definitions/model:FooBar"),
    *          @SWG\Schema(
    *              required={"unique_to_foo_fields"},
    *              type="object",
    *              @SWG\Property(property="unique_to_foo_fields", type="integer")
    *          )
    *      }
    * )
    *
    * @SWG\Definition(
    *      definition="model:bar",
    *      allOf={
    *          @SWG\Schema(ref="#/definitions/model:FooBar"),
    *          @SWG\Schema(
    *              required={"unique_to_bar_fields"},
    *              type="object",
    *              @SWG\Property(property="unique_to_foo_fields", type="integer")
    *          )
    *      }
    * )
    */

Much appreciated, thanks :)

**Comment by bfanger** [comment]
This is outside the scope of this project, if you know how the json should look but are unable to generate that with the annotations open a new issue.
