### ISSUE TITLE
how can i send accept data in header with 3.0

### ISSUE THREAD

**Issue by nilsir** [zircote/swagger-php#681]
when i send the request for post with the customize accept, the docs request with as "accept:*/*", but i want to it like "accept:application/prs.cloud_shop", can you help me, thanks lot

**Comment by bfanger** [comment]
You can specify that your API responds with a custom mimetype using the `@OA\MediaType` annotation:
```php
/**
 * @OA\Get(path="/example",
 *   @OA\Response(response="default",description="An example",
 *     @OA\MediaType(mediaType="accept:application/prs.cloud_shop")
 *   )
 * )
 */
```

It's up to the openapi client to specify the `Accept` header.

See https://swagger.io/docs/specification/describing-request-body/ for more info.
