### ISSUE TITLE
Tag new 2.x release

### ISSUE THREAD

**Issue by thePanz** [zircote/swagger-php#682]
Please tag a new release on the latest 2.x branch.
See: https://github.com/zircote/swagger-php/pull/643

**Comment by bfanger** [comment]
@thePanz done, just released [2.0.14](https://github.com/zircote/swagger-php/releases/tag/2.0.14)

@zircote GitHub deprecated legacy hooks, and I don't have the needed rights.  
Could you setup auto-update on [packagist](https://packagist.org/packages/zircote/swagger-php)?
It currently has a `(Legacy Auto-Update, Needs Attention)` message, re-authenticating packagist with your github is needed.

**Comment by thePanz** [comment]
Thank you @bfanger
