### ISSUE TITLE
Feature request: support yaml dump options

### ISSUE THREAD

**Issue by itsjavi** [zircote/swagger-php#683]
`\OpenApi\Annotations\AbstractAnnotation::toYaml` does not support custom YAML options like `\OpenApi\Annotations\AbstractAnnotation::toJson` does.

One of the use cases is supporting multiline markdown in descriptions. Without the `Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK` option, it's not supported and line breaks are escaped.

**Comment by bfanger** [comment]
Thanks for the suggestion, the next version will support `toYaml($flags)` options.
