### ISSUE TITLE
Openapi CLI ignore --format if --output set.

### ISSUE THREAD

**Issue by PikaYellow35** [zircote/swagger-php#686]
Hello.

I'm using swagger-php version 3.0.2 installed by Composer. When I create an API description via openapi cli, using the command
```
openapi -o ./ -f json ./
```
then the -f option is ignored and the openapi.yaml file is always created. But with the command
```
openapi -f json ./> openapi.json
```
The file is created in the desired format.
I think the problem is in [this part of the code](https://github.com/zircote/swagger-php/blob/0dd7be1cead244bd13eb8deb2546e0c56eea47a6/bin/openapi#L238)

**Comment by bfanger** [comment]
Its line 247, which appends the "openapi.yaml" as filename because the output is a directory, (but inside it wil be json)

workaround is to change "-o ./" into "-o ./openapi.json" 
You don't need to pass "-f json" because swagger looks at the json extension.

**Comment by PikaYellow35** [comment]
Thanks, @bfanger, it's work.
