### ISSUE TITLE
define a single error report function

### ISSUE THREAD

**Issue by ym2048** [zircote/swagger-php#688]
Swagger-php use error_log function to report error info, some people may like use their self defined function to output errors, so it may be better to define a single error report function and call error_log in that function.In that case it will be easy to change way of showing errors

**Comment by bfanger** [comment]
This is already the case.  #607

```php
OpenApi \Logger::getInstance()->$log = function ($entry, $type) {
   // custom way of showing the error here
}
```

**Comment by ym2048** [comment]
I mean these call to error_log
https://github.com/zircote/swagger-php/blob/master/bin/openapi#L95-L96
https://github.com/zircote/swagger-php/blob/master/bin/openapi#L120
https://github.com/zircote/swagger-php/blob/master/bin/openapi#L154
https://github.com/zircote/swagger-php/blob/master/bin/openapi#L156
https://github.com/zircote/swagger-php/blob/master/bin/openapi#L212
 and so on.

**Comment by bfanger** [comment]
That all in the cli, You'll need to create your own script if you want to customize that.
