### ISSUE TITLE
Reusing third-party annotations

### ISSUE THREAD

**Issue by frankkoornstra** [zircote/swagger-php#690]
First of all, thank you for making this wonderful project! I was thinking of creating something similar because our specs tend to get out-of-sync with the real code and then I saw you already created it :D I do have a question though and wonder what your vision is.

In our projects, we tend to use many different vendor for different purposes: JMS, Symfony Validation, [Chimera](https://github.com/chimeraphp), etc. A lot of these projects define their own annotations for things like property names, validation rules, routing, etc. Looking through your project's docs, I see that we now have to re-annotate that information. That's already a big step ahead since the information of, for example, routing annotation for the framework and for the specs is right next to each other _but_ I was wondering if it could be even simpler :)

Would there be a chance to make your project extensible? So instead of defining the routes with this project's annotation, reuse the annotation of a third party and getting the information from there? Or maybe even more useful: validation annotations. I'd love to hear your thoughts on this, if it even makes sense. It goes without saying that we'd donate time to make this happen if we see it brings benefits.

**Comment by bfanger** [comment]
Swagger-PHP's architecture allows for running additional Processors which can augment the annotations it already detected or generate new ones.

This way framework specific plugins can be created for swagger-php.

**Comment by frankkoornstra** [comment]
That's great! Is there any kind of documentation for that or should I just take a peek in the Processors and be able to figure it out from there?

**Comment by DerManoMann** [comment]
I went the other way and wrote adapters for some frameworks to make routing work with the original swagger-php annotations :)
Means there is only one set of annotations for routing across frameworks which is quite nice.

The project includes some custom processors to add support for a Controller annotation to be able to annotate things shared for all endpoints handled by a controller - that might give you some ideas.

https://github.com/DerManoMann/openapi-router

**Comment by frankkoornstra** [comment]
Interesting approach! Eventually the goal is, like you said, a single annotation so I don't really mind which way around I get to that point :) I'll take a look at your link, thanks for the inspiration.
