### ISSUE TITLE
PHP Code Sniffer: Expected 1 space after asterisk; x found

### ISSUE THREAD

**Issue by kmarilleau** [zircote/swagger-php#691]
Hi, I need and use PHP Code Sniffer for a project and I notice it raise `Expected 1 space after asterisk; x found` for each line of comment blocks that start with `*[2 or more space]@SWG\`.

Example of comment blocks that don't raise error with PHP Code Sniffer:
```php
/**
 * @SWG\Parameter(
 *   name="limit",
 *   in="query",
 *   description="Example",
 *   required=false,
 *   type="number",
 *   format="int32",
 *   default=10
 * )
```

Example of comment blocks that raise error with PHP Code Sniffer:
```php
/**
 * @SWG\Definition(
 *   definition="error",
 *   required={"success", "data"},
 *   @SWG\Xml(name="error"),                
 *       @SWG\Property(
 *           property="success",
 *           format="boolean",
 *           description="Example",
 *           example=false,
 *           default=false
 *       ),
 *       @SWG\Property(
 *           property="data",
 *           format="object",
 *           required={"message", "code"},
 *           @SWG\Property(property="message", format="string", example=400),
 *           @SWG\Property(property="code", format="int32")
 *       )
 * )
 */
```

Linter Result:
```bash
4 | ERROR | [x] Expected 1 space after asterisk; 3 found
5 | ERROR | [x] Expected 1 space after asterisk; 7 found
12 | ERROR | [x] Expected 1 space after asterisk; 7 found
16 | ERROR | [x] Expected 1 space after asterisk; 11 found
17 | ERROR | [x] Expected 1 space after asterisk; 11 found
```

**Comment by kmarilleau** [comment]
I find the 'Sniff' file that raise an error in PHP Code Sniffer project.

I think we need to create custom Sniffer that ignore `php_codesniffer/Commenting.DocCommentAlignmentSniff` and create custom sniff almost identical except this piece of code:

https://github.com/squizlabs/PHP_CodeSniffer/blob/c271465ddacf1a64f7531d3f20cfab860bf5b2c8/src/Standards/Squiz/Sniffs/Commenting/DocCommentAlignmentSniff.php#L143-L150

**Comment by bfanger** [comment]
PHP Code Sniffer linting rules are outside the scope of this project. 

Open an issue on the PHP Code Sniffer repository to get improved support for doctrine annotations
