### ISSUE TITLE
Annotation definition for html form array with index

### ISSUE THREAD

**Issue by ekumahost** [zircote/swagger-php#694]
I have html form array with input name = items, my server processes x-www-form-urlencoded each item has an index and value.
`<input name='items[1]' value='a'>
`
The post section is set to:

`*     consumes={"application/x-www-form-urlencoded"},
`
The the Parameter Definition.

  
     @OA\Parameter(

      name="items[]",

      in="formData",
      description="",
      required=false,
     @OA\Schema(
       type="array",
       @OA\Items(type="string")
     )
      ),

I just want the swagger to be able to give the user form to add multiple array of items with their index and value but swagger show me to add only array of values only.

**Comment by bfanger** [comment]
What is the question?

**Comment by ekumahost** [comment]
with POSTMAN its posted thus: https://ibb.co/0ywwfFN

**Comment by bfanger** [comment]
Ah "with index"
As far a i know you can't dynamicly build the name field of a parameter. The array options available in openapi spec don't provide the php specific implementation. If you find a solution let me know.

As a workaround you can provide multiple parameter say name="items[1]" till name="items[3]" to give the reader of the documentation an indication how this api expects its items.
