### ISSUE TITLE
Examples definition bug

### ISSUE THREAD

**Issue by hotrush** [zircote/swagger-php#695]
![2019-07-09_17-59](https://user-images.githubusercontent.com/1247004/60899563-5b681f80-a273-11e9-96c6-e4eafb072939.png)

But

![2019-07-09_18-00](https://user-images.githubusercontent.com/1247004/60899606-6d49c280-a273-11e9-8a02-a9dc515cd1b8.png)

This produces an error:
```
PHP Warning:  [Syntax Error] Expected PlainValue, got '[' in ... on line 231:33 in /.../vendor/zircote/swagger-php/src/Logger.php on line 39
```

**Comment by bfanger** [comment]
Doctrine uses { for arrays not [ sadly. See the getting started for examples

**Comment by hotrush** [comment]
@bfanger don't sure what are you talking about, i'm not using doctrine or symfony. And can you point me into getting started example page, don't see anything here https://github.com/zircote/swagger-php

**Comment by hotrush** [comment]
https://i.imgur.com/7Xi1Hdh.png this way works, thanks @bfanger

**Comment by Joandysson** [comment]
replace [] with {}

The swagger doesn't accept square brackets, only braces, but it will still interpret as array
would be like this:

`examples={"for", "bar"}`
