### ISSUE TITLE
Missing examples for @OA\Examples

### ISSUE THREAD

**Issue by ghost** [zircote/swagger-php#697]
There is no example for the @OA\Examples annotation.

**Comment by SieciechPL** [comment]
@OA\Examples export examples to array, not to object so you need to use:
`@OA\Parameter(
...
                examples={
                    "country":{
                        "summary": "Country",
                        "value": "France",
                    },
                    "city": {
                        "summary": "City",
                        "value": "Sussex",
                    },
                },
...
            )`

**Comment by bfanger** [comment]
PR's  adding docs or examples are welcome

**Comment by liuquanhao** [comment]
Thank you, SieciechPL.

```php
@OA\Response(
    response="default",
    description="登录",
    @OA\JsonContent(
        ref="#/components/schemas/response",
        examples={
            "200": {
                "summary": "登录成功",
                "value": {
                    "code": 200,
                    "message": "登录成功",
                    "data": {
                        "user_token": "fwefnn2342423",
                        "role_type": "admin" 
                    }
                }
            },
            "403": {
                "summary": "登录失败",
                "value": {
                    "code": 403,
                    "message": "登录失败",
                    "data": null
                }
            },
        }
    ),
)
```
