### ISSUE TITLE
Proposal multiple schemas of the same Class

### ISSUE THREAD

**Issue by zim32** [zircote/swagger-php#698]
It is very common to have different fields exposed f.e. for POST or GET methods.
I propose to make **groups** option in Schema and Property annotations.

By default if no groups specified, group with empty name "" (empty string) implied. All previous code will work as expected without any modifications. 

If groups are specified, we create multiple schemas with name ClassNameGroupName with properties of the same group.
  
```
/**
 * @ORM\Entity
 * @OA\Schema(groups={"get", "post"})
 */
class Project
{
    /**
     * @var string
     * @ORM\Column(type="string", unique=true, nullable=false)
     * @OA\Property(groups={"get", "post"})
     * @Groups({"get", "post"})
     */
    protected $name;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     * @OA\Property(groups={"get"})
     * @Groups({"get"})
     */
    protected $createdDate;
```

Will create ProjectGet and ProjectPost schemas with name property in both schemas and createdDate only in ProjectGet schema.

After than I can reference schema in GET request like '#/components/schemas/ProjectGet'
and in post like '#/components/schemas/ProjectPost'

What do you think?

**Comment by bfanger** [comment]
I think this would be a great idea for a plugin.
Grouping and sorting is a much requested feature, but is outside the scope of swagger-php, which I'd like to keep unopinionated.

Let me know if you encounter roadblocks that prevents such a plugin.

**Comment by zim32** [comment]
As I understand this is job of Processors? So I can write Processor which group schemas something like that?

**Comment by bfanger** [comment]
Yes, that is correct.

**Comment by zim32** [comment]
Ok it will be nice if you add something like **public $vendor = []** to AbstractAnnotation to make it possible to extend

**Comment by zim32** [comment]
Ah I see $x; Ok.
