### ISSUE TITLE
Root level security - inconsistent between JSON and YAML

### ISSUE THREAD

**Issue by floggle** [zircote/swagger-php#701]
Following on from this ticket: https://github.com/zircote/swagger-php/issues/598

Using this as suggested (thanks!):
```
/**
 * @OA\OpenApi(
 *   security={
 *     {
 *       "api_key_query": {},
 *     }, {
 *       "api_key_header": {}
 *      }
 *   }
 * )
```
Does indeed generate for JSON (as you said):
```
    "security": [
        {
            "api_key_query": []
        },
        {
            "api_key_header": []
        }
    ],
```
Note that both members are Arrays (lists).

However, for YAML it produces:
```
security:
  -
    api_key_query: {  }
  -
    api_key_header: {  }
```
As you can see, it's stating the two members are Objects when they should be Arrays (lists).
This fails validation with both Speccy and the Python OpenAPI-spec-validator.

**Comment by bfanger** [comment]
Has been fixed, the current version generates:

```yaml
security:
  -
    api_key_query: []
  -
    api_key_header: []
```
