### ISSUE TITLE
Unable to authenticate with laravel passport

### ISSUE THREAD

**Issue by menadio** [zircote/swagger-php#702]
I am using swagger and l5-swagger package for the documentation of an API application built using Laravel 5.8. I am also using Passport for the API authentication and tried implementing it in the documentation.

When I try to authorize a user on swagger, I get the error here
> auth errorTypeError: NetworkError when attempting to fetch resource.

Here's how I have set it up swagger up

In `l5-swagger.php` config file
```
/* Open API 3.0 support */
'passport' => [ // Unique name of security
    'type' => 'oauth2', // The type of the security scheme. Valid values are "basic", "apiKey" or "oauth2".
    'description' => 'Laravel passport oauth2 security.',
    'in' => 'header',
    'scheme' => 'https',
    'flows' => [
        "password" => [
            "authorizationUrl" => config('app.url') . '/oauth/authorize',
            "tokenUrl" => config('app.url') . '/oauth/token',
            "refreshUrl" => config('app.url') . '/token/refresh',
            "scopes" => []
        ],
    ],
],
```
In the controller I have the swagger code
```
/**
* @OA\Get(
*      path="/products/{product}",
*      tags={"Product"},
*      description="Gets specified product",
*      operationId="getProductById",
*      summary="Fetches a product by the product Id",
*      security={{"passport": {}}},
*      @OA\Parameter(...),
*      @OA\Response(...),
* )
*/
```
This is the image of swagger authorization screen

https://i.stack.imgur.com/aiYjs.png

I get the `client_id` & `client_secret` from the `oauth_clients` table.

What am I doing wrong?

**Comment by bfanger** [comment]
Authentication is outside the scope of this project.

I did find a passport section in the l5-swagger readme:
https://github.com/DarkaOnLine/L5-Swagger/blob/master/README.md#using-swagger-ui-with-passport
Try reporting the issue there.
