### ISSUE TITLE
 unrecognized option '--bootstrap'mkdir: unrecognized option '--bootstrap'

### ISSUE THREAD

**Issue by meyfemi** [zircote/swagger-php#703]
I am new to swagger documentation. I got the following error while trying to run ./swagger.sh

mkdir: unrecognized option '--bootstrap'
Try 'mkdir --help' for more information.

Laravel version
 "laravel/framework": "5.8.*",
Swagger version
 "zircote/swagger-php": "^3.0"

**Comment by bfanger** [comment]
Could you provide the command line you're executing? (Looks like a missing space, but then the i expected a directory name not mkdir )

**Comment by meyfemi** [comment]
i have the following commans in the swagger.sh file

#!/bin/bash

mkdir ../public/swagger php ../vendor/bin/swagger --bootstrap ./swagger-constants.php --output ../public/swagger ./swagger-v1.php ../app/Http/Controllers

 according to this tutorial

**Comment by meyfemi** [comment]
the tutorial i followed
http://blogs.quovantis.com/swagger-integration-with-laravel/

**Comment by bfanger** [comment]
That tutorial is outdated (uses swagger-php:2.x), and is missing an enter right after the mkdir command just before the `php`command in the swagger.sh

I see you're using Laravel, you might want to try out [L5-Swagger](https://github.com/DarkaOnLine/L5-Swagger)
