### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by chrisnharvey** [zircote/swagger-php#717]
Are there any plans to support PHP 7.4?

Currently, the following error occurs when scanning my application. I've tried PHP 7.0 - 7.3 and it works fine.

Message: Trying to access array offset on value of type bool
File: vendor/zircote/swagger-php/src/StaticAnalyser.php
Line: 329

**Comment by bfanger** [comment]
No plans (this is a hobby project) and PHP 7.4 is not released yet.

a PR adding 7.4 support would be much  appreciated.

**Comment by chrisnharvey** [comment]
No worries, totally understand.

I will try to find some time over the next few weeks to get this working on PHP 7.4 and hopefully get a PR submitted.

**Comment by vkhramtsov** [comment]
Is #722 ok for support php 7.4?
