### ISSUE TITLE
How to describe multiple ExternalDocumentation field?

### ISSUE THREAD

**Issue by matyuda** [zircote/swagger-php#718]
Hi!

I want to write multiple ExternalDocumentation field as follows.

```
/**
 * @OA\Info(
 *  title="title sample",
 *  description="description sample",
 *  version="0.0.1",
 *  @OA\Contact(
 *    email="emailaddress"
 *  ),
 * ),
 * @OA\ExternalDocumentation(
 *   description="externaldoc1",
 *   url="https://example.com/externaldoc1/"
 * ),
 * @OA\ExternalDocumentation(
 *   description="externaldoc2",
 *   url="https://example.com/externaldoc2/"
 * )
 */
```

However, running openapi fails with the following error message.

> Only one @OA\ExternalDocumentation() allowed for @OA\OpenApi() multiple found in:
>     Using: /path/to/swagger-api.php on line 2
>   Skipped: /path/to/dfm-1_outmaker/swagger-api.php on line 2

Is there a way to describe multiple ExternalDocumentation fields?

**Comment by Doqnach** [comment]
Doesn't seem like OpenAPI supports this.

See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schema

**Comment by matyuda** [comment]
Hi @Doqnach
Thanks for the reply.
I understood that OpenAPI is not supported.
Do you know how to describe multiple external document fields?

**Comment by Doqnach** [comment]
Not while following the OpenAPI spec. You could add more by using an extension, line `x-Additional-ExternalDocumenttations: []`.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#specificationExtensions

Following the spec it would mean you should make a page that links to the different documentations you want to add, and reference that page instead, as a hub.

**Comment by matyuda** [comment]
Thanks for telling me. 
I try using x-Additional-ExternalDocumentations.
