### ISSUE TITLE
Problem escaping media type

### ISSUE THREAD

**Issue by coolg54321** [zircote/swagger-php#720]
I have a response annotation, like

```
    /**
     *   @OA\Response(
     *     response=200,
     *     description="File content",
     *     @OA\Header(header="Content-Type", @OA\Schema(type="string")),
     *     @OA\MediaType(
     *        mediaType="*\/*",
     *        @OA\Schema(type="string", format="binary"),
     *     ),
     *   ),
     */
```

Here as you can see I have to escape the forward slash in media type `*/*` (else the there will be a syntax error with PHP) so it becomes `*\/*` in the generated openapi document.

It is possible to escape it properly, so that the extra `\` won't come in the openapi document?

**Comment by bfanger** [comment]
I don't know doctine-annotations deep enough, you could ask them.
Let me know if its possible, I'm curious.

A workaround is to define ("STAR_SLASH_STAR", "*/*")

**Comment by coolg54321** [comment]
@bfanger thank you so much!

**Comment by Doqnach** [comment]
has nothing to do with doctine-annotations and everything with the PHP parsing of the file: the `*/` denotes the end of the docblock... 😛 .

So indeed the above method of escaping or using the constant would work and nothing can be done really from the library's point of view I think.

**Comment by mykola-ivashchuk** [comment]
The solution that works for me - just add spaces:
`    *     @OA\Parameter(
     *         name="Accept",
     *         in="header",
     *         required=true,
     *         example="* / *",
     *         @OA\Schema(type="string"),
     *     ),`

Also in the official Swagger docs, ~1 is using for escaping or replacing / symbol, but in this package, it doesn't work.
