### ISSUE TITLE
phpstorm annotations format

### ISSUE THREAD

**Issue by l1zard** [zircote/swagger-php#721]
Hey, i have issue (not a bug) with formatting annotations in phpstorm. When I write example annotation it looks like this
<img width="326" alt="Snímek obrazovky 2019-09-26 v 11 48 03" src="https://user-images.githubusercontent.com/4013674/65678420-87659680-e053-11e9-8b31-e8bd40663d28.png">
It's only format first line of annotation. Next levels inside are not formatted.
The bracket is formatted on start of line and no formatting under the "@OA\Response". I want achieve this
<img width="326" alt="Snímek obrazovky 2019-09-26 v 13 49 32" src="https://user-images.githubusercontent.com/4013674/65686401-9b65c400-e064-11e9-8a69-887ea9c0537d.png">

I google it and didn't find something helpful. Thanks for help.

**Comment by bfanger** [comment]
That would be useful, but is outside the scope of this project, file an issue to the phpstorm project.
