### ISSUE TITLE
@SWG\Parameter Does it support array nested objects?

### ISSUE THREAD

**Issue by WonlyCms** [zircote/swagger-php#723]
The interface requires a set of parameters similar to this
```json
{
    "goods": [
        {
            "id": 1,
            "number": 1
        },
        {
            "id": 2,
            "number": 1
        }
    ]
}
```
```
@SWG\Parameter(parameter="goods",name="goods",in="formData",type="array",description="goods",
    @SWG\Items(
        @SWG\Parameter(parameter="id",name="id",in="formData",type="integer",description="ID",required=true),
        @SWG\Parameter(parameter="number",name="number",in="formData",type="integer",description="number"),
    ),
),

```

But it doesn't work

```
@SWG\Items()->type="" not allowed inside a @SWG\Parameter() must be "string", "number", "integer", "boolean", "array" 
```
When I try

```
@SWG\Parameter(parameter="goods",name="goods",in="formData",type="array",description="goods",
    @SWG\Items(
        type="array", 
        @SWG\Parameter(parameter="id",name="id",in="formData",type="integer",description="ID",required=true),
        @SWG\Parameter(parameter="number",name="number",in="formData",type="integer",description="number"),
    ),
),

```
```
@SWG\Items() is required when @SWG\Items() has type "array" in 
```

So, what should I do right?

**Comment by Doqnach** [comment]
You are missing a `@SWG\Schema` within the `@SWG\Items`. The nested key=values are `@SWG\Property`s. `@SWG\Parameter` is only for header/query-string/path parameters. 

https://swagger.io/specification/#schemaObject

> items - Value MUST be an object and not an array. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. items MUST be present if the type is array.

```
@SWG\Parameter(parameter="goods",name="goods",in="formData",type="array",description="goods",
    @SWG\Items(
        @SWG\Schema(
            @SWG\Property(parameter="id",name="id",in="formData",type="integer",description="ID",required=true),
            @SWG\Property(parameter="number",name="number",in="formData",type="integer",description="number"),            
        ),
    ),
),
```

Take the OpenAPI spec as your basis, and write your docblocks accordingly.

**Comment by WonlyCms** [comment]
> You are missing a `@SWG\Schema` within the `@SWG\Items`. The nested key=values are `@SWG\Property`s. `@SWG\Parameter` is only for header/query-string/path parameters.
> 
> https://swagger.io/specification/#schemaObject
> 
> > items - Value MUST be an object and not an array. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. items MUST be present if the type is array.
> 
> ```
> @SWG\Parameter(parameter="goods",name="goods",in="formData",type="array",description="goods",
>     @SWG\Items(
>         @SWG\Schema(
>             required={"id"},
>             @SWG\Property(property="id",type="integer",description="ID"),
>             @SWG\Property(property="number",type="integer",description="number"),            
>         ),
>     ),
> ),
> ```
> 
> Take the OpenAPI spec as your basis, and write your docblocks accordingly.
> 
> PS: I also think the main `@SWG\Parameter` should probably not be `formData`... the above example json is being sent as body content?

Thank you very much, with your help, I tried using `@SWG\Parameter(... type="body")` (** this is very important**), because at the beginning I didn't know `@SWG\Property ` Can work in `@SWG\Parameter`, so I raised this question, now I use `@SWG\Schema`, it is already working. To help others, I posted the code I used below. .

```
@SWG\Parameter(parameter="goods",name="goods",in="body",required=true,type="array",description="ObjectArray",
    @SWG\Schema(
        @SWG\Items(
          @SWG\Property(type="integer",property="id",description="ID"),
          @SWG\Property(type="integer",property="number",description="Number"),
       )
    )
),
```
like this,
![image](https://user-images.githubusercontent.com/31845646/66796704-1e2ec000-ef3b-11e9-940b-87b7a1c98f10.png)

I changed another way because of business changes, like this.
```
@SWG\Parameter(parameter="goods",name="goods",in="body",required=true,type="array",description="ID Array",
    @SWG\Schema(
        @SWG\Items(
          type="integer"
       )
    )
),
```
It looks like this.
![image](https://user-images.githubusercontent.com/31845646/66796813-60f09800-ef3b-11e9-9f40-c44d2eb6978f.png)

**Comment by Doqnach** [comment]
The above also looks like Swagger 2.0 instead of OpenAPI 3 (it's successor). I do advise you to switch, and to the newer version of swagger-php.

It would then look something like this:

```
    /**
     * @OA\Post(
     *     path="/foo",
     *     operationId="doFoo",
     *     tags={"Foo"},
     *     @OA\RequestBody(
     *          @OA\Schema(
     *              @OA\Property(
     *                  property="goods", 
     *                  type="array",
     *                  @OA\Items(
     *                      @OA\Schema(
     *                          required={"id"},
     *                          @OA\Property(property="id", type="integer"),
     *                          @OA\Property(property="number", type="integer"),
     *                      )
     *                  )
     *              )
     *          )
     *     ),
     *     @OA\Response(
     *          response=201,
     *          description="Done foo",
     *     ),
     *     @OA\Response(
     *          response=400,
     *          description="Failed to save",
     *          @OA\Schema(ref="#/definitions/failure"),
     *     ),
     * )
     */
```

**Comment by WonlyCms** [comment]
> The above also looks like Swagger 2.0 instead of OpenAPI 3 (it's successor). I do advise you to switch, and to the newer version of swagger-php.
> 
> It would then look something like this:
> 
> ```
>     /**
>      * @OA\Post(
>      *     path="/foo",
>      *     operationId="doFoo",
>      *     tags={"Foo"},
>      *     @OA\RequestBody(
>      *          @OA\Schema(
>      *              @OA\Property(
>      *                  property="goods", 
>      *                  type="array",
>      *                  @OA\Items(
>      *                      @OA\Schema(
>      *                          required={"id"},
>      *                          @OA\Property(property="id", type="integer"),
>      *                          @OA\Property(property="number", type="integer"),
>      *                      )
>      *                  )
>      *              )
>      *          )
>      *     ),
>      *     @OA\Response(
>      *          response=201,
>      *          description="Done foo",
>      *     ),
>      *     @OA\Response(
>      *          response=400,
>      *          description="Failed to save",
>      *          @OA\Schema(ref="#/definitions/failure"),
>      *     ),
>      * )
>      */
> ```

Ok, I will try to do this in the future, thank you.
