### ISSUE TITLE
Broken comment block in Examples/petstore-3.0/api.php

### ISSUE THREAD

**Issue by csbarker** [zircote/swagger-php#727]
The comment block is broken here:

https://github.com/zircote/swagger-php/blob/master/Examples/petstore-3.0/api.php#L10

**Comment by bfanger** [comment]
The comment block is fine, but the formatting and linters disagree.
I don't like it either, but his is an issue with doctine-annotations, if you'll find a better way to document multi-line text inside an annotation, let me know.

Until then this remains a good example annotation.

**Comment by Doqnach** [comment]
Could always put it in a `define()` and reference it there? It would satisfy the linters and formatters... even though it's of course not the prettiest solution.
