### ISSUE TITLE
Required @OA\Info() not found

### ISSUE THREAD

**Issue by mukeshphpdev** [zircote/swagger-php#730]
getting -> Required @OA\Info() not found

**Comment by Doqnach** [comment]
That means that nowhere in the `scan()` path(s) any `@OA\Info()` is specified, but it is mandatory.

**Comment by mukeshphpdev** [comment]
Thanks you for the answering, i was using swagger-php: 3.0 version then i getting the error, when i use swagger-php: 2.* version and after install 2.* version need to clear cache then its working perfectly.

Thanks.

**Comment by Doqnach** [comment]
@mukeshphpdev Please note that the namespace for the annotations changed from `@SWG\` to `@OA\` between versions 2.x and 3.x, to reflect the change from Swagger (<=2.x) to OpenAPI (>3.x).

**Comment by JimChenWYU** [comment]
@mukeshphpdev Hi, i was using swagger-php: 3.0 version then i meeting the problem, how to clear cache?

**Comment by emund1101** [comment]
the file charset must be set utf-8,otherwise will notice Required @OA\Info() not found;

**Comment by Doqnach** [comment]
@emund1101 that is a very interesting quirk? Could you maybe provide an example github repo that showcases this behaviour? Because that does sound like a bug to me.
