### ISSUE TITLE
Site of Documentation is broken

### ISSUE THREAD

**Issue by DanielOrtegaZ** [zircote/swagger-php#732]
Seems like your site where documentation is given is broken

**Comment by Doqnach** [comment]
Looks like a DNS issue... there is no A record at all for `zircote.com`.
There is however a CNAME for `www.zircote.com` that points to `zircote.github.com`, but that redirects back to `zircote.com`.

**Comment by mcarbonneaux** [comment]
is not a tentative to rework the documentation site to use github page ?

**Comment by eleftrik** [comment]
@zircote What happened to your site?

**Comment by qkdreyer** [comment]
Could you have a look a this issue @zircote ?

**Comment by umbrellait-danil-rodin** [comment]
http://zircote.github.io/swagger-php/
