### ISSUE TITLE
How to use class doc-block comment as the Schema description?

### ISSUE THREAD

**Issue by scipilot** [zircote/swagger-php#733]
It's great that properties pick up their `description` from the doc-block comment.

However it seems that the doc-block comment for a model as a Schema doesn't do the same. So I have to duplicate the description in the annotations. I've looked through the documentation and also tried to follow the code, but cannot see if I've done something wrong, or this isn't supported. I can't see any closed or open issues either, I'm surprised no one else has requested it.

Am I missing something or is this how it's supposed to work?

e.g. I have many models, to which I simply added `@OA\Property()` annotations to, and they look pretty good in the swagger docs with their existing comments.

But the main schema description doesn't get scraped from the class doc-block, so I have to copy it in:

```
/**
 * News articles are announcements from the test admin team.
 * 
 * @OA\Schema(description="News articles are announcements from the test admin team.")
 */
class NewsArticle {

	/**
	 * Article Title
	 * @var string
	 * @OA\Property()
	 */
	public $title;

	/**
	 * Main article body content.
	 * @var string
	 * @OA\Property()
	 */
	public $body;

	/**
	 * Publish/sort date.
	 * Enables the list of articles to be presented on the site in date-order.
	 * 
	 * @var \DateTime
	 * @OA\Property()
	 */
	public $published;
}
```

Is there a way to automate it and keep it DRY?

**Comment by bfanger** [comment]
This feature will be part of the next release
