### ISSUE TITLE
@OA\Property()->maxLength is a "string", expecting a "integer"

### ISSUE THREAD

**Issue by bobahbi44** [zircote/swagger-php#737]
https://swagger.io/docs/specification/data-models/data-types/

A string of text is defined as:
>type: string

String length can be restricted using minLength and maxLength:
>type: string
minLength: 3
maxLength: 20

Note that an empty string "" is a valid string unless minLength or pattern is specified.

**Comment by Doqnach** [comment]
What the error means is that when defining the value a string is given instead of an integer.
Example:
```
WRONG:
@OA\Property(type="string", maxLenght="3")

RIGHT:
@OA\Property(type="string", maxLength=3)
```

Note the quotes around the value in the first example, and none in the second.
