### ISSUE TITLE
Homepage is down

### ISSUE THREAD

**Issue by ll9** [zircote/swagger-php#740]
Since several days I cant reacht http://zircote.com/swagger-php/. 
You should either fix the link or remove it entirely.

**Comment by javaDeveloperKid** [comment]
Still down. Can someone take care of it?

**Comment by Doqnach** [comment]
No, only people who can manage the DNS records of the domain can... which I guess is only @zircote .

**Comment by dev-mansonthomas** [comment]
The get started can be still read here (scroll down, the lack of css mess up the ui) : 
https://web.archive.org/web/20190531222822/http://zircote.com/swagger-php/Getting-started.html

@zircote any new year resolution around to bring the website up :)

**Comment by luhuiya** [comment]
@zircote the web cannot be accessed

**Comment by ThaDaVos** [comment]
Any ETA for it getting back up? Some documentation would be nice to have ;)

**Comment by bfanger** [comment]
The documentation is up again, but on a different url:

https://zircote.github.io/swagger-php/
