### ISSUE TITLE
PHP 7.4 Class typed properties breaks Analysis

### ISSUE THREAD

**Issue by ymilin** [zircote/swagger-php#742]
Hi,

The new PHP 7.4 typed property feature is a godsend for this library and would really help reduce the use of comment Annotations in Models.

`type` can now be directly deduced from `PHP` tokens as well as the `nullable` property (c.f. #705 / #711), which brings a more robust way of defining Models.

Example:
PHP < 7.4
```php
/**
 * @OA\Schema
 */
class ExampleModel
{
    /**
     * @var int|null
     * @OA\Property
     */
    private $id;

    /**
     * @var string
     * @OA\Property
     */
    private $name;

    /**
     * @var \DateTimeInterface|null
     * @OA\Property(type="datetime")
     */
    private $createdAt;
}
```

PHP >= 7.4
```php
/**
 * @OA\Schema
 */
class ExampleModel
{
    /** @OA\Property */
    private ?int $id;

    /** @OA\Property */
    private string $name;

    /** @OA\Property(type="datetime") */
    private ?\DateTimeInterface $createdAt;
}
```

I tried them out and they make the `StaticAnalyser` fail; it fails to get property names while parsing the tokens as it doesn't recognise the new format.

**Comment by rbaarsma** [comment]
Any chance we can merge this. It's an annoying bug that kind of prevents me from using php 7.4 (although I could create a workaround, I'd prefer this to be fixed :) and looks like a simple merge)

**Comment by ymilin** [comment]
@rbaarsma This is the issue, not the PR so your comment is off topic here.

I'd like to be fixed too and IMO @jpuck did a great job.

But it's not a _simple merge_ and maintainers must take the time to review the PR. Sometimes they don't and we must accept that.
