### ISSUE TITLE
how to specify a hashmap?

### ISSUE THREAD

**Issue by dbu** [zircote/swagger-php#744]
Looking at the OpenAPI spec, there seems to be a way to specify a hashmap, that is, a PHP array with string keys: https://swagger.io/docs/specification/data-models/dictionaries/

What would be the correct annotation to have swagger-php generate this?

A standard thing that e.g. JMSSerializer uses is `@var array<string, Model>`, but that generates me a openapi json that only has `description: Model>` (with the closing `>`). Do you use a different syntax, or is this not implemented?

**Comment by Doqnach** [comment]
The comments follow the same syntax as OpenAPI, so:

```php
/**
 *     @OA\Schema(
 *       additionalProperties={
 *         "type":"integer",
 *         "format":"int32"
 *       }
 *     )
 */
```
See `zircote/swagger-php/Examples/petstore.swagger.io/controllers/StoreController.php`

Since there is no official PHPDoc/Psr-5 notation for this data-type I don't think swagger-php has any auto-detect support for it based on `@var`.

**Comment by dbu** [comment]
thanks, indeed!

i did this on my model:

```
    /**
     * Hashmap of variant attributes.
     *
     * @var Attribute[]
     * @SWG\Property(
     *     type="object",
     *     additionalProperties={
     *         "$ref":"#/definitions/Attribute"
     *     }
     * )
     */
     private $attributes = [];
```

**Comment by Doqnach** [comment]
@dbu the above notation does not look right, see my example. 

You also seem to be still using the older version of swagger-php? (because of the `@SWG\` namespace).

**Comment by dbu** [comment]
we are on version 2. the annotation that i did worked fine in version 2, we saw the expected output in swagger-ui. 

thanks for the heads up. we hopefully will migrate to version 3 at some point, but as our consumers are based on swagger 2.0, this will be a complex operation and is not high on the priority list...
