### ISSUE TITLE
Seemingly cannot define and use a reuseable parameters list

### ISSUE THREAD

**Issue by richvigorito** [zircote/swagger-php#745]
There doesnt seem to be a way to create a reusable list parameters to be reusable in multiple routes. I posted the desired outcome here. Ive been scratching my head on this for a day, cant tell if im ignorant to some syntax/annotation or if this is a swagger OR swagger-php package limitation.

https://stackoverflow.com/questions/59428832/how-to-define-and-use-a-reuseable-parameter-list-for-swagger-in-php

**Comment by Doqnach** [comment]
Swagger-PHP reflects OpenAPI directly... so whatever you can do there you can do in Swagger-PHP.

https://swagger.io/docs/specification/components/

**Comment by bfanger** [comment]
swagger-php ( and the spec https://github.com/OAI/OpenAPI-Specification/issues/445 ) does not provide a way to reuse a group of parameters. 

You can write your own plugin by writing a processor which injects those `@OA\Parameter(ref)`s based on a custom var like `x={"params":"sort-by,sort-order,page,page-size"}` for example.
