### ISSUE TITLE
Validate data types

### ISSUE THREAD

**Issue by waahhhh** [zircote/swagger-php#749]
**Feature-Request:**
This project should validate the given data types.  
For valid data types see: https://swagger.io/docs/specification/data-models/data-types

**As example:**
We define the type of "load" as `float`, but this should be `number`.

Defined in test.php:  
```php
<?php declare(strict_types=1);

use OpenApi\Annotations as OA;

/**
 * @OA\Info(title="Example", version="3.0")
 * @OA\Server(
 *     description="Dev",
 *     url="https://localhost"
 * )
 * @OA\Get(
 *      path="/health/load.json",
 *      @OA\Response(
 *          response=200,
 *          description="Get current server load",
 *          @OA\JsonContent(
 *              required={"success"},
 *              @OA\Property(property="success", type="boolean"),
 *              @OA\Property(property="load", type="float")
 *          )
 *      )
 * )
 */
```

Generate output as YAML (no error):  
```bash
php ./vendor/bin/openapi --output test.yml test.php
```
Output as test.yml:  
```yml
openapi: 3.0.0
info:
  title: Example
  version: '3.0'
servers:
  -
    url: 'https://localhost'
    description: Dev
paths:
  /health/load.json:
    get:
      responses:
        '200':
          description: 'Get current server load'
          content:
            application/json:
              schema:
                required:
                  - success
                properties:
                  success: { type: boolean }
                  load: { type: float }
                type: object

```

Verify output with http://editor.swagger.io:  
![image](https://user-images.githubusercontent.com/40632052/72153523-8a8c5480-33ae-11ea-9a8d-d2a0b00a72a3.png)

**Comment by bfanger** [comment]
That would be nice, looking forward to your PR.

**Comment by deepakboyka** [comment]
instead of using float as type write type="number"

**Comment by waahhhh** [comment]
@deepakboyka thanks for your feedback, but you don't seem to have understood the feature request.
Your answer is already described in the example.

This issue has also been closed for 1 year.
If there is still a need, please create a new issue.
