### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by bfanger** [zircote/swagger-php#751]
Looks like http://zircote.com is no longer hosted by github.

@zircote Could you change the DNS settings back to github? 

If you have other plans for zircote.com, could you remove the CNAME from https://github.com/zircote/zircote.github.com, that way the documentation url would become https://zircote.github.io/swagger-php/

**Comment by Doqnach** [comment]
See also #740

**Comment by luizjr** [comment]
See also

**Comment by marufmax** [comment]
still down, can someone care of it please?

**Comment by bfanger** [comment]
Documentation site has been moved to https://zircote.github.io/swagger-php/
