### ISSUE TITLE
Is it possible to inject php callable as enum values?

### ISSUE THREAD

**Issue by bogdan-dubyk** [zircote/swagger-php#752]
Is it possible to do something similar to https://symfony.com/doc/current/reference/constraints/Choice.html#supplying-the-choices-with-a-callback-function but passing callback to the enum?

It's annoying and hard to keep up to date if you need to specify a list of possible values in all places just as a string. Much easier is to hold all the list in one place and reuse it

**Comment by Doqnach** [comment]
The workaround I'm sometimes using right now is having a `const` with the enum values defined, and reference that.

```php
// pseudo-code:
define('MY_ENUM_VALUES', function() { /* get enum values */ });
/** @OA\Property(enum=MY_ENUM_VALUES) */
```

**Comment by bogdan-dubyk** [comment]
Not very clean. And how it works? I mean why define value accessible in annotations? I'm not familiar how it works

**Comment by bfanger** [comment]
No, as far as I know doctrine/annotations does not support passing a callback to an annotation
