### ISSUE TITLE
How do I define JSON response examples?

### ISSUE THREAD

**Issue by guillefixx** [zircote/swagger-php#753]
As far as I know, there's the **example** property, but how do I use it?

Let's say I want to define a JSON example for 200 HTTP responses. How can I achieve that?

Thanks in advance.

**Comment by kgrosvenor** [comment]
Hey you use the example property and just set it?

**Comment by guillefixx** [comment]
Hey @kgrosvenor,

Alright, but how do I set a JSON response? If I paste one, I can't generate swagger docs because it breaks due to having multiple lines between the double quotes.

**Comment by Doqnach** [comment]
Please provide an example of what you currently have.

One solution can be to put the example in a `define()` and then to refer to that in the docblock.

**Comment by bfanger** [comment]
You can write objects in doctrine annotations: http://zircote.github.io/swagger-php/Getting-started.html#arrays-and-objects (see the don't write section)

And because there is no annotation for your specific example object you should write that as an object.

**Comment by 54853315** [comment]
Hi 

Normally ,swagger OpenAPI can write `example: {"foo":"xxx"}` ,In swagger-php ,write `example="{foo:xxx}"` not work ,It show me like string ,not a JSON.

**Comment by Doqnach** [comment]
@54853315 try it without the quotes around it. See the comment above yours.
