### ISSUE TITLE
Swagger-php and CakePHP 3.x

### ISSUE THREAD

**Issue by ev8dev** [zircote/swagger-php#755]
Currently I am using CakePHP 3.6 and would like to create API documentation in AO 3 format. I can't seem to get it to work, how do I generate the json/yaml file? I've tried using the CLI with no luck.

Thanks in advance.

**Comment by bfanger** [comment]
Closing the issue as it's not specific enough, i'll need at least an swagger-php specific error message to provide a helpful answer.
