### ISSUE TITLE
502 http status code on web-site

### ISSUE THREAD

**Issue by maxnag** [zircote/swagger-php#757]
When I am trying to reach http://zircote.com/swagger-php/ I have:

DNS error
DNS error (the host name of the page you are looking for does not exist)

Please check that the host name has been spelled correctly.

**Comment by Doqnach** [comment]
Duplicate of #751 #740

**Comment by pmediel** [comment]
The documentation website is still down

**Comment by youkaihiei** [comment]
Looks like its up now.

**Comment by bfanger** [comment]
Documentation site has been moved to https://zircote.github.io/swagger-php/
