### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by vsychov** [zircote/swagger-php#759]
Hi guys, 

is this project abandoned or development continued in another place?
http://zircote.com/ is down, no commits and no PR accepted since end of 25 January.

**Comment by Doqnach** [comment]
In regards to the website, see: #757 #751 #740 #732

There is limited activity by e.g. @bfanger, no word at all from @zircote though since a long time.

Very unclear what the current status of this project is. Would love to contribute to it myself.

**Comment by mroeling** [comment]
I second that. Tried to contact both through Social media channels. No respons though. 

I'm looking forward to see some v2 php7.4 improvements, especially regarding the typed properties. 
Also tried to use the 3.x variant, but IMHO some conversions are incorrect in the current version (#750).

**Comment by DerManoMann** [comment]
:+1: Thought about that myself last week. Maybe one of the more active contributors could fork and merge some of the PRs under the premise to transfer code back should the owner(s) come back?

**Comment by bfanger** [comment]
I've transitioned to frontend-developer so I don't write a lot of api's these days.
I have limited free time and after 5 years this project is low on my fun-stuff-to-do list. 

I also don't have the rights to add new collaborators, which makes it hard to enroll active contributors.

@DerManoMann I like the idea of a trusted fork where i can just merge from.

I hope this clarifies the state of the project, so i'm closing this issue.

**Comment by DerManoMann** [comment]
@bfanger I suppose you have considered forking yourself and decided not to due to time/motivation constraints?
I'd be happy to discuss investing some time into an 'official' fork as I am using the project in some of my own libraries and projects so I do have an interest in keeping it going...
