### ISSUE TITLE
How to descript my doc friendly

### ISSUE THREAD

**Issue by hanyunmuyu** [zircote/swagger-php#762]
When I use "descriotion" to descript my response , I want to use markdown to descript my doc.
`

    /**
     * @OA\Get(
     *     path="/admin/v2/group",
     *     summary="获得节点列表",
     *     description="|  表头   | 表头  |
|  ----  | ----  |
| 单元格  | 单元格 |
| 单元格  | 单元格 |
```javascript
$(document).ready(function () {
alert('RUNOOB');
});
```
    ",
     *     tags={"cdn","区域分组"},
     *      security={{"bearerAuth":{}}},
     *     @OA\Parameter(
     *     required=false,
     *     name="page",
     *     in="query",
     *     description="页码",
     *     @OA\Schema(type="integer",default="1")
     * ),
     *     @OA\Response(response="200",
     *      description="成功",
     *       @OA\JsonContent(ref="#/components/schemas/Response")
     * ),
     *     @OA\Response(response="400",
     *      description="失败",
     *       @OA\JsonContent(ref="#/components/schemas/Response")
     * )
     * ),
     */

`
this is unfriendly,
Can I use like this
`

    /**
     * @OA\Get(
     *     path="/admin/v2/group",
     *     summary="获得节点列表",
     *     description="|  表头   | 表头  |",
     *     description="|  ----  | ----  |",
     *     description="| 单元格  | 单元格 |",
     *     tags={"cdn","区域分组"},
     *      security={{"bearerAuth":{}}},
     *     @OA\Parameter(
     *     required=false,
     *     name="page",
     *     in="query",
     *     description="页码",
     *     @OA\Schema(type="integer",default="1")
     * ),
     *     @OA\Response(response="200",
     *      description="成功",
     *       @OA\JsonContent(ref="#/components/schemas/Response")
     * ),
     *     @OA\Response(response="400",
     *      description="失败",
     *       @OA\JsonContent(ref="#/components/schemas/Response")
     * )
     * ),
     */
`
I think is friendly to write my doc.But  php swagger does not supported.

**Comment by Doqnach** [comment]
Easier is to put the description in a `define()` and reference that from the docs.

```php
define('MY_DESCRIPTION', <<<EOF
    |  表头   | 表头  |
    | ---- | ---- |
    | 单元格 | 单元格 |
    | 单元格 | 单元格 |
    EOF
);
/**
 * @OA\Get(
 *     path="/admin/v2/group",
 *     summary="获得节点列表",
 *     description=MY_DESCRIPTION,
 *     tags={"cdn","区域分组"},
 *      security={{"bearerAuth":{}}},
 *     @OA\Parameter(
 *     required=false,
 *     name="page",
 *     in="query",
 *     description="页码",
 *     @OA\Schema(type="integer",default="1")
 * ),
 *     @OA\Response(response="200",
 *      description="成功",
 *       @OA\JsonContent(ref="#/components/schemas/Response")
 * ),
 *     @OA\Response(response="400",
 *      description="失败",
 *       @OA\JsonContent(ref="#/components/schemas/Response")
 * )
 * ),
 */
```

**Comment by hanyunmuyu** [comment]
Thanks. I have a of APIs and everyone has a different doc , i must descipt them to the others.

**Comment by bfanger** [comment]
Multiline values are possible in doctrine/annotations, but are not pretty (my editor doesn't like em) but they do work:

```
/**
 * @OA\Get(
 *     path="/admin/v2/group",
 *     summary="获得节点列表",
 *     description="|  表头   | 表头  |
    | ---- | ---- |
    | 单元格 | 单元格 |
    | 单元格 | 单元格 |",
 *   tags={"cdn","区域分组"},
 *   ...
```
