### ISSUE TITLE
Too little documentation/examples

### ISSUE THREAD

**Issue by MartijnZuijd** [zircote/swagger-php#763]
As it seems the original project owner seems to have abandoned the project and the documentation website does not seem to be reachable, this project now has too little documentation. 

I want to work with features like oneOf responses and expanding models but there does not seem to be any documentation/example of this.

Is there a way to get in repos documentation on how to use this and other use cases?

**Comment by Doqnach** [comment]
See https://github.com/zircote/swagger-php/issues/740#issuecomment-570922327 for the link to the web archive of the docs.

There are quite a few issues regarding `oneOf` and `anyOf` which might help you.

**Comment by umbrellait-danil-rodin** [comment]
http://zircote.github.io/swagger-php/

**Comment by bfanger** [comment]
http://zircote.github.io/swagger-php/ shows how to get up and running with swagger-**php**

We also have [lots of examples](https://github.com/zircote/swagger-php/tree/master/Examples)

But documenting openapi/swagger specification or doctrine-annotations is outside the scope of this project.

I'll recommend:
https://swagger.io/docs/specification/about/
https://swagger.io/specification/

That said, the documentation can always be improved, this is open-source and the docs are just markdown files in https://github.com/zircote/swagger-php/tree/master/docs
**Feel free to contribute!**
