### ISSUE TITLE
Swagger annotation multiple object

### ISSUE THREAD

**Issue by Nadery** [zircote/swagger-php#764]
Hey I face problems to create this  JSON format with swagger annotation 
{
"users": [
                {
                    "user_id": 2,
                    "response":"test"
                },
                {
                     "user_id": 5,
                    "response":"test"
                }
             ]
}
t tried many things but not work for me this is my actual code

    * @SWG\Post(
     *      path="/users",
     *      tags={"Users"},
     *      security={
     *            {"passport": {}},
     *          },
     *      @SWG\Parameter(name="body",required=true,in="body",
     *         @SWG\Schema(
     *             @SWG\Property(
     *                 property="users",
     *                 type="array",
     *                @SWG\Items(
     *                 type="object",
     *                    @SWG\Property(
     *                    property="user_id",
     *                    type="integer",
     *                     ),
     *                    @SWG\Property(
     *                    property="response",
     *                    type="string"
     *                    ),
     *                 ),
     *              ),
     *           ),
     *        ),

**Comment by Flavyoo** [comment]
I'm also trying to figure out if we can have multiple objects returned in an array as ref for `Items`.

**Comment by bfanger** [comment]
I believe `@SWG\Parameter` is already a schema and doesn't need a nested `@SWG\Schema`

@Flavyoo you can define multiple object shapes with the `anyOf` and `oneOf`

But 2.x is no longer supported.
