### ISSUE TITLE
Downloading PDF in response through swagger UI

### ISSUE THREAD

**Issue by ovosodo** [zircote/swagger-php#766]
Hello,

I'm documenting APIs for a Laravel 6 application.
I'm trying to describe a response for an API that download a PDF in response and trying to download that file through Swagger UI.

response si described ad:

```
     *     @OA\Response(
     *         response="200",
     *         description="Success",
     *          @OA\MediaType(
     *              mediaType="application/pdf",
     *              @OA\Schema(type="string",format="binary")
     *          )
            )
```

the documentation is correctly generated but when I trying the API a get the PDF printed as string with the following message:

`Unrecognized response type; displaying content as text.`

The API works correctly and produces following headers:

```
access-control-allow-headers: *  
access-control-allow-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS  
access-control-allow-origin: *  
cache-control: no-cache, private  
connection: keep-alive  
content-disposition: inline; filename="document.pdf"  
content-type: application/pdf  
date: Mon, 06 Apr 2020 09:43:21 GMT  
server: nginx/1.15.0  
transfer-encoding: chunked  
x-ratelimit-limit: 120  
x-ratelimit-remaining: 117
```

Can you suggest a solution, please?

**Comment by Doqnach** [comment]
This doesn't really have anything to do with swagger-php. This might be a tooling issue. Swagger-php only provides documentation, no implementation.

**Comment by ovosodo** [comment]
I know that... but it parses annotations around the code to generate interactive OpenAPI documentation.
I'm asking what is the correct way to declare that an API returns a PDF as downloadable file because the interactive documentation is not beheaving correctly in my case.

**Comment by Doqnach** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

Might be the `inline` there, instead of `attachment`. Don't think OpenAPI gives any specific control over that, but maybe some `X-...` extension can help with it?

**Comment by ovosodo** [comment]
Ok, thank you.. That is the problem. I'll figure out it how to solve differently.

**Comment by allestaire** [comment]
Please share your solution
