### ISSUE TITLE
Exit Code !=0 on INFO

### ISSUE THREAD

**Issue by pharazon** [zircote/swagger-php#767]
I would like swagger-php to exit code (unix exit code) other than 0 (true) if there is any INFO or NOTICE

For example I get:
Swagger-PHP 2.0.6
-----------------
[INFO] @SWG\Put() requires at least one @SWG\Response() in \My\Project\MyService->setProperty() in ./src/MyProject/MyService.php on line 70
[NOTICE] Undefined index: allowMultiple in /vagrant/myproject/vendor/zircote/swagger-php/src/Annotations/AbstractAnnotation.php on line 241

but the exit code is 0.

My use case is that I would like to build a CI (Jenkins) job that would fail if there are any INFO or NOTICE errors, meaning that there is a syntax error in the swagger/openapi tags, and fail the build.

**Comment by bfanger** [comment]
The behavior you're describing is indeed unwanted, but 2.x is no longer actively maintained (by me).

Try fixing it yourself and create a PR.
