### ISSUE TITLE
Cannot use Response's `response` property for status codes when that Response is used for refs

### ISSUE THREAD

**Issue by amcsi** [zircote/swagger-php#769]
I want to create a reusable response that also has the status code applied.

Here is a rough example of how it would look like. (I made it super simple looking just for the sake of example; I actually have a bunch of properties in the response, I just don't want it to distract anyone):

A.php
```php
/**
 * @OA\Response(
 *   response=422,
 *   description="Error during input validation.",
 */
```

The `response` property is for specifying what the response code should be.

However, for Response annotations the `response` property _also_ is responsible for making it reference-able as a ref. So if I wanted to reuse that response, it would have to look like e.g.:

A.php
```php
/**
 * @OA\Response(
 *   response="validation_error",
 *   description="Error during input validation.",
 */
```

And where I'd be using it would be:

B.php
```php
/**
 *    @OA\Response(
 *      response=422,
 *      ref="#/components/responses/validation_error"
 *    ),
```

See how I had to specify the response code above _outside_. This is not good; I don't want to have to repeat specifying the response status code every time I use this reusable ref; I want the status code specified in `A.php` so I wouldn't have to repeat it. But I can't tell it that, because I need to use the `response` field there for reference-ability, and I can't use it for status codes anymore.

How can I be able to specify the response status code in `A.php` while being able to reference that as a ref?

**Comment by bfanger** [comment]
You can't, this has to do with the way refs work and how the spec formats the responses (using the http code as key)

You can write your own plugin for swagger-php using a custom annotation `@MyNamespace\Response("validation_error")` and implement a processor to inject the statuscodes, but that a lot of work to reduce some duplication.

If you do write a plugin, let me know i'll glady add it to the [Related projects page](http://zircote.github.io/swagger-php/Related-projects.html)
