### ISSUE TITLE
Allowed Memory size exhausted

### ISSUE THREAD

**Issue by bratelefant** [zircote/swagger-php#787]
Hi there,

after adding some new @OA\Schema entries to my project, swagger-php gives me this memory warning

```PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8388616 bytes) in .../.composer/vendor/zircote/swagger-php/src/StaticAnalyser.php on line 75```

What is the typical memory consumption for swagger-php, and can I assign more memory than just 128MB to the process? Or is it possible that my annotations using ref cause some infinite loop during processing?

Any help appreciated

**Comment by DerManoMann** [comment]
You can alwasy try to give it more memory to see if that helps.

Not sure about typical memory usage, but it is something I've started thinking about working on a few PRs lately. We'll see..

If increased memory doesn't help and there isn't any other error message I guess a recursion of some sort is a good candidate. If that is the case it will be hard to diagnose without the source files being parsed...

**Comment by bratelefant** [comment]
Doubled the assigned memory to 256M, now it’s doing well again, so no recursion issue or something.
