### ISSUE TITLE
Creating components.responses

### ISSUE THREAD

**Issue by BarryHelfrich** [zircote/swagger-php#788]
Hello,
Is there a way to re-use responses as defined in:
https://swagger.io/docs/specification/describing-responses/#reuse
Excellent project, thank you very much.

**Comment by DerManoMann** [comment]
Yes, you can. Only caveat is that due to the way the spec is structured for responses right now you need to always specify the response status code.

Controller:
```
/**
 *  ... 
 *    @OA\Response(
 *      response=404,
 *      ref="#/components/responses/NotFound"
 *    ),
 *  ... 
 */
```
Somewhere central to reuse...
```
/**
 * @OA\Response(
 *   response="NotFound",
 *   description="The specified resource was not found",
 *  ... 
 */
```

**Comment by DerManoMann** [comment]
There are also a couple examples in here: 
https://github.com/zircote/swagger-php/tree/master/Examples/using-refs

**Comment by BarryHelfrich** [comment]
Thanks!
