### ISSUE TITLE
User Notice: Required @OA\PathItem() not found

### ISSUE THREAD

**Issue by mohamed-jebri** [zircote/swagger-php#797]
Hi,
I m using symfony 4.4 / nelmio api doc bundle 4.0 / swagger-php 3.0.
When i try with a first example i get this error : User Notice: Required @OA\PathItem() not found

`
   namespace App\Controller;

 use OpenApi\Annotations as OA;

 /**
  * @OA\PathItem(
  *   path="/products/{product_id}",
  *   @OA\Parameter(ref="#/components/parameters/product_id_in_path_required")
  * )
  */

   class ProductController
   {

    /**
     * @OA\Get(
     *   tags={"Products"},
     *   path="/products/{product_id}",
     *   @OA\Response(
     *       response="default",
     *       description="successful operation",
     *       @OA\JsonContent(ref="#/components/responses/product")
     *   )
     * )
     */
    public function getProduct($id)
    {
    }

    }`

**Comment by Doqnach** [comment]
`@OA\PathItem` you don't normally use, but use `@OA\Get` and it's siblings instead.

https://zircote.github.io/swagger-php/Getting-started.html#json-or-xml

> On a similar note, you generally don't have to write a @OA\PathItem because this annotation will be generated based on the path in operation @OA\Get, @OA\Post, etc.

**Comment by mohamed-jebri** [comment]
i have tried with this example but the error still here : 

`namespace App\Controller;

use OpenApi\Annotations as OA;


class ProductController
{

    /**
     * @OA\Get(
     *   tags={"Products"},
     *   path="/products/{product_id}",
     *   @OA\Response(
     *       response="default",
     *       description="successful operation",
     *       @OA\JsonContent(ref="#/components/responses/product")
     *   )
     * )
     */
    public function getProduct($id)
    {
    }

    }`

**Comment by mohamed-jebri** [comment]
I tried with examples : 
https://github.com/zircote/swagger-php/blob/3.0.0/Examples/example-object/example-object.php
https://github.com/zircote/swagger-php/blob/3.0.0/Examples/using-refs/ProductController.php

**Comment by vitornovo54** [comment]
Same here, breaks everything and the path object in the JSON is not being created.

FastCGI sent in stderr: "PHP message: PHP Notice:  Required @OA\PathItem() not found

**Comment by mohamed-jebri** [comment]
[2020-06-09 09:49:33] request.INFO: Matched route "app.swagger_ui_summary". {"route":"app.swagger_ui_summary","route_parameters":{"_route":"app.swagger_ui_summary","_controller":"nelmio_api_doc.controller.swagger_ui","area":"default"},"request_uri":"https://127.0.0.1:8000/api/doc","method":"GET"} []
[2020-06-09 09:49:33] request.CRITICAL: Uncaught PHP Exception ErrorException: "User Notice: Required @OA\PathItem() not found" at C:\wamp64\www\api\vendor\zircote\swagger-php\src\Logger.php line 39 {"exception":"[object] (ErrorException(code: 0): User Notice: Required @OA\\PathItem() not found at C:\\wamp64\\www\\api\\vendor\\zircote\\swagger-php\\src\\Logger.php:39)"} []

**Comment by DerManoMann** [comment]
When you say `swagger-php 3.0.` - do you mean 3.0.**0** or 3.0.**1** or ...?

The examples are all evaluated as part of the tests, so I would strongly believe they do work as expected.

Apart from providing a small, self contained sample app the only thing I can think of is to run swagger-php manually, something like
```
./vendor/bin/openapi src/
```

although most likely that will also show 
```
Required @OA\Info() not found
Required @OA\PathItem() not found
```
as typically those are injected by the `NelmioApiDocBundle`

**Comment by DerManoMann** [comment]
Any chance this is due to cached routes or similar?

**Comment by mohamed-jebri** [comment]
"zircote/swagger-php": "3.0.4"

the output of : $ ./vendor/bin/openapi src/ : 
openapi: 3.0.0
paths:
  '/products/{product_id}':
    get:
      tags:
        - Products
      operationId: 'App\Controller\ProductController::products'
      responses:
        default:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/responses/product'
    parameters:
      -
        $ref: '#/components/parameters/product_id_in_path_required'
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header

**Comment by mohamed-jebri** [comment]
[OK] Web server listening                                                     
      The Web server is using PHP CGI 7.2.10                                   
      https://127.0.0.1:8000

**Comment by DerManoMann** [comment]
Does that mean it is now working? The output from the manual run suggests that swagger-php seems to be happy with the annotations.

**Comment by mohamed-jebri** [comment]
The output of the command is ok but the output of the browser is not ok : User Notice: Required @OA\PathItem() not found

**Comment by Doqnach** [comment]
@mohamed-jebri could you maybe create a github repo that shows the exact problem you are having, with sample code and the exact commands you are giving/steps you are taking? Right now I'm having a really hard time understanding what is happening.

**Comment by DerManoMann** [comment]
> The output of the command is ok but the output of the browser is not ok : User Notice: Required @OA\PathItem() not found

That is my point - swagger-php is happy with the annotations. 

The code reading the annotations during request handling is from `NelmioApiDocBundle` (which does use swagger-php underneath, but also other code).
So, in my view that means this is more a `NelmioApiDocBundle` issue that swagger-php.

Apart from that I agreee with @Doqnach that having a repo that illustrates the problem, from here, is the only way forward.
