### ISSUE TITLE
Upgrade repository access for DerManoMann

### ISSUE THREAD

**Issue by bfanger** [zircote/swagger-php#802]
@zircote could invite @DerManoMann as Collaborator?

See [Inviting collaborators to a personal repository](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository)

**Comment by zircote** [comment]
@bfanger sorry for the delay; the invite is sent @DerManoMann.

**Comment by Doqnach** [comment]
congrats @DerManoMann !

**Comment by DerManoMann** [comment]
@bfanger @zircote thanks for the trust!

**Comment by DerManoMann** [comment]
> congrats @DerManoMann !

Thanks, @Doqnach
