### ISSUE TITLE
PHP 8.1 Attributes

### ISSUE THREAD

**Issue by DerManoMann** [zircote/swagger-php#806]
More a question than an issue....

Decided to have a play with [PHP8 attributes](https://stitcher.io/blog/attributes-in-php-8) today.

Looks like a lot of work ahead :)

**Comment by DerManoMann** [comment]
For anyone wondering here is the current state of affairs: https://github.com/DerManoMann/swagger-php/blob/php8/tests/Fixtures/Apis/basic_php8.php

A few notes:
* this branch mutated into a semi-major refactor, mostly due to the fact that I was determined to use reflection instead of the build in tokenizer to parse files/classes/interfaces/traits...
This does work well but comes with some overhead in case we also need to support scanning files/folders
* There is still a bug in the way attribute-annotations are added to the analysis - something in the context is not right
* I am doubtful that attributes are going to be usable for anyone unless nesting is supported (currently it is not :/ )
* It's fun how each PHP8 beta changes the attribute syntax :)
* Named arguments are rad!

**Comment by Doqnach** [comment]
I think scanning files/folders is rather important, isn't it? For one, I use the cli tool to scan a directory of source code to generate a static file.

`#[Attr]` should now be the final notation for PHP Attributes: https://externals.io/message/111630#111778

**Comment by DerManoMann** [comment]
> `#[Attr]` should now be the final notation

Yeah, I've updated the syntax for each beta so far :)

**Comment by Doqnach** [comment]
They said it's coming in next RC (see above link)

**Comment by DerManoMann** [comment]
Nested attribute support (via nested `new Attribute()`): https://wiki.php.net/rfc/new_in_initializers

**Comment by DerManoMann** [comment]
Time for an update - with PHP 8.1 looming its time to look at this again.

I've managed to sneak in a lot of smaller changes in the 3.x branch since I started on the php8/ attributes branch but there is still lots to do :)

Because of that I would propose bumping swagger-php version top 4.x with this change. I haven't refreshed my memory properly yet, but there is some significant changes required, in particular since attributes require to use reflection instead of just reading/tokenizing files...

**Comment by DerManoMann** [comment]
I should probably also add that with the version buming to 4.x all curently deprecated elements would be removed....

**Comment by DerManoMann** [comment]
Spend quite some time last weekend resurrecting my PHP/attributes branch. I think I am slowly moving towards a usable solution. However, there is one big gotcha.

Using reflection to find and instantiate attributes means we are limitied to things PHP can reflect on. In order to make things simpler the docblock based annotations will move to the same behavioir.

So, from what I can see that means file docblocks (not related to a class/method/interface/trait/etc.) cannnot be **seen** any more, unless there is a way to use reflection to find those.
That means all stand-alone docblocks will need to get a placeholder class so reflection can find them. Typically that should only affect the main `OpenApi` docblock/attributes so I think this is tolerable.

**Comment by DerManoMann** [comment]
I should also mention that reflection requires the files to be loaded, so classloading is required files that trigger sideeffects when loaded will be a problem!

**Comment by DerManoMann** [comment]
The attribute PR #982 is coming along nicely. Getting things to work across versions < 8.1 was a bit tryicky but is ok, IMHO.

Worth giving a try if you have access to a PHP 8.1 build. Support for named parameters is a bit random and not all annotations are supported but enough got get started.

If a (named) parameter is missing there is always  the option to pass in a map of key/value pairs...

**Comment by Saeed-Pooyanfar** [comment]
Waiting for v4 :smile:

**Comment by DerManoMann** [comment]
@Saeed-Pooyanfar feel free to give the branch a try.
There are a couple examples - https://github.com/DerManoMann/swagger-php/tree/php81-attributes/Examples/openapi-spec and https://github.com/DerManoMann/swagger-php/tree/php81-attributes/tests/Fixtures/Apis have attributes if you need inspiration to get started.

**Comment by Saeed-Pooyanfar** [comment]
``` php8.1 vendor/bin/openapi --help```
PHP Fatal error:  Uncaught Error: Class "Psr\Log\AbstractLogger" not found in /home/saeed/Projects/swagger/vendor/zircote/swagger-php/src/Loggers/ConsoleLogger.php:9
Stack trace:
#0 /home/saeed/Projects/swagger/vendor/composer/ClassLoader.php(571): include()
#1 /home/saeed/Projects/swagger/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 /home/saeed/Projects/swagger/vendor/zircote/swagger-php/bin/openapi(99): Composer\Autoload\ClassLoader->loadClass()
#3 {main}
  thrown in /home/saeed/Projects/swagger/vendor/zircote/swagger-php/src/Loggers/ConsoleLogger.php on line 9

**Comment by Saeed-Pooyanfar** [comment]
> ` php8.1 vendor/bin/openapi --help`
> PHP Fatal error: Uncaught Error: Class "Psr\Log\AbstractLogger" not found in /home/saeed/Projects/swagger/vendor/zircote/swagger-php/src/Loggers/ConsoleLogger.php:9
> Stack trace:
> #0 /home/saeed/Projects/swagger/vendor/composer/ClassLoader.php(571): include()
> #1 /home/saeed/Projects/swagger/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
> #2 /home/saeed/Projects/swagger/vendor/zircote/swagger-php/bin/openapi(99): Composer\Autoload\ClassLoader->loadClass()
> #3 {main}
> thrown in /home/saeed/Projects/swagger/vendor/zircote/swagger-php/src/Loggers/ConsoleLogger.php on line 9

I just manually installed `"psr/log": "^1.1.4"`
Now i'm getting: `PHP Warning: Required @OA\PathItem() not found in /home/saeed/Projects/swagger/vendor/zircote/swagger-php/src/Loggers/DefaultLogger.php on line 27`

**Comment by DerManoMann** [comment]
That is a bit disapointing :/
I'll have a look, thanks

**Comment by DerManoMann** [comment]
Updated - on `master` too!

**Comment by DerManoMann** [comment]
Pushed some refactoring and fixes that should make things work as expected - at least now all tests pass - even the accidentally broken examples test :)

**Comment by DerManoMann** [comment]
Removal of the remaining deprecated bits (static `Analysis` bits) is next on the list. This will include a refactor of the doctrine registry loader stuff... should be interesting!

**Comment by djairhogeuens** [comment]
@DerManoMann I had the same idea of using PHP attributes to generate an OpenAPI spec and then I stumbled into this thread. I had a quick look at your setup and I was wondering why you are trying to nest the attributes. Personally, I think it's a bit messy. I prefer to have it split across multiple attributes like this:

```php
#[Put]
#[Path(path: "news/:newsItemId")]
#[Response(code: HttpConstants::HTTP_STATUS_CODE_OK)]
public function updateNewsItem(
    #[PathParameter]
    int $newsItemId,
    #[RequestBody]
    UpdateNewsItemRequest $request
): NewsItemDetailResponse;
```

This is more in line with the Jax-RS specification in Java which can be used by the https://github.com/OpenAPITools/openapi-generator project for example.

Except for readability, the advantage is that it is also possible to use the attributes for other stuff (e.g. for routing and validating HTTP requests). I do this in my projects and my life has never been easier. I'm thinking about making the implementation a bit more generic so I can put it out on GitHub for the community to use it as well.

Are you willing to consider this or do you see any problems with this approach? If needed, I'm also willing to help out with this as I will probably try to set this up anyway if I cannot use the SwaggerPHP project.

Let me know what you think!

**Comment by DerManoMann** [comment]
That is actually a nice idea. I guess I got caught up in mirroring what the annotations do. I will have a bit of a think about it - I believe there might be value in both as I suspect there is quite some code out there where the request  body is not reflected in a model or frameworks allow to inject model instances directly into the controller where the path parameter is just an id. etc.

As for using things for routing and validating - have you seen my https://github.com/DerManoMann/openapi-router and https://github.com/DerManoMann/openapi-verifier projects :)

**Comment by DerManoMann** [comment]
Just looking at how non nested attributes could be implemented - might not be too hard in principle if there is a feasable way of knowing how to merge; I really do not want to break all similarities with what we have right now and internally pretty much everything can have a parent except `Annotations\OpenApi`... hhhm.

**Comment by djairhogeuens** [comment]
@DerManoMann I agree with the fact that there will still be a need for some nesting (the JsonContent nesting within the Response attribute is a good example where it makes sense indeed).

I would definitely try to remove the need for any order of attributes.

Is there something I can help you with? I will have to take a thorough look at the codebase first though as I've never seen it yet.

**Comment by DerManoMann** [comment]
Yeah, I don't like the ordering myself. Not sure if all dependencies are unambiguous which would be great.
Help, I don't know. Looking at the codebase definitely 🙂
Some testing would be good to get going. I know also that a few attribute constructors are still missing named properties...

**Comment by DerManoMann** [comment]
I've changed the code to not care about ordering. Also you can now add multiple operations :)
I guess we can leave it like that and see if we run into problems with ambiguity of parent / child relationships.

@djairhogeuens depending on how you feel about it it would be great to get a full API example using attributes (and perhaps the same in docblocks) - not necessarily lots of repeats, but using all annotations. I would expect that to break right now due to missing ctor args...

Another thing to get your vision forward would be to come up with a proposal for more attributes that could be useful. Just keep in mind that this project is about OpenAPI, not routing or other aspects...

**Comment by djairhogeuens** [comment]
@DerManoMann I would actually propose to create a different project that just contains all PHP attributes to offer full support for the OpenAPI spec as I don't think that exists yet (I propose a PHP port of https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-annotations). The SwaggerPHP project (and other projects, e.g. for routing, verification, etc.) could then just use this spec project to generate the JSON/YAML from it.

Then, I could set up an API with these attributes and a matching YAML file. What do you think?

**Comment by DerManoMann** [comment]
Interesting - I hadn't seen that before.

Not sure I want to start from scratch again although sometimes that would be nice rather than tiptoe around existing code ;)

Looking at issues I do not think there are a lot of things missing and if so it seems noone is missing them. I think I'd prefer to add support for missing things here if people are asking for it than starting from scratch for the sake of completeness that is not used (if that makes sense).

OTOH, if there was a simple, clean PHP implementation I'd be really keen to see if that could be incorporated ;)

**Comment by Saeed-Pooyanfar** [comment]
@DerManoMann Hi, can you please add example for json RequestBody ?
I want to document my api takes: `{items: MyModel[]}` as input, thanks.

**Comment by DerManoMann** [comment]
@Saeed-Pooyanfar on attributes branch? Sure.

**Comment by Saeed-Pooyanfar** [comment]
@DerManoMann yes, attributes branch. thanks.

**Comment by djairhogeuens** [comment]
@DerManoMann I've set up a PHP implementation of the OpenAPI spec based on attributes over the last few days. I would still like to include an extensive example using these attributes and some unit tests. I'll probably have something ready somewhere this week so you van take a look at it.

**Comment by DerManoMann** [comment]
@Saeed-Pooyanfar Branch is updated - thanks for testing :)

**Comment by Saeed-Pooyanfar** [comment]
@DerManoMann Thanks for the update!
In https://github.com/DerManoMann/swagger-php/blob/php81-attributes/src/Annotations/Operation.php#L237 i think we don't need `if ... else` because this is only for php8.1^
Also my IDE can't detected `Operation` class construct args because of `if ... else` and multiple definitions

**Comment by DerManoMann** [comment]
Well, it is and it isn't. The classes are also used for pre 8.1 PHP versions and named args are not compatible.
PHPStorm shows 2 class definitions but works fine if you set the level to 8.1 - at least for me.
The CLI should still work, I would think.
I'll have a play tomorrow, not sure I've used Operation directly before.

**Comment by DerManoMann** [comment]
Ha! So, I made `Operation` abstract again just as it is currently. With the individual HTTP method annotations (`@OA\Get`, etc.) there is no reason to use `Operation` directly and it is only there to share code. Makes sense?

**Comment by Saeed-Pooyanfar** [comment]
Hi @DerManoMann 
Can we use php8.1 enum for documenting ?
For example instead of declaring string type, using `MyEnum: string` to shows possible values ?

**Comment by DerManoMann** [comment]
Unfortunately no. T.he library requirements are ≥ PHP 7.2 for now.
However, since this is going to be a major version bump we could perhaps go for 8.0 although that still doesn't give you enums.
Hmmm, something to think about.

**Comment by Saeed-Pooyanfar** [comment]
@DerManoMann It would be better if you create specific version for php8.1^ because of important changes like attributes (new keyword) + enum + ...
Also you can remove multiple definitions for classes :smile:

**Comment by DerManoMann** [comment]
> @DerManoMann It would be better if you create specific version for php8.1^ because of important changes like attributes (new keyword) + enum + ... Also you can remove multiple definitions for classes 😄

I know, but that is unfortunately not how it works right now. Attributes are not going to disappear suddenly and there is no reasonable way to maintain more than one main branch.

**Comment by DerManoMann** [comment]
@djairhogeuens Any news on your more extensive test case? I think slowly the code is ready :)

Also I just pushed support for `PathParameter` as per your example: 4234c2d3f8a8665f1ca89f7ad93b2269a799f419 :)

**Comment by DerManoMann** [comment]
Sure can. However, rather than go through this too often, how about either collection a list of missing bits or creating a small repo with your annotated code using the properties array for missing bits and then I can fix all of those...?

**Comment by Saeed-Pooyanfar** [comment]
@DerManoMann i have to prepare api doc for our front-end developer.
I really want to help you to find all missing named args.
But i can't because of our project deadline. I comment missing cases here while I'm documenting the API.
Well! It's better than nothing :)

**Comment by DerManoMann** [comment]
Fair enough. Oh, well, if this is the only way..

**Comment by DerManoMann** [comment]
Yeah. There are 4 annotations that extend Schema... Will do but probably only next week

**Comment by DerManoMann** [comment]
@Saeed-Pooyanfar done

**Comment by DerManoMann** [comment]
Looking forward to seeing that extended example!

**Comment by Saeed-Pooyanfar** [comment]
@DerManoMann It seems that you just forgot to add `$deprecated` for `#[OA\Property(...)]`

**Comment by DerManoMann** [comment]
@Saeed-Pooyanfar Any update on your side? I'd be keen to get your extended example merged soon if possible. Even it is not complete it soulds like it will be a lot more that what I got so far :)

**Comment by Saeed-Pooyanfar** [comment]
> @Saeed-Pooyanfar Any update on your side? I'd be keen to get your extended example merged soon if possible. Even it is not complete it soulds like it will be a lot more that what I got so far :)

@DerManoMann unfortunately our front end developer left the team and i have to work as full stack developer, so i stopped using swagger for now!
But i'll write some examples if i get some free time.

**Comment by DerManoMann** [comment]
Flagged PR #982 as 'ready for review' - now is the time to test and give feedback!
