### ISSUE TITLE
Use Example Object 

### ISSUE THREAD

**Issue by liuquanhao** [zircote/swagger-php#807]
responses:
   200:
     examples: 
        foo:
          summary: A foo example
          value: {"foo": "bar"}
        bar:
          summary: A bar example
          value: {"bar": "baz"}

How write annotations?

**Comment by DerManoMann** [comment]
I think we'll need a few more details about what you are trying to do here.
Have you looked at the [examples](https://github.com/zircote/swagger-php/tree/master/Examples) at all?
