### ISSUE TITLE
array input parameter name in example lacks square brackets

### ISSUE THREAD

**Issue by charonme** [zircote/swagger-php#809]
I was testing the example in https://github.com/zircote/swagger-php/blob/master/Examples/swagger-spec/petstore-simple/SimplePetsController.php and it only worked properly with `name="tags[]",` instead of  `name="tags",` but I don't know if the annotation example is wrong or the generator that reads the annotation  forms the request incorrectly

**Comment by Doqnach** [comment]
The docblock is correct.

See: https://swagger.io/specification/#style-values

What generator are you talking about?

**Comment by charonme** [comment]
this one: https://github.com/swagger-api/swagger-ui/

**Comment by Doqnach** [comment]
The example is taken from the official repository: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore-expanded.yaml

Swagger-UI handles this as expected.

**Comment by charonme** [comment]
hmm so I guess it's a bug in that generator. I apologize I didn't realize it's not affiliated with this project

**Comment by Doqnach** [comment]
It is not a bug at all. URIs allow for the same query param to exist multiple times. The common way many programming language, especially PHP, do it is by adding the 'array' brackets to the name and they will end up as an array in the code (instead of overwriting a previously declared version). So it is not wrong to write it as `tags`, but more common in specifically PHP would be `tags[]`.

**Comment by charonme** [comment]
interesting, in that case the php api would have to implement its own special request data parser as php built-in request parser only accepts "tags[]" as array

**Comment by Doqnach** [comment]
No one is telling you that you should not use the `myVariableHere[]` notation for your own API. If your API is built in PHP it makes sense to use that notation instead.

**Comment by rodrigowbazevedo** [comment]
If you use `style="deepObject"` it'll send array data in the PHP way.

**Comment by bfanger** [comment]
The `-spec` examples try to generate yaml output that matches the spec: https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v3.0 using swagger-php annotations.

The https://petstore.swagger.io backend is an [Eclipse Jetty](https://www.eclipse.org/jetty/) (Java) server.
Thats the reason the `tags` don't use the php specific `tags[]` notation.

I've added a small section to the Getting started guide.
