### ISSUE TITLE
Multiple @OA\Response() with the same response="200"

### ISSUE THREAD

**Issue by DorelBesliu** [zircote/swagger-php#810]
That issue occurs only on server side. 
`local.ERROR: ErrorException: Multiple @OA\Response() with the same response="200":
  \App\Http\Controllers\Student\EventsController->update() in /var/www/html/app/Http/Controllers/Student/EventsController.php on line 136
  \App\Http\Controllers\Student\EventsController->store() in /var/www/html/app/Http/Controllers/Student/EventsController.php on line 51 in /var/www/html/vendor/zircote/swagger-php/src/Logger.php:39`
I tried api-docs generated on local in https://editor.swagger.io and that works very well. How that can be resolved?

**Comment by Doqnach** [comment]
Instead have one `response="200"` and use `oneOf` to provide information about the different possible payloads.

Can you provide an example that does work in SwaggerUI? Because neither JSON nor YAML allow for duplicate keys in an object/mapping.

**Comment by DorelBesliu** [comment]
Why does it work on local environment and don't on server side ? 
openapi: 3.0.0
info:
  title: App API
  version: 1.0.0
servers:
  - url: 'http://app-api.local/api'
    description: Development Server
paths:
  /student/events:
    post:
      tags:
        - Student
      summary: Create event
      operationId: 'App\Http\Controllers\Student\EventsController::store'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                teacher_id:
                  description: Teacher id
                  type: integer
                start:
                  description: Start event time
                  type: string
                  format: date
                lesson_duration:
                  description: Lesson duration in minutes
                  type: integer
                  format: date
                lessons_amount:
                  description: Amount of lessons
                  type: integer
                  format: date
                type:
                  description: Store a newly created resource in storage.
                  type: string
                  enum:
                    - EVENT_TYPE_OFFTIME
              type: object
      responses:
        '200':
          description: Event created succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResource'
        '401':
          description: Unauthorized
        '500':
          description: Sever error
      security:
        - auth:
            - '*'
  '/student/events/{event}':
    put:
      tags:
        - Student
      summary: Get event information
      operationId: 'App\Http\Controllers\Student\EventsController::update'
      parameters:
        - name: event
          in: path
          description: Event id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              properties:
                teacher_id:
                  description: Teacher id
                  type: integer
                start:
                  description: Start event time
                  type: string
                  format: date
                lesson_duration:
                  description: Lesson duration in minutes
                  type: integer
                  format: date
                lessons_amount:
                  description: Amount of lessons
                  type: integer
                  format: date
                type:
                  description: Update the specified resource in storage.
                  type: string
                  enum:
                    - EVENT_TYPE_OFFTIME
              type: object
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResource'
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Sever error
      security:
        - auth:
            - '*'
components:
  schemas:
    EventResource:
      title: Event
      properties:
        id:
          description: Event id
          type: integer
          format: int64
        teacherId:
          description: Teacher id
          type: integer
          format: int64
        studentId:
          description: Student id
          type: integer
          format: int64
        eventTipropertytle:
          description: Event title
          type: string
        eventText:
          description: Event notices
          type: string
        start:
          description: Event start
          type: string
          format: date
        lessonDuration:
          description: Lesson duration
          type: integer
          format: int32
        lessonsAmount:
          description: Lesson amount
          type: integer
          format: int32
        eventType:
          description: Event type
          type: string
      type: object
      xml:
        name: Event
  securitySchemes:
    auth:
      type: oauth2
      flows:
        password:
          tokenUrl: 'http://student-app-api.local/api/login'
          scopes: {}
tags:
  - name: Student
    description: ''

**Comment by DerManoMann** [comment]
I know its a basic question, but are PHP and library versions the same for local and server?
Also I'd be curious if the local setup generates YAML with multiple 200 response entities for the endpoint or just one?

**Comment by Doqnach** [comment]
I think that the problem might be that you try to declare the `@OA\Response` outside of a `@OA\Path` context, and then it tries to add both at the same place but can't because of the collision of having the same response code.

Please provide a full example of your PHPDOC, because I think that is where your problem lies.

See https://github.com/zircote/swagger-php/blob/master/Examples/petstore-3.0/controllers/Pet.php#L66 as an example on how to declare a path and response in PHPDOC.

**Comment by DorelBesliu** [comment]
I think I know there is the problem. Firstly, I had this problem https://github.com/DarkaOnLine/L5-Swagger/issues/191 and I resolved it by put in the start of documentation:
`
@OA\Get(
 *     path="/",
 *     description="Home page",
 *     @OA\Response(response="default", description="Welcome page")
 * )
`
And I think that generates the problem with two 200 responses. Why I have to put @OA\PathItem() as a starting point - if I don't need it ?

**Comment by Doqnach** [comment]
It feels like you maybe do not entirely grasp how OpenAPI and by extension the PHPDOC for SwaggerPHP work.

Maybe it would be good to read up on the documentation at https://zircote.github.io/swagger-php/Getting-started.html and to have a look at the many examples at https://github.com/zircote/swagger-php/tree/master/Examples/petstore-3.0 to give you a basis on how to properly document the code.

Usually you start with a `@OA\Info()` block in some common entrypoint code (bootstrap, index, kernel, etc...), have a `@OA\Get/Post/Put/Patch/etc...` at each 'controller', and a `@OA\Schema()` at each 'model'.

**Comment by DorelBesliu** [comment]
@OA\PathItem() - From https://swagger.io/specification/ - A relative path to an individual endpoint. The field name MUST begin with a forward slash (/). 
`
[2020-07-09 09:08:17] local.ERROR: Required @OA\PathItem() not found {"exception":"[object] (ErrorException(code: 0): Required @OA\\PathItem() not found at /var/www/html/vendor/zircote/swagger-php/src/Logger.php:39)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(1024, 'Required @OA\\\\Pa...', '/var/www/html/v...', 39, Array)
#1 /var/www/html/vendor/zircote/swagger-php/src/Logger.php(39): trigger_error('Required @OA\\\\Pa...', 1024)
#2 [internal function]: OpenApi\\Logger->OpenApi\\{closure}('Required @OA\\\\Pa...', 1024)
#3 /var/www/html/vendor/zircote/swagger-php/src/Logger.php(71): call_user_func(Object(Closure), 'Required @OA\\\\Pa...', 1024)
#4 /var/www/html/vendor/zircote/swagger-php/src/Annotations/AbstractAnnotation.php(427): OpenApi\\Logger::notice('Required @OA\\\\Pa...')
#5 /var/www/html/vendor/zircote/swagger-php/src/Annotations/OpenApi.php(135): OpenApi\\Annotations\\AbstractAnnotation->validate(Array, Array, '#')
#6 /var/www/html/vendor/zircote/swagger-php/src/Analysis.php(422): OpenApi\\Annotations\\OpenApi->validate()
#7 /var/www/html/vendor/zircote/swagger-php/src/functions.php(48): OpenApi\\Analysis->validate()
#8 /var/www/html/vendor/darkaonline/l5-swagger/src/Generator.php(119): OpenApi\\scan(Array, Array)
#9 /var/www/html/vendor/darkaonline/l5-swagger/src/Generator.php(66): L5Swagger\\Generator->scanFilesForDocumentation()
#10 /var/www/html/vendor/darkaonline/l5-swagger/src/Console/GenerateDocsCommand.php(32): L5Swagger\\Generator::generateDocs()
#11 [internal function]: L5Swagger\\Console\\GenerateDocsCommand->handle()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#18 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#20 /var/www/html/vendor/symfony/console/Application.php(1001): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/html/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand(Object(L5Swagger\\Console\\GenerateDocsCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /var/www/html/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 {main}
"} 
`
What does it mean - I forgot to put somewhere or I need to put it in a base controller as the main path?

**Comment by Doqnach** [comment]
Have you tried using `@OA\Get/Put/Post/Patch` instead? Normally you would start with an operation, not a path item object.

Is it possible to give maybe a more clear example of your code? Best would be a self contained codebase that shows the problem we can actually execute. Because the error messages you give unfortunately give very little to hunt down the actual source of your problem with.

**Comment by sublime392** [comment]
I don't know if this pertains to the op's problem, but I had the same sort of error in production vs local dev, and in case someone else ends up here like I did, here was my mistake. I inadvertently had some of the `@OA\Get/Put/Post` items as `@OA\GET/PUT/POST`. Presumably this worked on my case-insensitive MacBook, but not on the Linux production server.

**Comment by DorelBesliu** [comment]
[](url)

**Comment by DorelBesliu** [comment]
> I don't know if this pertains to the op's problem, but I had the same sort of error in production vs local dev, and in case someone else ends up here like I did, here was my mistake. I inadvertently had some of the `@OA\Get/Put/Post` items as `@OA\GET/PUT/POST`. Presumably this worked on my case-insensitive MacBook, but not on the Linux production server.

@sublime392 Thank you. The same issue was on my side

**Comment by fredEbho** [comment]
> I don't know if this pertains to the op's problem, but I had the same sort of error in production vs local dev, and in case someone else ends up here like I did, here was my mistake. I inadvertently had some of the `@OA\Get/Put/Post` items as `@OA\GET/PUT/POST`. Presumably this worked on my case-insensitive MacBook, but not on the Linux production server.

Please what did you say we should do? I'm having the same issue

**Comment by fredEbho** [comment]
> I don't know if this pertains to the op's problem, but I had the same sort of error in production vs local dev, and in case someone else ends up here like I did, here was my mistake. I inadvertently had some of the `@OA\Get/Put/Post` items as `@OA\GET/PUT/POST`. Presumably, this worked on my case-insensitive MacBook, but not on the Linux production server.

The casing of @OA\Get, @OA\Post, @OA\Put etc. is really important, don't mistake it for their capitalized counterparts e.g @OA\GET, @OA\POST, @OA\PUT etc.

**Comment by haohetao** [comment]
I have same problem.
The @OA annotation is case sensitivity,linux also case sensitivity,but windows case insensitivity,so must ensure capitalized is right.

**Comment by Doqnach** [comment]
This is not so much a Swagger-PHP thing but a PHP/composer autoload thing. Class names are case sensitive because it tries to load the file with the same name and thus casing on case-sensitive OS (read: filesystems). These (doctrine) annotations are in the end just classes that are loaded so casing matters.

**Comment by MdkanokHossain** [comment]
@DorelBesliu
Did you find solution yet, cause i am having same problem

**Comment by norellanac** [comment]
/**
 * @OA\Info(title="My First API", version="0.1")
 * @OA\Get(
 *     path="/",
 *     @OA\Response(response="200", description="Display a listing of projects.")
 * )
 */
