### ISSUE TITLE
Error generating JSON for optional security

### ISSUE THREAD

**Issue by hpatoio** [zircote/swagger-php#811]
I've an endpoint that has optional security. So I need to generate a JSON like

```
     *     security={
     *          { },
     *          {"api-key": []},
     *     },
```

I put this annotation in my code 

```
     *     security={
     *          { },
     *          {"api-key": {}},
     *     },
```

but this JSON is generated

```
     *     security={
     *          [ ],
     *          {"api-key": [ ] },
     *     },
```

instead of 

```
     *     security={
     *          { },
     *          {"api-key": [ ] },
     *     },
```

This is because PHP json-serialize this structure

```
    ["security"]=>
    array(2) {
      [0]=> array(0) {}
      [1]=> array(1) {
        ["api-key"]=> array(0) {}
      }
    }
```

Any hint about where to start to fix it ?

**Comment by Doqnach** [comment]
I believe this needs to be fixed in swagger-php code. There have been a few more places before where empty objects were wrongly converted to arrays that needed to have exceptions made for them. This sounds like the case here too.

**Comment by hpatoio** [comment]
I found this comment https://github.com/zircote/swagger-php/issues/614#issuecomment-624927355 in #614 

So I changed my definition to 

```
     *     security={
     *          @OA\Schema(),
     *          {"api-key": []},
     *     },
```

and the result is correct.

Not closing this issue because I think this is not a real solution.

**Comment by DerManoMann** [comment]
@hpatoio Would you be able to test the PR I created to fix your issue and let me know if that works as expected?

**Comment by hpatoio** [comment]
@DerManoMann I'll do it later today. I was on vacationt.

**Comment by hpatoio** [comment]
When I use your branch (on the very same codebase) I get many more notice like 

`Notice: Unexpected @OA\JsonContent() in @OA\JsonContent() ... `
`Notice: $ref "#/components/schemas/ResponseDTO" not found for @OA\Schema() ...`

Dunno why. I'll go deeper.

**Comment by Doqnach** [comment]
Please also provide (if possible) a minimal working example that gives these notices, so others can try to reproduce.

**Comment by DerManoMann** [comment]
Yes, please. THere have been a few other changes which means this could be a regression... :/

**Comment by hpatoio** [comment]
I fixed all annotations in the the project and now I do not have any error when I generate the OpenAPI using `master`. When I switch to you branch I get lot of errors like

```
Notice: $ref "#/components/schemas/ResponseDTO" not found for @OA\Schema()
```

`ResponseDTO` is an empty interface

```
interface ResponseDTO
{
}
```

and I've lot of models that implement it.

**Comment by hpatoio** [comment]
If I add

```
/**
 * @OA\Schema(
 *     schema="ResponseDTO",
 *     type="object",
 *     @OA\Property(
 *        property="foo",
 *        type="string"
 *     )
 * )
 */
```

in `ResponseDTO` errors disappear.

**Comment by DerManoMann** [comment]
Oops. I rebased the branch on master so that should be fixed. If not I'd really appreciate if you could put together a small repo with the code breaking for me to have a look.

**Comment by hpatoio** [comment]
It worked ! Thanks ! When you plan to merge and release your branch ? Just need to know when I can update my `composer.json`

**Comment by DerManoMann** [comment]
Not up to me. @zircote needs to do that or @bfanger 
Ideally I'd like to wait until the other potential regressions are sorted

**Comment by DerManoMann** [comment]
@hpatoio This is now merged to master, but since packagist is not auto-updating you might need to pull a specific hash rather than dev-master or wait until @zircote or @bfanger update and create a new release.

Again, a good first step would be to [configure/enable auto updating of packagist](https://packagist.org/about#how-to-update-packages)...

**Comment by hpatoio** [comment]
@zircote and @bfanger any news about create a new release and update packagist ?
