### ISSUE TITLE
How can send base64 format in swagger-php RequestBody

### ISSUE THREAD

**Issue by jeff-cmyk** [zircote/swagger-php#817]
I want to upload base64 format in requestbody json array. How can send base64 format in an array you can see my code below.

```
/**
* @OA\Post(
*      path="/products/save",
*      tags={"Product"},
*      summary="Post bulk products",
*      description="Return bulk products",
*      @OA\RequestBody(
*       required=true,
*       description="Bulk products Body",
*       @OA\JsonContent(
*           @OA\Property(
*               property="products",
*               @OA\Items(
*                  @OA\Property(property="first_name", type="string"),
*                  @OA\Property(property="last_name", type="string"),
*                  @OA\Property(property="email", type="string"),
*                  @OA\Property(property="phone", type="string"),
*                  @OA\Property(property="resume", type="string", format="byte")
*               ),
*           )
*       )
*     ),
* )
*/
```

**Comment by Doqnach** [comment]
@jeff-cmyk what you are showing is not actual functioning "code". This is only documentation that SwaggerPHP will parse to generate a spec. It does not do any execution of any form, unless you have some other library that provides that functionality.

See also #805

**Comment by bfanger** [comment]
`type="string", format="byte"` is the [correct way](https://swagger.io/docs/specification/data-models/data-types/#string) to document that the property `resume` should be formatted as "base64-encoded character"
I see you didn't provide the `type="array"` hint for the products property (but swagger-ui detect that). 

Subjective, but if i'd design the api I would remove the unnecessary products property and specify the `@OA\Items` directly inside the `@OA\JsonContent`
