### ISSUE TITLE
Inherit annotations from other folder/file

### ISSUE THREAD

**Issue by pe1uca** [zircote/swagger-php#821]
I have a code base that has separate APIs.
e.g.
code/api1
code/api2

In this, api2 is a superset of api1, so api1 is inherited and api2 just adds/or changes some methods.

Is there a way to include the annotation from api1 when calling `OpenApi\scan()` on api2?
This should overwrite api1 with api2.

Let's say I have in api1
```
/**
 * @OA\Info(title="api1", version="1.0")
 */

/**
 * @OA\Get(
 *     path="/test",
 *     @OA\Response(response="200", description="A test endpoint")
 * )
 */
```
And in api2
```
/**
 * @OA\Info(title="api2", version="2.0")
 */

/**
 * @OA\Get(
 *     path="/test2",
 *     @OA\Response(response="200", description="A 2nd test endpoint")
 * )
 */
```

So the call to generate openapi on api1 should be normal (title=api1, paths=/test).
And the call for api2 should have title=api2, paths=/test and /test2

**Comment by DerManoMann** [comment]
I might be missing something but you can scan multiple directories. Either on the command line or by passing an array into the scan call.

**Comment by pe1uca** [comment]
Yes, I was not aware that declaring again the annotation does not overwrite them.
I was sending ['api1','api2'] and this resulted just the merge of endpoints and from api1.
Sending ['api2','api1'] properly displays the info from api2 and merging the endpoints.

**Comment by Doqnach** [comment]
I believe (but @DerManoMann correct me if I'm wrong) but the scanner does not override definitions. If it encounters a duplicate I think it will skip it. So scanning first `api2` should give you the result you are looking for.
