### ISSUE TITLE
Unexpected @OA\JsonContent() must be nested

### ISSUE THREAD

**Issue by karlos1338** [zircote/swagger-php#823]
Hi,

i just upgraded from 3.0.3 to version 3.0.4.

When creating the yaml with the following command
php /var/www/controlpanel/vendor/bin/openapi --output openapi.yaml /var/www/controlpanel/src/Con
troller/ServicesController.php  /var/www/controlpanel/src/Schema/
I receive the following warning:
Unexpected @OA\JsonContent() must be nested

Controller
```
/**
     * List weather information
     * @Rest\Route("/api/services/weather", methods={"GET"}, name="api_services_weather"),
     *
     * @Get(path="/api/services/weather", tags={"Services"},
     *
     *     @Response(response="200", description="Returned when request successful",
     *          @JsonContent(ref="#/components/schemas/WeatherList")
     *     ),
     * )
     */
```

Schema
```
/**
 * @Schema(
 *     schema="WeatherList",
 *     description="List of WeatherElements",
 *     type="array",
 *     items=@JsonContent(ref="#/components/schemas/WeatherElement"),
 * ),
 *
 * @Schema(
 *     schema="WeatherElement",
 *     type="object",
 *     @Property(property="weekday", type="string", example="Donnerstag"),
 *     @Property(property="state", type="string", example="bedeckt"),
 *     @Property(property="low_temp", type="number", example="1"),
 *     @Property(property="high_temp", type="number", example="1"),
 *     @Property(property="icon", type="string", example="bedeckt.png"),
 * ),
```

Any idea?

**Comment by DerManoMann** [comment]
This is a regression I think. I've tried your example with the current master and that seems to be happy with the annotations.
Could you try to use that instead?

One note about your dockblocks: If you use the prefix `@OA\` there is no need to import each annotation class which makes things a bit easier to read. If you want to you can still import annotations with a single line.
Something like:

```
<?php

use OpenApi\Annotations as OA;

/**
 * @OA\Get(...)
 */
```

**Comment by karlos1338** [comment]
Hi,
i just updated to master.
Still have the same error. 3.0.3 works fine. 3.0.4. or master not :(

**Comment by DerManoMann** [comment]
Strange. 
All I can say is that the annotations you pasted do work for me :/ It would be great if you could create a small repo with just the bare minimum of code to show it breaking so I can have a play...

**Comment by DerManoMann** [comment]
Could you check that you are really using the actual master? See #772 for details why packagist might not be up to date...

**Comment by bfanger** [comment]
Issue is with `items=@JsonContent`

Change the line:  
`items=@JsonContent(ref="#/components/schemas/WeatherElement"),`
to
`@OA\Items(ref="#/components/schemas/WeatherElement")`

`@OA\JsonContent` should only be used inside `@OA\Response` or `@OA\RequestBody`  (without an prop=)
