### ISSUE TITLE
Swagger UI does not display a header

### ISSUE THREAD

**Issue by milutinke** [zircote/swagger-php#824]
`
...
     *@OA\Header(
     *          header="Authorization",
     *          description="Bearer JWT Token",
     *          @OA\Schema( type="string" )
     *      ),
...
`

It does not get displayed on the documentation page.

**Comment by DerManoMann** [comment]
request header are defined using `@OA\Parameter`

```
 *   @OA\Parameter(
 *     name="Authorization",
 *     in="header",
 *     description="Bearer JWT Token",
 *     @OA\Schema(type="string")
 *   ),

```

**Comment by DerManoMann** [comment]
Just realized this is about authentication - have you looked at the security definitions and annotations, for example https://github.com/zircote/swagger-php/blob/master/Examples/petstore-3.0/security.php#L21 or similar?
Saves a lot of typing and is well supported by  the UI

**Comment by milutinke** [comment]
I did not know about that.
Thank you very much.

**Comment by yupeng2015** [comment]
> Just realized this is about authentication - have you looked at the security definitions and annotations, for example https://github.com/zircote/swagger-php/blob/master/Examples/petstore-3.0/security.php#L21 or similar?
> Saves a lot of typing and is well supported by the UI

I tried, and it still doesn't work

**Comment by yupeng2015** [comment]
> request header are defined using `@OA\Parameter`
> 
> ```
>  *   @OA\Parameter(
>  *     name="Authorization",
>  *     in="header",
>  *     description="Bearer JWT Token",
>  *     @OA\Schema(type="string")
>  *   ),
> ```

I tried, and it still doesn't work

**Comment by yupeng2015** [comment]
> @yupeng2015 please check the link that @DerManoMann gave about security definitions. That is what you are supposed to use for this, for Swagger-UI to show the authorization dialog.

`    /**
     * @OA\Post(
     *     tags={"staff"},
     *     path="/user/staff/retrieve",
     *     summary="summary",
     *     @OA\Parameter(name="Authorization",in="header",required=true,@OA\Schema(type="string"),description="Authorization",example="Berear <token>"),
     *     @OA\Parameter(name="mobile",in="query",required=true,@OA\Schema(type="string"),description="description",example="11111111111"),
     *     @OA\Response(
     *     response=200,
     *     description="ok",
     * )
     * )
     */`

I do write the rule like this. There is a header parameter input box on the swagger UI page, but there are no parameters in the header when the request is actually executed.
