### ISSUE TITLE
Array example

### ISSUE THREAD

**Issue by hotrush** [zircote/swagger-php#828]
Hi

```
@OA\Property(
    property="locations",
    type="array",
    example=["Germany", "France"],
    @OA\Items(
        type="string"
    )
)
```

Hi, this code sample returns an error when swagger docs say that it should be possible https://swagger.io/docs/specification/adding-examples/

Is there any way to provide an array as example for array data type?

**Comment by Doqnach** [comment]
the `[]` notation is wrong, it should use `{}` in PHPDOC.

**Comment by hotrush** [comment]
Works, thanks

**Comment by hpatoio** [comment]
How do you handle example with multiple values ?

**Comment by hotrush** [comment]
That works to me

```
@OA\Property(
    property="locations",
    type="array",
    example={"Germany", "France"},
    @OA\Items(
        type="string"
    )
)
```

**Comment by hpatoio** [comment]
ok ... and what about more example with multiple values :D #inception

**Comment by Doqnach** [comment]
In OpenAPI 3 you have `example` which is a totally freeform key you can put anything into, but you also have `examples` which has a slightly more strict format (for parameters for instance).

http://spec.openapis.org/oas/v3.0.3#fixed-fields-9
