### ISSUE TITLE
The formData in type not accepted

### ISSUE THREAD

**Issue by roland-d** [zircote/swagger-php#829]
Hello,

I am stumped as to how to specify parameters to be send as form data. 

This is the error I get:

```
User Notice: @OA\Parameter(name="filter[kvkNumber]",in="formData")->in "formData" is invalid, expecting "query", "header", "path", "cookie"
```

This is my annotation:
```
 /**
     * @Route("/api/infoKvk", name="infoKvk", methods={"Post"})
     *
     * @Security(name="ApiKeyAuth")
     *
     * @OA\Parameter (
     *     in="formData",
     *     name="filter[kvkNumber]",
     * )
     * @OA\Parameter (
     *     in="path",
     *     name="filter[postcode]",
     * )
     *
     * @OA\Response(response=200,
     *   description="KvK details"
     * )
     * @OA\Response(response=401,
     *   description="This error is thrown if no authorization token is provided"
     * )
     *
     * @OA\Tag(name="Api")
```

From all the documentation, examples and other issues I figured this should work but it does not and that is why I am here :) 

I am using:
- Symfony 4.18.4
- NelmioApiDocBundle `master`
- Zircote  3.0.4

Any help is appreciated.

**Comment by Doqnach** [comment]
http://spec.openapis.org/oas/v3.0.3#parameter-object

In OpenAPI 3+ a parameter can indeed only be in "query", "header", "path" or "cookie".

`formData` should be defined by a `requestBody`: http://spec.openapis.org/oas/v3.0.3#special-considerations-for-multipart-content

**Comment by roland-d** [comment]
Thank you very very much.
