### ISSUE TITLE
How to use brackets in @SWG\Examples?

### ISSUE THREAD

**Issue by mvnp** [zircote/swagger-php#831]
I need to load data into **information: [{ }, { }, { }, { } ...]** on this format but all time I try this, I have a bug. How to show example with an array of objects?

**Comment by Doqnach** [comment]
Please provide a more complete example because your question does not make much sense to me I'm afraid.

**Comment by moxival** [comment]
@mvnp Take a look here: http://zircote.github.io/swagger-php/Getting-started.html#arrays-and-objects

You do not use brackets but curly brackets, e.g. `{{},{},{}}` this is the same (and it will be interpreted) as `[{},{},{}]`
