### ISSUE TITLE
[Help Needed] Keycloak integration

### ISSUE THREAD

**Issue by mostafamaklad** [zircote/swagger-php#833]
I am trying to authenticate using keycloak using OpenID but it fails with me always I tried to check the swagger documentation here [https://swagger.io/docs/specification/authentication/openid-connect-discovery/](https://swagger.io/docs/specification/authentication/openid-connect-discovery/ ) but there is something missing
``` php
/*
 * @OA\SecurityScheme(
 *      securityScheme="openId",
 *      name="openId",
 *      type="openIdConnect",
 *      openIdConnectUrl="https://KEYCLOAK.LOCAL/auth/realms/MyRELM/.well-known/openid-configuration"
 * ),
 */
```

**Comment by Doqnach** [comment]
Is your problem that the OpenAPI spec is not generated correctly? That can be a bug in Swagger-PHP. Swagger-PHP does nothing more than generating an OpenAPI specification in yaml or JSON based on the PHPDOC provided in the code. It does not provide any executable code, or any code that sends or receives any requests.

Or is your problem that the API server is not accepting the authentication you are doing from whatever client you are using? Then the question is not for this github repo, but rather for whatever client (Swagger-UI maybe?) or server you are using.
All I can advise is to hand-write a correct specification and to try that out with your client & server of choice to see if that works. If you find a working version, then implement that as PHPDOC to have Swagger-PHP generate a valid specification for you.

**Comment by mostafamaklad** [comment]
Thanks for your reply it wasn't supported in swagger-ui

**Comment by mostafamaklad** [comment]
Thanks for your support I am trying to follow it
