### ISSUE TITLE
3.0.5 breaks PHPStan

### ISSUE THREAD

**Issue by swiffer** [zircote/swagger-php#834]
After upgrading to 3.0.5 I'm experiencing a lot of errors when running PHPStan

 ------ --------------------------------------------------------------------
         Reflection error: ake\Http\BaseApplication not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ --------------------------------------------------------------------

 ------ ------------------------------------------------------------
  Line   Command\ConsoleCommand.php
 ------ ------------------------------------------------------------
  17     Syntax error, unexpected T_NAME_FULLY_QUALIFIED on line 17
 ------ ------------------------------------------------------------

**Comment by weirdan** [comment]
Also breaks `vimeo/psalm` and other packages using `nikic/php-parser`, on PHP 7.4. Have traced the problem to these lines:
https://github.com/zircote/swagger-php/blob/7f4b9e09c9e96a4c7dd57b0a4ddd5b45f1e261e1/src/functions.php#L21-L27

/cc @Arslanoov
Refs vimeo/psalm#4086

**Comment by DerManoMann** [comment]
Could I get some details about PHPStan version and the level you are using?
Just running `phpstan analyse src` does not report any errors for me on master.

**Comment by swiffer** [comment]
I'm using the latest PHPStan in a Cake PHP project that has swagger-php installed as well.

I think it's not an issue when running against this project but within a project that has swagger-php as a dependency.

**Comment by DerManoMann** [comment]
Hmmm. Tricky; I guess without reproduction steps this will be hard to change.

**Comment by weirdan** [comment]
# Repro repo
https://github.com/weirdan/parser-fail
# Steps to reproduce
```console
$ git clone git@github.com:weirdan/parser-fail.git
Cloning into 'parser-fail'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
Receiving objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 6 (delta 0), pack-reused 0

$ cd parser-fail

$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 8 installs, 0 updates, 0 removals
  - Installing doctrine/lexer (1.2.1): Loading from cache
  - Installing nikic/php-parser (v4.9.1): Loading from cache
  - Installing symfony/deprecation-contracts (v2.1.3): Loading from cache
  - Installing symfony/polyfill-ctype (v1.18.1): Loading from cache
  - Installing symfony/yaml (v5.1.3): Loading from cache
  - Installing symfony/finder (v5.1.3): Loading from cache
  - Installing doctrine/annotations (1.10.4): Loading from cache
  - Installing zircote/swagger-php (3.0.5): Loading from cache
symfony/yaml suggests installing symfony/console (For validating YAML files using the lint command)
Generating autoload files
5 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

$ vendor/bin/php-parse test.php
====> File test.php:
Syntax error, unexpected T_NAME_FULLY_QUALIFIED on line 2
```
# Expected
```console
$ vendor/bin/php-parse test.php
====> File test.php:
==> Node dump:
array(
    0: Stmt_Namespace(
        name: Name(
            parts: array(
                0: Weirdan
                1: ParserFail
            )
        )
        stmts: array(
        )
    )
)
```
# Actual
```console
$ vendor/bin/php-parse test.php
====> File test.php:
Syntax error, unexpected T_NAME_FULLY_QUALIFIED on line 2
```

**Comment by DerManoMann** [comment]
Funny, for some reason it doesn't like them both having the same value.

I can create a fix, but unfortunately I have no permission to update pacagist or create a release :/

**Comment by swiffer** [comment]
🤔 still happening for me on dev-master

**Comment by weirdan** [comment]
You must be getting an old revision of dev-master, as the [package on Packagist](https://packagist.org/packages/zircote/swagger-php) is not autoupdated:
![image](https://user-images.githubusercontent.com/57403/92020713-3da42680-ed61-11ea-8713-d06c548e01ba.png)

**Comment by weirdan** [comment]
@swiffer doing `pushd vendor/zircote/swagger-php; git pull --ff-only; popd` should allow you to fix it locally so that you can verify the fix.

**Comment by swiffer** [comment]
yes, now works fine - thanks!
