### ISSUE TITLE
How to combine swagger-php with existing JSON

### ISSUE THREAD

**Issue by Ooypunk** [zircote/swagger-php#836]
Hello,

My question in short: I have an existing OpenApi JSON/array, and a number of "@OA" DocBlocks, how can I combine those into one? Is this possible?

The existing JSON is generated from a pre-defined array, a database table, and a number of model definitions (components/schemas, in OpenApi language).

Now, I could move the (contents of the) DocBlocks to somewhere else (the pre-defined array, for instance), but then I would have that information in two places. Something that I tried to avoid using  the swagger-php DocBlocks.

I tried using \OpenApi\scan(), but the first hurdle was that the “info” part is mandatory (which is in the pre-defined array); after having copied that into a "@OA" DocBlock I ran into the second one: the schemas are missing (as said, these are generated). I tried to find a solution in the documentation, but I found nothing. Can someone help me, point me in the right direction, maybe?

**Comment by DerManoMann** [comment]
If you look at the scan method you'll see a call `$analysis->validate();` near the end. That is what triggers those errors.
You could just copy the relevant bits out of that method and leave out the validation step.

That would give you the pure JSON for what has been processed. That output could then be merged with the existing JSON.

**Comment by Ooypunk** [comment]
Works like a charm. Thanks!
