### ISSUE TITLE
overwriting referenced parameters is no longer possible in 3.0.5+

### ISSUE THREAD

**Issue by swiffer** [zircote/swagger-php#838]
when defining a parameter

```php
    /**
     * @OA\Parameter(parameter="impersonate", name="impersonate", in="query", required=false, @OA\Schema(type="integer"))
     */
```

and overwriting required for a specific action via

```php
    /**
     *     @OA\Parameter(ref="#/components/parameters/impersonate", required=true),
     */
```

this renders to this in 3.0.4, in 3.0.5 the required: true flag is missing.

![grafik](https://user-images.githubusercontent.com/2990373/91983082-775a3a80-ed2b-11ea-8408-2c5a3c7d7687.png)

**Comment by DerManoMann** [comment]
I am not sure I fully understand your example. Would you be able to expand this a bit so we can see the relationships a bit more?
I suspect this is in the context of inheritance of some sort?

**Comment by bfanger** [comment]
That worked in 3.0.4? 
Could you provide the generated output (old and new)

**Comment by swiffer** [comment]
@bfanger / @DerManoMann - i've modified the description. it's inheritance

**Comment by swiffer** [comment]
ok, interesting. while it worked in swagger-php it does not seem to be support in openapi. at least swagger ui is not flagging the parameter as required if specified via ref.

https://swagger.io/docs/specification/using-ref/

"Any sibling elements of a $ref are ignored. This is because $ref works by replacing itself and everything on its level with the definition it is pointing at."
