### ISSUE TITLE
Having properties inside items in a schema does not render properly in Swagger UI

### ISSUE THREAD

**Issue by achristodoulou** [zircote/swagger-php#846]
Hi, I have a schema that has several properties which can be seen below and one of them is called `data` its type is an object. I tried to add all object properties inside @OA\Items and generate the spec in json. Then I check it inside swagger web UI and `data` property was not render properly and was showing an empty object. Then I took the properties outside of @OA\Items and it worked. By the way I uploaded my spec in swaggerhub editor and it did not show any error messages, also in swaggerhub UI property `data` was empty. Is the first attempt using @OA\Items a valid structure, if not shouldn't swagger cmd that generates the spec `php vendor/bin/openapi `  give me an error instead.

Before:
```
@OA\Schema(
    schema="MySchema",
    @OA\Property(property="status", type="integer"),
    @OA\Property(
        property="data",
        type="object",
        @OA\Items(
            @OA\Property(property="message", type="string"),
            @OA\Property(property="valid", type="boolean")
	   )
	)
)


Example Value
Schema
{
  "status": 0,
  "data": {}
}
````

After:
```
@OA\Schema(
    schema="MySchema",
    @OA\Property(property="status", type="integer"),
    @OA\Property(
        property="data",
        type="object",
            @OA\Property(property="message", type="string"),
            @OA\Property(property="valid", type="boolean")
     )
)


Example Value
Schema
{
  "status": 0,
  "data": {
    "message": "string",
    "valid": true
    }
  }
}
```

**Comment by Doqnach** [comment]
`@OA\Items` is for arrays, not for objects. So the result would become:
```
{
  "status": 0,
  "data": []
}
{
  "status": 0,
  "data": [
    {
      "message": "",
      "valid": true
    }
  ]
}
```

**Comment by achristodoulou** [comment]
Thanks for your prompt response and clarifying this. I suggest to add a check when generating the spec to check if Items is used inside a property of type not equal to array to throw a meaningful error, that would really be helpful for developers to understand openapi spec even better.
