### ISSUE TITLE
Interface schema can be null

### ISSUE THREAD

**Issue by chq81** [zircote/swagger-php#847]
With the fix for #842, the following code was introduced.
This breaks if the interfaceSchema is null.

https://github.com/zircote/swagger-php/blob/9d9f038a97d02f043abbacaa6248088a4803d0e3/src/Processors/InheritInterfaces.php#L23-L25

In the InheritTraits class this was correctly implemented, see
https://github.com/zircote/swagger-php/blob/9d9f038a97d02f043abbacaa6248088a4803d0e3/src/Processors/InheritTraits.php#L25-L27

**Comment by DerManoMann** [comment]
Having thought some more about this I think both are actually wrong.

The interface related code tried to avoid the case where it would do inheritance without a schema and therefore generate a $ref that doesn't exist.

The correct thing IMO is to merge the inherit/merge processors:
* inherit if the schema is not null
* merge if the schema is null and there are annotations

**Comment by chq81** [comment]
@DerManoMann What about the case that an interface does not have a schema at all? Is that the second case you mentioned? By annotations, you mean OA annotations?
Still, to fix the problem at hand temporarily, would it make sense to create a PR with just that one change?

**Comment by DerManoMann** [comment]
I'd rather fix it properly first time around. Not sure when the next release will be cut so it might be easier for you to stick with the last working release for now.

**Comment by DerManoMann** [comment]
@chq81 Would you be able to try this PR #850 and give some feedback?
