### ISSUE TITLE
Upgrade from 3.0.4 to 3.1.0: Lost nullable & readOnly on ref

### ISSUE THREAD

**Issue by marc-mabe** [zircote/swagger-php#848]
Lost nullable on 
```php
    /**
     * @OA\Property(ref="#/components/schemas/GeoRegion/properties/id", nullable=true)
     *
     * @var null|int
     */
    private $regionId;
```

Lost readOnly on:
```php
    /**
     * @OA\Property(ref="#/components/schemas/GeoRegion/properties/id", readOnly=true)
     *
     * @var null|int
     */
    private $regionId;
```

**Comment by Doqnach** [comment]
Please see #838. Any support for parameters with `ref=""` was wrong. So the behaviour in 3.1.0 is actually correct.

>$ref and Sibling Elements
>
> Any sibling elements of a $ref are ignored. This is because $ref works by replacing itself and everything on its level with the definition it is pointing at.

**Comment by DerManoMann** [comment]
Yes, sorry. This was changed in PR #822, and strictlty speaking is a breaking change - still finding our feet doing semver...
