### ISSUE TITLE
Support for HAL (Hypermedia Application Language)

### ISSUE THREAD

**Issue by pietervogelaar** [zircote/swagger-php#85]
At the moment I'm building a REST API in Zend Framework 2 with the [PhlyRestfully module](https://github.com/weierophinney/PhlyRestfully).

The response is in JSON+HAL. For example a list of resources is enclosed in the "_embedded" key.

http://phlyrestfully.readthedocs.org/en/latest/halprimer.html

**Comment by Jmeyering** [comment]
:+1:

**Comment by nnnnathann** [comment]
+1

I am also struggling to figure out how to support JSON-API schema as well, seems support for arbitrarily nested attribute objects is not straight forward unless I'm missing something.

i.e. how would I support this response:

```json
{
  "data": [
    {
      "id": "1",
      "type": "pet",
      "attributes": {
        "id": 1,
        "name": "Dog"
      },
      "links": {
        "count": "/pets/1/count"
      }
    }
  ]
}
```

**Comment by adambro** [comment]
@nnnnathann got similar issue with nested object. I've just created a class for each object in JSON and marked them in phpdoc annotations. Example based on your JSON:
```php
class Pet {
  /** @var PetAttrs */
  var $attributes;
}

class PetAttrs {
  var $id;
  var $name;
}
```

**Comment by AaronJan** [comment]
@adambro @nnnnathann for nested definition, you can check [this](https://github.com/AaronJan/Kobe) out. 😃

**Comment by babarizbak** [comment]
+1 for HAL support.

**Comment by bfanger** [comment]
HAL support is outside the scope of the swagger-php project.

Feel free to experiment and create a swagger-php plugin, i'll gladly add that to the [related projects](http://zircote.com/swagger-php/Related-projects.html) page
