### ISSUE TITLE
Syntax error, unexpected T_ATTRIBUTE on line 4

### ISSUE THREAD

**Issue by swiffer** [zircote/swagger-php#855]
Syntax error, unexpected T_ATTRIBUTE on line 4

I'm getting this after upgrading to PHPStan. Is this similar to #841 ?

**Comment by swiffer** [comment]
seems to be nikic/php-parser latest release

**Comment by michaljusiega** [comment]
@swiffer See https://github.com/zircote/swagger-php/pull/857
