### ISSUE TITLE
Security for all endpoints

### ISSUE THREAD

**Issue by carlinchisart** [zircote/swagger-php#862]
Hi all,

in the doc of swagger i found  the option to put globally key security for all endpoint of my API https://swagger.io/docs/specification/authentication/api-keys/

but i can't found the anotation in the example or in the documentation of swagger-php, is implement this option?

```
# 2) Apply the API key globally to all operations
security:
  - ApiKeyAuth: []  # use the same name as under securitySchemes
```

Thanks

**Comment by Doqnach** [comment]
This is part of the `@OA\OpenApi` annotation.

**Comment by lol768** [comment]
It helps if you can provide an example.

Is this correct?

```
/**
 * @OA\OpenApi(
 *     security={"apiKeyAuth"}
 * )
 */
```

Generates the following JSON:

```
    "security": [
        []
    ]
```

Like this?

```
/**
 * @OA\OpenApi(
 *     security={
 *         {"apiKeyAuth": {}}
 *     }
 * )
 */
```

Seemingly generates the following JSON:

```
    "security": [
        []
    ]
```

**Comment by Doqnach** [comment]
Do verify that the second one generates the expected result, but that looks correct, yes.

**Comment by DerManoMann** [comment]
Seems the original question is answered.
