### ISSUE TITLE
Parse error: syntax error, unexpected '=' in ..... \vendor\zircote\swagger-php\src\StaticAnalyser.php on line 261

### ISSUE THREAD

**Issue by csearfarf** [zircote/swagger-php#867]
I tried this library regarding to the usage of swagger in Codeigniter 3 and 4 . It works actually in my localhost dev, but when i set it up in my live test server , it gives me error . i hope you can help me regarding to this issue that i encountered .
**Localhost setup / Live test setup** 
* _Codeigniter 3_ 
* _Php 7_

**Localhost preview:**
![image](https://user-images.githubusercontent.com/33477572/95339273-78f8be80-08e6-11eb-8322-c6d7595c8102.png)

**Live test server :** 
![image](https://user-images.githubusercontent.com/33477572/95339551-c07f4a80-08e6-11eb-9f3f-3af49aa88e94.png)

**Comment by Doqnach** [comment]
What version of php 7 are you using? Because the notation that is used on that line is supported from PHP 7.1

If you are using 7.0 consider upgrading to 7.4 since the older 7.X versions are not supported anymore by PHP (or will end support soon).

**Comment by DerManoMann** [comment]
Unresponsive - closing.
