### ISSUE TITLE
AugmentOperations processor class missing in v3.1.0

### ISSUE THREAD

**Issue by itsjavi** [zircote/swagger-php#871]
I recently upgraded from 3.0.4 to 3.1.0 and turns out that the `\OpenApi\Processors\AugmentOperations` class has disappeared.
There is no mention of that in the releases page or the commit messages.
I didn't expect 3.1.0 to contain breaking changes, but unfortunately it does.

Is there any alternative for this class? What are we supposed to use instead?

**Comment by DerManoMann** [comment]
That got renamed `DocBlockDescriptions` in  9a8691a43c456574fe403304acf66aeb5bb5b54d

**Comment by itsjavi** [comment]
@DerManoMann thanks. I think it's is worth mentioning that in the releases description. Kind of "migration" instructions.

**Comment by DerManoMann** [comment]
Could be. I am not sure how much the processors are considered internal and that people using individual processors know what they are doing. Renaming one would still come as a surprise, I agree...

**Comment by itsjavi** [comment]
In my case I am using custom processors to add API descriptions from external documents and process other custom x- fields. So I need to provide the default ones mixed with mine.

![image](https://user-images.githubusercontent.com/122741/96428593-3f865400-1200-11eb-9a5e-02312faf40d4.png)


Replacing the processors is an option of "scan":

```php
$jsonSpec = \OpenApi\scan($sourceDirs, ['processors' => $this->getProcessors()])->toJson();
```

So we can consider it a public API.

**Comment by itsjavi** [comment]
So I still think it's important to mention this change somewhere.
