### ISSUE TITLE
need your help

### ISSUE THREAD

**Issue by hanyunmuyu** [zircote/swagger-php#874]
**Excause me,Can you create a plugin for vscode to formate the code,thanks!**

**Comment by EvilFreelancer** [comment]
https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi

**Comment by Doqnach** [comment]
Do you mean to format the PHPDOC? or the resulting yaml spec?

**Comment by hanyunmuyu** [comment]
> The PHPDOC

**Comment by hanyunmuyu** [comment]
> Hello! First result in Google :) https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi

I write the api document with swagger-php . But I think that  the PHPDoc is hard to write .

**Comment by hanyunmuyu** [comment]
> Hello! First result in Google :) https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi

the swagger-php is hard to write the PHPDOC , Could you  understand ?

**Comment by hanyunmuyu** [comment]
I think if there is a a tool looks like 'VS Code ESLint extension' to formate the PHPDOC for swagger-php .Then more and more phper will use swagger-php to write api document.

**Comment by Doqnach** [comment]
Swagger-PHP uses "Doctrine" style PHPDOC. So the feature request more belongs there. But more often than not, those extensions are not written by the people providing the library...
