### ISSUE TITLE
Using environment variable in annotations

### ISSUE THREAD

**Issue by tarach** [zircote/swagger-php#883]
Hi,
I know it is possible to use constants in annotations. https://github.com/zircote/swagger-php/blob/master/docs/Getting-started.md#using-variables

What about environment variables?

I've tried:
```
     *              @OA\Property(
     *                  property="name",
     *                  type="string",
     *                  example="APP_NAME"
     *              ),
```
example=env(APP_NAME), example=%env(APP_NAME)%, example=env(APP_NAME)%' and APP_NAME
None of them work unfortunately.

**Comment by Doqnach** [comment]
It should be without the double quotes for sure, since now it is interpreted as a string.

This feature is provided by Doctrine Annotations, and not actually part of SwaggerPHP codebase itself: https://www.doctrine-project.org/projects/doctrine-annotations/en/1.10/custom.html#constants

**Comment by DerManoMann** [comment]
Closing as this is outside the scope of swagger-php.
