### ISSUE TITLE
Multiple @OA\Response() with the same response="200": 

### ISSUE THREAD

**Issue by buildsomethingdifferent** [zircote/swagger-php#888]
I'm facing this issue when generating docs. On my local this is working fine but I get an exception on server.
Steps To Reproduce:
php artisan l5-swagger:generate

![image](https://user-images.githubusercontent.com/38312207/102351869-f452ac80-3fc8-11eb-8a3b-8a4b0e15c636.png)

**Comment by buildsomethingdifferent** [comment]
@Doqnach any information on it ?

**Comment by Doqnach** [comment]
Any chance you could provide the source of the actual controllers? (can be sanitised by removing the body of the methods).

The basics are that you can not define multiple responses with the same HTTP status code for the same endpoint, as the error states. If you do have responses in that way, it is worth rethinking the design of the API, or to use `oneOf` to show that one of the given responses is possible.

**Comment by buildsomethingdifferent** [comment]
class CompanyController extends Controller
    {
    /**
     * @OA\GET(
     *   path="/api/company",
     *   operationId="getCompaniesList",
     *   tags={"Company"},
     *security={
     *{
     *"passport": {}},
     *},
     *      summary="Get list of Companies",
     *      description="Returns list of Companies",
     *      @OA\Response(
     *          response=200,
     *          description="Successful operation",
     *          @OA\MediaType(
     *           mediaType="application/json",
     *      )
     *      ),
     *      @OA\Response(
     *          response=401,
     *          description="Unauthenticated",
     *    @OA\JsonContent(
     *       @OA\Property(property="message", type="string", example="Not authorized"),
     *    )
     *      ),
     *      @OA\Response(
     *          response=403,
     *          description="Forbidden"
     *      ),
     *  )
     */
    public function index()
    {
        return CompanyResource::collection(Company::paginate(10));
    }


    /**
     * @OA\Post(
     ** path="/api/company",
     *   summary="Store Company",
     *security={
     *{
     *"passport": {}},
     *},
     *    tags={"Company"},
     *   operationId="companyStore",
     *   @OA\Parameter(
     *      name="first_name",
     *      in="query",
     *      required=true,
     *      @OA\Schema(
     *          type="string"
     *      )
     *   ),
     *   @OA\Parameter(
     *      name="last_name",
     *      in="query",
     *      required=true,
     *      @OA\Schema(
     *          type="string"
     *      )
     *   ),
     *   @OA\Parameter(
     *      name="email",
     *      in="query",
     *      required=true,
     *      @OA\Schema(
     *          type="string",
     *          format="email"
     *      )
     *   ),
     *     @OA\Parameter(
     *      name="phone",
     *      in="query",
     *      required=true,
     *      @OA\Schema(
     *          type="number"
     *      )
     *   ),
     *   @OA\Response(
     *      response=200,
     *       description="Success",
     *      @OA\MediaType(
     *           mediaType="application/json",
     *      )
     *   ),
     *   @OA\Response(
     *      response=401,
     *       description="Unauthenticated"
     *   ),
     *      @OA\Response(
     *          response=403,
     *          description="Forbidden"
     *      )
     *)
     **/


    public function store(Request $request)
    {
        
    }

    /**
     * @OA\GET(
     ** path="/api/company/{company_id}",
     *   tags={"Company"},
     *security={
     *{
     *"passport": {}},
     *},
     *   summary="Company Detail",
     *   operationId="companydetails",
     *   @OA\Parameter(
     *      name="company_id",
     *      in="path",
     *      required=true,
     *      @OA\Schema(
     *           type="integer"
     *      )
     *   ),
     *   @OA\Response(
     *      response=200,
     *       description="Success",
     *      @OA\MediaType(
     *          mediaType="application/json",
     *      )
     *   ),
     *   @OA\Response(
     *      response=401,
     *       description="Unauthenticated"
     *   ),
     *   @OA\Response(
     *      response=404,
     *      description="not found"
     *   ),
     *      @OA\Response(
     *          response=403,
     *          description="Forbidden"
     *      )
     *)
     **/


    public function show($id)
    {
        $company = Company::findOrFail($id);
        return new CompanyResource($company);
    }

    /**
     * @OA\PUT(
     ** path="/api/company/{company_id}",
     *   summary="Update Company",
     *security={
     *{
     *"passport": {}},
     *},
     *    tags={"Company"},
     *   operationId="companyUpdate",
     *     @OA\Parameter(
     *      name="company_id",
     *      in="path",
     *      required=true,
     *      @OA\Schema(
     *           type="integer"
     *      )
     *   ),
     *   @OA\Parameter(
     *      name="first_name",
     *      in="query",
     *      @OA\Schema(
     *          type="string"
     *      )
     *   ),
     *   @OA\Parameter(
     *      name="last_name",
     *      in="query",
     *      @OA\Schema(
     *          type="string"
     *      )
     *   ),
     *   @OA\Parameter(
     *      name="email",
     *      in="query",
     *      @OA\Schema(
     *          type="string",
     *          format="email"
     *      )
     *   ),
     *     @OA\Parameter(
     *      name="phone",
     *      in="query",
     *      @OA\Schema(
     *          type="number"
     *      )
     *   ),
     *   @OA\Response(
     *      response=200,
     *       description="Success",
     *      @OA\MediaType(
     *           mediaType="application/json",
     *      )
     *   ),
     *   @OA\Response(
     *      response=401,
     *       description="Unauthenticated"
     *   ),
     *      @OA\Response(
     *          response=403,
     *          description="Forbidden"
     *      )
     *)
     **/

    public function update(Request $request, $company_id)
    {
        
    }


    /**
     * @OA\DELETE(
     ** path="/api/company/{company_id}",
     *   tags={"Company"},
     *security={
     *{
     *"passport": {}},
     *},
     *   summary="Delete Company",
     *   operationId="deletepcompany",
     *   @OA\Parameter(
     *      name="company_id",
     *      in="path",
     *      required=true,
     *      @OA\Schema(
     *           type="integer"
     *      )
     *   ),
     *   @OA\Response(
     *      response=204,
     *       description="Success",
     *      @OA\MediaType(
     *          mediaType="application/json",
     *      )
     *   ),
     *   @OA\Response(
     *      response=401,
     *       description="Unauthenticated"
     *   ),
     *   @OA\Response(
     *      response=404,
     *      description="not found"
     *   ),
     *      @OA\Response(
     *          response=403,
     *          description="Forbidden"
     *      )
     *)
     **/

    public function destroy($company_id)
    {
       
    }

}

**Comment by Doqnach** [comment]
Are you using a case-sensitive filesystem? If so, it is important (but absolutely recommended either way) to use the correct casing for the annotations: `@OA\Get` (instead of all-caps).

Otherwise I can't really see anything wrong here since there are no multiple responses of the same endpoint and verb...

**Comment by DerManoMann** [comment]
Looks resolved to me so closing.
