### ISSUE TITLE
No default values accepted on RequestBody

### ISSUE THREAD

**Issue by stacoverf** [zircote/swagger-php#891]
I'm trying to setup OA annotations for my endpoints.
I've a POST endpoint that receives an `application/json` request body with several parameters.
Following the [documentation setup here ](https://github.com/zircote/swagger-php/blob/4931df2e8f11bb9cfe1dbd7d976a7bc08d97ad34/Examples/petstore.swagger.io/controllers/PetController.php#L241) I have been trying to add a default value to the `@OA/Property` but haven't been successful to it. Is this even possible at all?

If not, should I be setting up my annotations in a different way? Please advise, haven't been able to found a solution for this for days now, and no info on documentation either here or OpenApi.

Here is a redacted snippet of what I'm trying to do

```
     *    @OA\Post(
     *     path="/api/v1/create",
     *     summary="Create and store",
     *     description="Create and store",
     *     operationId="postCreateAction",
     *     tags={"V1"},
     *     @OA\RequestBody(
     *       @OA\MediaType(
     *           mediaType="application/json",
     *           @OA\Schema(
     *               type="object",
     *               required={"token"},
     *               @OA\Property(
     *                   property="token",
     *                   description="some token",
     *                   @OA\Schema(
     *                      type="string",
     *                      default="default token"
     *                   )
     *               ),
```

Thanks in advance

**Comment by DerManoMann** [comment]
Almost there. I think the `@OA\Schema` around the `default` property is wrong; 'default' is a direct propery on `@OA\Property`; something like
```
/**
 *    @OA\Post(
 *     path="/api/v1/create",
 *     summary="Create and store",
 *     description="Create and store",
 *     operationId="postCreateAction",
 *     tags={"V1"},
 *       @OA\RequestBody(
 *         @OA\MediaType(
 *           mediaType="application/json",
 *           @OA\Schema(
 *               type="object",
 *               required={"token"},
 *               @OA\Property(
 *                   property="token",
 *                   description="some token",
 *                   default="default token"
 *               )
 *           )
 *         )
 *       )
 *    )
 */
```

**Comment by DerManoMann** [comment]
Looks like this question is answered - closing.
