### ISSUE TITLE
Most "use" statements are ignored completely when using a namespaces whitelist

### ISSUE THREAD

**Issue by sjuvonen** [zircote/swagger-php#893]
There seems to be a bug in the static analyser; see highlighted lines.

https://github.com/zircote/swagger-php/blob/3.1.0/src/StaticAnalyser.php#L368-L378
https://github.com/zircote/swagger-php/blob/3.1.0/src/Analyser.php#L49

Comparison on line 372 is broken. It will not detect plain `use OpenApi\Annotations as FOO` statements at all, hence ignoring custom namespace aliases altogether. This happens everytime the whitelisted entry ends with a slash but also is the "complete namespace" where target classes are reside in.

I think the issue with trying to match namespaces with whitelist entries can be fixed as follows:

**Original code**
```php

if (strcasecmp(substr($target, 0, strlen($namespace)), $namespace) === 0) {
    $imports[strtolower($alias)] = $target;
    break;
}
```

**Patched code**
```php
if (strcasecmp(substr($target . '\\', 0, strlen($namespace)), $namespace) === 0) {
    $imports[strtolower($alias)] = $target;
    break;
}
```

P.S. Line 378 (`$analyser->docParser->setImports(...)`) is in the wrong place, it should be completely outside the outermost loop; it should likely be placed on line 383.

**Comment by sjuvonen** [comment]
Currently it is possible to workaround this bug by omitting the tailing backwards slash in the whitelist entry. This is not safe because it can lead to wrong namespaces being imported due to a sub-match; e.g. `My\Foo` would also cause `My\FooBar` to match incorrectly.

**Comment by DerManoMann** [comment]
Thanks for the details and analysis! I'll try to have a look in the next few days.

**Comment by sjuvonen** [comment]
I withdraw the latter comment about moving `setImports()` call to a different place. I did additional digging and found out that I had misunderstood the code.

**Comment by DerManoMann** [comment]
Good, that was also my conclusion :)
