### ISSUE TITLE
Annotation parser does not recognize references to class constants from the context class

### ISSUE THREAD

**Issue by sjuvonen** [zircote/swagger-php#896]
Annotations that use class constants from the same class that is currently being parsed are not recognized, leading to errors such as this:

```
User Warning: [Semantical Error] Couldn't find constant Foo::ADD, \My\Foo->property in /.../My/Foo.php on line xx
```

My class definition looks like this (note the use of constants in Choice annotation):

```php
namespace My;

use Symfony\Component\Validator\Constraints as Assert;

class Foo
{
    public const ADD = 'add';
    public const MULTIPLY = 'multiply';

    /**
     * Some property.
     *
     * @Assert\NotBlank
     * @Assert\Choice(choices={
     *   Foo::ADD,
     *   Foo::MULTIPLY,
     * })
     */
    public ?string $property = null;
}
```

I think the currently parsed class should always be added to imports, also ignoring whitelists and such.

My suggestion for the patch below. Sorry for not providing a proper patch, but I am doing this on my paid worktime.

I am patching this highlighted block here:

https://github.com/zircote/swagger-php/blob/3.1.0/src/StaticAnalyser.php#L117-L171

```php
if ($token[0] === T_CLASS) {
    /**
     * [EXISTING CODE HERE]
     * /


    /**
     * Insert this piece of code at the end of the block.
     */
    $class = $classDefinition['class'];
    $namespace = $parseContext->namespace;
    $alias = strtolower($class);
    $imports[$alias] = "{$parseContext->namespace}\\{$class}";
    $analyser->docParser->setImports($imports);
}
```

**Comment by sjuvonen** [comment]
Well, of course this change is also required for traits and interfaces, so the patch needs revising, but the basic idea is there.

**Comment by DerManoMann** [comment]
Just remembered PR #852 - isn't that the same (and the test is passing)?

**Comment by DerManoMann** [comment]
Seems to be working so closing.
