### ISSUE TITLE
Version >3.0.1 conflicts with roave/security-advisories

### ISSUE THREAD

**Issue by ndurchx** [zircote/swagger-php#899]
Because of the dependency symfony/yaml, the package is not installable when using roave/security-advisories.
There are a lot packages, which are using this meta package to check for security problems.

**Comment by DerManoMann** [comment]
Thanks for bringing up this topic. I've added a new action via 320ae56 to tackle this. Not sure why that is not failing, but then I also couldn't reproduce an error with `roave/security-advisories` either.

My understanding is that both tools are using the same sources, namely https://github.com/FriendsOfPHP/security-advisories...

Either way it's a start.

**Comment by DerManoMann** [comment]
Closing for now. Feel free to open this again if there is a good way to reproduce this issue...
