### ISSUE TITLE
$ref Syntax

### ISSUE THREAD

**Issue by pouriabagheri** [zircote/swagger-php#900]
I am migrating from a different api documentation library which supported external json resources as response. However, I haven't been able to find the equivalent in the swagger-php while there are some examples on the https://swagger.io/docs/specification/using-ref/.
any advice?

**Comment by Doqnach** [comment]
SwaggerPHP implements the OpenApi spec. So any place that OpenApi allows a `ref`, so does SwaggerPHP.

**Comment by DerManoMann** [comment]
As for an example, you can do something like this:
```
/**
 *     @OA\Response(
 *         response="200",
 *         description="Ok",
 *         @OA\JsonContent(ref="pet.yml")
 */
```
which will result in
```
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: pet.yml
```

This is, I believe, the expected outcome and follows http://spec.openapis.org/oas/v3.0.3#relative-schema-document-example

**Comment by DerManoMann** [comment]
Looks like this question is answered - closing.
