### ISSUE TITLE
Difficulties updating to 3.0 due to usage of Parameter->type and formData

### ISSUE THREAD

**Issue by ostrolucky** [zircote/swagger-php#902]
We use lot of this kind of annotations and I wonder what's the migration path there.

```
     *     @SWG\Parameter(
     *         name="number_of_learners",
     *         in="formData",
     *         description="Number of places on the vacancy.",
     *         required=false,
     *         type="integer"
     *     ),
```

Problem 1:`Unexpected field "type" for @OA\Parameter(name="number_of_learners",in="formData")`. Ok, even though not a fan of that because consumer looses information, I've just removed type from there.
Problem 2: `@OA\Parameter(name="number_of_learners",in="formData")->in "formData" is invalid, expecting "query", "header", "path", "cookie"`

**Comment by ostrolucky** [comment]
https://blog.readme.com/an-example-filled-guide-to-swagger-3-2/, section "Request Format"

**Comment by Doqnach** [comment]
When going from Swagger 2.0 to OpenAPI 3.0+, please read: https://swagger.io/docs/specification/describing-request-body/
