### ISSUE TITLE
Can't get security to work at root level

### ISSUE THREAD

**Issue by kurt-wasabi** [zircote/swagger-php#903]
Hi.

I'm trying to get security to work at root level with no success. I have tried a lot of different variations on the annotations, but I always get an empty security thing in the openapi output:
    "security": [
        []
    ]

The last thing I tried is below.

Any help would be greatly appreciated.

  /**
     *  @OA\Info(
     *      version="1.0.0",
     *      title="xxx",
     *      description="xxx",
     *      @OA\Contact(
     *          email="xxx"
     *      )
     *  ),
     * 
     *  @OA\Server(
     *      url=L5_SWAGGER_CONST_HOST,
     *      description="xxx"
     *  ),
     * 
     *  @OA\Components(
     *      @OA\SecurityScheme(
     *          securityScheme="bearerAuth",
     *          in="header",
     *          name="bearerAuth",
     *          type="http",
     *          scheme="bearer",
     *      ),
     *  )
     */

    /**
     * @OA\OpenApi(
     *  security={{"bearerAuth": {}}}
     * )
     */

**Comment by aesyondu** [comment]
It worked for me:

```php
    /**
    *     @OA\Components(
    *         @OA\SecurityScheme(
    *             securityScheme="bearer",
    *             type="http",
    *             scheme="bearer",
    *         )
    *     ),
    *     @OA\OpenApi(
    *        security={{"bearer": {}}}
    *     )
    */
```

I get the following json output:

```json
    "components": {
        "securitySchemes": {
            "bearer": {
                "type": "http",
                "scheme": "bearer"
            }
        }
    },
    "security": [
        {
            "bearer": []
        }
    ],
```

I'm using:
```
        "darkaonline/swagger-lume": "5.6.*",
        "laravel/lumen-framework": "5.8.*",
```
