### ISSUE TITLE
Multiple paths fail with symfony/finder: 5.2.2

### ISSUE THREAD

**Issue by orbex** [zircote/swagger-php#904]
The combination of zircote/swagger-php : v2.1.0 with symfony/finder : 5.2.2 will cause the creation of complete JSON files to fail when using multiple paths.
Only the last path entry will be processed, resulting in [INFO] notices because of missing refs/definitions.

Sidenote: VERSION file @ tag 2.1.0 says 2.0.16 ...

**Comment by Doqnach** [comment]
Could you provide any sort of example? Best would be a small project in github that shows the problem.

**Comment by DerManoMann** [comment]
Two thoughts:
* The change in title suggests this is a specific issue with finder-5.2.2. If that is the case then it feels this is not a swagger-php problem and can be avoided by using a different version.
* Version 2 is deprecated and there is no active development on the 2.x branch any more.

Having said that, it is still nice to know about these things, in particular for people still using 2.x, so thanks anyway.

**Comment by orbex** [comment]
You are correct DerManoMann, pinning finder @ v5.2.1 in our composer.json fixed the issue. So it is not a swagger-php issue.
