### ISSUE TITLE
List of available annotations

### ISSUE THREAD

**Issue by FabianTe** [zircote/swagger-php#905]
Hi,

maybe I am missing something, but I can't find any documentation that lists all available annotations including their possible properties.

Is there such a list?

**Comment by DerManoMann** [comment]
Not as such. To see a list there is always https://github.com/zircote/swagger-php/tree/master/src/Annotations.

**Comment by FabianTe** [comment]
I added a documentation page that links to the given namespace and the examples folder in #915.

Right now I don't have the time to add more documentation but maybe this encourages someone to go the extra mile 😉

**Comment by FabianTe** [comment]
Thank you. Somehow the website didn't update. Is there anything I could to to make it so?

**Comment by DerManoMann** [comment]
Yeah, that is a separate step. Sorry, slow going at the moment.
