### ISSUE TITLE
Support for Multiple Examples

### ISSUE THREAD

**Issue by JohnRoux** [zircote/swagger-php#908]
Currently I haven't found a way to annotate multiple examples

This should be an option for certain types as per https://swagger.io/docs/specification/adding-examples/

Most notably I'm wanting this for parameters.

Eg:

```
     *     path="/api/card/{card_id}/scrape",
     *     @OA\Parameter(
     *         description="The id, scryfall_id or oracle_id of the card",
     *         in="path",
     *         name="card_id",
     *         required=true,
     *         @OA\Schema(type="string"),
     *         examples=[1, 0006faf6-7a61-426c-9034-579f2cfcfa83],
     *     ),
     ```
     
The above parameter can either be an integer id, or a uuid and I'd like to be able to show that to the api users

**Comment by DerManoMann** [comment]
There is a dedicated `@OA\Examples` annotation for this sort of thing - I'll add an example later today...

```
 *     @OA\Parameter(
 *         description="The id, scryfall_id or oracle_id of the card",
 *         in="path",
 *         name="id",
 *         required=true,
 *         @OA\Schema(type="string"),
 *         @OA\Examples(example="int", value="1", summary="An int value."),
 *         @OA\Examples(example="uuid", value="0006faf6-7a61-426c-9034-579f2cfcfa83", summary="An UUID value."),
 *     ),
```

**Comment by JohnRoux** [comment]
Ahhh this makes a lot more sense!

Thank you so so much! What a champion :1st_place_medal:
