### ISSUE TITLE
Convert JSON to PHP Swagger annotations.

### ISSUE THREAD

**Issue by connerbw** [zircote/swagger-php#909]
Hi, I wrote this one page tool:

+ https://kizu514.com/swagit.php
+ [Gist here...](https://gist.github.com/ls-dac-chartrand/5481b91bc97b828b348df8077269ff47). 

It converts JSON to (partial) PHP Swagger annotations.

Often I already had a working JSON API. After-the-fact, I had to write Swagger PHP annotations. This tool reduced some of the work for me.

Does something like this already exist? I could not find it.

**Comment by DerManoMann** [comment]
First I hear about something like this. Sounds useful!

**Comment by DerManoMann** [comment]
Feel free to create a PR for https://github.com/zircote/swagger-php/blob/gh-pages/Related-projects.html if you think it is worth adding...

**Comment by connerbw** [comment]
Thanks for the tip. I have opened a PR.

**Comment by DerManoMann** [comment]
Fixed via  9b2acd5

**Comment by victorobama** [comment]
This is really helpful, wish i knew about it earlier :(

Thanks a lot :D

**Comment by valkedev** [comment]
@connerbw tyvm! I was about to write my own one but you saved me a bunch of time!

**Comment by valkedev** [comment]
Just noticed examples doesn't work as expected
![image](https://user-images.githubusercontent.com/1539181/202694261-f5acce3f-6dd9-40ef-b349-84ac800ee292.png)

**Comment by connerbw** [comment]
Sorry I don't see the problem. This tool converts JSON not JSON swagger. Please fork and patch as you see fit.

**Comment by AlexKhranovskiy** [comment]
Men, thank you, so much)

**Comment by mnr73** [comment]
thanks bro ❤😍😍😍😍
