### ISSUE TITLE
OA\Examples seems do not work well

### ISSUE THREAD

**Issue by phper5** [zircote/swagger-php#925]
I tried the demo https://github.com/zircote/swagger-php/blob/master/Examples/example-object/example-object.php 
write:
<pre>
 *         @OA\Examples(example="int", value="1", summary="An int value."),
 *         @OA\Examples(example="uuid", value="0006faf6-7a61-426c-9034-579f2cfcfa83", summary="An UUID value."),
 * </pre>
 
however it do not generate
<pre>examples:
            int:
              summary: 'An int value.'
              value: '1'
            uuid:
              summary: 'An UUID value.'
              value: 0006faf6-7a61-426c-9034-579f2cfcfa83</pre>

instead. it is :

<pre>examples:
            -:
              example:int
              summary: 'An int value.'
              value: '1'
            -:
              example:uuid
              summary: 'An UUID value.'
              value: 0006faf6-7a61-426c-9034-579f2cfcfa83</pre>

**Comment by gserrg** [comment]
I also ran into this problem while trying to figure out how to fix it.

**Comment by gserrg** [comment]
Fixed in https://github.com/zircote/swagger-php/releases/tag/3.0.4 Alas, php <7.2 remains a problem. :(

**Comment by DerManoMann** [comment]
Closing as the original issue is resolved.
