### ISSUE TITLE
multipart/form-data can't inset array object

### ISSUE THREAD

**Issue by chaknop96** [zircote/swagger-php#927]
/**
     * @OA\Post(
     *      path="/beneficiary",
     *      operationId="storeBeneficiary",
     *      tags={"Beneficiary"},
     *      summary="Store new Beneficiary",
     *      description="Returns Beneficiary data",
     *      security={{"bearerAuth":{}}},
     *     @OA\RequestBody(
     *       @OA\MediaType(
     *           mediaType="multipart/form-data",
     *           @OA\Schema(
     *              ref="#/components/schemas/StoreBeneficiaryRequest",
     *           ),
     *       )
     *     ),
     *      @OA\Response(
     *          response=201,
     *          description="Successful operation",
     *          @OA\JsonContent(
     *              @OA\Property(property="success", type="boolean",example=true),
     *              @OA\Property(property="http_code", type="integer",example=200),
     *              @OA\Property(property="data", type="object", ref="#/components/schemas/BeneficiaryResource"),
     *              @OA\Property(property="message", type="string",example="Save Success"),
     *          )
     *       ),
     *      @OA\Response(
     *          response=400,
     *          description="Bad Request"
     *      ),
     *      @OA\Response(
     *          response=401,
     *          description="Unauthenticated",
     *      ),
     *      @OA\Response(
     *          response=403,
     *          description="Forbidden"
     *      )
     * )
     */

StoreBeneficiaryRequest

 /**
     * @OA\Property(
     *     property="documentSupports",
     *     type="array",
     *      @OA\Items(
     *          @OA\Property(property="document_type_id", type="integer", example="1"),
     *          @OA\Property(property="document_no", type="integer", example="00011"),
     * ),
     * ),
     */

Curl

curl -X 'POST' \
  'http://localhost:8000/api/beneficiary' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -H 'X-CSRF-TOKEN: ' \
  -F 'is_literate=1' \
  -F 'is_attend_school=1' \
  -F 'sex=M' \
  -F 'is_income_earner=1' \
  -F 'death_ref=sick' \
  -F 'name=Dara' \
  -F 'occupation_id=2' \
  -F 'death_reason=sick' \
  -F 'factory_id=1' \
  -F 'photo=' \
  -F 'health_facility_id=1' \
  -F 'beneficiary_household_id=2' \
  -F 'death_under_48=0' \
  -F 'dob=2020-01-27' \
  -F 'is_alive=1' \
  -F 'relationship_type_id=1' \
  -F 'is_in_picture=1' \
  -F 'disabilities=' \
  -F 'phone_number=012345678' \
  -F 'monitored_by=2020-01-27' \
  -F 'has_chronic_disease=1' \
  -F 'documentSupports={
  "document_type_id": 1,
  "document_no": "00011"
}'

Error

{
  "success": false,
  "http_code": 500,
  "error_code": 1,
  "errors": [
    "Illegal string offset 'document_type_id'"
  ]
}

**Comment by DerManoMann** [comment]
This looks like an issue with the actual request handling which is outside of the scope of this project.

If you have a specific question about the JSON/Yaml generated from the posted annotations please feel free to do so.
We'd need the annotations, the generated specs and ideally what the specs you were expecting.
