### ISSUE TITLE
Exclude files and folders from scan()

### ISSUE THREAD

**Issue by winternet-studio** [zircote/swagger-php#932]
Here it says to use relative or absolute paths:
https://github.com/zircote/swagger-php/blob/e62ff09e69a8d8b5c2de849f9c9d9c64cd4d7931/src/functions.php#L36-L38

I tried using relative paths but it didn't work - I figured out I have to use regular expressions (glob?) instead. Like this:

```
$openapi = \OpenApi\scan(__DIR__, [
	'exclude' => ['/vendor/', '/runtime/', '/tests/', '/web/', '/data-persistence/', '/mail/'],
]);
```

This article led me to it: https://stackoverflow.com/questions/43798928/symfony-finder-exclude-with-glob

Also it would be good mention that it uses the [Symfony Finder component](https://symfony.com/doc/current/components/finder.html).

**Comment by DerManoMann** [comment]
#928 will change things a bit - I'll try to add more about the finder in there...

**Comment by DerManoMann** [comment]
Closing now that the `Generator` code has landed. Documentation is here: https://zircote.github.io/swagger-php/Generator-migration.html
