### ISSUE TITLE
Examples with oneOf

### ISSUE THREAD

**Issue by winternet-studio** [zircote/swagger-php#933]
Couldn't find any examples of using `oneOf` but finally figured it out. Would be good to add these examples to the Examples folder (I would do it myself if I knew how and had the time):

```
/**
 *	@OA\Response(
 *		response=200,
 *		description="Successful operation",
 *		@OA\JsonContent(
 *			oneOf={
 *				@OA\Schema(ref="#/components/schemas/PwResetResponseBoolean"),
 *				@OA\Schema(ref="#/components/schemas/PwResetResponseInteger"),
 *			},
 *		),
 *	),
 */

/**
 *	@OA\JsonContent(
 *		oneOf={
 *			@OA\Schema(type="boolean"),
 *			@OA\Schema(type="integer"),
 *		},
 *	),
 */
```

Still struggling to figure out the right syntax for these annotations... First one needs to know the OpenAPI specs, then to find out how to write it in these annotations - it's not a walk in the park... :(

**Comment by DerManoMann** [comment]
Thanks for that. Examples are always welcome!

**Comment by Revisor** [comment]
Thanks, this works for properties with mixed types as well

    /**
     * @OA\Property(
     *     oneOf={
     *         @OA\Schema(type="string"),
     *         @OA\Schema(type="integer"),
     *         @OA\Schema(type="boolean"),
     * })
     */

**Comment by DerManoMann** [comment]
@winternet-studio Would you be able to provide a PR for this?

**Comment by winternet-studio** [comment]
> @winternet-studio Would you be able to provide a PR for this?

Done.
