### ISSUE TITLE
Array of objects as a Property results in strict substr() error

### ISSUE THREAD

**Issue by JimmyBanks** [zircote/swagger-php#938]
I am trying to document models that return an array of objects, like so:

    public function __construct(
        /**
         * Future List
         * @var Future[] $future
         * @OA\Property()
         */
        public array $future
    )
    {}

However, this throws a strict error: `Fatal error: Uncaught TypeError: substr(): Argument #1 ($string) must be of type string, null given in /composer/vendor/zircote/swagger-php/src/Annotations/AbstractAnnotation.php:414 `

If I include an optional null, it functions properly, this works:

    public function __construct(
        /**
         * Future List
         * @var Future[]|null $future
         * @OA\Property()
         */
        public array $future
    )
    {}

How do I resolve this issue? Or is this a bug?

**Comment by DerManoMann** [comment]
Hi there, I've been trying to debug this issue and cannot seem to make it break :)

In #951 I've added a test case based on your example and that seem to work fine. Could you perhaps provide a complete example (single file) that breaks when running `openapi` on it?

**Comment by JimmyBanks** [comment]
> Hi there, I've been trying to debug this issue and cannot seem to make it break :)
> 
> In #951 I've added a test case based on your example and that seem to work fine. Could you perhaps provide a complete example (single file) that breaks when running `openapi` on it?

So I have tested the identical code that used to cause this bug to occur, and the issue no longer appears to be happening.

One of the updates since I posted here must have resolved the issue

**Comment by DerManoMann** [comment]
Cool. I was wondering... Pretty sure I have seen a similar issue before.
I'll close this for now, feel free to open a new issue if you run into this again.
