### ISSUE TITLE
Sortable Schemas

### ISSUE THREAD

**Issue by JimmyBanks** [zircote/swagger-php#939]
Is there a method currently where the Schemas generated can be sorted alphabetically prior to the Yaml/Json generation?

Right now the default (and only method that I am able to find?) is sorted numerically from when each schema is identified by the scan method.

**Comment by DerManoMann** [comment]
Not that I know of. Sounds like something for a custom processor.

**Comment by DerManoMann** [comment]
Example added that should get you started :)
