### ISSUE TITLE
Cannot create mediaType="*/*"

### ISSUE THREAD

**Issue by rauwebieten** [zircote/swagger-php#943]
I want to add mediaType information, but I cannot use the suggested wildcard `*/*` as value.
Because PHP interprets the */ as closing my docblock comment.

      @OA\MediaType(
          mediaType="*/*",
          @OA\Schema(type="string",format="binary") 
      )

Any ideas on how to fix this?
Is there a way to escape the `*/*` value?

**Comment by rauwebieten** [comment]
I fixed it by using `*` or  `application/octet-stream`.
Seems to work and make no difference.

**Comment by DerManoMann** [comment]
Not much we can do about that I think.
