### ISSUE TITLE
Add line-break in description?

### ISSUE THREAD

**Issue by winternet-studio** [zircote/swagger-php#945]
How do I add a line-break in a description? This doesn't work:

```
/**
 * @OA\Info(
 *	title="My API Documentation",
 *	description="NOTES:\nWhen sending data to the API...",
 * )
 */
```

It produces JSON string `"NOTES:\\nWhen sending..."` instead of `"NOTES:\nWhen sending..."`

Tried with "\\n" as well.Don't find any in examples either...

**Comment by DerManoMann** [comment]
Have you tried just sa regular newline?
```
/**
 * @OA\Info(
 *	title="My API Documentation",
 *	description="NOTES:
When sending data to the API...",
 * )
 */
```
Looks not great, but the annotation parser seems to cope with it.

**Comment by winternet-studio** [comment]
Ha, never even thought of such an ugly thing... but it works! Will do a PR.
