### ISSUE TITLE
 Multiple @OA\Schema() with the same schema

### ISSUE THREAD

**Issue by amir-shadanfar** [zircote/swagger-php#962]
I have a problem with schema defining, when I create a schema, I got a error in terminal when generate a doc with this content:

Multiple @OA\Schema() with the same schema="User":
  \App\Http\Resources\UserResource->toArray() in /var/www/html/app/Http/Resources/UserResource.php on line 20
  \App\Http\Resources\UserResource->toArray() in /var/www/html/app/Http/Resources/UserResource.php on line 20

  at vendor/zircote/swagger-php/src/Logger.php:40
     36▕         $this->log = function ($entry, $type) {
     37▕             if ($entry instanceof Exception) {
     38▕                 $entry = $entry->getMessage();
     39▕             }
  ➜  40▕             trigger_error($entry, $type);
     41▕         };
     42▕     }
     43▕ 
     44▕     public static function getInstance(): Logger

      +28 vendor frames 
  29  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by amir-shadanfar** [comment]
I am using php 7.4 with laravel8 and  "zircote/swagger-php": "3.*"

**Comment by DerManoMann** [comment]
Without the full project (all processed annotations) this is going to be hard to debug.
Have you searched for another instance of `schema="User"` in your sources? Not sure of the top of my head if the name is case sensitive or not...

Also, schema annotations without the `schema` might get one set based on the context (class name, etc.) so that is another thing to look out for.

From the distance all I can see is to look at improving the error messages, which is something that's on my list anyway :)

**Comment by amir-shadanfar** [comment]
I tried different name for schema but the problem is still exist. 
I used to package on laravel 5.8 and with "zircote/swagger-php": "~2.0|3.*" and everything is work... I think it is maybe related to new version.

**Comment by Tomizzi** [comment]
Hello,

Same issue with my Laravel project.
```
Multiple @OA\Schema() with the same schema="UserD":
app/Documentation/Models/User.php on line 5
app/Documentation/Models/User.php on line 5
```

```
// User.php
<?php

namespace App\Documentation\Models;

/**
 * @OA\Schema(
 *     title="User model",
 *     description="User model",
 *     @OA\Xml(
 *         name="User"
 *     )
 * )
 */
class User
{
    /**
     * @OA\Property(
     *     title="ID",
     *     description="ID",
     *     format="int64",
     *     example=1
     * )
     *
     * @var integer
     */
    public $id;

    /**
     * @OA\Property(
     *      title="givenName",
     *      description="User's given name",
     *      example="John"
     * )
     *
     * @var string
     */
    public $givenName;
}
```

**Comment by DerManoMann** [comment]
Hmm, the model/controller/resource example above works for me locally with both 3.2.3 and `master`!?!
I copied all three into a single file (removing just the namespaces) and that is fine.

It would be cool if you could try doing the same and using the CL to run swagger-php against it.

Another question: are you using swagger-php stand-alone or via something like `NelmioApiDocBundle`? Any changes on that side, perphaps? (Clutching at straws until I can get a proper reproducer...)

**Comment by Tomizzi** [comment]
> Hmm, the model/controller/resource example above works for me locally with both 3.2.3 and `master`!?!
> I copied all three into a single file (removing just the namespaces) and that is fine.
> 
> It would be cool if you could try doing the same and using the CL to run swagger-php against it.
> 
> Another question: are you using swagger-php stand-alone or via something like `NelmioApiDocBundle`? Any changes on that side, perphaps? (Clutching at straws until I can get a proper reproducer...)

Thanks for your answer, I did not actually test in standalone way but with https://github.com/DarkaOnLine/L5-Swagger ... I'll test as soon as possible and I come back to you.

**Comment by DerManoMann** [comment]
Thanks. I guess it is time to create some simple reference projects using some of the big framework bundles/plugins to be able to see what the impact is for those when changing things.. Its been on my list for quite some time....

**Comment by Tomizzi** [comment]
I tested in standalone, no problem. 👍 
In my case, it was the l5-swagger config file (config/l5-swagger.php)

The file has been modified recently making the old config unusable:

Old
``` PHP
            /**
             * Custom query path processors classes.
             *
             * @link https://github.com/zircote/swagger-php/tree/master/Examples/schema-query-parameter-processor
             * @see \OpenApi\scan
             */
            'processors' => [
                // new \App\SwaggerProcessors\SchemaQueryParameter(),
            ],
```
New
``` PHP
            /**
             * Custom query path processors classes.
             *
             * @link https://github.com/zircote/swagger-php/tree/master/Examples/schema-query-parameter-processor
             * @see \OpenApi\scan
             */
            'processors' => array_merge(
                \OpenApi\Analysis::processors(),
                [
                    // new \App\SwaggerProcessors\SchemaQueryParameter(),
                ]
            ),
```

Sorry for the inconvenience, the problem wasn't related to this project.

**Comment by DerManoMann** [comment]
No problem - good to have it sorted.
