### ISSUE TITLE
convert api-docs.json to @OA syntanxis

### ISSUE THREAD

**Issue by cirelramostrabajo** [zircote/swagger-php#965]
i have documentation in OpenApi-php 2.x and migrate to OpenApi-php 2.x thought api-docs.json, i did with swagger editor, here was good, but now i can't  transform api-docs.json to @OA syntaxis to laravel swagger o php-swagger, any ideas?

I think there must be another more automated way to migrate

**Comment by DerManoMann** [comment]
Depends on what exactly you need, I guess.
Do you want to migrate swagger-php 2 to 3? Or convert a swagger2 spec to OpenApi3?
There are some related projects around, have you looked there yet?
https://zircote.github.io/swagger-php/Related-projects.html

**Comment by cirelramostrabajo** [comment]
thanks, i did read your link, i try something like https://kizu514.com/swagit.php 

Then I'll tell you if it worked, if it works I close the topic

**Comment by cirelramostrabajo** [comment]
it doesn't working, i try conver OpenAPI Spec v2 to OpenAPI Spec v3

example this is v2, i want conver to v3 with something application 
```

    /**
     * @SWG\Get(
     *   path="/products",
     *   summary="Show product list ",
     *   tags={"Products"},
     *   @SWG\Parameter(
     *     name="page_pagination",
     *     in="query",
     *     description="page pagination",
     *     type="integer",
     *     default=1
     *   ),
     *   @SWG\Parameter(
     *     name="size_pagination",
     *     in="query",
     *     description="size pagination",
     *     type="integer",
     *     default=15
     *   ),
     *   security={
     *     {"Content-Language":{}, "Key-access": {}, "id-company":{}, "id-user":{}, "Content-Language":{}}
     *   },
     *   @SWG\Response(
     *     response=200,
     *     description="Successful operation",
     *   ),
     *   @SWG\Response(response=401, ref="#/responses/401"),
     *   @SWG\Response(
     *     response="403",
     *     description="Forbidden Access",
     *     @SWG\Schema(
     *       @SWG\Property(property="error", type="string",
     *                                       description="Message error",
     *                                       example="This data is not allowed
     *                                       for you"),
     *       @SWG\Property(property="code", type="integer",
     *                                      description="Response code",
     *                                      example="403"),
     *     ),
     *   ),
     *   @SWG\Response(response=500, ref="#/responses/500"),
     * )
     *
     */
```

**Comment by DerManoMann** [comment]
Yeah, the tools I saw were only to convert specs, not the actual annotations.
To migrate the annotations I think you'll need to do that manually.
Have you looked at the migration guide?
https://zircote.github.io/swagger-php/Migrating-to-v3.html#swg-definition-is-removed

I would think with a good IDE that shouldn't be too hard.
