### ISSUE TITLE
Multiple @OA\Response() with the same response

### ISSUE THREAD

**Issue by ivan1986** [zircote/swagger-php#969]
```
Multiple @OA\Response() with the same response="404":
\app\modules\api\controllers\CartController->actionUpdateTransfer() in /app/source/modules/pages/controllers/../../api/controllers/CartController.php on line 295
/app/source/modules/pages/controllers/../../api/actions/domain/DomainInfoAction.php on line 21
```
I look to other issues - cases is correct, add vardump near exeption and looks like incorrect context merge, because 

![screencapture-dev-local-namesilo-net-8080-swagger-api-json-2021-07-15-18_29_08](https://user-images.githubusercontent.com/156418/125814928-65a60907-13a7-4d19-96e5-b1562444b9fa.png)

items with different contexts in same array
maybe some incorrect context calculation

**Comment by ivan1986** [comment]
should be only first two
class DomainInfoAction and @OA\Get(path="/domain/api/info/{domain}"
but in same array
InfoAction and @OA\Get(path="/ssl-manager/api/{sslId}"
InstallAction and @OA\Post(path="/ssl-manager/api/install"
and added new  \app\modules\api\controllers\CartController->actionUpdateTransfer() with @OA\Post(path="/cart/api/item/{id}/transfer"

**Comment by DerManoMann** [comment]
Does `DomainInfoAction` extend `InfoAction`? Any chance of extracting enough annotations and (empty) classes to reproduce this?
Also, is this using the latest version or dev-master?

**Comment by ivan1986** [comment]
No, all classes is yii actions and yii controllers
Yes, latest release and dev-master - same error

Try to clean all project

**Comment by ivan1986** [comment]
[bug.zip](https://github.com/zircote/swagger-php/files/6826488/bug.zip)

Clean project
yii2 app, `source/web/` - root, error in page `/swagger/api-json`

if remove in `CartController.php` `@OA\Response(response=404, description="Item not found")` all work fine

**Comment by DerManoMann** [comment]
Well, that was a good one!

its the `JsonContent` line in the 200 response! There is an additional closing backet at the end..

```
     *   @OA\Response(response=200, description="Item updated successfully",
     *     @OA\JsonContent(type="object", ref="#/components/schemas/ObjectResponseDto"))
     *   ),
```

What happens is that the doctrine parser accepts it so the `Post` is finished after that and the 404 becomes a top level annotation 🤷

**Comment by ivan1986** [comment]
Thanks
sorry

**Comment by ivan1986** [comment]
https://github.com/doctrine/annotations/issues/420
added issue - they ignore bracket balanse
