### ISSUE TITLE
PHP8 annotation in 3.0.2 breaks importing Schema on PHP 7

### ISSUE THREAD

**Issue by EdieLemoine** [zircote/swagger-php#972]
I'm on PHP 7.1, using zircote/swagger-php 3.0.2.

In Schema.php the following code is used:
```php
#[\Attribute] class Schema extends AbstractAnnotation
```
The annotation at the beginning is not supported until PHP 8. So when I do the following in my code:

```php
<?php

use OpenApi\Annotations as OA; // For autocompletion in my IDE

/**
 * @OA\Schema()
 */
class ErrorResource
{
}
```

And run `./vendor/bin/openapi src --output swagger.json` I get the following output:
```
Exception: syntax error
```

I noticed this annotation is gone in newer versions of this package, but I can't upgrade because 3.1.0 and newer require PHP 7.2. Is it still possible to create a 3.0.3 without this annotation?

**Comment by DerManoMann** [comment]
I am a bit confused - you mean this file: https://github.com/zircote/swagger-php/blob/3.0.2/src/Annotations/Schema.php ?

I might be missing something but I cannot see an attribute in there.
