### ISSUE TITLE
Minor error in example

### ISSUE THREAD

**Issue by mroeling** [zircote/swagger-php#975]
https://github.com/zircote/swagger-php/blob/e2497374d50cc11ac70eb85ef2c97745617ef43c/Examples/using-refs/ProductController.php#L49

`@OA\Parameter` schould be `@OA\RequestBody`

**Comment by DerManoMann** [comment]
Hmm, could you check what version you are one? Looks like this is already fixed on master.

**Comment by mroeling** [comment]
Indeed! Sorry. Strange, I didn't choose a specific commit/tag and just browsed the repo.
