### ISSUE TITLE
Merging operations together

### ISSUE THREAD

**Issue by jkbennemann** [zircote/swagger-php#976]
Hey there,

I'm wondering if it is possible to merge operations together and if how could it be accomplished?

I do have dynamic generation of controllers and their routes so I want to add basic annotation scaffolding for that, e.g

```
/**
 * @OA\Get(
 *      path="{{ $dynamicPath }}",
 *      tags={ {{ $dynamicTags }} },
 *      summary="Get list of {{ $value }}",
 *      description="{{ $dynamicDescription}}",
 *      @OA\Response( response=200, description="successful operation")
 * )
 */
```
 
 Later on I want to overwrite/extend for example the available responses.
 If I simply specify the operation again but with additional information like 

```
/**
 * @OA\Get(
 *      path="/products",
 *      @OA\Response( response=200, description="Returns list of all products"),
 *      @OA\JsonContent(ref="#/components/schemas/InvalidRequest"),
 *      @OA\JsonContent(ref="#/components/schemas/NotAuthorized")
 * )
 */
```
 
 I do get the following error
`Unable to merge @OA\Get() in ...`

Is there any way around this to get this dynamic extensions working?

Thanks in advance for your help

Jakob

**Comment by DerManoMann** [comment]
Not sure I fully understand this - would there actually be annotations with `{{ placeholder }}` in it or is that updated at code generation time?
In any case I suspect you might need a custom processor to allow for the merging. [NelmioApiDocBundle](https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html) might have some inspiration for that; iirc that one handles merging of multiple sets of annotations for the same route.

**Comment by jkbennemann** [comment]
Exactly.
I do have a file with placeholder text in it as it is basically the same for most of my routes.
In addition of that I do have a console command (I'm using Laravel) which generates a api.php for each of my dynamic controllers which replaces the placeholders with the actual values.

**Comment by DerManoMann** [comment]
Hmm, so we agree but I am still not sure I know about what exactly 😁
If you parse the placeholder annotations too I cannot see how you would match the resolved annotations in `api.php` with the placeholder ones as they are keyed on the path/method (and probably something else).

I suppose you'd do something similar to generate routes?

**Comment by DerManoMann** [comment]
Looks like this is not going anywhere so closing. Sorry if I was too thick to understand...
