### ISSUE TITLE
Yaml or Json file

### ISSUE THREAD

**Issue by renatocosta** [zircote/swagger-php#983]
Hello,

Can specification be living in yaml or json file rather than method Controller?

If so, then How Can I do it?

Best,

**Comment by DerManoMann** [comment]
Hmm, like an API spec you mean ;) ?

Seriously though, what would that look like. Wouldn't it be easier to just write the spec from hand and not have annotations in the first place.

One of the main reasons for using annotations is that the OpenAPI details live with the code so it is harder to get out of sync (but not impossible, of course).  If you take that away and start writing a yaml file where is the difference to writing a proper spec file directly?
