### ISSUE TITLE
Two array is combined to one array

### ISSUE THREAD

**Issue by stevenleesf** [zircote/swagger-php#989]
- PHP Version (`php -v`): 7.4.13
- OS:Window 10

Description:
I have been trying to send an array to my controller using the swagger-ui. But I am not sure why when I send an array using swagger it will combine 2 arrays into 1 array.

I am using **application/x-www-form-urlencoded**.

As shown below, This is the result I get.
![image](https://user-images.githubusercontent.com/67547139/134487166-4c4d4910-76f0-4df1-91e1-b24e613302c8.png)

and here is my code:
```
     *               @OA\Property(
     *                   property="benefits[]",
     *                   description="Benefit ID",
     *                  type="array",
     *                  example={"1","2"},
     *                  collectionFormat="multi",
     *                   @OA\Items(type="integer"
     *                  )
     *               )
  ```
  The expected result is
  
  'benefits' => 
    array (
      0 => '1',
      1 = > '2',
  )
  
  Thanks for taking a look at my question.

**Comment by DerManoMann** [comment]
I haven't tried this, but you might want to try setting `explode=true` .

**Comment by GueroSF** [comment]
`property[]` is an array element. it's like `$arr[] = "1";`. that is, for such an entry, you need to specify 'string' because "1".  
but, if you need documentation for api, then you need a construction like this `@Property(type=array, @Items(type=string))`

**Comment by DerManoMann** [comment]
I've added an example to the docs: https://zircote.github.io/swagger-php/guide/cookbook#multi-value-query-parameter-q-1-q-1
