### ISSUE TITLE
Support for x-foo annotations

### ISSUE THREAD

**Issue by Seldaek** [zircote/swagger-php#994]
I'm not sure exactly what would be the best way here but I'm thinking a new `@OA\Extended()` annotations taking arbitrary info would be a good solution.

So one could for example do `@OA\Extended(internal=true)` to add an `x-internal: true` to the exported node (be that a Property, or PathInfo, not sure what else this could be valuable on).

The main use case I have is we are exporting some generated docs from our code into a stoplight.io documentation render, and having the ability to support their internal field would be very valuable. I'm sure there may be other use cases though.

**Comment by Seldaek** [comment]
Ah I found https://zircote.github.io/swagger-php/Getting-started.html#vendor-extensions which does allow this as `@OA\Put(x={"internal": true})` for example. 

I am going to leave this open though as it would IMO be nicer to have a top level annotation for this instead of having it nested in the `x={}`, and would be happy to hear your opinion about it. The other benefit I see to an own annotation is that when using NelmioApiDocBundle for example I wouldn't need the `@OA\Put` at all in this case, so I have to declare it only to add the vendor extension. Same for properties which are auto-generated. 

Anyway I'm for sure glad it's already possible :)

**Comment by DerManoMann** [comment]
Hehe, I've done that a few times - create ticket, find the solution  2 min later...

It's still not a bad idea to perhaps have an annotation to arbitry add stuff. Thinking about it it would also be nice to have a way of attaching any data to a route for custom processing in swagger-php without the need of having to create custom versions of `GET`, `PUT`, ...

Just not sure about having only that, in particular when routes are involved in combination with other annotations. Could you perhaps provide an example of what the fuill set of annotations for an endpoint looks like

**Comment by Seldaek** [comment]
Here is an example, where the `OA\Put` doesn't strictly have to be defined as the `@Route` does it already:

```
    /**
     * Update user information
     *
     * Allows storing user preferences
     *
     * @Route("/user/me", name="users_account_update", methods={"PUT"})
     *
     * @OA\Put(x={"internal": true})
     * @OA\RequestBody(
     *     description="User attributes to update",
     *     @OA\JsonContent(
     *         ref=@Model(type=User::class, groups={"update"}))
     *     ),
     *     required=true
     * )
     * @OA\Response(response=201, description="No content")
     * @OA\Response(response=401, ref="#/components/responses/login_required")
     */
```

**Comment by DerManoMann** [comment]
Hmm, yes, I expected something like this.

Having thought about this a bit more I can see a couple issues with replacing `x=..` with a new annotation.

The vendor extension mechanism is valid on all annotations, so unless it is nested a new annotation at the same level as `@Route` will be ambiguous unless we consider the order of attributes - does it belong to `@Route`, `@OA\RequestBody` or one of the `@OA\Response`?

Secondly, `@Route` is not even part of swagger-php and NelmioApiDocBundle has custom code to "merge" all those different annotations. So, in a way `@OA\Put` is actually the best solution here - an annotation attaching a custom property to the route.

Hope that makes sense?

**Comment by Seldaek** [comment]
Right that's a fair point. It probably belongs more in NelmioApiDocBundle itself then.. or some custom extension of it. Thanks
