### ISSUE TITLE
How to remove swagger documentation in production env. ?

### ISSUE THREAD

**Issue by daoudi5** [zircote/swagger-php#996]

**Comment by DerManoMann** [comment]
Not sure what you actually mean here? The spec file? The annotations? A bundle that generates the spec on the fly and perhaps even includes swagger-ui?

Removing the annotations does not seem practical so I will assume the spec file (yaml/json). ..

If and how you deploy your code and whether that includes the generated openap spec is entirely up to you. 

If it is a bundle then you should perhaps disable it for your production environment.

**Comment by DerManoMann** [comment]
Closing as not related to swagger-php functionallity.
